<script src="<?php echo $this->basePath() ?>/showhidepassword/hideShowPassword.min.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/showhidepassword/css/example.wink.css">

<div id="change-password-page" class="about container">  
    <div class="row">
        <div class="col-sm-12">
            <h3 class="title lowcase">Lost Your Password?</h3>
            <form id="change-pass-form" method="POST" class="form">
                <div class="form-group">
                    <label>NEW PASSOWORD <span class="required">*</span></label> <br>
                    <input type="password" class="form-control flat" data-msg-required="Please enter the Email" maxlength="100" name="password" id="password">
                </div>
                <div class="form-group">
                    <label>RE-ENTER  YOUR NEW PASSWORD <span class="required" >*</span></label> <br>
                    <input type="password" class="form-control flat" data-msg-required="Please enter the Email" maxlength="100" name="repassword" id="repassword">
                </div>
                <button type="submit" class="btn btn-default btn-submit btn-block" id="btn-change-pass">Confirm</button>
                <input type="hidden" name="email" id="email" value="<?php echo $this->encryptemail; ?>" />
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
    //Plugin Hide/Show Password
    $('#password').hidePassword(true); 
    $('#repassword').hidePassword(true); 

    //Script close popup
    $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
        $("button.my_btn_ok").click(function(){
            $('a.close-reveal-modal').trigger('click');
        });
    });

    $("#btn-change-pass").on("click", function(e) {
        var newPass = $.trim($("#password").val());
        var confirmPass = $.trim($("#repassword").val());
        //Password validation
        var upperCase= new RegExp('[A-Z]');
        var lowerCase= new RegExp('[a-z]');
        var numbers = new RegExp('[0-9]');
        if( !(newPass.length >= 8 ) || !newPass.match(upperCase) || !newPass.match(lowerCase) || !newPass.match(numbers))
        {
            myalert('alertPassNotValid','type_missing','Oops', 'Password shouldn\'t be less than 8 characters. It must contain a mixture of upper and lower case letters, and at least one number.','');
        } else if (confirmPass == ""){
            myalert('alertConfirmPassNull','type_missing','Oops', 'Seems like you forgot to tell us confirm password.','');
        } else if (newPass != confirmPass) {
            myalert('alertPassAndConfirmNotSame','type_missing','Oops', 'Please enter confirm password same as password.','');
        } else {
            return true;
        }
        return false;
    });
});
</script>