<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.12.0/jquery.validate.min.js"></script>
<div class="forgot-password-page">
    <div class="container">
    <div class="topnavi">
           <?php 
            $session = new \Zend\Session\Container('alert');
            if(isset($session->alert)) {
                echo '<div class="green_box">';
                echo $session->alert;
                echo '</div>';
                unset($session->alert);
            }
    ?>
    </div>
  
        <section id="main-content-wrap">
            <div class="about">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="box">
                            <div class="block">
                            <h3 class="title lowcase">Lost Your Password?</h3>
                                <form name="myForm" id="myForm" method="POST" class="form" action="/profile/forgotpassword">
                                    <div class="form-group">
                                        <label>
                                        ENTER YOUR EMAIL <span class="required">*</span>
                                        </label> <br>
                                        <input type="text" class="form-control flat" data-msg-required="Please enter the Email" maxlength="100" name="email" id="email">
                                    </div>
                                        <button type="submit" class="btn btn-default btn-submit btn-block" id="btnNextStep">Reset Your Password</button>
                                </form>
                        </div>
                        </div>
                            
                        

                            
                   
                  
                    </div>
                </div>
            </div>
        </section>
    </div><!-- /.container -->   
</div>
<script>
    $(document).ready(function(){
        $.validator.addMethod("customemail", 
            function(value,element, regexp) {
                return regexp.test(value);
        }, "Sorry, I've enabled very strict email validation");


        $("#myForm").validate({
            errorPlacement: function(error, element) {
            },
             
            invalidHandler: function(form, validator) {
                var errors = validator.numberOfInvalids();
                if (errors) {
                     myalert('myalertID1', 'type_missing','Oops', validator.errorList[0].message ,'');  
                 $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
                    $("button.my_btn_ok").click(function(){
                        $('a.close-reveal-modal').trigger('click');
                        });
                    }); 
                    validator.errorList[0].element.focus(); //Set Focus
                }
            },
            rules: {
                email: {
                    required: true,
                    email: true,
                    // remote: {
                    //     url: "/user/checkAccount",
                    //     type: "post",
                    //     data: {
                    //       email: function() {
                    //         return $( "#email" ).val();
                    //       }
                    //     }
                    // },
                    customemail:/^[^\s@]+@[^\s@]+\.[^\s@]+$/

                },
            },
            messages: {
                email: {
                    required: 'Seems like you forgot to fill out email. Don\'t worry, we are not going to sell or share your information and promise no spam.',
                    email: 'Please enter a valid email address',
                    remote:'Your entered email address is already in use'
                },
            }
        });
    });

</script>
<script type="text/javascript">
    window.setTimeout(function() {
    $(".topnavi").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 5000);
</script>
