
<div class="req2c-page">
	 <div class="wrap wrap-1">
            <div class="container">
                <section>
                    <div class="about">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="box">
                                    <div class="block find-stitch-block">
                                    <h3 class="title lowcase title-find-stitch">What Size do You Wear?</h3>
                                    <div class="form-group">
                                        <ul class="list-radio list-radio-find-stitch list-inline">
                                            <li><div class="radio radio-find-stitch">
                                                <input type="radio" disabled name="radio2" id="radio2" value="option1" >
                                                <label for="radio2" class="radio-label">
                                                </label>
                                            </div>
                                            </li>
                                            <li>
                                                <div class="radio radio-find-stitch">
                                                    <input type="radio" disabled name="radio2" id="radio2" value="option1" >
                                                    <label for="radio2" class="radio-label">
                                                    </label>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="radio radio-find-stitch">
                                                    <input type="radio" disabled name="radio2" id="radio3" value="option1" checked="">
                                                    <label for="radio3" class="radio-label">
                                                    </label>
                                                </div>
                                            </li>
                                                 <li><div class="radio radio-find-stitch">
                                                <input type="radio" disabled name="radio2" id="radio2" value="option1" >
                                                <label for="radio2" class="radio-label">
                                                </label>
                                            </div>
                                            </li>
                                            <li>
                                                <div class="radio radio-find-stitch">
                                                    <input type="radio" disabled name="radio2" id="radio2" value="option1" >
                                                    <label for="radio2" class="radio-label">
                                                    </label>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="radio radio-find-stitch">
                                                    <input type="radio" disabled name="radio2" id="radio3" value="option1" >
                                                    <label for="radio3" class="radio-label">
                                                    </label>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <form action="" id="myForm" method="POST">
                                    <div class="size-box">
                                        <div class="select form-control_style">
                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <div class="form-group">
                                                        <select name="<?php echo $this->waist['name'] ?>" class="select form-control selectpicker" id="idWaistHidden">
                                                         
                                                            <?php 
                                                     
                                                            foreach ($this->waist['list'] as $key => $val) {  ?>
                                                                <option value="<?php echo $key ?>" class="option" <?php echo ($this->waist['value'] == $key ? 'selected' : '') ?>> <?php echo $val ?>
                                                                </option>
                                                            <?php } ?>

                                                        </select>
                                                         <div class="text-input"><input type="text" name="waistOther" class="others form-control" id="idWaistOther" value="<?php echo $this->waistOther;?>"/></div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <div class="form-group">
                                                        <select name="<?php echo $this->inseam['name'] ?>" class="select form-control selectpicker" id="idInseamHidden">
                                                          
                                                              <?php foreach ($this->inseam['list'] as $key => $val) { ?>
                                                                <option value="<?php echo $key ?>" class="option" <?php echo ($this->inseam['value'] == $key ? 'selected="selected"' : '') ?>><?php echo $val ?>
                                                                </option>
                                                            <?php } ?>
                                                        </select>
                                                               <div class="text-input"><input type="text" name="inseamOther" class="others form-control" id="idInseamOther" value="<?php echo $this->inseamOther;?>"/></div>
                                                        </div>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <div class="form-group">
                                                        <select name="<?php echo $this->shoeSize['name'] ?>" class="select form-control selectpicker" id="idShoeSizeHidden">
                                                         
                                                                 <?php foreach ($this->shoeSize['list'] as $key => $val) { ?>
                                                                <option value="<?php echo $key ?>" class="option" <?php echo ($this->shoeSize['value'] == $key ? 'selected="selected"' : '') ?>><?php echo $val ?>
                                                                </option>
                                                            <?php } ?>
                                                            

                                                        </select>
                                                         <div class="text-input">
                                                             <input type="text" name="shoeSizeOther" class="others form-control" id="idShoeSizeOther" value="<?php echo $this->shoeSizeOther;?>"/>
                                                             </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <div class="form-group">
                                                        <select name="<?php echo $this->jacketSize['name'] ?>" class="select form-control selectpicker" id="idJacketSizeHidden">
                                                                 <?php foreach ($this->jacketSize['list'] as $key => $val) { ?>
                                                                <option value="<?php echo $key ?>" class="option" <?php echo ($this->jacketSize['value'] == $key ? 'selected="selected"' : '') ?>><?php echo $val ?>
                                                                </option>
                                                            <?php } ?>
                                                                 
                                                                 

                                                        </select>
                                                         <div class="text-input">
                                                         <input type="text" name="jacketSizeOther" class="others form-control" id="idJacketSizeOther" value="<?php echo $this->jacketSizeOther;?>"/>
                                                                  </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <div class="form-group">
                                                        <select name="<?php echo $this->shirtSize['name'] ?>" class="form-control select selectpicker" id="idShirtSize">
                                                            
                                                                <?php foreach ($this->shirtSize['list'] as $key => $val) { ?>
                                                                <option value="<?php echo $key ?>" class="option" <?php echo ($this->shirtSize['value'] == $key ? 'selected="selected"' : '') ?>><?php echo $val ?>
                                                                </option>
                                                            <?php } ?>

                                                             
                                                             
                                                        </select>
                                                         <div class="text-input" id="nomargin">
                                                         <input type="text" name="shirtSizeOther" class="others form-control" id="idShirtSizeOther" value="<?php echo $this->shirtSizeOther;?>" />
                                                              </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    </form>
                                    </div>
                                </div>
                                    
                            </div>
                        </div>


                 
                    </div>
                </section>
                
            </div><!-- /.container -->
            <div class="continue">
                <button type="button" class="btn btn-default btn-submit btn-block btn-continue fix-button" id="btnNextStep">Continue</button></a>
            </div>
        </div>

</div>

<script>
     $(window).on('load', function () {
           var url = "/profile/profiletraking";
        $.ajax({
            url: url,
            type: 'POST',
            data: {page: 'size'},
            dataType: 'json',
            success: function (result) {
            }});
        $('#idWaistHidden').on('change', function() {
              if (this.value == 'other') {
                $('#idWaistOther').css('display', 'block');
            }
            else {
                $('#idWaistOther').css('display', 'none').val('');

            }
        });

         $('#idInseamHidden').on('change', function() {
              if (this.value == 'other') {
             
                $('#idInseamOther').css('display', 'block');
            }
            else {
                $('#idInseamOther').css('display', 'none').val('');
            }
        });


         $('#idShoeSizeHidden').on('change', function() {
              if (this.value == 'other') {
             
                $('#idShoeSizeOther').css('display', 'block');
            }
            else {
                $('#idShoeSizeOther').css('display', 'none').val('');
            }
        });

         $('#idJacketSizeHidden').on('change', function() {
              if (this.value == 'other') {
             
                $('#idJacketSizeOther').css('display', 'block');
            }
            else {
                $('#idJacketSizeOther').css('display', 'none').val('');
            }
        });

      $("#btnNextStep").on("click", function (e) {
            var allOK = true;
            $("select.selectpicker").each(function () {
                if ((this.value == '') || (this.value == 'other' && $('#' + this.id.replace("Hidden", "") + 'Other').val() == '')) {
                    //sweetAlert("Oops...", "ENTER ALL REQUIRED VALUES..", "error"); 
                      myalert('myalertid1','type_missing','Oops', 'Seems like you forgot to tell us your '+ $(this).find('option:first').html() + '. Don\'t be shy we are here to help.','');      
                     $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
                    $("button.my_btn_ok").click(function(){
                        $('a.close-reveal-modal').trigger('click');
                        });
                    });                   
                    allOK = false;
                    return false;
                }
            });
            if (allOK) {
                $("#myForm").submit();
            }
        });

     });


    //show other value
    var otherArr = ['idWaistOther','idInseamOther','idShoeSizeOther','idJacketSizeOther','idShirtSizeOther'];
    for (i = 0; i < otherArr.length; i++) { 
       
       if($('#'+otherArr[i]).val() !='') 
        $("#" + otherArr[i]).css("display","block");
    }
</script>