
<?php $baseUrl = 'http://'.URL_APPLICATION; 
?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Notification</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:700,400' rel='stylesheet' type='text/css'>
</head>
<body style="margin:0">
    <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="margin:0;padding:0;background-color:#fff;width:100% !important;font-family:Helvetica,sans-serif;font-size:12px;color:#444;line-height:18px">
        <tr>
            <td align="center" align="top" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#444;line-height:18px;font-weight:normal;">
                <table border="0" cellpadding="0" cellspacing="0" width="600" style="background-color: #f9f9f7;">
                    <tbody>
                        <tr>
                            <td align="center" style="padding:20px 0px"><img src="<?php echo $baseUrl; ?>/sendmail/image/lnove_logo.png"></td>
                        </tr>
                        <tr>
                            <td>
                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="500" style="background-color: #f9f9f7">
                                    <tbody>
                                        <tr>
                                            <td align="center" style="border:3px solid #dfe2e2">
                                               <table align="center" style="width:100%">
													<thead>
														<tr>
															<th>ID</th>
															<th>Title</th>
															<th>Creator</th>
														</tr>
													</thead>
													<tbody>
														<?php foreach ($outfitMissing as $value): ?>
															<tr>
															<td align="center">
                                                            <a href="<?php echo $baseUrl.'/service/createoutfit/?outfit='.$value->outfit_id; ?>" style="text-decoration: none;color:#444"><?php echo $value->outfit_id ?></a>
                                                            
                                                            </td>
															<td align="center">
                                                            <a href="<?php echo $baseUrl.'/service/createoutfit/?outfit='.$value->outfit_id; ?>" style="text-decoration: none;color:#444"><?php echo $value->title ?></a>
                                                            </td>
															<td align="center" style="color:#444"><?php echo $value->firstName ?></td>
															</tr>
														<?php endforeach ?>
														
													</tbody>
												</table>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="500" style="margin-top:25px;background-color: #dbdbdd;">
                                    <tbody>
                                        <tr>
                                            <td >
                                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="500">
                                                    <tbody>
                                                        <tr>
                                                            <td>
                                                            <table align="center" style="width:100%" border="0" cellpadding="0" cellspacing="0">
                                                                <tbody>
                                                                    <tr>
                                                                        <td style="font-family: 'Roboto'; font-weight: 400;color:#525058;font-size:11px;    padding: 10px 0 10px 18px;width:45%">
                                                                            <div>
                                                                            <p>Via Lorem Ipsum, 38 - City  - Country</p>
                                                                            </div>  
                                                                            <div>
                                                                            <p>
                                                                        Tel. +00 00 00000000</p>
                                                                            </div>
                                                                            <div>
                                                                            <p>email@example.com</p>
                                                                            </div>
                                                                        </td>
                                                                        <td >
                                                                    <table align="center" style="background-color: #e5e5e5;width:100%" border="0" cellpadding="0" cellspacing="0">
                                                                        <tbody>
                                                                            <tr>
                                                                <td style="padding: 10px 0;text-align: center">
                                                                <p><a target="_blank" style="text-decoration: none; color:#898697;font-size:13px;font-family: 'Open Sans', sans-serif;font-weight: 700" href="#">www.elnove.com</a></p>
                                                                                </td>
                                                    <td style="text-align: center">
                                                        <div>
                                                            <span style="padding-right:5px;"><img src="<?php echo $baseUrl; ?>/sendmail/image/twitter.png"></span>
                                                            <span style="padding-right:5px;"><img src="<?php echo $baseUrl; ?>/sendmail/image/facebook.png"></span>
                                                            <span style="padding-right:5px;"><img src="<?php echo $baseUrl; ?>/sendmail/image/instagram.png"></span>
                                                            <span><img src="<?php echo $baseUrl; ?>/sendmail/image/youtube.png"></span>
                                                        </div>
                                                        
                                                    </td>
                                                                            </tr>
                                                                        </tbody>
                                                                    </table>
                                                                            
                                                                        </td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align: center; padding-bottom: 30px;font-family: 'Open Sans', sans-serif;font-weight: 400;font-size: 11px">
                                <p>You can unsubscribe to these emails or change your notification settings.</p>
                            </td>
                        </tr>

                    </tbody>
                </table>
            </td>
            
        </tr>
    </table>
</body>
</html>