<div id="about_us">
    <?php echo $this->partial('application/common/banner_header.phtml'); ?> 
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1">
            <section>
                <div class="">
                    <div class="section section_one section_one_first">
                        <h1 class="title">About Us</h1>
                        <p >El Nove is the premiere service for men looking to dress to the nines at all times and in all places. What does it mean to be "dressed to the nines"? Well, it's simple, really. "To the nines" is simply a phrase - a quite old one, actually - that means to perfection or to the highest class.</p>
                        <p>El in Spanish simply means "the", and "nove" is the Italian for "nine". This sums up the "to the nines" ethic behind our service, while also demonstrating our commitment to providing our customers with diverse fashion options.</p>
                    </div> 
                    
                    <div class="clr"></div>
                    
                    <div class="section section_two">
                        <span>Why We Started El Nove</span>
                        <p>Let's face it. Most men aren't born with a gift for fashion or for knowing what looks good and what doesn't. That's why the rich and the famous hire personal stylists to make them look as good as they do.</p>
                        <p>By leveraging modern technology, some of the leading stylists in the world, and by partnering with the world's best men's fashion brands, we're able to provide all men with their own personal stylists ... For free.</p>
                        <p>We think that every man has the right to be dressed to the nines. And, it's our goal to make every man who uses our service look perfect, whether they're dressing up for the office, the club, or for something else entirely.</p>
                    </div>

                    <div class="clr"></div>
                                
                    <div class="section section_one">
                        <span>Clothing For Your Personality</span>
                        <p>When a man is at his most fashionable, he's wearing clothes that reflect and enhance his personality. That's why we've designed a powerful algorithm that learns as much as it can about you.</p>
                        <p>You tell us what kind of a man you are. Are you rough and rugged? Artistic and urbane? Casual and relaxed? It doesn't matter. We can connect you with clothes that are perfect for any kind of personality.</p>
                        <p>Let us know what you need your clothes for, too. Are you trying to dress your best for work? Are you trying to get noticed on your nights out on the town? Do you simply need some good-looking duds for a weekend bumming around? We find clothes from ultra-casual to ultra-professional, and everything in between.</p>
                        <p>Our system works to understand precisely who you are and what you're looking for. It then connects you with clothing from the world's leading brands, ones that are a perfect match for your personality, lifestyle and needs. After that, all you have to do is choose which clothes match what you're looking for. It's that easy.</p>
                    </div> 
                    
                    <div class="clr"></div>
                    
                    <div class="section section_two">
                        <span>Who Should Use El Nove?</span>
                        <p >Any man that wants to know what it looks and feels like to dress to the nines should use our service. As long as you're open to looking good and expanding your fashion horizons, El Nove can help you.</p>
                        <p>If you're ready to start looking and feeling your best, let El Nove become your personal stylist today. There's nothing to lose, because it's absolutely free!</p>
                    </div>

                    <div class="clr"></div>
                    <div class="top_page">
                        <img src="/img/arrow.png" id="click_to_top">
                        <p>TOP OF PAGE</p>
                    </div>
                    
                    
                </div>
            </section>
        </div>
    </div>
    <div class="clr"></div>
</div>

<script type="text/javascript">
    $('.top_page').click(function(){
        $('html, body').animate({scrollTop : 0},800);
        return false;
    });
</script>