<div id="careers_page" class="content-page">
   <?php echo $this->partial('application/common/banner_header.phtml'); ?> 
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1" id="content-wrap">
            <section>
                <div class="skeleton col-lg-8 col-lg-offset-2" >

                    <h1 class="title">CAREERS</h1>
                    <p class="p">
                    At El Nove we are constantly looking for Stylists to help create outfits for all occasions. We are looking for all levels of professionals- new and aspiring Stylists to seasoned Professionals. If you are interested in being part of this rapidly growing venture, please fill out the form below.<br>
                    </p>

                    <?php if(isset($_GET['success']) && $_GET['success']='1'){ ?>
                    <div class="green_box">
                        <p>Your message has been successfully sent.</p>
                    </div>
                    <?php } ?>
                    <div class="row"> 
                    <form action="/info/careers" id="contactForm" method="post" enctype="multipart/form-data" class="col-lg-12">
                    <input type="text" placeholder="Name" class="label" id="name" name="name"><br/><br/><br/>
                    <input type="text" placeholder="Email" class="label" id="email" name="email"><br/><br/><br/>
                    <input type="file" placeholder="Subject" class="label" id="subject" name="subject"><br/><br/><br/>
                    <span class="label color_diff">Description</span><br/> 
                    <textarea class="textarea" id="message" name="message"></textarea>
                    <div class="fr"><button class="btn-st-silver">Send</button></div>
                    </form>
                    </div>  
                    <div class="clr"></div>

                    <div class="top_page">
                        <img src="/img/arrow.png" id="click_to_top">
                        <p>TOP OF PAGE</p>
                    </div>

                </div>
                <div class="clr"></div>
            </section>
        </div>
    </div>
</div>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.12.0/jquery.validate.min.js"></script>

<script>
$(document).ready(function(){
    $.validator.addMethod("regexname", function(value,element, regexp) {          
        return regexp.test(value);
    }, 'Please enter a valid name.');
   $("#contactForm").validate({
        errorPlacement: function(error, element) {

        },
        invalidHandler: function(form, validator) {
            var errors = validator.numberOfInvalids();
            if (errors) {
                 myalert('myalertID1', 'type_missing','Oops', validator.errorList[0].message ,'');  
             $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
                $("button.my_btn_ok").click(function(){
                    $('a.close-reveal-modal').trigger('click');
                    });
                }); 
                validator.errorList[0].element.focus(); //Set Focus
            }
        },
     rules: {
        name: {
            required: true,
            minlength:4,
            maxlength:20,
            regexname:/^[a-zA-Z\ \.]+$/,
        },
        email: {
            required: true,
            email: true
        },
        message: {
            required: true
        }
     },
     messages: {
        name: {
            required: 'Please enter your name.',
            minlength:'Name shouldn\'t be less than 4 characters.',
            maxlength:'Name shouldn\'t be greater than 20 characters.',
        },
        email: {
            required: 'Please enter your email address.',
            email: 'Please enter a valid email address.'
        },
        message: {
            required: 'Please enter your message.'
        }
     }
   });
 });
</script>


<script type="text/javascript">
    $('.top_page').click(function(){
        $('html, body').animate({scrollTop : 0},800);
        return false;
    });
</script>