<!-- <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script> -->
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.12.0/jquery.validate.min.js"></script>

<script>
$(document).ready(function(){

    $.validator.addMethod("regexname", function(value,element, regexp) {          
            return regexp.test(value);
        }, 'Please enter a valid name.'); 


   $("#contactForm").validate({
        errorPlacement: function(error, element) {

        },
        invalidHandler: function(form, validator) {
            var errors = validator.numberOfInvalids();
            if (errors) {
                 myalert('myalertID1', 'type_missing','Oops', validator.errorList[0].message ,'');  
             $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
                $("button.my_btn_ok").click(function(){
                    $('a.close-reveal-modal').trigger('click');
                    });
                }); 
                validator.errorList[0].element.focus(); //Set Focus
            }
        },
     rules: {
        name: {
            required: true,
            minlength:4,
            maxlength:20,
            regexname:/^[a-zA-Z\ \.]+$/
        },
        email: {
            required: true,
            email: true
        },
        subject: {
            required: true
        },
        message: {
            required: true
        }
     },
     messages: {
        name: {
            required: 'Please enter your name.',
            minlength:'Name shouldn\'t be less than 4 characters.',
            maxlength:'Name shouldn\'t be greater than 20 characters.',
        },
        email: {
            required: 'Please enter your email address.',
            email: 'Please enter a valid email address.'
        },
        subject: {
            required: 'Please enter subject of your message.'
        },
        message: {
            required: 'Please enter your message.'
        }
     }
   });
 });
</script>

<style type="text/css">
    form label { width: 250px; }
    form label.error {color: #FF0000; }
</style>

<div class="banner2"></div>

<div class="container">
    <section>
        <div class="skeleton" style="margin: -480px auto 0;">

            <h1 class="title">DRESS TO THE NINES</h1>
            <p class="">The Office</p>
            <p class="p">Address: 97 Ecclesfield Drive, Toronto, Ontario, M1W 2Y3 <br>
                Email: <span class="hlink">support@elnove.com</span>
            </p>

            <?php if(isset($_GET['success']) && $_GET['success']='1'){ ?>
            <div class="green_box">
                <p>Your message has been successfully sent.</p>
            </div>
            <?php } ?>

            <form action="<?=isset($this->postURL)?$this->postURL:'/info/contactUs'?>" id="contactForm" method="post">
            <input type="text" placeholder="Name" class="label" id="name" name="name"><br/><br/><br/>
            <input type="text" placeholder="Email" class="label" id="email" name="email"><br/><br/><br/>
            <input type="text" placeholder="Subject" class="label" id="subject" name="subject"><br/><br/><br/>
            <span class="label">Your Message</span><br/>
            <textarea class="textarea" id="message" name="message"></textarea>
            <div class="fr"><button type="submit" class="contact_btn">Send</button></div>
            </form>

            <div class="clr"></div>

            <div class="top_page">
                <img src="/img/arrow.png" id="click_to_top">
                <p>TOP OF PAGE</p>
            </div>

        </div>
        <div class="clr"></div>
    </section>
</div>

<script type="text/javascript">
    $('.top_page').click(function(){
        $('html, body').animate({scrollTop : 0},800);
        return false;
    });
</script>