<div id="fre_ask_question">

<div class="banner2"></div>
<div class="row">
<div class="col-lg-10 col-lg-offset-1">
    <section>
        <div class="faq_one ">
            <!-- <p>FAQ &nbsp; &nbsp;  <span> >  &nbsp; &nbsp;   Shipping </span> </p> -->
            <h1 class="title col-lg-12 col-lg-offset-2">frequently asked questions</h1>
            <div class="faq-box-right col-lg-4 ">

                    <h1>BROWSE BY TOPIC</h1>
                 <div class="topic col-lg-4 col-xs-4 col-sm-4">
                    <div class="img-topic "  >
                        <a id="pricingID" href="#pricing"><img src="/img/doller.png"></a>
                    </div>
                    <p id="anc_pricing">Pricing</p>
                </div>

                <div class="topic col-lg-4 col-xs-4 col-sm-4">
                    <div class="img-topic ">
                        <a href="#shipping"><img src="/img/shipping.png"></a>
                    </div>
                    <p id="anc_shipping">Shipping</p>
                </div>

                <div class="topic col-lg-4 col-xs-4 col-sm-4">
                    <div class="img-topic">
                        <a id="shippingID" href="#shipping"><img src="/img/back.png"></a>
                    </div>
                    <p>Returns and Exchanges</p>
                </div>

                <div class="topic col-lg-4 col-xs-4 col-sm-4">
                    <div class="img-topic">
                        <a href=""><img src="/img/cart.png"></a>
                    </div>
                    <p>How to Buy</p>
                </div>

                <div class="topic col-lg-4 col-xs-4 col-sm-4">
                    <div class="img-topic">
                        <a href=""><img src="/img/bag.png"></a>
                    </div>
                    <p>Products <br>/ Services</p>
                </div>

                <div class="topic col-lg-4 col-xs-4 col-sm-4">
                    <div class="img-topic">
                        <a href=""><img src="/img/save.png"></a>
                    </div>
                    <p>Miscellaneous</p>
                </div>
                
            </div>
             
            
                    
                <div class="faq-box-left col-lg-8 col-sm-8">
                    <h3>What areas does El Nove serve?</h3>
                    <p>
                    Currently, El Nove is for men who live in the United States and Canada. The fashion algorithm that we work with selects clothing based upon our customers' locations within these two nations, offering items that are ideal for the climates in which they live. For example, our algorithm will not suggest winter parkas for men who live in Southern California, nor will it suggest stylish shorts for those living in the cold of the Yukon.                    
                    </p>
                    <a name="pricing"></a>
                </div>
            
                <div class="faq-box-left col-lg-8 col-sm-8">
                    <h3>How much does El Nove cost?</h3>

                    <p>Our service is entirely free. El Nove connects you with clothing provided by our partners, and they set the prices for the clothing items that they offer. We connect you with clothing that matches your budget, and our algorithm is always on the lookout for the best prices, deals and sales.</p>
                    <a name="shipping"></a>
                </div>
                
                
               
                <div class="faq-box-left col-lg-8 col-sm-8">
                    <h3>How much does shipping cost? How do you handle returns and exchanges?</h3>

                    <p>El Nove is a service that connects you with clothing provided by our partners. Therefore, all shipping costs are determined by our partners, and vary between them. In addition, our partners each have their own returns and exchanges policies. We encourage you to look into these policies before making a purchase, in the event you'll need to avail yourself of them.</p>
                </div>
              

                <div class="faq-box-left col-lg-8 col-sm-8">
                    <h3>Why do I have to answer so many questions to set up a profile?</h3>
                    <p>In order for El Nove to function as your personal stylist, our algorithm needs to understand you personally. Answering all of these questions helps our algorithm to connect you with the ideal clothing choices. For example, knowing your date of birth will help our algorithm to choose clothing that's age appropriate.</p>
                </div>
                

                <div class="faq-box-left col-lg-8 col-sm-8">
                    <h3>How does El Nove's algorithm say current with all of the latest fashion trends and styles?</h3>
                    <p>We work with a network of leading stylists around the world in order to refine and develop our algorithm. These stylists are constantly teaching it about the latest trends and styles, ensuring that they're reflected in the clothing choices we offer to you.</p>
                </div>
                

                <div class="faq-box-left col-lg-8 col-sm-8">
                    <h3>Does El Nove hire stylists?</h3>
                    <p>Absolutely! If you'd like to share your knowledge of fashion and help men across the United States and Canada dress to the nines, then <a href="/info/careers" class="hlink">click here</a>.</p>
                </div>
                
                
                
            

            
            <div class="clr"></div>

            <div class="top_page">
                <img src="/img/arrow.png" id="click_to_top"> 
                <p>TOP OF PAGE</p>
            </div>
            <div class="div"></div>
        </div>
    </section>
</div>
</div>
</div>
<script type="text/javascript">

    $(function() {
        
        $('.top_page').click(function(){
            $('html, body').animate({scrollTop : 0},800);
            return false;
        });
        
        $('#anc_shipping').click(function(){ 
        	location.href = '#shipping'
        });    
            
        $('#anc_pricing').click(function(){ 
        	location.href = '#pricing'
        });   
        
        $('a').click(function(){
            $('html, body').animate({
                scrollTop: $('[name="' + $.attr(this, 'href').substr(1) + '"]').offset().top
            }, 500);
            return false;
        });    

        <?php if(isset($this->queryParams['tag']) && $this->queryParams['tag']) {?>
        $('#<?php echo $this->queryParams['tag']?>ID').trigger( "click" );
        <?php }?>
        
	});


    
</script>
    
    
    