<div class="banner2"></div>
<div class="container">
<section>
<div class="howitwork">



<div class="container">

    <div class="pagetitle_new1">how it works</div>

    <div class="work_box_main clear_fix">
        <h3 class="new-title">TELL US ABOUT YOU</h3>
        <div class="relative">
            <div class="work_box_1">
                <div class="work_box_1_contant">
                    <p>Getting dressed to the nines begins with you.</p>
                </div>
                
            </div>
            <div class="work_box_1_img">
                <img src="<?php echo $this->basePath() ?>/img/new_work_1.jpg" alt="work" />
            </div>
            <div class="work_box_2 absolutely">
                <div class="work_box_number work_box_2_number">1</div>
                <div class="work_box_2_contant">
                    <h3>CREATE YOUR PROFILE</h3>
                    <p>
                    What kind of man are you? Are you the casual, outdoorsy type? Are you a young professional, looking to get ahead? Are you an artist that enjoys nights out on the town? Are you an athlete who presses hard on and off the court?<br /><br />
                    In order to match you with the clothes you're meant to wear, we need to understand the man that you are. That's how we make you look like the man you want to become.<br /><br />
                    So, tell us about your lifestyle and what kinds of clothes you like already. Let us know about what you need new clothes for. The more information you share with us, the better we'll be able to match you with the perfect clothes.<br />
                    </p>
                </div>
            </div>
        </div>
    <!--     <div class="work_box_1">
            <div class="work_box_1_contant">
                <h3 class="new-title">TELL US YOUR STYLE. FIND YOUR STITCH</h3>
                <p>We aim to provide you a fully personalized experience
                across all major brand name. All you have to do is
                create a profile and you can start Stylin
                </p>
            </div>
            <div class="work_box_1_img">
                <img src="<?php echo $this->basePath() ?>/img/shutterstock_193602344.jpg" alt="work" />
            </div>
        </div>
        <div class="work_box_2">
            <div class="work_box_2_number">1</div>
            <div class="work_box_2_contant">
                <h3>CREATE YOUR PROFILE</h3> 
                <p>
What kind of man are you?
Are you the casual, outdoorsy type? Are you a young professional, looking to get ahead? Are you an artist that enjoys nights out on the town? Are you an athlete who presses hard on and off the court? <br /> <br />
In order to match you with the clothes you're meant to wear, we need to understand the man that you are. That's how we make you look like the man you want to become. <br /> <br />
So, tell us about your lifestyle and what kinds of clothes you like already. Let us know about what you need new clothes for. The more information you share with us, the better we'll be able to match you with the perfect clothes.
                </p>
            </div>
        </div> -->
    </div>

    <div class="work_box_main">
        <div class="work_box_3 ">
            <div class="work_box_number work_box_3_number">2</div>
            <div class="work_box_3_contant">
                <h3>GET STYLED</h3>
                <p>
                After you've let us know about you, El Nove goes to work.<br /><br />
                Using top-flight stylists from around the world, as well as a powerful fashion algorithm, we search our partners to find the clothes that will be ideal.<br /><br />
                While the stylists we work with might sleep, our algorithm is always at work. This means that we're empowered to not only connect you with the best clothing for you, but also the best prices as well.<br /><br />
                It doesn't matter what you're looking for. El Nove can connect you with individual pieces to build an outfit or to enhance an outfit you already have.<br /><br />
                That's what a personal stylist does. That's what El Nove does for you.
                </p>
            </div>
        </div>
        <div class="work_box_1">
            <div class="work_box_1_contant" style="clear:both"></div>
            <div class="work_box_1_img" >
                <img src="<?php echo $this->basePath() ?>/img/work_img2.jpg" alt="work" />
            </div>
        </div>
    </div>

    <div class="work_box_main workbox_top_space2">
        <div class="work_box_1">
            <div class="work_box_1_contant"></div>
            <div class="work_box_1_img" style="margin-top:0px">
                <img src="<?php echo $this->basePath() ?>/img/new_work_2.jpg" alt="work" />
            </div>
        </div>
        <div class="work_box_2 workbox_top_space">
            <div class="work_box_number work_box_2_number">3</div>
            <div class="work_box_2_contant">
                <h3>GET DRESSED</h3>
                <p>
                After identifying the clothes that match your personality, lifestyle and needs, we present you with a variety of options from our partners.<br /><br />
You simply browse the articles that we've chosen for you, and decide if they're right for you. If you find articles that you like, it's as simple as purchasing them from our partners. Because our fashion algorithm is always at work, you'll always be assured of getting the best deal too.
                
                </p>
            </div>
        </div>
    </div>

    <div class="clr"></div>

    <div class="light_gray_bg">
        <h1>IT'S TIME TO DRESS TO THE NINES!</h1>
        <p>
Don't you think it's high time that you started dressing in clothes that fit, that match your personality, and that present you in the best way possible? <br /><br />
With El Nove as your personal stylist, you'll look and feel great, and those around will notice how sharp you look.<br /><br />
So, why not get started today? El Nove is entirely free, and you're never obligated to purchase the clothing that we locate for you.<br /><br />
Start dressing to the nines. Fill out a profile, and let us connect you with the clothing you should be wearing.
        
        </p>
    </div>

    <div class="get"><a href="/profile">get started now</a></div>

    <div class="clr"></div>

    <div class="top_page page">
        <img src="/img/arrow.png" id="click_to_top">
        <p>TOP OF PAGE</p>
    </div>

</div><!--container-->


<script type="text/javascript">
    $('.top_page').click(function(){
        $('html, body').animate({scrollTop : 0},800);
        return false;
    });
</script>


</div>
<div class="clr"></div>
</section>
</div>
<script type="text/javascript">
    $('.click_to_top').click(function(){
        $('html, body').animate({scrollTop : 0},800);
        return false;
    });
    $('.learn').click(function(){
        $('html, body').animate({scrollTop : 500},800);
        return false;
    });    
</script>
