<div class="banner2"></div>

<div class="container">
    <section>
		<div class="faq_one">
            <h1 class="title">Privacy and Policies</h1>
            <div class="faq-box">
                <div class="faq-box-left" style="width:85%">
                    <h3>Scope of El Nove Privacy policy</h3>
                    <p >
						El Nove believes that protection and safety of user data is paramount. El Nove takes the issue of privacy very seriously and would like the users of the Website to know that El Nove takes all the necessary steps to ensure safety of their data. Therefore, the collection, processing and use of data during a visit or use of the Website, its services and offers is in strict compliance with this privacy policy. El Nove will only gather and process personal data if the user has granted El Nove consent to do so, or if El Nove is allowed or required to do so by law or legislature.
					</p>
					<p >
						The following privacy policy aims to explain how El Nove collects, processes and uses users’ data to offer the Website services and benefits to users and our aim to prevent illegal and abusive use, manipulation, loss, destruction or misuse of users data. El Nove ensures that all data is securely stored and processed.
					</p>
                </div>
                <div class="clr"></div>
                <div class="faq-box-left" style="width:85%">
					<h3>Personal data</h3>
					<p >
						Personal information is usually required to be able to identify the user. Examples of personal information include first and last name, address, phone number or email, or when an email has an identifiable reference to users’ name. The collection and use of personal data by El Nove is mainly used for establishment and provision of personal user accounts in order to properly render El Nove services and benefits to its user base. <b>User personal information will be treated confidentially at all times.</b> Any other information that cannot be used to identify a user is considered general information (data that cannot be used to directly identify includes, but not limited to, reference to users username, Internet browser information, gender, age or education).
					</p>
                </div>
                <div class="clr"></div>  
				<div class="faq-box-left" style="width:85%">
					<h3>Data Use and Collection</h3>   
					<ol class="list-group" style="list-style-type:lower-latin;">
						<li class="list-group-item" style="list-style:inherit">
							<p>The Website can be visited without any personal data provision. Visitors of the Website can optto remain anonymous. El Nove processes anonymous metadata through cookies such as the URLof the requested file, the amount of data transferred, the date and time of the request from the user, Internet browser information, operating system type, the IP address of the used device, the Internet service provider used, reference links such as user clicks on a sponsored links. This metadata cannot be used by El Nove to obtain personally identifiable information. This information is only used for general purposes, such as technical improvements and statistical purposes.</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p>When a visitor chooses to participate actively in the Website, through for example, registration or login, the visitor must enter their personal information, such as their address and contact information which is collected for security reasons. If users opts to provide personal data that user provides the necessary authorisation to transmit, process and store this data on the serverof the web hosting companies used by El Nove. In similar way, some information can be collected during the process of placing and processing orders on the Website.</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p><b>El Nove's will not share personal information with third parties unless our users have expressly given their permission to do so.</b> Due to legal requirements, El Nove is forced to reveal users personal information in certain cases, for example, upon request of the authorities or to process payments. This also includes El Nove exchanging information on individual users to enable and facilitate credit card transactions or assess the creditworthiness of the user. El Nove could be required to disclose information to appropriate authorities for investigation should that be required to do so by virtue of law or to protect itself, its users and contractors from potential abuses.</p>	
						</li>
				</div>
				<div class="clr"></div>
				<div class="faq-box-left" style="width:85%">
					<h3>COMMUNICATIONS</h3>
					<p >
						El Nove might send you a welcome email to verify your account and other transactional emails for operational purposes, such as billing, account management, or system maintenance. You might only stop those emails by terminating your account.<br>
						El Nove might also send you promotions, product announcements, surveys, newsletters, developer updates, product evaluations, and event information or other marketing or commercial e-mails. You can opt out of receiving these email communications from El Nove at any time by unsubscribing using the unsubscribe link within each email, updating your e-mail preferences on your El Nove account or emailing us to have your contact information removed from our email list or registration database.				
					</p>				
				</div>
				<div class="clr"></div>
				<div class="faq-box-left" style="width:85%">
					<h3>WHAT INFORMATION DO WE COLLECT?</h3>
					<p>When you use at the pages on the El Nove website or website, information is automatically recorded that identifies, for each page accessed:</p>
					<ol class="list-group" style="list-style-type:disc;">
						<li class="list-group-item" style="list-style:inherit">
							<p> the IP (Internet Protocol) address of the machine which has accessed it;</p>
						</li>	
						<li class="list-group-item" style="list-style:inherit">
							<p>  your top-level domain name (for example .com, .gov, .ca etc.);</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p>  the address of your server;</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p>  the date and time of your visit to the site;</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p>  the pages accessed and documents downloaded;</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p>  the previous website visited; and</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p>  the type of browser and operating system you have used.</p>
						</li>
					</ol>
					<p>We might also embed a piece of code into some pages of El Nove website. This gives us statistical application usage information about:</p>
					<ol class="list-group" style="list-style-type:disc;">
						<li class="list-group-item" style="list-style:inherit">
							<p>  the pages visited;</p>
						</li>	
						<li class="list-group-item" style="list-style:inherit">
							<p>  duration of page view,</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p>  location previous to visiting the El Nove website or website; and</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p>  the navigation habits of the user.</p>
						</li>
					</ol>
					<p>Personal Information: We might collect the following types of personal information in order to provide you with the use and access to the El Nove website, site, services and tools, and for any additional purposes set out in this Privacy Policy:</p>
					<ol class="list-group" style="list-style-type:disc;">
						<li class="list-group-item" style="list-style:inherit">
							<p>  Name, and contact information, such as email address, phone number, mobile telephone number, physical address, and (depending on the service used) sometimes financial information, such as bank account numbers;</p>
						</li>	
						<li class="list-group-item" style="list-style:inherit">
							<p>  transactional information based on your activities on the sites and other information you provide to receive or provide payment;</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p>  personal information you provide to us through correspondence, chats, or shared by you from other social applications, services or website or websites;</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p>  additional personal information we ask you to submit to authenticate yourself if we believe you are violating website policies;</p>
						</li>
						<li class="list-group-item" style="list-style:inherit">
							<p>  information from your interaction with our sites, services, content and advertising, including, but not limited to, device ID, device type, geo-location information, computer and connection information, statistics on page views, traffic to and from the sites, ad data, IP address and standard web log information.</p>
						</li>
					</ol>
				</div>
				<div class="clr"></div>
				<div class="faq-box-left" style="width:85%">
					<h3>WILL THIS POLICY BE UPDATED OVER TIME?</h3>
					<p >
						Due to the developing nature of privacy principles for online communication, this policy might be modified or expanded in light of new developments or issues that might arise from time to time. The amended policy will be posted to our site and/or website and will operate from the time it is posted.
					</p>
				</div>
				<div class="clr"></div>
				<div class="top_page" id="click_to_top" style="cursor: pointer">
					<img src="/img/arrow.png">
					<p>TOP OF PAGE</p>
				</div>
            </div>
        </div>
    </section>
</div>
<div class="clr"></div>

<script type="text/javascript">
    $('#click_to_top').click(function(){
        $('html, body').animate({scrollTop : 0},800);
        return false;
    });
</script>