<div class="banner2"></div>

<div class="container">
    <section>
        <div class="padbtm" style="margin: -480px auto 0;">
            <div class="section_one">
                <h1 class="title">Privacy and Policies</h1>
                <span>TELL US YOUR STYLE. FIND YOUR STITCH</span>
                <p >We aim to provide you a fully personalized experience <br>
                    across all major brand name. All you have to do is <br>
                    create a profile and you can start Styling
                </p>
            </div>
            <div class="section_two">
                <span>TELL US YOUR STYLE. FIND YOUR STITCH</span>
                <p >All services available at your fingertips will be absolutely free! Once you find your perfect outfit, <br>
                    you purchase directly with the major brands <br><br>
                    You purchase the clothes at what price they are being sold at.<br>
                    There are no hidden fees
                </p>
            </div>
            <div class="clr"></div>
            <div class="top_page" id="click_to_top" style="cursor: pointer">
                <img src="/img/arrow.png">
                <p>TOP OF PAGE</p>
            </div>
        </div>
    </section>
</div>
<div class="clr"></div>


<script type="text/javascript">
    $('#click_to_top').click(function(){
        $('html, body').animate({scrollTop : 0},800);
        return false;
    });
</script>