<div id="term-conditions" class="row">
	<div class="banner2"></div>

	<div class="col-lg-10 col-lg-offset-1" id="content-wrap">
	    <section class="row">
			<div class="faq_one col-lg-10 col-lg-offset-1">
				<div class="row">
		            <h1 class="title col-lg-12">Terms and Conditions</h1>
		            <div class="faq-box col-lg-12">
						<div class="faq-box-left">
							<h3>User Agreement</h3>
							<p style="line-height: 23px;">
								In This User Agreement:<br>
								<span class="text-muted"><strong>"Account"</strong> means your account on this website corporate, business or personal.</span><br>
								<span class="text-muted"><strong>"Customer"</strong> means a User of El Nove Services.</span>
								<span class="text-muted"><strong>"El Nove", "we", "our"</strong>, or <strong>"us"</strong> means Stitch Style Solutions Inc. incorporated under Canada Business Corporations Act - 2013-09-08.</span><br>
								<span class="text-muted"><strong>"Intellectual Property Rights"</strong> refers to all intellectual rights including but not limited to: (a) copyright, patents, registered designs, trademarks, and any right to have confidential information kept confidential; and (b), whether or not such privileges are listed or capable of being listed and whether current under any laws.</span><br>
								<span class="text-muted"><strong>"El Nove Services"</strong> means services delivered by El Nove.</span><br>
								<span class="text-muted"><strong>"User", "you"</strong> or <strong>"your"</strong> means any entity who uses the website.</span><br>	
								<span class="text-muted"><strong>"User Contract"</strong> means :</span><br>	
							</p>
							<ol class="list-group" style="list-style-type:decimal;">
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted">this User Agreement;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted">any other provisions acknowledged by both the El Nove and Customer, to the degree not conflicting with the User Agreement and the Privacy Policy; </span>
								</li>
							</ol>
							<span class="text-muted">
								<strong>"Website"</strong> refers to the websites operated by Stitch Style Solutions Inc. and/or El Nove: such as El Nove.com and any connected El Nove services, implements or applications.	
							</span>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
		                    <h3>Summary</h3>
		                    <p style="line-height: 23px;">
								<span class="text-muted" style="line-height: 30px;">By opening an account and using the Website, you acknowledge and agree to the subsequent terms with El Nove.</span><br>
								<span class="text-muted" style="line-height: 30px;">We might change User Agreement along with any related material as required by posting amended terms on the Website.</span><br>
								<span class="text-muted">The Services are provided by <strong>STITCH STYLE SOLUTIONS INC. ("El Nove"),</strong> located at <strong>97 Ecclesfield Dr., Toronto ON M1W 2Y3, Canada</strong></span><br><br>
								<span class="text-muted">El Nove is an online personal styling service, El Nove acts as a platform connecting buyers of services and those who are prepared to sell the outfits, garments and styling services and any other services users might elect to exchange via the platform. El Nove is not, in any way, part of the transaction, but is acting as a marketplace and platform provider. El Nove is not responsible for the type, quantity, essence and scope of the information and services exchanged by platform users. Patrons must register for an Account so they can to utilise El Nove Services.</span>	
							</p>
		                </div>
		                <div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Scope</h3>
							<p style="line-height: 23px;">
								<span class="text-muted"  style="line-height: 40px;">As you start utilising El Nove Website, read the whole User Agreement, relevant terms and all related information.</span><br>					
								<span class="text-muted">You need to read and accept all of the terms in this User Agreement, the El Nove Privacy Policy and all Website policies. You confirm that this User Agreement will relate to whenever you use the El Nove Website, services provided and any products we make accessible to interact with the El Nove Website.</span>	
							</p>
		                </div>
		                <div class="clr"></div>  
						<div class="faq-box-left" >
							<h3>Eligibility</h3>
							<p style="line-height: 23px;">You will refrain from using El Nove Website if you:</p>
							<ol class="list-group" style="list-style-type:decimal;">
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted">barred form legally binding contracts; or</span>
								</li>	
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted">are below the age of 16; or</span>
								</li>	
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted">a person forbidden from receiving services under the rules of Germany or other appropriate jurisdiction; or</span>
								</li>	
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted">are banned from using the El Nove Website.</span>
								</li>	
							</ol>
							<p style="margin:4px 0px 13px 0px;">Subject to your native rules, an individual over 16 but under 18 can use a regular account with the consent of the Parent and/or Guardian. Though, the account owner is accountable for entirety performed with that account.</p>
							<p style="margin:4px 0px 13px 0px;">Users might arrange for a commercial name or a business name to be linked with the User's Account. Users accept and come to an agreement that where a commercial name or business name is related with their Account, this User Agreement is an agreement with the User as an officer of that business and Users stay solely accountable for all activity carried out in relation of their Account.</p>	
							<p style="margin:4px 0px 13px 0px;">We might refuse to accept an individual or business entity as a User at our sole discretion.</p>
						</div>
						<div class="clr"></div>
						<div class="faq-box-left" >
							<h3>Using El Nove</h3>
							<p>
								While using the El Nove Website, you will not:
							</p>
							<ol class="list-group" style="list-style-type:lower-roman;">
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">post content or items in inappropriate categories or areas on our websites and services;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">infringe any laws, third party rights or our policies;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">work with false, inaccurate, misleading, defamatory or offensive content;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">distribute or post spam, unsolicited, or bulk electronic communications, chain letters, or pyramid schemes;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">distribute viruses or any other technologies that may harm El Nove, the Website, or the interests or property of El Nove users (including their Intellectual Property Rights, privacy and publicity rights) or is unlawful, threatening, abusive, defamatory, invasive of privacy, vulgar, obscene, profane or which may harass or cause distress or inconvenience to, or incite hatred of, any person;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">attempt to modify, translate, adapt, edit, decompile, disassemble, or reverse engineer any software programs used by us in connection with the El Nove Website;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">copy, modify or distribute rights or content from the El Nove Website or El Nove's copyrights and trademarks; or</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">harvest or otherwise collect information about Users, including email addresses, without their consent</span>
								</li>
							</ol>
						</div>
						<div class="clr"></div>
						<div class="faq-box-left">
							<h3>Fees And Services</h3>
							<p>We do not charge fees for providing services to the user, we however might receive fees for eligible purchases made by a user through our site and eligible referrals.</p>
						</div>
						<div class="clr"></div>
						<div class="faq-box-left" >
							<h3>Content</h3>
							<p>
								You represent and warrant that your content:
							</p>
							<ol class="list-group" style="list-style-type:lower-roman;">
								<li class="list-group-item" style="list-style:inherit"  style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">will not infringe upon or misappropriate any copyright, patent, pattern, trademark, trade secret, or other intellectual property right or proprietary right or right of publicity or privacy of any person;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">will not violate any law or regulation;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">will not be defamatory or trade libellous;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">will not be obscene or contain child pornography;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">will not contain the development, design, manufacture or production of missiles, or nuclear, chemical or biological weapons</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">will not contain material linked to terrorist activities</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">will not include incomplete, false or inaccurate information about User or any other individual; and</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">will not contain any viruses or other computer programming routines that are intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information.</span>
								</li>
							</ol>
							<p>The Website may contain links to other third party websites. We do not control the websites to which we link from the Website. We do not endorse the content, products, services, practices, policies or performance of the websites we link to from the Website. Use of third party content, links to third party content and/or websites is at your risk.</p>
						</div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Your Content in our Services</h3>
							<p>Some of our Services allow you to upload, submit, store, send or receive content. You retain ownership of any intellectual property rights that you hold in that content. In short, what belongs to you stays yours.</p>
							<p style="margin:4px 0px 13px 0px;">When you upload, submit, store, send or receive content to or through our Services, you give El Nove (and those we work with) a worldwide license to use, host, store, communicate and distribute such content. The rights you grant in this license are for the limited purpose of operating, promoting, and improving our Services, and to develop new ones.</p>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Account Terms</h3>
							<p>
								You are responsible for your account credentials and security and maintaining the security of these. The Account holder has the complete and final responsibility for any financial and non-financial transactions that were undertaken via account, regardless if they authorised these transaction or not.
							</p>
							<p>
								El Nove cannot and will not be liable for any loss or damage from your failure to comply with this security obligation.
							</p>
							<ol class="list-group" style="list-style-type:decimal;">
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">You are responsible for all content added to El Nove and activity that occurs within your account; </span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">You may not use El Nove for any illegal purpose or to violate any laws (including but not limited to copyright laws);</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">You are responsible for properly managing users of your account, all activity performed by your users;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">You are responsible for assigning appropriate permissions and responsibilities to your users, managing these and any actions performed by your delegates.</span>
								</li>						
							</ol>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Right To Review</h3>
							<p>
								We may read all correspondence posted to the Website and download or access, and test (if necessary), all uploaded files, programs and websites related to your use of the Website for the purpose of investigating fraud and for risk management and related purposes.
							</p>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Right To Refuse Service</h3>
							<p>
								We might chose to close your account, at our sole discretion, including but not limited to the reasons outlined below:
							</p>
							<ol class="list-group" style="list-style-type:lower-roman;">
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">if we conclude that you are in breach of our terms and conditions, or are not acting on terms of this agreement;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">if you breached a law;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">if you breached someone’s Intellectual Property Rights;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">if you engage in fraudulent or deceptive activities;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">we are required to do so by law;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">you might result in risk to us;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">you result in loss to us;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">you are offending or a risk to another user;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">for other similar reasons.</span>
								</li>
							</ol>
							<p>
								If we decide to close your account due to this agreement you will become liable to pay all your outstanding fees and settle your account in full.
							</p>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Privacy</h3>
							<p>
								Your privacy is of utmost importance to us. Any of your personal details will only be used by us in accordance with our Privacy Policy. If you do not agree with this policy in any way please refrain from using our services.
							</p>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Indemnity</h3>
							<p>
								You will protect us (and our directors, officers, agents, and employees) against any entitlement or request, including permissible costs and fees arising out of or due to your acting in contradiction to this Agreement, or your breach of any laws in the course of using the El Nove Website and El Nove Services.
							</p>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Limitation Of Liability</h3>
							<p>
								Under no circumstances shall we be liable for:
							</p>
							<ol class="list-group" style="list-style-type:lower-roman;">
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">any unintended, consequential, distinctive or related damages that might arise;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">any damage to business, income, or profits (whether indirect or direct) that might be experienced by you;</span>
								</li>
								<li class="list-group-item" style="list-style:inherit">
									<span class="text-muted" style="line-height: 23px;">any damage, claim, or loss which might be sustained by you as a consequence of any of your dealings concerning the Website.</span>
								</li>
							</ol>
							<p>
								The limits on our accountability to you will be effective if we or not, staff, our affiliates, our related entities or anyone else connected with us have been counselled of the likelihood of such damages or costs arising.
							</p>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Our Warranties and Disclaimers</h3>
							<p>
								OTHER THAN AS EXPRESSLY SET OUT IN THESE TERMS OR ADDITIONAL TERMS, NEITHER EL NOVE NOR ITS SUPPLIERS OR DISTRIBUTORS MAKE ANY SPECIFIC PROMISES ABOUT THE SERVICES. FOR EXAMPLE, WE DON'T MAKE ANY COMMITMENTS ABOUT THE CONTENT WITHIN THE SERVICES, THE SPECIFIC FUNCTIONS OF THE SERVICES, OR THEIR RELIABILITY, AVAILABILITY, OR ABILITY TO MEET YOUR NEEDS. WE PROVIDE THE SERVICES "AS IS".
							</p>
							<p>
								SOME JURISDICTIONS PROVIDE FOR CERTAIN WARRANTIES, LIKE THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, WE EXCLUDE ALL WARRANTIES.
							</p>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Liability for our Services</h3>
							<p>
								WHEN PERMITTED BY LAW, EL NOVE, AND EL NOVE’S SUPPLIERS AND DISTRIBUTORS, WILL NOT BE RESPONSIBLE FOR LOST PROFITS, REVENUES, OR DATA, FINANCIAL LOSSES OR INDIRECT, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES.
							</p>
							<p>
								TO THE EXTENT PERMITTED BY LAW, THE TOTAL LIABILITY OF EL NOVE, AND ITS SUPPLIERS AND DISTRIBUTORS, FOR ANY CLAIMS UNDER THESE TERMS, INCLUDING FOR ANY IMPLIED WARRANTIES, IS LIMITED TO THE AMOUNT YOU PAID US TO USE THE SERVICES (OR, IF WE CHOOSE, TO SUPPLYING YOU THE SERVICES AGAIN).	
							</p>
							<p>
								IN ALL CASES, EL NOVE, AND ITS SUPPLIERS AND DISTRIBUTORS, WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE THAT IS NOT REASONABLY FORESEEABLE.	
							</p>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Jurisdiction Limitations</h3>
							<p>
								In case any law or jurisdiction prohibits limitations outlined in this agreement or sets limits to these limitations, we reserve the right to request limitations to the maximum extend permit table by these laws.
							</p>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Law And Forum For Legal Disputes</h3>
							<p>
								This Agreement will be governed in all respects by the laws of Ontario, Canada. If a dispute cannot be resolved then you and El Nove irrevocably submit to the exclusive jurisdiction of the courts of Ontario, Canada.
							</p>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Severability</h3>
							<p>
								The inaccuracy of any part of this agreement will not and shall not be thought to affect the legitimacy of any other part. In the event that any provision of this agreement is held to be invalid, the parties agree that the left over provisions shall be considered to be in full force and effect as if they had been executed by both parties subsequent to the expungement of the invalid provision.
							</p>
		                </div>
						<div class="clr"></div>
		                <div class="faq-box-left" >
							<h3>Interpretation</h3>
							<p>
								Titles are for reference purposes only and in no way limit, define, describe or construe the range or degree of such section.
							</p>
		                </div>
						<div class="clr"></div>
						<div class="top_page" id="click_to_top" style="cursor: pointer">
							<img src="/img/arrow.png">
							<p>TOP OF PAGE</p>
						</div>
		            </div>
	            </div>	
	        </div>
	    </section>
	</div>
	<div class="clr"></div>
</div>
<script type="text/javascript">
    $('#click_to_top').click(function(){
        $('html, body').animate({scrollTop : 0},800);
        return false;
    });
</script>