<div class="forgot-password-page container">
    <div class="topnavi">
        <?php 
        $session = new \Zend\Session\Container('alert');
        if(isset($session->alert)) {
            echo '<div class="green_box">';
            echo $session->alert;
            echo '</div>';
            unset($session->alert);
        }
        ?>
    </div>

    <div class="brand-box">
        <div class="lost-password-box">
            <h1>Lost Your Password?</h1>

            <div class="red_box" id="errormsgblock">
                <div class="cross_img">
                    <img src="/img/cross.png" >
                </div>
                <p id="errormsg"></p>
                <div class="cross_img1 fr"><img src="/img/cross.png" >
                    <div class="clr"></div>
                </div>
            </div>

            <div class="clr"></div>

            <form name="myForm" id="myForm" method="POST" class="form" action="/profile/forgotpassword">
                <lable>ENTER YOUR EMAIL *</lable> <br>
                <input type="text" class="input_box" data-msg-required="Please enter the Email" maxlength="100" name="email" id="email">
                <input type="hidden" name="existemail" id="existemail" value="">
                <br>
                <input type="submit" class="signup" id="btnNextStep" value="Reset Password">
            </form>
        </div>
    </div><!--brand-box -->
    <div class="clr"></div>
</div>

<script>
$(window).on('load', function () {
    $("#btnNextStep").on("click", function(e) {
        $('#errormsgblock').hide();
        $('#errormsg').html('');
        $('#existemail').val('');

        if( !($("#email").val().match(/^[+a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i)) ) {
            alert('Please enter valid Email address.');
            return false;
        }

        $.ajax({
            type: "POST",
            url: "/user/checkAccount",
            data: { email: $("#email").val() },
            async : false
        }).done(function( data ) {
            if( data != 'false' ) {
                $('#existemail').val('1');
                return false;
            }
        });

        if( $("#existemail").val() == 1 ) {
            alert('Your entered email address is not exist in our database.');
            return false;
        }

        $( "#myForm" ).submit();
    });
});

window.setTimeout(function() {
    $(".topnavi").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 5000);
</script>