<style type="text/css">
/*.profile-box {
    zoom: 1;
}

.profile-box:after {
    clear: both;
    content: ".";
    display: block;
    height: 0;
    line-height: 0;
    visibility: hidden;
}
.des{
    margin-top: 94px;
}

textarea{
    height: auto !important;
}*/
</style>

<div class="container" id="profile_myaccount">
    <div class="row">
        <div class="account-btn col-lg-3">
            <a href="/profile/myaccount" class="btn-1 myaccount">
                ACCOUNT
            </a>
            <a href="/profile" class="btn-2 edit_msq">
                EDIT MY STYLE QUESTIONS
            </a>
        </div>

        <?php
            $dob_year = '';
            $dob_month = '';
            $dob_date = '';

            if (trim($userdata['dob']) != '') {
                $dob = $userdata['dob'];
                $dobarray = explode('-', $dob);
                $dob_year = $dobarray[0];
                $dob_month = $dobarray[1];
                $dob_date = $dobarray[2];
            }
            if (isset($userdata['user_pp']) && !empty($userdata['user_pp']) && $userdata['user_pp']) {
                $classUpp = 'fa-check-circle';
                $userPPV = 'Yes';
            } else {
                $classUpp = 'fa-close';
                $userPPV = 'No';
            }
        ?>
        <div class="col-lg-9">
            <form name="myForm" id="myForm" method="POST">
                <input type="hidden" value="<?php echo $userdata['user_pp']; ?>" id="profile-pp-val" name="profile-pp-val">
                <div class="account-box">
                    <h1>Account</h1>

                    <div class="red_box" id="errormsgblock">
                        <div class="cross_img">
                            <img src="/img/cross.png" >
                        </div>
                        <p id="errormsg"></p>
                        <div class="cross_img1 fr"><img src="/img/cross.png" >
                            <div class="clr"></div>
                        </div>
                    </div>

                    <?php if ($this->flashmessage) { ?>
                        <div class="green_box"><p><?php echo $this->flashmessage; ?></p></div>
                    <?php } ?>

                    <div class="profile-box row">
                        <div class="box-one col-lg-3">
                            <?php
                            $basePath = $this->basePath('img/profilepic/'.$userdata['user_prp_pic']);
                            if (isset($userdata['user_prp_pic']) && !empty($userdata['user_prp_pic'])) {
                                ?>
                                <img src="<?php echo $basePath; ?>">
                                <p><a href="/profile/upload">Change Picture</a></p>
                                <?php
                            } else {
                                ?>
                                <img src="<?php echo $this->basePath('img/profile.png'); ?>">
                                <p><a href="/profile/upload">Upload Picture</a></p>
                            <?php } ?>

                        </div>

                        <div class="box-two col-lg-9">
                            <div class="row">
                                <div class="first_name_mpf col-lg-5">
                                    <h2>First Name</h2>
                                    <input type="text" class="name" id="firstName" name="firstName" value="<?php echo $userdata['firstName']; ?>">
                                </div>
                                <div class="last_name_mpf col-lg-7">
                                    <h2>Last Name</h2>
                                    <input type="text" class="name" id="lastName" name="lastName" value="<?php echo $userdata['lastName']; ?>">
                                </div>
                            </div>
                            <div class="row">
                                <div class="email_address_mpf col-lg-5">
                                    <h2>Email Address</h2>
                                    <div class="bdrnone"><?php echo $userdata['email']; ?></div>
                                </div>
                                <div class="password_mpf col-lg-7">
                                    <h2>Password</h2>
                                    <div class="simplepwd">********</div>
                                
                                <a href="/profile/resetpassword" class="reset">Reset your password</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="default1 col-lg-5">
                                    <h2>Birthday</h2>
                                    <select name="month" class="fr" name="month" id="suMonth">
                                        <option value="">Month</option>
                                        <option value="01" <?php
                                        if ($dob_month == 1) {
                                            echo 'SELECTED';
                                        }
                                        ?>>January</option>
                                        <option value="02" <?php
                                        if ($dob_month == 2) {
                                            echo 'SELECTED';
                                        }
                                        ?>>February</option>
                                        <option value="03" <?php
                                        if ($dob_month == 3) {
                                            echo 'SELECTED';
                                        }
                                        ?>>March</option>
                                        <option value="04" <?php
                                        if ($dob_month == 4) {
                                            echo 'SELECTED';
                                        }
                                        ?>>April</option>
                                        <option value="05" <?php
                                        if ($dob_month == 5) {
                                            echo 'SELECTED';
                                        }
                                        ?>>May</option>
                                        <option value="06" <?php
                                        if ($dob_month == 6) {
                                            echo 'SELECTED';
                                        }
                                        ?>>June</option>
                                        <option value="07" <?php
                                        if ($dob_month == 7) {
                                            echo 'SELECTED';
                                        }
                                        ?>>July</option>
                                        <option value="08" <?php
                                        if ($dob_month == 8) {
                                            echo 'SELECTED';
                                        }
                                        ?>>August</option>
                                        <option value="09" <?php
                                        if ($dob_month == 9) {
                                            echo 'SELECTED';
                                        }
                                        ?>>September</option>
                                        <option value="10" <?php
                                        if ($dob_month == 10) {
                                            echo 'SELECTED';
                                        }
                                        ?>>October</option>
                                        <option value="11" <?php
                                        if ($dob_month == 11) {
                                            echo 'SELECTED';
                                        }
                                        ?>>November</option>
                                        <option value="12" <?php
                                        if ($dob_month == 12) {
                                            echo 'SELECTED';
                                        }
                                        ?>>December</option>
                                    </select>
                                                                
                                    <select name="day" class="fl" id="suDay">
                                        <option value="">Day</option>
                                        <?php for ($date = '1'; $date <= '31'; $date++) { ?>
                                            <option value="<?php echo $date; ?>" <?php
                                            if ($dob_date == $date) {
                                                echo 'SELECTED';
                                            }
                                            ?>><?php echo $date; ?></option>
                                                <?php } ?>
                                    </select>
                                    <select name="year" class="" id="suYear">
                                        <option value="">Year</option>
                                        <?php for ($year = '1996'; $year >= '1934'; $year--) { ?>
                                            <option value="<?php echo $year; ?>" <?php
                                            if ($dob_year == $year) {
                                                echo 'SELECTED';
                                            }
                                            ?>><?php echo $year; ?></option>
                                                <?php } ?>
                                    </select>

                                </div>
                                                                                                                           
                                <div class="default col-lg-7">
                                    <h2>Your Default Venue</h2>
                                    <input type="radio" name="defaultVenue" id="radio1" value="Work" <?php
                                    if ($userdata['defaultVenue'] == 'Work') {
                                        echo 'CHECKED';
                                    }
                                    ?> />
                                    <label for="radio1" class="outfit1">
                                        <!-- <span class="fa-stack ">
                                            <i class="fa fa-circle-o fa-stack-1x"></i>
                                            <i class="fa fa-circle fa-stack-1x"></i>
                                        </span> --> 
                                        Work
                                    </label>
                                    <input type="radio" name="defaultVenue" id="radio2" value="NightOut" <?php
                                    if ($userdata['defaultVenue'] == 'NightOut') {
                                        echo 'CHECKED';
                                    }
                                    ?> />
                                    <label for="radio2"  class="outfit1">
                                       <!--  <span class="fa-stack">
                                            <i class="fa fa-circle-o fa-stack-1x"></i>
                                            <i class="fa fa-circle fa-stack-1x"></i>
                                        </span>  -->
                                        Night Out
                                    </label>
                                    <input type="radio" name="defaultVenue" id="radio3" value="Casual" <?php
                                    if ($userdata['defaultVenue'] == 'Casual') {
                                        echo 'CHECKED';
                                    }
                                    ?> />
                                    <label for="radio3"  class="outfit1">
                                        <!-- <span class="fa-stack">
                                            <i class="fa fa-circle-o fa-stack-1x"></i>
                                            <i class="fa fa-circle fa-stack-1x"></i>
                                        </span>  -->
                                        Casual
                                    </label>
                                    <div class="clr"></div>
                                    <div class="blue-btn" id="profile-pp">
                                        <i class="fa <?php echo $classUpp; ?> fa-lg white "></i>
                                        <div class="square"><?php echo $userPPV; ?></div>
                                    </div>

                                    
                                    <p class="head">Let my Closet Public</p>
                                </div>
                            </div>
                            <div class="des">
                                <h2>Description</h2>
                                <textarea name="description" class="name" rows="3"><?php echo trim($userdata['description']); ?></textarea>
                            </div>  
                            <div class="fr"><button class="contact_btn" id="submit">Submit</button></div>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div><!--container-->
</div>

<script>
    $(window).on('load', function () {

        <?php if( $this->editSuccessfull ) {?>
        jQuery.gritter.add({
            //title: result.mgs,
            title: '<div class="wrap_ion_mgs"><div class="icon_gritter"></div><div class="dary_message">Your style profile has been updated</div></div><div class="my_close my_wrap_close">\
                        <a href="javascript:void(0)"  class="close-reveal-modal x_close type_close"><span>X</span></a>\
                        </div>',
            class_name: 'growl-success',
            sticky: false,
            time: 3000
        })         
        <?php }?>

        $(".cross_img1").on("click", function (e) {
            $('#errormsgblock').hide();
            $('#errormsg').html('');
        });

        $("#submit").on("click", function (e) {

            $('#errormsgblock').hide();
            $('#errormsg').html('');

            if (!($("#firstName").val().match(/^[a-zA-Z\ \.]+$/)))
            {
                $('#errormsgblock').show();
                $('#errormsg').html('Please enter valid First Name');
                return false;
            }

            if (!($("#lastName").val().match(/^[a-zA-Z\ \.]+$/)))
            {
                $('#errormsgblock').show();
                $('#errormsg').html('Please enter valid Last Name');
                return false;
            }

            if ($("#suDay").val() == '')
            {
                $('#errormsgblock').show();
                $('#errormsg').html('Please choose day of birth.');
                return false;
            }

            if ($("#suMonth").val() == '')
            {
                $('#errormsgblock').show();
                $('#errormsg').html('Please choose month of birth.');
                return false;
            }

            if ($("#suYear").val() == '')
            {
                $('#errormsgblock').show();
                $('#errormsg').html('Please choose Year of birth.');
                return false;
            }

            if ($("#radio1").is(':checked') != true && $("#radio2").is(':checked') != true && $("#radio3").is(':checked') != true)
            {
                $('#errormsgblock').show();
                $('#errormsg').html('Please choose your default venue.');
                return false;
            }

            $("#myForm").submit();

        });

        $('#profile-pp').on('click', function () {
            var classes = $(this).children(".fa-lg").attr('class');
            var classA = classes.split(" ");
            if ($.inArray('fa-check-circle', classA) == -1) {
                $('.fa-lg').removeClass('fa-close');
                $('.fa-lg').addClass('fa-check-circle');
                $(this).children(".square").html('Yes');
                $('#profile-pp-val').val(1);
                $(".square").css('float', 'right');
                
            } else {
                $('.fa-lg').removeClass('fa-check-circle');
                $('.fa-lg').addClass('fa-close');
                $(this).children(".square").html('No');
                $('#profile-pp-val').val(0);
                $(".square").css('float', 'left');
                $(".square").css('margin-left', '5px');
}
        })
    });
</script>

