<!-- <link rel="stylesheet" href="/vendor/jqueryui/development-bundle/themes/base/jquery.ui.all.css"> -->
<link rel="stylesheet" href="/vendor/jqueryui/custom.css">
<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.core.js"></script>
<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.widget.js"></script>
<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.mouse.js"></script>
<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.slider.js"></script>
 <?php echo $this->headLink()
                 ->appendStylesheet($this->basePath() . '/assets/css/you_page.css')
                 ->appendStylesheet($this->basePath() . '/templates/mobile/ion.rangeSlider/css/ion.rangeSlider.css')
                 ->appendStylesheet($this->basePath() . '/templates/mobile/ion.rangeSlider/css/ion.rangeSlider.skinHTML5.css');
 ?>
 
<div class="row">
    <div id="profile_price" class="content-page">
        <div class="row row_here">
            <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                <div class="topnavi">
                    <div class="brand-box col">
                        <div class="menu-box <?php echo ($this->mode=='edit')?'menu-box-bigger':''?>">
                            <ul class="about">
                                <li>
                                    <a href="/profile">LOOK YOU&#39;D WEAR<div class="fa"><i class="fa fa-check green"></i></div></a>
                                </li>
                                <li>
                                    <a href="/profile/you">ABOUT YOU<div class="fa"><i class="fa fa-check green"></i></div></a>
                                </li>
                                <li>
                                    <a href="/profile/size">YOUR SIZE<div class="fa"><i class="fa fa-check green"></i></div></a>
                                </li>
                                <li class="blue">
                                    <a class="active">YOUR LOOK<div class="fa"></div></a>
                                </li>
                                <?php if( $this->mode == 'new' ) { ?>
                                <li>
                                    <a href="/profile/signup">SIGN UP<div class="fa"></div></a>
                                </li>
                                <?php }//end if ?>
                            </ul>
                            <div class="clr"></div>
                        </div><!--menu-box -->
                        <div class="form-group">
                            <ul class="list-radio list-radio-find-stitch list-inline">
                                <li><div class="radio radio-find-stitch">
                                    <input type="radio" disabled name="radio4" id="radio4" value="option1" >
                                    <label for="radio4" class="radio-label">
                                    </label>
                                </div>
                                </li>
                                <li>
                                    <div class="radio radio-find-stitch">
                                        <input type="radio" disabled name="radio4" id="radio2" value="option1" >
                                        <label for="radio2" class="radio-label">
                                        </label>
                                    </div>
                                </li>
                                <li>
                                    <div class="radio radio-find-stitch">
                                        <input type="radio" disabled name="radio4" id="radio3" value="option1" >
                                        <label for="radio3" class="radio-label">
                                        </label>
                                    </div>
                                </li>
                                     <li><div class="radio radio-find-stitch">
                                    <input type="radio" disabled name="radio4" id="radio4" value="option1" checked="" >
                                    <label for="radio4" class="radio-label">
                                    </label>
                                </div>
                                </li>
                                <li>
                                    <div class="radio radio-find-stitch">
                                        <input type="radio" disabled name="radio4" id="radio2" value="option1" >
                                        <label for="radio2" class="radio-label">
                                        </label>
                                    </div>
                                </li>
                                
                            </ul>
                        </div>

                        <div class="clr"></div>

                        <div class="page_one-box">
                            <div class="wrap_title-page">
                                <div class="shadow_title-page">
                                    <h1 class="title-page">How Much Would you Spend </h1>
                                </div>
                            </div>
                        </div> <!--page_one-box -->
                    </div><!--brand-box -->
                    <div class="clr"></div>

                    <div class="about_box" id="HowMuchWouldyouSpend">
                        <?php for ($i = 0; $i < 5; $i++) { ?>
                            <div class="bdr about_content">
                                <h2><?php echo  $this->price[$i]['title'] ?></h2>
                                <input type="text" class="lb" id="<?php echo  $this->price[$i]['name'] ?>Value">
                                <div class="line-bar">
                                    
                                    <div class="ranger" id="<?php echo  $this->price[$i]['name'] ?>">
                                        <input type="text" id="<?php echo  $this->price[$i]['name'] ?>range" value="" name="shirtrange" />
                                    </div>

                                </div>
                            </div>
                        <?php }//end for ?>
                        <div class="clr"></div>
                    </div>

                    <div class="brand-box">
                        <a href="javascript:void(0);" class="next fr btn-st-blue" id="btnNextStep"><?php echo ($this->mode=='edit'?'SUBMIT':'NEXT')?> ></a>
                        <div class="clr"></div>
                        <a href="javascript:void()" id="clearFilters" class="italic-box fr hlink"> <i>Clear filters</i></a>
                        <div class="clr"></div>
                    </div>
                </div><!--container-->
            </div>
        </div>
    </div>
</div>

<form id="myForm" method="POST">
    <?php foreach($this->price as $aBox) {
        $valueDefault = $aBox['value'];
    ?>
        <input type="hidden" id="id<?php echo  $aBox['name'] ?>Input" name="<?php echo  $aBox['name'] ?>" value="<?php echo $valueDefault ?>" />
    <?php }//end foreach ?>
</form>
<script src="<?php echo $this->basePath().'/templates/mobile' ?>/ion.rangeSlider/js/ion.rangeSlider.min.js"></script>
<script type="text/javascript">
$(function () {
    /*** Script for Close Popup alert ***/
    $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
        $("button.my_btn_ok").click(function(){
            $('a.close-reveal-modal').trigger('click');
        });
    });
    
    /*** SETUP FOR ALL SLIDER ***/
    <?php foreach ($this->price as $aBox) { ?>
    //Process when client scroll Slider
    $("#<?php echo  $aBox['name'] ?>range").ionRangeSlider({
        hide_min_max: true,
        type: "single",
        min: <?php echo  $aBox['minPrice'] ?>,
        max: <?php echo  $aBox['maxPrice'] ?>,
        from: <?php echo  $aBox['value'] ?>,
        keyboard: true,
        step: <?php echo  $aBox['step'] ?>,
        hide_from_to:true,
        onStart: function (value) {
            if($("#id<?php echo  $aBox['name'] ?>Input").val() > 0) {
                newValue = value.from >= <?php echo  $aBox['maxPrice'] ?> ? '<?php echo  $aBox['maxPrice'] ?>+' : value.from;
                $("#<?php echo  $aBox['name'] ?>Value").val(newValue);
                $("#id<?php echo  $aBox['name'] ?>Input").val(value.from); 
            }
        },
        onChange:function(){
            newValue = $('#<?php echo  $aBox['name'] ?>range').prop("value");
            $("#<?php echo  $aBox['name'] ?>Value").val(newValue >= <?php echo  $aBox['maxPrice'] ?> ? '<?php echo  $aBox['maxPrice'] ?>+' : newValue);
            $("#id<?php echo  $aBox['name'] ?>Input").val(newValue);
        }
    });
    //Save slider instance to var for update
    var <?php echo  $aBox['name'] ?>Slider = $("#<?php echo  $aBox['name'] ?>range").data("ionRangeSlider");
    //Process when client input anything to textbox
    $("#<?php echo  $aBox['name'] ?>Value").keyup(function(){
        this.value = this.value.replace(/[^0-9]/g,'');
        <?php echo  $aBox['name'] ?>Slider.update({
            from: this.value > <?php echo $aBox['maxPrice'] ?> ? <?php echo $aBox['maxPrice'] ?> : this.value,
        });
        $( "#id<?php echo  $aBox['name'] ?>Input" ).val(this.value);
    });
    //Process when client move out textbox
    $("#<?php echo  $aBox['name'] ?>Value").change(function(){
        if(this.value < <?php echo  $aBox['minPrice'] ?>){
            $( "#id<?php echo  $aBox['name'] ?>Input" ).val('');
            myalert('alerterror<?php echo $aBox['name'] ?>','type_missing','Oops', 'Min value for <?php echo  $aBox['name'] ?> must be $'+<?php echo  $aBox['minPrice'] ?>,'');
        }
        if(this.value > <?php echo  $aBox['maxPrice'] ?>){
            $("#<?php echo  $aBox['name'] ?>Value").val(<?php echo  $aBox['maxPrice'] ?>+'+');
        }
    });
<?php }//end foreach ?>

    /*** CLIENT SUBMIT ***/
    $("#btnNextStep").on("click", function (e) {
        <?php foreach($this->price as $aBox) {?>
            if( $( "#id<?php echo  $aBox['name'] ?>Input" ).val() < 1 ) { 
                myalert('myalertid<?php echo  $aBox['name'] ?>Input','type_missing','Oops', 'Seems like you forgot to answer, How much would you spend <?php echo  $aBox['title'] ?>.','','',function(){
                    $('a.close-reveal-modal').trigger('click');
                });   
                $('html, body').animate({scrollTop: $("#<?php echo  $aBox['name'] ?>Value").offset().top - 200}, 500);  
                $( "#<?php echo  $aBox['name'] ?>Value" ).val('');
                return false;
            }
        <?php }?>   
        $("#myForm").submit();
    });

    /*** CLEAR FILTER ***/
    $("#clearFilters").on("click", function(e) {
        $("#myForm input[type=hidden]").each(function(index,value){
            $(value).val("");
        });
        <?php foreach ($this->price as $aBox) { ?>
           $("#<?php echo  $aBox['name'] ?>range").data("ionRangeSlider").reset();
            $("#<?php echo  $aBox['name'] ?>Value").val('');        
        <?php }//end foreach ?>
    });
});

$(window).load(function () {
    var url = "/profile/profiletraking";
    $.ajax({
        url: url,
        type: 'POST',
        data: {page: 'price'},
        dataType: 'json',
        success: function (result) {
        }});
});
</script>