<script src="<?php echo $this->basePath() ?>/showhidepassword/hideShowPassword.min.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/showhidepassword/css/example.wink.css">

<div class="container">
    <div class="e">
        <div class="account-btn">
            <a href="/profile/myaccount" class="btn-1">
                ACCOUNT
            </a>
            <br>
            <a href="/profile" class="btn-2">
                EDIT MY STYLE QUESTIONS
            </a>
        </div>

        <form name="myForm" id="myForm" method="POST">
            <div class="account-box">
                <h1>Reset Password</h1>
                <div class="red_box" id="errormsgblock">
                    <div class="cross_img">
                        <img src="/img/cross.png" >
                    </div>
                    <p id="errormsg"></p>
                    <div class="cross_img1 fr"><img src="/img/cross.png" >
                        <div class="clr"></div>
                    </div>
                </div>
                <div class="profile-box">
                    <div class="box-one">&nbsp;</div>
                    <div class="box-two">
                        <h2>New Password</h2>
                        <input type="password" class="namepwd" id="password" name="password" value="">
                        <h2>&nbsp;</h2>
                        <h2>Confirm Password</h2>
                        <input type="password" class="namepwd" id="confirm_password" name="confirm_password" value="">
                        <h2>&nbsp;</h2>
                        <div class="default1"></div>
                        <div class="clr"></div>
                        <div class="fr"><button class="contact_btn" id="reset_pass_btn">Submit</button></div>
                    </div>
                    <div class="box-three"></div>
                </div>
            </div>
        </form>
    </div>
</div><!--container-->

<script type="text/javascript">
$(function() {
    //Plugin Hide/Show Password
    $('#password').hidePassword(true); 
    $('#confirm_password').hidePassword(true); 

    //Script close popup
    $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
        $("button.my_btn_ok").click(function(){
            $('a.close-reveal-modal').trigger('click');
        });
    });

    $("#reset_pass_btn").on("click", function(e) {
        var newPass = $.trim($("#password").val());
        var confirmPass = $.trim($("#confirm_password").val());
        //Password validation
        var upperCase= new RegExp('[A-Z]');
        var lowerCase= new RegExp('[a-z]');
        var numbers = new RegExp('[0-9]');
        if( !(newPass.length >= 8 ) || !newPass.match(upperCase) || !newPass.match(lowerCase) || !newPass.match(numbers))
        {
            myalert('alertPassNotValid','type_missing','Oops', 'Password shouldn\'t be less than 8 characters. It must contain a mixture of upper and lower case letters, and at least one number.','');
        } else if (confirmPass == ""){
            myalert('alertConfirmPassNull','type_missing','Oops', 'Seems like you forgot to tell us confirm password.','');
        } else if (newPass != confirmPass) {
            myalert('alertPassAndConfirmNotSame','type_missing','Oops', 'Please enter confirm password same as password.','');
        } else {
            return true;
        }
        return false;
    })
})
</script>