
<?php    echo $this->headScript()
     ->appendFile($this->basePath() . '/js/jquery.ddslick.js')  ?>
<style id="css-ddslick" type="text/css">
                .dd-select{ border-radius:2px; border:solid 1px #ccc; position:relative; cursor:pointer;}
                .dd-desc { color:#aaa; display:block; overflow: hidden; font-weight:normal; line-height: 1.4em; }
                .dd-selected{ overflow:hidden; display:block; padding:10px; font-weight:normal; background-color:#e5e5e5; color:#254f73 }
                .dd-pointer{ width:0; height:0; position:absolute; right:10px; top:50%; margin-top:-3px;}
                .dd-pointer-down{ border:solid 5px transparent; border-top:solid 5px #000; }
                .dd-pointer-up{border:solid 5px transparent !important; border-bottom:solid 5px #000 !important; margin-top:-8px;}
                .dd-options{ border:solid 1px #b1b0b0; border-top:none; list-style:none; box-shadow:0px 1px 5px #ddd; display:none; position:absolute; z-index:2000; margin:0; padding:0;background:#c2c0c0; overflow:auto;}
                .dd-option{ padding:10px; display:block; border-bottom:solid 1px #ddd; overflow:hidden; text-decoration:none; color:#fff; cursor:pointer;-webkit-transition: all 0.25s ease-in-out; -moz-transition: all 0.25s ease-in-out;-o-transition: all 0.25s ease-in-out;-ms-transition: all 0.25s ease-in-out; }
                .dd-options > li:last-child > .dd-option{ border-bottom:none;}
                .dd-option:hover{ background:#cac9c9; color:#fff;}
                .dd-selected-description-truncated { text-overflow: ellipsis; white-space:nowrap; }
                .dd-option-selected { background:#c2c0c0  url("/img/req2c-tick_03.jpg")  no-repeat right 5% center }
                .dd-option-selected:hover{ background:#cac9c9  url("/img/req2c-tick_03.jpg")  no-repeat right 5% center }
                .dd-option-image, .dd-selected-image { vertical-align:middle; float:left; margin-right:5px; max-width:64px;}
                .dd-image-right { float:right; margin-right:15px; margin-left:5px;}
                .dd-container{ position:relative; float:left; margin-right:21px}
                .dd-selected-text { font-weight:normal}
                
                .text-input{width: 175px; margin-right:21px}
                
</style>
                
                
                
<div class="container topnavi">
    <div class="brand-box">
        <div class="menu-box <?=($this->mode=='edit')?'menu-box-bigger':''?>">
            <ul class="about">
                <li>
                    <a href="/profile">LOOK YOU&#39;D WEAR<div class="fa"><i class="fa fa-check green"></i></div></a>
                </li>
                <li>
                    <a href="/profile/you">ABOUT YOU<div class="fa"><i class="fa fa-check green"></i></div></a>
                </li>
                <li class="blue">
                    <a class="active">YOUR SIZE<div class="fa"></div></a>
                </li>
                <!-- <li>
                    <a>FAVOURITE BRAND<div class="fa"></div></a>
                </li> -->
                <li>
                    <a href="/profile/price">YOUR LOOK<div class="fa"></div></a>
                </li>
                <?php if( $this->mode == 'new' ) { ?>
                <li>
                    <a href="/profile/signup">SIGN UP<div class="fa"></div></a>
                </li>
                <?php }?>
            </ul>
            <div class="clr"></div>
        </div><!--menu-box -->

        <div class="clr"></div>

        <div class="choose-box">
            <h1>What Size do you Wear?</h1>
        </div><!--choose-box -->
    </div><!--brand-box -->

    <div class="clr"></div>

    <form id="myForm" method="POST">
        <div class="size_box">
            <div class="dropdown-menu">
                <div class="select_style">

                 <div id="idWaist"></div>
                 <div id="idInseam"></div>
                 <div id="idShoeSize"></div>
                 <div id="idJacketSize"></div>
                 <div id="idShirtSize"></div>
                 
                 
                 
 <div style="poistion:absolute; display:none">       
                
<select name="<?= $this->waist['name'] ?>" class="select selectpicker" id="idWaistHidden">
<!-- <option value="" class="option">Waist</option> -->
<?php foreach ($this->waist['list'] as $key => $val) { ?><option value="<?= $key ?>" class="option" <?= ($this->waist['value'] == $key ? 'selected="selected"' : '') ?>><?= $val ?></option><?php } ?>
</select>

<select name="<?= $this->inseam['name'] ?>" class="select selectpicker" id="idInseamHidden">
<!-- <option value="" class="option">Inseam</option> -->
<?php foreach ($this->inseam['list'] as $key => $val) { ?><option value="<?= $key ?>" class="option" <?= ($this->inseam['value'] == $key ? 'selected="selected"' : '') ?>><?= $val ?></option><?php } ?>
</select>

<select name="<?= $this->shoeSize['name'] ?>" class="select selectpicker" id="idShoeSizeHidden">
<!-- <option value="" class="option">Shoe Size</option> -->
<?php foreach ($this->shoeSize['list'] as $key => $val) { ?><option value="<?= $key ?>" class="option" <?= ($this->shoeSize['value'] == $key ? 'selected="selected"' : '') ?>><?= $val ?></option><?php } ?>
</select>

<select name="<?= $this->jacketSize['name'] ?>" class="select selectpicker" id="idJacketSizeHidden">
<!-- <option value="" class="option">Jacket Size</option> -->
<?php foreach ($this->jacketSize['list'] as $key => $val) { ?><option  value="<?= $key ?>" class="option" <?= ($this->jacketSize['value'] == $key ? 'selected="selected"' : '') ?>><?= $val ?></option><?php } ?>
</select>

<select name="<?= $this->shirtSize['name'] ?>" class="select selectpicker nomargin" id="idShirtSizeHidden">
<!-- <option value="" class="option">Shirt Size</option> -->
<?php foreach ($this->shirtSize['list'] as $key => $val) { ?><option value="<?= $key ?>" class="option" <?= ($this->shirtSize['value'] == $key ? 'selected="selected"' : '') ?>><?= $val ?></option><?php } ?>
</select>
 </div>         
                 
                 
                 
                 
                 
                 
                 
 
                </div>
                <div class="clr"></div>
            </div>

            <div class="clr"></div>

            <div class="text_box">
                <div class="text-input"><input type="text" name="waistOther" class="others" id="idWaistOther" value="<?php echo $this->waistOther;?>"/></div>
                <div class="text-input"><input type="text" name="inseamOther" class="others" id="idInseamOther" value="<?php echo $this->inseamOther;?>"/></div>
                <div class="text-input"><input type="text" name="shoeSizeOther" class="others" id="idShoeSizeOther" value="<?php echo $this->shoeSizeOther;?>"/></div>
                <div class="text-input"><input type="text" name="jacketSizeOther" class="others" id="idJacketSizeOther" value="<?php echo $this->jacketSizeOther;?>"/></div>
                <div class="text-input" id="nomargin"><input type="text" name="shirtSizeOther" class="others" id="idShirtSizeOther" value="<?php echo $this->shirtSizeOther;?>" /></div>
            </div>
        </div><!--size_box-->
        
        
            <div id="next"><a href="javascript:void(0);" class="next fr " id="btnNextStep">NEXT ></a>
                <div class="clr"></div>
                <div class="clr"></div>
                <a href="javascript:void(0)" id="clearFilters" class="italic-box fr hlink"> <i>Clear filters</i></a>
                <div class="clr"></div>
            </div>


    </form>
    <div class="clr"></div>

</div>
<script type="text/javascript">
    $(window).on('load', function () {

        function valueChanged( data ) {
            $('#' + data.original.attr('id') + 'Hidden').val( data.selectedData.value );
            
            if (data.selectedData.value == 'other') {
                $('#' + data.original.attr('id') + 'HiddenOther').val('');
                $('#' +data.original.attr('id') + 'Other').css('display', 'block');
            }
            else {
                $('#' + data.original.attr('id') + 'Other').css('display', 'none');
            }

            $(".size_box").css('height', '121px');
            $("select.selectpicker").each(function () {
                if (this.value == 'other') {
                    $(".size_box").css('height', '195px');
                }

            });
            
        }   

        $(".size_box").css('height', '121px');
        $("select.selectpicker").each(function () {
            if (this.value == 'other') {
                $('#' + this.id.replace("Hidden", "") + 'Other').css('display', 'block');
            }
            else {
                $('#' + this.id.replace("Hidden", "") + 'Other').css('display', 'none');
            }
        });
        $("select.selectpicker").each(function () {
            if (this.value == 'other') {
                $(".size_box").css('height', '195px');
            }

        });        

        $("#btnNextStep").on("click", function (e) {
            var allOK = true;
            $("select.selectpicker").each(function () {
                if ((this.value == '') || (this.value == 'other' && $('#' + this.id.replace("Hidden", "") + 'Other').val() == '')) {
                    // swal({title: "Oops...", text:   '"'+ $(this).find('option:first').html() +'" is not selected and is mandatory', type: "error"});  
                    myalert('myalertid1','type_missing','Oops', 'Seems like you forgot to tell us your '+ $(this).find('option:first').html() + '. Don\'t be shy we are here to help.','');      
                     $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
                    $("button.my_btn_ok").click(function(){
                        $('a.close-reveal-modal').trigger('click');
                        });
                    });        
                    allOK = false;
                    return false;
                }
            });
            if (allOK) {
                $("#myForm").submit();
            }
        });
        var url = "/profile/profiletraking";
        $.ajax({
            url: url,
            type: 'POST',
            data: {page: 'size'},
            dataType: 'json',
            success: function (result) {
            }});



        

             $('#idWaist').ddslick({
                 data: [
                        <?php foreach ($this->waist['list'] as $key => $val) { ?>
                        {
                            text: "<?= $val ?>",
                            value: "<?= $key ?>",
                            selected: <?= ($this->waist['value'] == $key ? 'true' : 'false') ?>,
                            description: "",
                            imageSrc: ""
                        },
                        <?php } ?>
                    ],
                 width: 175,
                 height: 500,
                 imagePosition: "left",
                 selectText: "Waist",
                 onSelected: function (data) {
                     valueChanged(data);
                 }
             });

             $('#idInseam').ddslick({
                 data: [
                        <?php foreach ($this->inseam['list'] as $key => $val) { ?>
                        {
                            text: "<?= $val ?>",
                            value: "<?= $key ?>",
                            selected: <?= ($this->inseam['value'] == $key ? 'true' : 'false') ?>,
                            description: "",
                            imageSrc: ""
                        },
                        <?php } ?>
                    ],
                 width: 175,
                 height: 500,
                 imagePosition: "left",
                 selectText: "Inseam",
                 onSelected: function (data) {
                     valueChanged(data);
                 }
             });     

             $('#idShoeSize').ddslick({
                 data: [
                        <?php foreach ($this->shoeSize['list'] as $key => $val) { ?>
                        {
                            text: "<?= $val ?>",
                            value: "<?= $key ?>",
                            selected: <?= ($this->shoeSize['value'] == $key ? 'true' : 'false') ?>,
                            description: "",
                            imageSrc: ""
                        },
                        <?php } ?>
                    ],
                 width: 175,
                 height: 500,
                 imagePosition: "left",
                 selectText: "Shoe Size",
                 onSelected: function (data) {
                     valueChanged(data);
                 }
             });                       


             $('#idJacketSize').ddslick({
                 data: [
                        <?php foreach ($this->jacketSize['list'] as $key => $val) { ?>
                        {
                            text: "<?= $val ?>",
                            value: "<?= $key ?>",
                            selected: <?= ($this->jacketSize['value'] == $key ? 'true' : 'false') ?>,
                            description: "",
                            imageSrc: ""
                        },
                        <?php } ?>
                    ],
                 width: 175,
                 height: 500,
                 imagePosition: "left",
                 selectText: "Jacket Size",
                 onSelected: function (data) {
                     valueChanged(data);
                 }
             });  


             $('#idShirtSize').ddslick({
                 data: [
                        <?php foreach ($this->shirtSize['list'] as $key => $val) { ?>
                        {
                            text: "<?= $val ?>",
                            value: "<?= $key ?>",
                            selected: <?= ($this->shirtSize['value'] == $key ? 'true' : 'false') ?>,
                            description: "",
                            imageSrc: ""
                        },
                        <?php } ?>
                    ],
                 width: 175,
                 height: 500,
                 imagePosition: "left",
                 selectText: "Shirt Sizes", 
                 onSelected: function (data) {
                     valueChanged(data);
                 }
             });
    });

</script>
<script type="text/javascript">
    $("#clearFilters").click(function(){
        var selectInput = ['waist','inseam','shoeSize','jacketSize','shirtSize'];
        var id =  ['Waist','Inseam','ShoeSize','JacketSize','ShirtSize'];
        var text = ['Waist','Inseam','Shoe Size','Jacket Size','Shirt Size'];
        $.each(selectInput, function( index, value ) {
            $('select[name=' + value  + '] option')
             .removeAttr('selected')
             .filter('[value=""]')
                 .attr('selected', true);
            //$('select[name=' + value  + '] option:first').attr('selected','selected');
            $('#id'+ id[index] +' .dd-selected-text').text(text[index]);
            $('#id'+ id[index] + ' .dd-selected-value').val("");
            $('#id'+ id[index] +' ul.dd-options li a').each(function (index, element) {
                if((index == 0) && !$(element).hasClass("dd-option-selected")){
                    $(element).addClass("dd-option-selected");
                }
                else {
                    $(element).removeClass("dd-option-selected");
                }
            });

            $("#id"+id[index]+'Other').val("").hide();
        });
         
    });
</script>