 <?php echo $this->headLink()
                 ->appendStylesheet($this->basePath() . '/assets/css/you_page.css');
 ?>
 
<div id="size_profile_pages" class="content-page row">             
    <div class="col-lg-10 col-lg-offset-1 topnavi" id="size_profile">
        <div class="brand-box">
            <div class="menu-box <?=($this->mode=='edit')?'menu-box-bigger':''?>">
                <ul class="about">
                    <li>
                        <a href="/profile">LOOK YOU&#39;D WEAR<div class="fa"><i class="fa fa-check green"></i></div></a>
                    </li>
                    <li>
                        <a href="/profile/you">ABOUT YOU<div class="fa"><i class="fa fa-check green"></i></div></a>
                    </li>
                    <li class="blue">
                        <a class="active">YOUR SIZE<div class="fa"></div></a>
                    </li>
                    <!-- <li>
                        <a>FAVOURITE BRAND<div class="fa"></div></a>
                    </li> -->
                    <li>
                        <a href="/profile/price">YOUR LOOK<div class="fa"></div></a>
                    </li>
                    <?php if( $this->mode == 'new' ) { ?>
                    <li>
                        <a href="/profile/signup">SIGN UP<div class="fa"></div></a>
                    </li>
                    <?php }?>
                </ul>
                <div class="clr"></div>

            </div><!--menu-box -->

            <div class="clr"></div>
            <div class="form-group">
                    <ul class="list-radio list-radio-find-stitch list-inline">
                        <li><div class="radio radio-find-stitch">
                            <input type="radio" disabled name="radio4" id="radio1" value="option1" >
                            <label for="radio1" class="radio-label">
                            </label>
                        </div>
                        </li>
                        <li>
                            <div class="radio radio-find-stitch">
                                <input type="radio" disabled name="radio4" id="radio2" value="option1" >
                                <label for="radio2" class="radio-label">
                                </label>
                            </div>
                        </li>
                        <li>
                            <div class="radio radio-find-stitch">
                                <input type="radio" disabled name="radio4" id="radio3" value="option1" checked="">
                                <label for="radio3" class="radio-label">
                                </label>
                            </div>
                        </li>
                             <li><div class="radio radio-find-stitch">
                            <input type="radio" disabled name="radio4" id="radio4" value="option1" >
                            <label for="radio4" class="radio-label">
                            </label>
                        </div>
                        </li>
                        <li>
                            <div class="radio radio-find-stitch">
                                <input type="radio" disabled name="radio4" id="radio5" value="option1" >
                                <label for="radio5" class="radio-label">
                                </label>
                            </div>
                        </li>
                        
                    </ul>
                </div>
            <div class="choose-box">
                <div class="wrap_title-page">
                    <div class="shadow_title-page">
                        <h1 class="title-page">What Size do you Wear?</h1>
                    </div>
                </div>
            </div><!--choose-box -->
        </div><!--brand-box -->

        <div class="clr"></div>

        <form id="myForm" method="POST" class="col-lg-12">
            <div class="size_box row">
                <div class="dropdown-menu_size">
                    <div class="select_style">
                        <div id="idWaist"></div>
                        <div class="text_box">
                            <div class="text-input"><input type="text" name="waistOther" class="others" id="idWaistOther" value="<?php echo $this->waistOther;?>"/></div>
                        </div>
                    </div>
                    <div class="select_style">
                        <div id="idInseam"></div>
                        <div class="text_box">
                            <div class="text-input"><input type="text" name="inseamOther" class="others" id="idInseamOther" value="<?php echo $this->inseamOther;?>"/></div>
                        </div>
                    </div>
                    <div class="select_style">
                        <div id="idShoeSize"></div>
                        <div class="text_box">
                            <div class="text-input"><input type="text" name="shoeSizeOther" class="others" id="idShoeSizeOther" value="<?php echo $this->shoeSizeOther;?>"/></div>
                        </div>
                    </div>
                    <div class="select_style">
                        <div id="idJacketSize"></div>
                        <div class="text_box">
                            <div class="text-input"><input type="text" name="jacketSizeOther" class="others" id="idJacketSizeOther" value="<?php echo $this->jacketSizeOther;?>"/></div>
                        </div>
                    </div>
                    <div class="select_style">
                        <div id="idShirtSize"></div>
                        <div class="text_box">
                            <div class="text-input" id="nomargin"><input type="text" name="shirtSizeOther" class="others" id="idShirtSizeOther" value="<?php echo $this->shirtSizeOther;?>" /></div>
                        </div>
                    </div>
                    
                    <div class="clr"></div>
                </div>

                <div class="clr"></div>
                <div id="form_input_dn" style="poistion:absolute; display:none">       
                                    
                        <select name="<?= $this->waist['name'] ?>" class="select selectpicker" id="idWaistHidden">
                        <!-- <option value="" class="option">Waist</option> -->
                        <?php foreach ($this->waist['list'] as $key => $val) { ?><option value="<?= $key ?>" class="option" <?= ($this->waist['value'] == $key ? 'selected="selected"' : '') ?>><?= $val ?></option><?php } ?>
                        </select>

                        <select name="<?= $this->inseam['name'] ?>" class="select selectpicker" id="idInseamHidden">
                       
                        <?php foreach ($this->inseam['list'] as $key => $val) { ?><option value="<?= $key ?>" class="option" <?= ($this->inseam['value'] == $key ? 'selected="selected"' : '') ?>><?= $val ?></option><?php } ?>
                        </select>

                        <select name="<?= $this->shoeSize['name'] ?>" class="select selectpicker" id="idShoeSizeHidden">
                        <?php foreach ($this->shoeSize['list'] as $key => $val) { ?><option value="<?= $key ?>" class="option" <?= ($this->shoeSize['value'] == $key ? 'selected="selected"' : '') ?>><?= $val ?></option><?php } ?>
                        </select>

                        <select name="<?= $this->jacketSize['name'] ?>" class="select selectpicker" id="idJacketSizeHidden">
                       <?php foreach ($this->jacketSize['list'] as $key => $val) { ?><option  value="<?= $key ?>" class="option" <?= ($this->jacketSize['value'] == $key ? 'selected="selected"' : '') ?>><?= $val ?></option><?php } ?>
                        </select>

                        <select name="<?= $this->shirtSize['name'] ?>" class="select selectpicker nomargin" id="idShirtSizeHidden">
                        <!-- <option value="" class="option">Shirt Size</option> -->
                        <?php foreach ($this->shirtSize['list'] as $key => $val) { ?><option value="<?= $key ?>" class="option" <?= ($this->shirtSize['value'] == $key ? 'selected="selected"' : '') ?>><?= $val ?></option><?php } ?>
                        </select>
                     </div>
                
            </div><!--size_box-->
            
            
                <div id="next"><a href="javascript:void(0);" class="next fr btn-st-blue" id="btnNextStep">NEXT ></a>
                    <div class="clr"></div>
                    <div class="clr"></div>
                    <a href="javascript:void(0)" id="clearFilters" class="italic-box fr hlink"> <i>Clear filters</i></a>
                    <div class="clr"></div>
                </div>


        </form>
        <div class="clr"></div>

    </div>
</div>  
<script type="text/javascript">
    $(window).on('load', function () {
        function valueChanged( data ) {
            $('#' + data.original.attr('id') + 'Hidden').val( data.selectedData.value );
            
            if (data.selectedData.value == 'other') {
                $('#' + data.original.attr('id') + 'HiddenOther').val('');
                $('#' +data.original.attr('id') + 'Other').css('display', 'block');
            }
            else {
                $('#' + data.original.attr('id') + 'Other').css('display', 'none');
            }

            // $(".size_box").css('height', '121px');
            $("select.selectpicker").each(function () {
                if (this.value == 'other') {
                   $(".text-input").css('margin-top', '33px');
                }
            });
            
        }   
        $("select.selectpicker").each(function () {
            if (this.value == 'other') {
                $('#' + this.id.replace("Hidden", "") + 'Other').css('display', 'block');
                
            }
            else {
                $('#' + this.id.replace("Hidden", "") + 'Other').css('display', 'none');
            }
        });
            

        $("#btnNextStep").on("click", function (e) {
            var allOK = true;
            $("select.selectpicker").each(function () {
                if ((this.value == '') || (this.value == 'other' && $('#' + this.id.replace("Hidden", "") + 'Other').val() == '')) {
                    myalert('myalertid1','type_missing','Oops', 'Seems like you forgot to tell us your '+ $(this).find('option:first').html() + '. Don\'t be shy we are here to help.','');      
                     $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
                    $("button.my_btn_ok").click(function(){
                        $('a.close-reveal-modal').trigger('click');
                        });
                    });        
                    allOK = false;
                    return false;
                }
            });
            if (allOK) {
                $("#myForm").submit();
            }
        });
        var url = "/profile/profiletraking";
        $.ajax({
            url: url,
            type: 'POST',
            data: {page: 'size'},
            dataType: 'json',
            success: function (result) {
            }});



        

             $('#idWaist').ddslick({
                 data: [
                        <?php foreach ($this->waist['list'] as $key => $val) { ?>
                        {
                            text: "<?= $val ?>",
                            value: "<?= $key ?>",
                            selected: <?= ($this->waist['value'] == $key ? 'true' : 'false') ?>,
                            description: "",
                            imageSrc: ""
                        },
                        <?php } ?>
                    ],
                 width: "100%",
                 height: 400,
                 imagePosition: "left",
                 selectText: "Waist",
                 onSelected: function (data) {
                     valueChanged(data);
                 }
             });

             $('#idInseam').ddslick({
                 data: [
                        <?php foreach ($this->inseam['list'] as $key => $val) { ?>
                        {
                            text: "<?= $val ?>",
                            value: "<?= $key ?>",
                            selected: <?= ($this->inseam['value'] == $key ? 'true' : 'false') ?>,
                            description: "",
                            imageSrc: ""
                        },
                        <?php } ?>
                    ],
                 width: "100%",
                 height: 400,
                 imagePosition: "left",
                 selectText: "Inseam",
                 onSelected: function (data) {
                     valueChanged(data);
                 }
             });     

             $('#idShoeSize').ddslick({
                 data: [
                        <?php foreach ($this->shoeSize['list'] as $key => $val) { ?>
                        {
                            text: "<?= $val ?>",
                            value: "<?= $key ?>",
                            selected: <?= ($this->shoeSize['value'] == $key ? 'true' : 'false') ?>,
                            description: "",
                            imageSrc: ""
                        },
                        <?php } ?>
                    ],
                 width: "100%",
                 height: 400,
                 imagePosition: "left",
                 selectText: "Shoe Size",
                 onSelected: function (data) {
                     valueChanged(data);
                 }
             });                       


             $('#idJacketSize').ddslick({
                 data: [
                        <?php foreach ($this->jacketSize['list'] as $key => $val) { ?>
                        {
                            text: "<?= $val ?>",
                            value: "<?= $key ?>",
                            selected: <?= ($this->jacketSize['value'] == $key ? 'true' : 'false') ?>,
                            description: "",
                            imageSrc: ""
                        },
                        <?php } ?>
                    ],
                 width: "100%",
                 height: 400,
                 imagePosition: "left",
                 selectText: "Jacket Size",
                 onSelected: function (data) {
                     valueChanged(data);
                 }
             });  


             $('#idShirtSize').ddslick({
                 data: [
                        <?php foreach ($this->shirtSize['list'] as $key => $val) { ?>
                        {
                            text: "<?= $val ?>",
                            value: "<?= $key ?>",
                            selected: <?= ($this->shirtSize['value'] == $key ? 'true' : 'false') ?>,
                            description: "",
                            imageSrc: ""
                        },
                        <?php } ?>
                    ],
                 width: "100%",
                 height: 400,
                 imagePosition: "left",
                 selectText: "Shirt Sizes", 
                 onSelected: function (data) {
                     valueChanged(data);
                 }
             });
    });

</script>
<script type="text/javascript">
   $("#clearFilters").click(function(){
        var selectInput = ['waist','inseam','shoeSize','jacketSize','shirtSize'];
        var id =  ['Waist','Inseam','ShoeSize','JacketSize','ShirtSize'];
        var text = ['Waist','Inseam','Shoe Size','Jacket Size','Shirt Size'];
        $.each(selectInput, function( index, value ) {
            $('select[name=' + value  + '] option')
             .removeAttr('selected')
             .filter('[value=""]')
                 .attr('selected', true);
            $('#id'+ id[index] +' .dd-selected-text').text(text[index]);
            $('#id'+ id[index] + ' .dd-selected-value').val("");
            $('#id'+ id[index] +' ul.dd-options li a').each(function (index, element) {
                if((index == 0) && !$(element).hasClass("dd-option-selected")){
                    $(element).addClass("dd-option-selected");
                }
                else {
                    $(element).removeClass("dd-option-selected");
                }
            });

            $("#id"+id[index]+'Other').val("").hide();
        });
         
    });
</script>