<?php
$weightSliderDefault = $this->weight['value'];
$heightSliderDefault = $this->height['value'];   
?>
 <?php echo $this->headLink()
                 ->appendStylesheet($this->basePath() . '/assets/css/you_page.css')
                 ->appendStylesheet($this->basePath() . '/templates/mobile/ion.rangeSlider/css/ion.rangeSlider.css')
                 ->appendStylesheet($this->basePath() . '/templates/mobile/ion.rangeSlider/css/ion.rangeSlider.skinHTML5.css')
                 ;
 ?>

<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.core.js"></script>
<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.widget.js"></script>
<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.mouse.js"></script>
<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.slider.js"></script>

<div class="content-page row" id="profile_you_page">
    <div id="profile-you-page" class="col-lg-10 col-lg-offset-1 topnavi">
        <div class="brand-box">
            <div class="menu-box <?=($this->mode=='edit')?'menu-box-bigger':''?>">
                <ul class="about">
                    <li>
                        <a href="/profile">LOOK YOU&#39;D WEAR<div class="fa"><i class="fa fa-check green"></i></div></a>
                    </li>
                    <li class="blue">
                        <a class="active">ABOUT YOU<div class="fa"></div></a>
                    </li>
                    <li>
                        <a href="/profile/size">YOUR SIZE<div class="fa"></div></a>
                    </li>
                    <li>
                        <a href="/profile/price">YOUR LOOK<div class="fa"></div></a>
                    </li>
                    <?php if( $this->mode == 'new' ) { ?>
                    <li>
                        <a href="/profile/signup">SIGN UP<div class="fa"></div></a>
                    </li>
                    <?php }?>
                </ul>
                <div class="clr"></div>
            </div><!--menu-box -->

            <div class="clr"></div>
            <div class="form-group">
                    <ul class="list-radio list-radio-find-stitch list-inline">
                        <li><div class="radio radio-find-stitch">
                            <input type="radio" disabled name="radio4" id="radio1" value="option1"  >
                            <label for="radio1" class="radio-label">
                            </label>
                        </div>
                        </li>
                        <li>
                            <div class="radio radio-find-stitch">
                                <input type="radio" disabled name="radio4" id="radio2" value="option1" checked="">
                                <label for="radio2" class="radio-label">
                                </label>
                            </div>
                        </li>
                        <li>
                            <div class="radio radio-find-stitch">
                                <input type="radio" disabled name="radio4" id="radio3" value="option1" >
                                <label for="radio3" class="radio-label">
                                </label>
                            </div>
                        </li>
                             <li><div class="radio radio-find-stitch">
                            <input type="radio" disabled name="radio4" id="radio4" value="option1" >
                            <label for="radio4" class="radio-label">
                            </label>
                        </div>
                        </li>
                        <li>
                            <div class="radio radio-find-stitch">
                                <input type="radio" disabled name="radio4" id="radio5" value="option1" >
                                <label for="radio5" class="radio-label">
                                </label>
                            </div>
                        </li>
                        
                    </ul>
                </div>
            <div class="page_one-box">
                <h1>Tell us About You </h1>
            </div> <!--page_one-box -->
        </div><!--brand-box -->

        <div class="clr"></div>

        <div class="about_box">
            <div class="about_block" >
                <div class="col-lg-3 col-xs-12 left_sb">
                    <h2>How Much Do You Weight?</h2>
                </div>
                <div class="col-lg-9 col-xs-12 right_sb" id="box_weight">
                    <div class="box_left">
                        <input type="text" class="lb" id="weightSliderValue"/>
                        <span class="lb_unit">lbs</span>
                    </div>    
                    <div class="box_right">
                        <div class="line-bar">
                           <div class="ranger">
                                <input type="text" id="weightSlider" value="" name="weighSlider" />
                            </div>
                        </div>  
                    </div>
                    
                </div>
            </div>
            <div class="about_block">
                <div class="col-lg-3 col-xs-12 left_sb">
                    <h2>How Tall Are You?</h2>
                </div>
                <div class="col-lg-9 col-xs-12 right_sb" id="box_height">
                    <input type="text" class="lb" id="heightSliderValue" /> 
                    <span class="point-char">.</span> 
                    <input type="text" class="lb" id="heightSliderValueInch" />
                    <span class="lb_unit">feet</span>
                    <div class="line-bar">
                        <!-- <div class="content">
                            <div id="heightSlider"></div>
                            <div class="sliderSteps"></div>
                        </div> -->
                        <div class="ranger">
                            <input type="text" id="heightSlider" value="" name="heightSlider" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="body_shape about_block">
                <div id="listBODYSHAPE">
                    <div class="col-lg-3 col-xs-12 left_sb">
                        <h2>What Is Your Body Shape?</h2>
                    </div>    
                    <div class="col-lg-9 col-xs-12 right_sb">
                        <?php 
                        foreach($this->body_shape as $aBox) { 
                            $classes = $aBox['value'] ? 'check-one1 fa fa-check' : 'check-blank1';
                        ?>
                            <a href="#" id="id<?php echo $aBox['name']?>" class="thumb-info body-shape <?php echo ($aBox['value']?'lock':'')?>">
                                <div class="about_img ">
                                    <img src="/img/profile/<?php echo $aBox['img']?>" class="img-reposive" alt="image" />
                                    <div class="checkbox_wrap clr">
                                        <p class="body_shape_name"><?php echo str_replace("_"," ",$aBox['name'])?></p>
                                        <div class="checkmark <?php echo $classes;?>"></div>
                                    </div>
                                </div>
                            </a>
                        <?php } //end foreach ?>
                    </div>
                </div>
            </div>
            <div class="skin_tone about_block">
                <div id="listSKINTONE">
                    <div class="col-lg-3 col-xs-12 left_sb">
                        <h2>What is Your Skin Tone?</h2>
                    </div>
                    <div class="col-lg-9 col-xs-12 right_sb">
                    <?php foreach($this->skin_tone as $aBox) { 
                        $classes = $aBox['value'] ? 'check-one1 fa fa-check' : 'check-blank1';
                        ?>
                    <a href="#" id="id<?php echo $aBox['name']?>" class="thumb-info skin-tone <?php echo ($aBox['value']?'lock':'')?>">
                    <div class="about_img ">
                        <div class="wrap_img">
                             <img src="/img/profile/<?php echo $aBox['img']?>" alt="image" />
                            <div class="clr"></div>
                            <div class="checkmark <?php echo $classes;?>"></div>
                        </div>        
                    </div>
                    </a>
                    <?php } ?>
                    </div>
                </div>
            </div>
            <div class="clr"></div>
        </div><!--about-box-->

        <div class="brand-box">
            <a href="javascript:void(0);" class="next fr btn-st-blue" id="btnNextStep">NEXT ></a>
            <div class="clr"></div>
            <a href="javascript:void(0)" id="clearFilters" class="italic-box fr hlink"> <i>Clear filters</i></a>
            <div class="clr"></div>
        </div>

    </div><!--container-->
</div>
<form id="myForm" method="POST">
    <input type="hidden" id="idWeightSliderInput" name="<?php echo $this->weight['name']?>" value="<?php echo $this->weight['value']?>" />
    <input type="hidden" id="idHeightSliderInput" name="<?php echo $this->height['name']?>" value="<?php echo $this->height['value']?>" />
    <?php foreach($this->body_shape as $aBox) {?><input type="checkbox" id="id<?php echo $aBox['name']?>Input" name="<?php echo $aBox['name']?>" style="display:none" /><?php }?>
    <?php foreach($this->skin_tone as $aBox) {?><input type="checkbox" id="id<?php echo $aBox['name']?>Input" name="<?php echo $aBox['name']?>" style="display:none" /><?php }?>
    <input type="hidden" name="myFormBtn" value="yes" />
</form>
<script src="<?php echo $this->basePath().'/templates/mobile' ?>/ion.rangeSlider/js/ion.rangeSlider.min.js"></script>
<script>
$(function() {
    /*** Script for Close Popup alert ***/
    $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
        $("button.my_btn_ok").click(function(){
            $('a.close-reveal-modal').trigger('click');
        });
    });

    var colMD = $( ".col-md-12" );

    /*** WEIGHT SLIDER ***/
    var weightSliderDefault = '<?php echo $weightSliderDefault ?>';
    weightMin = <?php echo $this->weight['min']?>;
    weightMax = <?php echo $this->weight['max']?>;
    weightStep = <?php echo $this->weight['step']?>;
    weightSliderDefault = weightSliderDefault >= weightMin ? weightSliderDefault : '';
    
    $("#weightSliderValue").val(weightSliderDefault >= weightMax ? weightMax+'+' : weightSliderDefault);
    $("#idWeightSliderInput").val(weightSliderDefault);
    //Process when client scroll slider
    // $( "#weightSlider" ).slider({
    //     value: <?php echo $weightSliderDefault?>,
    //     min: weightMin,
    //     max: weightMax,
    //     step: weightStep,
    //     slide: function( event, ui ) {
    //         $( "#weightSliderValue" ).val( ui.value + (ui.value==weightMax?'+':''));
    //         $( "#idWeightSliderInput" ).val(ui.value);
    //     },
        
    // });
    $("#weightSlider").ionRangeSlider({
            hide_min_max: true,
            type: "single",
            min: weightMin,
            max: weightMax,
            from: (weightSliderDefault > weightMax) ? weightMax : weightSliderDefault,
            keyboard: true,
            step: weightStep,
            hide_from_to:true,
            onStart: function (value) {
                if($( "#idHeightSliderInput" ).val() > 0) {
                    $("#weightSliderValue").val(value.from);
                    $( "#idWeightSliderInput" ).val(value.from);
                }
            },
            onChange:function(){
                weightInput = $('#weightSlider').prop("value");
                $("#weightSliderValue").val(weightInput);
                $("#idWeightSliderInput").val(weightInput);
            }
        });
    //Process when client input anything to textbox
    $("#weightSliderValue").keyup(function(){
        this.value = this.value.replace(/[^0-9]/g,'');
        var newWeight = this.value;
        $( "#weightSlider" ).slider({
            value: newWeight,
        });
        $( "#idWeightSliderInput" ).val(newWeight);
    });
    //Process when client move out textbox
    $("#weightSliderValue").change(function(){
        var newWeight = this.value;
        if(newWeight < weightMin){
            $( "#idWeightSliderInput" ).val('');
            myalert('myalertid6','type_missing','Oops', 'Min weight must be '+weightMin+' lbs.','');
        }
        if(newWeight > weightMax){
            $( "#weightSliderValue" ).val(weightMax+'+');
        }
    });

    /*** HEIGHT SLIDER ***/
    var heightSliderDefault = '<?php echo $heightSliderDefault ?>';
    var heightMax = <?php echo $this->height['max'] ?>;
    var heightMin = <?php echo $this->height['min'] ?>;
    var heightStep = 0.1;

    <?php 
    $iSelectedIndex = 0;
    $sHeightValues = array();
    for($i=$this->height['min']; $i<$this->height['max']; $i++) {
        for($j=0; $j<12; $j++) {
            $sHeightValues[] = "{$i}.{$j}";             
            if($heightSliderDefault == "$i.$j"){
                $iSelectedIndex = count($sHeightValues)-1;
            }
        }
    }
    $sHeightValues[] = $this->height['max'] . '.0';
    if($heightSliderDefault >= ($this->height['max'])){
        $iSelectedIndex = count($sHeightValues)-1;
    }
    
    echo 'var aHeightValues = ["' . implode('","', $sHeightValues) . '"];'; 
    ?>
    
    heightSliderDefault = heightSliderDefault >= heightMin ? heightSliderDefault : '';
    var heightArr = heightSliderDefault.split(".");
    $("#heightSliderValue").val(heightSliderDefault >= heightMax ? heightMax : heightArr[0]);
    $("#heightSliderValueInch").val(heightSliderDefault >= heightMax ? '0+' : heightArr[1]);
    $("#idHeightSliderInput").val(heightSliderDefault);
    //Process when client scroll slider
    // $( "#heightSlider" ).slider({
    //     value: <?php echo $iSelectedIndex?>,
    //     min: 0,
    //     max: <?php echo count($sHeightValues)-1?>,
    //     step: 1,
    //     slide: function( event, ui ) {
    //         var heightArr = aHeightValues[ui.value].split(".");
    //         $( "#heightSliderValue" ).val(heightArr[0]);
    //         $( "#heightSliderValueInch" ).val(heightArr[1] + (aHeightValues[ui.value]==<?=$this->height['max']?>?'+':''));
    //         $( "#idHeightSliderInput" ).val(aHeightValues[ui.value]);
    //     }
    // });
    $("#heightSlider").ionRangeSlider({
            hide_min_max: true,
            type: "single",
            min: 0,
            max: <?php echo count($sHeightValues)-1?>,
            from: <?php echo $iSelectedIndex ?>,
            keyboard: true,
            step: 1,
            hide_from_to:true,
            onStart: function (value) {
                var heightNew = aHeightValues[value.from];
                if($( "#idHeightSliderInput" ).val() > 0) {
                    var heightArr = heightNew.split(".");
                    $("#heightSliderValue").val(heightNew >= heightMax ? heightMaxArr[0] : heightArr[0]);
                    $("#heightSliderValueInch").val(heightNew >= heightMax ? (heightMaxArr[1]>0?heightMaxArr[1]:'0'+'+') : heightArr[1]);
                }
            },
            onChange:function(){
                heightNew = $('#heightSlider').prop("value");
                console.log(heightNew);
                var heightArr = aHeightValues[heightNew].split(".");
                $("#heightSliderValue").val(heightArr[0] >= heightMax ? heightMax : heightArr[0]);
                $("#heightSliderValueInch").val(heightArr[0] >= heightMax ? '0+' : heightArr[1]);
                $("#idHeightSliderInput").val(aHeightValues[heightNew]);
            }
        });
    //Process when client input anything to textbox
    $("#heightSliderValue").keyup(function(){
        this.value = this.value.replace(/[^0-9]/g,'');
        $("#heightSliderValueInch").val($("#heightSliderValueInch").val().replace("+", ""));
        var newHeightFeet = this.value;
        var newHeightInch = $("#heightSliderValueInch").val();
        var heightMinArr = heightMin.toFixed(2).split(".");
        $( "#heightSlider" ).slider({
            value: (newHeightFeet-heightMinArr[0])*12+(newHeightInch-heightMinArr[1])
        });
        $( "#idHeightSliderInput" ).val(newHeightFeet+'.'+newHeightInch);
    });
    $("#heightSliderValueInch").keyup(function(){
        this.value = this.value.replace(/[^0-9]/g,'');
        var newHeightFeet = $("#heightSliderValue").val();
        var newHeightInch = this.value;
        var heightMinArr = heightMin.toFixed(2).split(".");
        if(newHeightInch < 0 || newHeightInch > 11){
            myalert('myalertidHeightNotValid','type_missing','Oops', 'Height must be from X.0 to X.11','');
            $(this).val('');
        } else {
            $( "#heightSlider" ).slider({
                value: (newHeightFeet-heightMinArr[0])*12+(newHeightInch-heightMinArr[1])
            });
            $( "#idHeightSliderInput" ).val(newHeightFeet+'.'+newHeightInch);
        }
    });
    //Process when client move out textbox
    $("#heightSliderValue").change(function(){
        $("#heightSliderValueInch").val($("#heightSliderValueInch").val().replace("+", ""));
        var newHeightFeet = this.value;
        var newHeightInch = $("#heightSliderValueInch").val();
        var newHeight = parseFloat(newHeightFeet)+parseFloat(newHeightInch/10);
        if(newHeight < heightMin){
            $( "#idHeightSliderInput" ).val('');
            myalert('alertErrorHeightFeet','type_missing','Oops', 'Min height must be '+heightMin+' feet.','');
        }
        if(newHeight >= heightMax){
            var heightMaxArr = heightMax.toFixed(2).split(".");
            $( "#heightSliderValue" ).val(heightMaxArr[0]);
            $( "#heightSliderValueInch" ).val(heightMaxArr[1]>0?heightMaxArr[1]:'0' + '+');
        }
    });
    $("#heightSliderValueInch").change(function(){
        var newHeightFeet = $("#heightSliderValue").val();
        var newHeightInch = this.value;
        var newHeight = parseFloat(newHeightFeet)+parseFloat(newHeightInch/10);
        if(newHeight < heightMin){
            $( "#idHeightSliderInput" ).val('');
            myalert('alertErrorHeightInch','type_missing','Oops', 'Min height must be '+heightMin+' feet.','');
        }
        if(newHeight >= heightMax){
            var heightMaxArr = heightMax.toFixed(2).split(".");
            $( "#heightSliderValue" ).val(heightMaxArr[0]);
            $( "#heightSliderValueInch" ).val(heightMaxArr[1]>0?heightMaxArr[1]:'0'+'+');
        }
    });

    /*** CLIENT SUBMIT ***/
    $("#btnNextStep").on("click", function(e) {
        if( $( "#idWeightSliderInput" ).val() < weightMin ) {
            myalert('myalertid1','type_missing','Oops', 'Seems like you forgot to tell us your weight. Don\'t be shy we are here to help.','');
            $('html, body').animate({scrollTop: $("#weightSliderValue").offset().top - 200}, 500);
            $( "#weightSliderValue" ).val('');
            return false;
        }
        if( $( "#idHeightSliderInput" ).val() < heightMin ) {
            myalert('myalertid2','type_missing','Oops', 'Seems like you forgot to tell us your height. Don\'t be shy we are here to help.','');  
            $('html, body').animate({scrollTop: $("#heightSliderValue").offset().top - 200}, 500);
            $( "#heightSliderValue" ).val('');
            return false;
        }

        if( $("#listBODYSHAPE .lock").length < 1 ) {
            e.preventDefault();      
            myalert('myalertid3','type_missing','Oops','Seems like you forgot to tell us your body shape. Don\'t be shy we are here to help.','');  
            $('html, body').animate({scrollTop: $("#listBODYSHAPE").offset().top - 200}, 500);         
            return false;
        }
        if( $("#listSKINTONE .lock").length < 1 ) {   
            myalert('myalertid4','type_missing','Oops', 'Seems like you forgot to tell us your skin tone. Don\'t be shy we are here to help.','');  
            $('html, body').animate({scrollTop: $("#listSKINTONE").offset().top - 200}, 500);         
            return false;
        }

        $(".thumb-info").each( function( index, element ){
            if($(element).hasClass("lock")) {
                $("#"+element.id+"Input").prop( "checked", true );
            } else {
                $("#"+element.id+"Input").prop( "checked", false );
            }
        });

        $( "#myForm" ).submit();
    });

    /*** CLEAR FILTERS ***/
    $("#clearFilters").on("click", function(e) {
        $(".thumb-info").each(function (index, element) {
            if ($(element).hasClass("lock")) {
                $("#" + element.id + "Input").prop("checked", false);
                $(element).removeClass("lock");
                $(element).find(".checkmark").removeClass("check-one1 fa fa-check").addClass("check-blank1");
            }
        });

        $("#idWeightSliderInput").val(0);
        $("#weightSliderValue").val("");
        $("#idHeightSliderInput").val(0);
        $("#heightSliderValue").val("");
        $("#weightSlider").slider({ value: 0 });
        $("#heightSlider").slider({ value: 0 });
    });

    /*** CHOOSE OPTION THUMBNAIL ***/
    $(".thumb-info").on("click", function(e) {
        e.preventDefault();

        if($(this).hasClass("lock")) {
            if($(this).hasClass("body-shape")) {
                $("#listBODYSHAPE .checkmark ").removeClass("check-one1 fa fa-check").addClass("check-blank1");
                $(".body-shape").removeClass("lock");
            }
            if($(this).hasClass("skin-tone")) {
                $(this).parent( "#listSKINTONE" ).find('.checkmark').removeClass("check-one1 fa fa-check").addClass("check-blank1");
                $(".skin-tone").removeClass("lock");
            }

            $(this).removeClass("lock");
            $(this).find('.checkmark').removeClass("check-one1 fa fa-check");
            $(this).find('.checkmark').addClass("check-blank1");
        } else {
            if($(this).hasClass("body-shape")) {
                $("#listBODYSHAPE .checkmark ").removeClass("check-one1 fa fa-check").addClass("check-blank1");
                $(".body-shape").removeClass("lock");
            }
            if($(this).hasClass("skin-tone")) {
                $(this).parent( "#listSKINTONE" ).find('.checkmark').removeClass("check-one1 fa fa-check").addClass("check-blank1");
                $(".skin-tone").removeClass("lock");
            }

            $(this).addClass("lock");
            $(this).find('.checkmark').removeClass("check-blank1");
            $(this).find('.checkmark').addClass("check-one1 fa fa-check");
        }

        return false;
    });

});

$(window).load(function () {
    var url = "/profile/profiletraking";
    $.ajax({
        url: url,
        type: 'POST',
        data: {page: 'you'},
        dataType: 'json',
        success: function (result) {
        }});
    
});
</script>