<?php
$outfitsData = $this->outfits;
?>


            <?php if (isset($outfitsData) && !empty($outfitsData)) { ?>

            <?php foreach($outfitsData as $key => $outfitData) { ?>
            


            <div class="big_box">
                <div class="img_box_main">
                    <div class="main_big_product_box">
                        <?php if(isset($outfitData[0]['feedId']) && $outfitData[0]['onsale'] == 'Y') {?><div class="salePrice"><?php echo round(($outfitData[0]['price']-$outfitData[0]['saleprice'])/$outfitData[0]['price']*100)?>%<br/>OFF</div><?php }?>
                        <div class="main_big_product_img_box">
                            <?php if (isset($outfitData[0]['feedId']) && !empty($outfitData[0]['feedId'])) { ?>
                                <img src="<?php echo $outfitData[0]['imageurl']; ?>" id="img" height="369px">
                            <?php } else { ?>
                                <img src="/img/big_img.jpg" alt="product" />
                            <?php } ?>
                        </div>
                        <div class="main_big_product_tag_box">
                        </div>
                        <?php if (isset($outfitData[0]['feedId']) && !empty($outfitData[0]['feedId'])) { ?>
                        <div class="box-block1">
                            <div class="pad">
                                <span class="like_<?php echo  $outfitData[0]['id']; ?>"><?php echo  $outfitData[0]['likesCount'] != 0 ? $outfitData[0]['likesCount'] . ' likes' : ""; ?></span>
                                <h4><?php echo $this->string_helper($outfitData[0]['caption']); ?></h4>
                                <p><?php echo ($outfitData[0]['onsale']=='Y'?$outfitData[0]['saleprice']:$outfitData[0]['price'])?><span class="currency"><?php echo $outfitData[0]['currency'] ?></span></p>
                                <a class="buy_now my_tooltip" title="Purchase article through our partner" target="_blank" href="<?php echo $this->url('service/articlebought', array('feeddataid' => base64_encode($outfitData[0]['id']))); ?>">buy now</a>
                                <br>
                                <a class="discover my_tooltip" title="Learn more about this article" data-value="<?php echo $outfitData[0]['id']; ?>" href="javascript:void(0)">DISCOVER <img src="/img/right1.png" id="im"></a>
                            </div>
                            <div class="social_box1">
                                <?php
                                $page_url = $this->serverUrl() . '/service/feeddatadetail/' . $outfitData[0]['id'] . '/' . rand();
                                $title = 'ELNove - ' . $outfitData[0]['caption'];
                                ?>
                                <ul>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/f.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/pinterest/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/p1.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/t.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/google_plusone_share/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/g.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/email/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/msg.png"></a></li>
                                </ul>
                            </div>
                        </div>
                        <?php } ?>
                    </div>

                    <div class="main_sm_product_box">
                        <?php if(isset($outfitData[1]['feedId']) && $outfitData[1]['onsale'] == 'Y') {?><div class="salePrice"><?php echo round(($outfitData[1]['price']-$outfitData[1]['saleprice'])/$outfitData[1]['price']*100)?>%<br/>OFF</div><?php }?>
                        <div class="main_sm_product_img_box">
                            <?php if (isset($outfitData[1]['feedId']) && !empty($outfitData[1]['feedId'])) { ?>
                                <img src="<?php echo $outfitData[1]['imageurl']; ?>" id="img" height="251px">
                            <?php } else { ?>
                                <img src="/img/small_img2.jpg" alt="product" />
                            <?php } ?>
                        </div>
                        <div class="main_sm_product_tag_box">
                        </div>
                        <?php if (isset($outfitData[1]['feedId']) && !empty($outfitData[1]['feedId'])) { ?>
                        <div class="box-block2 blok1">
                            <div class="pad">
                                <span class="like_<?php echo  $outfitData[1]['id']; ?>"><?php echo  $outfitData[1]['likesCount'] != 0 ? $outfitData[1]['likesCount'] . ' likes' : ""; ?></span>
                                <h4><?php echo $this->string_helper($outfitData[1]['caption']); ?></h4>
                                <p><?php echo ($outfitData[1]['onsale']=='Y'?$outfitData[1]['saleprice']:$outfitData[1]['price'])?><span class="currency"><?php echo $outfitData[1]['currency'] ?></span></p>
                                <a class="buy_now my_tooltip" title="Purchase article through our partner" target="_blank" href="<?php echo $this->url('service/articlebought', array('feeddataid' => base64_encode($outfitData[1]['id']))); ?>">buy now</a>
                                <br>
                                <a class="discover my_tooltip" title="Learn more about this article" data-value="<?php echo $outfitData[1]['id']; ?>" href="javascript:void(0)">DISCOVER <img src="/img/right1.png" id="im"></a>
                            </div>
                            <div class="social_box1">
                                <?php
                                $page_url = $this->serverUrl() . '/service/feeddatadetail/' . $outfitData[1]['id'] . '/' . rand();
                                $title = 'ELNove - ' . $outfitData[1]['caption'];
                                ?>
                                <ul>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/f.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/pinterest/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/p1.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/t.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/google_plusone_share/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/g.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/email/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/msg.png"></a></li>
                                </ul>
                            </div>
                        </div>
                        <?php } ?>
                    </div>

                    <div class="main_sm_product_box">
                        <?php if(isset($outfitData[2]['feedId']) && $outfitData[2]['onsale'] == 'Y') {?><div class="salePrice"><?php echo round(($outfitData[2]['price']-$outfitData[2]['saleprice'])/$outfitData[2]['price']*100)?>%<br/>OFF</div><?php }?>
                        <div class="main_sm_product_img_box">
                            <?php if (isset($outfitData[2]['feedId']) && !empty($outfitData[2]['feedId'])) { ?>
                                <img src="<?php echo $outfitData[2]['imageurl']; ?>" id="img" height="251px">
                            <?php } else { ?>
                                <img src="/img/small_img2.jpg" alt="product" />
                            <?php } ?>
                        </div>
                        <div class="main_sm_product_tag_box">
                        </div>
                        <?php if (isset($outfitData[2]['feedId']) && !empty($outfitData[2]['feedId'])) { ?>
                        <div class="box-block2 blok1">
                            <div class="pad">
                                <span class="like_<?php echo  $outfitData[2]['id']; ?>"><?php echo  $outfitData[2]['likesCount'] != 0 ? $outfitData[2]['likesCount'] . ' likes' : ""; ?></span>
                                <h4><?php echo $this->string_helper($outfitData[2]['caption']); ?></h4>
                                <p><?php echo ($outfitData[2]['onsale']=='Y'?$outfitData[2]['saleprice']:$outfitData[2]['price'])?><span class="currency"><?php echo $outfitData[2]['currency'] ?></span></p>
                                <a class="buy_now my_tooltip" title="Purchase article through our partner" target="_blank" href="<?php echo $this->url('service/articlebought', array('feeddataid' => base64_encode($outfitData[2]['id']))); ?>">buy now</a>
                                <br>
                                <a class="discover my_tooltip" title="Learn more about this article" data-value="<?php echo $outfitData[2]['id']; ?>" href="javascript:void(0)">DISCOVER <img src="/img/right1.png" id="im"></a>
                            </div>
                            <div class="social_box1">
                                <?php
                                $page_url = $this->serverUrl() . '/service/feeddatadetail/' . $outfitData[2]['id'] . '/' . rand();
                                $title = 'ELNove - ' . $outfitData[2]['caption'];
                                ?>
                                <ul>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/f.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/pinterest/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/p1.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/t.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/google_plusone_share/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/g.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/email/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/msg.png"></a></li>
                                </ul>
                            </div>
                        </div>
                        <?php } ?>
                    </div>
                </div>

                <div class="img_box_main">
                    <div class="main_sm_product_box">
                        <?php if(isset($outfitData[3]['feedId']) && $outfitData[3]['onsale'] == 'Y') {?><div class="salePrice"><?php echo round(($outfitData[3]['price']-$outfitData[3]['saleprice'])/$outfitData[3]['price']*100)?>%<br/>OFF</div><?php }?>
                        <div class="main_sm_product_img_box">
                            <?php if (isset($outfitData[3]['feedId']) && !empty($outfitData[3]['feedId'])) { ?>
                                <img src="<?php echo $outfitData[3]['imageurl']; ?>" id="img" height="251px">
                            <?php } else { ?>
                                <img src="/img/small_img2.jpg" alt="product" />
                            <?php } ?>
                        </div>
                        <div class="main_sm_product_tag_box">
                        </div>
                        <?php if (isset($outfitData[3]['feedId']) && !empty($outfitData[3]['feedId'])) { ?>
                        <div class="box-block2 blok1">
                            <div class="pad">
                                <span class="like_<?php echo  $outfitData[3]['id']; ?>"><?php echo  $outfitData[3]['likesCount'] != 0 ? $outfitData[3]['likesCount'] . ' likes' : ""; ?></span>
                                <h4><?php echo $this->string_helper($outfitData[3]['caption']); ?></h4>
                                <p><?php echo ($outfitData[3]['onsale']=='Y'?$outfitData[3]['saleprice']:$outfitData[3]['price'])?><span class="currency"><?php echo $outfitData[3]['currency'] ?></span></p>
                                <a class="buy_now my_tooltip" title="Purchase article through our partner" target="_blank" href="<?php echo $this->url('service/articlebought', array('feeddataid' => base64_encode($outfitData[3]['id']))); ?>">buy now</a>
                                <br>
                                <a class="discover my_tooltip" title="Learn more about this article" data-value="<?php echo $outfitData[3]['id']; ?>" href="javascript:void(0)">DISCOVER <img src="/img/right1.png" id="im"></a>
                            </div>
                            <div class="social_box1">
                                <?php
                                $page_url = $this->serverUrl() . '/service/feeddatadetail/' . $outfitData[3]['id'] . '/' . rand();
                                $title = 'ELNove - ' . $outfitData[3]['caption'];
                                ?>
                                <ul>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/f.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/pinterest/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/p1.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/t.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/google_plusone_share/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/g.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/email/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/msg.png"></a></li>
                                </ul>
                            </div>
                        </div>
                        <?php } ?>
                    </div>

                    <div class="main_sm_product_box">
                        <?php if(isset($outfitData[4]['feedId']) && $outfitData[4]['onsale'] == 'Y') {?><div class="salePrice"><?php echo round(($outfitData[4]['price']-$outfitData[4]['saleprice'])/$outfitData[4]['price']*100)?>%<br/>OFF</div><?php }?>
                        <div class="main_sm_product_img_box">
                            <?php if (isset($outfitData[4]['feedId']) && !empty($outfitData[4]['feedId'])) { ?>
                                <img src="<?php echo $outfitData[4]['imageurl']; ?>" id="img" height="251px">
                            <?php } else { ?>
                                <img src="/img/small_img2.jpg" alt="product" />
                            <?php } ?>
                        </div>
                        <div class="main_sm_product_tag_box">
                        </div>
                        <?php if (isset($outfitData[4]['feedId']) && !empty($outfitData[4]['feedId'])) { ?>
                        <div class="box-block2 blok1">
                            <div class="pad">
                                <span class="like_<?php echo  $outfitData[4]['id']; ?>"><?php echo  $outfitData[4]['likesCount'] != 0 ? $outfitData[4]['likesCount'] . ' likes' : ""; ?></span>
                                <h4><?php echo $this->string_helper($outfitData[4]['caption']); ?></h4>
                                <p><?php echo ($outfitData[4]['onsale']=='Y'?$outfitData[4]['saleprice']:$outfitData[4]['price'])?><span class="currency"><?php echo $outfitData[4]['currency'] ?></span></p>
                                <a class="buy_now my_tooltip" title="Purchase article through our partner" target="_blank" href="<?php echo $this->url('service/articlebought', array('feeddataid' => base64_encode($outfitData[4]['id']))); ?>">buy now</a>
                                <br>
                                <a class="discover my_tooltip" title="Learn more about this article" data-value="<?php echo $outfitData[4]['id']; ?>" href="javascript:void(0)">DISCOVER <img src="/img/right1.png" id="im"></a>
                            </div>
                            <div class="social_box1">
                                <?php
                                $page_url = $this->serverUrl() . '/service/feeddatadetail/' . $outfitData[4]['id'] . '/' . rand();
                                $title = 'ELNove - ' . $outfitData[4]['caption'];
                                ?>
                                <ul>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/f.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/pinterest/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/p1.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/t.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/google_plusone_share/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/g.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/email/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/msg.png"></a></li>
                                </ul>
                            </div>
                        </div>
                        <?php } ?>
                    </div>

                    <div class="main_big_product_box">
                        <div class="main_big_product_img_box">
                            <?php if (isset($outfitData[5]['feedId']) && !empty($outfitData[5]['feedId'])) { ?>
                                <img src="<?php echo $outfitData[5]['imageurl']; ?>" id="img" height="369px">
                            <?php } else { ?>
                                <img src="/img/big_img.jpg" alt="product" />
                            <?php } ?>
                        </div>
                        <div class="main_big_product_tag_box">
                        </div>
                        <?php if (isset($outfitData[5]['feedId']) && !empty($outfitData[5]['feedId'])) { ?>
                        <div class="box-block1 blok1">
                            <?php if($outfitData[5]['onsale'] == 'Y') {?><div class="salePrice"><?php echo round(($outfitData[5]['price']-$outfitData[5]['saleprice'])/$outfitData[5]['price']*100)?>%<br/>OFF</div><?php }?>
                            <div class="pad">
                                <span class="like_<?php echo  $outfitData[5]['id']; ?>"><?php echo  $outfitData[5]['likesCount'] != 0 ? $outfitData[5]['likesCount'] . ' likes' : ""; ?></span>
                                <h4><?php echo $this->string_helper($outfitData[5]['caption']); ?></h4>
                                <p><?php echo ($outfitData[5]['onsale']=='Y'?$outfitData[5]['saleprice']:$outfitData[5]['price'])?><span class="currency"><?php echo $outfitData[5]['currency'] ?></span></p>
                                <a class="buy_now my_tooltip" title="Purchase article through our partner" target="_blank" href="<?php echo $this->url('service/articlebought', array('feeddataid' => base64_encode($outfitData[5]['id']))); ?>">buy now</a>
                                <br>
                                <a class="discover my_tooltip" title="Learn more about this article" data-value="<?php echo $outfitData[5]['id']; ?>" href="javascript:void(0)">DISCOVER <img src="/img/right1.png" id="im"></a>
                            </div>
                            <div class="social_box1">
                                <?php
                                $page_url = $this->serverUrl() . '/service/feeddatadetail/' . $outfitData[5]['id'] . '/' . rand();
                                $title = 'ELNove - ' . $outfitData[5]['caption'];
                                ?>
                                <ul>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/f.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/pinterest/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/p1.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/t.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/google_plusone_share/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/g.png"></a></li>
                                    <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/email/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/msg.png"></a></li>
                                </ul>
                            </div>
                        </div>
                        <?php } ?>
                    </div>
                </div>

                <div class="black-box">
                
                    <div class="outfitSharingLinks">url=<?php echo $this->serverUrl() . '/service?outfitd=' . $outfitData[0]['outfit_id']?>&title=<?php echo 'ELNove - ' . $outfitData[0]['outfittitle']?></div>                
                
                    <div class="thumb ">
                        <a href="javascript:void(0);" class="unsavecloseout" data-outfitid="<?php echo base64_encode($key)?>" ><div class="likeimg"></div> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UNSAVE THIS OUTFIT</a>
                    </div>
                    <div class="thumb shareDiv shclose">
                        <a href="javascript:void(0);"><div class="shareimg"></div> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SHARE THIS OUTFIT</a> 
                    </div>
                    <div class="thumb">
                        <a href="javascript:void(0);" class="clsBboughtEntireOutfit" data-outfitid="<?php echo base64_encode($key)?>"><p>bought entire outfit</p></a>
                    </div>
                    <span href="javascript:void(0);" class="thumblike"><div class="likeimg"></div> <span><?php echo number_format($outfitsLikes[$key]); ?></span></span>
                </div>
                <div class="clr"></div>
            </div>  <!-- big_box-->

            <div class="clr"></div>

            <?php } ?>

            <?php }  else { ?>
    <div class="outfitsnot">
 Outfits not available.
            
    </div>
<?php } ?>