<?php
        echo $this->headScript()->appendFile($this->basePath() . '/assets/js/tree.jquery.js')
                                ;
        ?>
<?php echo $this->headLink()
                 ->appendStylesheet($this->basePath() . '/assets/css/jqtree.css');
 ?> 
 
<div class="row" id="venue_style_page">
	<div class="venue_cat col-lg-2 col-lg-offset-1 col-sm-3">
	<div class="venue_cat_wrap">
		<h5>Venues</h5>
		<div id="tree1"></div>
	</div>
		
	</div>
	<div class="venue_main_content col-lg-8 col-sm-9">
		<h3 class="row">Venue 1</h3>
		<div class="row style_item">
			<div class="style_left col-lg-3 col-sm-3 ">
				<p>Style 1</p>
			</div>
			<div class="style_des_right col-lg-8 col-sm-8 ">
				<p>Color <span> Red ,Green</span></p>
				
				<p>Brand <span> Brand 1 ,Brand 2</span></p>
				
			</div>
		</div>
		<div class="row style_item">
			<div class="style_left col-lg-3 col-sm-3">
				<p>Style 2</p>
			</div>
			<div class="style_des_right col-lg-8 col-sm-8">
				<p>Color <span> Red ,Green</span></p>
				<p>Brand <span> Brand 1 ,Brand 2</span></p>
			</div>
		</div>
		<div class="row style_item" id="pick_style_row">
			<div class="style_left pick_style col-lg-5 col-sm-5">
				<p>Pick Styles</p>
				<select data-placeholder="Choose a country..." style="width:100%" class="chosen-select">

					<option selected="" disabled="">Brand</option>
					<option value="Belt Loop"> Belt Loop</option>
					<option value="Brand"> Brand</option>
					<option value="Break"> Break</option>
					<option value="Buttons/Zipper"> Buttons/Zipper</option>
					<option value="Canvas"> Canvas</option>
					<option value="Color"> Color</option>
					<option value="Cuff"> Cuff</option>
					<option value="Darts"> Darts</option>
					<option value="Fabric"> Fabric</option>
					<option value="Feature"> Feature</option>
					<option value="Fit"> Fit</option>
					<option value="Fly Type"> Fly Type</option>
					<option value="Hood"> Hood</option>
					<option value="In-Seam Rise"> In-Seam Rise</option>
					<option value="Lapel"> Lapel</option>
					<option value="Leg Opening"> Leg Opening</option>
					<option value="Neck"> Neck</option>
					<option value="Pattern"> Pattern</option>
					<option value="Pockets"> Pockets</option>
					<option value="Season"> Season</option>
					<option value="Sleeve Length"> Sleeve Length</option>
					<option value="Sleeves"> Sleeves</option>
					<option value="Stitch"> Stitch</option>
					<option value="Type"> Type</option>
					<option value="Vents"> Vents</option>
					<option value="Wash"> Wash</option>
					<option value="Washing Instructions"> Washing Instructions</option>
					<option value="Waterproof"> Waterproof</option>
				</select>
			</div>
			<div class="style_des_right col-lg-7 col-sm-7">
				<p>Color <span> Red ,Green</span></p>
				<p>Brand <span> Brand 1 ,Brand 2</span></p>
				
			</div>
		</div>
	</div>
</div>
<script>
var data = [
    <?php 
		$data_tree = $this->data_tree;
		echo $data_tree;
	?>
];
$(function() {
    $('#tree1').tree({
        data: data,
        selectable: true,
        closedIcon: $('<i class="fa fa-plus"/>'),
    	openedIcon: $('<i class="fa fa-minus"/>'),
        onCreateLi: function(node, $li) {
        	var a = $li.find('span')[0];
        	a.outerHTML = '<a href="' + node.url + '">' + a.outerHTML + '</a>';
        }
    });
    $(".chosen-select").chosen(); 
    $(".venue_cat_wrap h5").click(function(){
    	$(this).parent('.venue_cat_wrap').toggleClass('open');
    	// if($(this).parent('.venue_cat_wrap').hasClass('open')){
    	// 	$("#tree1").show();
    	// }else{
    	// 	$("#tree1").hide();
    	// }
    });
});
</script>