<?php
        echo $this->headScript()->appendFile($this->basePath() . '/assets/js/tree.jquery.js')
                                ;
        ?>
<?php echo $this->headLink()
                 ->appendStylesheet($this->basePath() . '/assets/css/jqtree.css');
 ?> 
<?php
	
?>

<div class="row" id="venue_style_page">
	<div class="venue_cat col-lg-2 col-lg-offset-1 col-sm-3">
	<div class="venue_cat_wrap">
		<h5>Venues</h5>
		<div id="tree1"></div>
	</div>
		
	</div>
	<div class="venue_main_content col-lg-8 col-sm-9">
		<h3 class="row">Venue 1</h3>
		<div class="row style_item">
			<div class="style_left col-lg-3 col-sm-3 ">
				<p>Style 1</p>
			</div>
			<div class="style_des_right col-lg-8 col-sm-8 ">
				<p>Color <span> Red ,Green</span></p>
				
				<p>Brand <span> Brand 1 ,Brand 2</span></p>
				
			</div>
		</div>
		<div class="row style_item">
			<div class="style_left col-lg-3 col-sm-3">
				<p>Style 2</p>
			</div>
			<div class="style_des_right col-lg-8 col-sm-8">
				<p>Color <span> Red ,Green</span></p>
				<p>Brand <span> Brand 1 ,Brand 2</span></p>
			</div>
		</div>
		<div class="row style_item" id="pick_style_row">
			<div class="style_left pick_style col-lg-5 col-sm-5">
				<p>Pick Styles</p>
				<select data-placeholder="Choose a country..." style="width:100%" class="chosen-select">

					<option selected disabled >Select</option>
					<option value="Belt Loop"> Belt Loop</option>
					
				</select>
			</div>
			<div class="style_des_right col-lg-7 col-sm-7">
				<!-- <p>Color <span> Red ,Green</span></p>
				<p>Brand <span> Brand 1 ,Brand 2</span></p> -->
				<button type="button" class="btn-st-blue btn-primary">Add</button>
			</div>
		</div>
	</div>
</div>
<script>
var data = [
    <?php 
		$data_tree = $this->data_tree;
		echo $data_tree;
	?>
];
$(function() {
    $('#tree1').tree({
        data: data,
        selectable: true,
        closedIcon: $('<i class="fa fa-plus"/>'),
    	openedIcon: $('<i class="fa fa-minus"/>'),
        onCreateLi: function(node, $li) {
        	var a = $li.find('span')[0];
        	a.outerHTML = '<a href="' + node.url + '">' + a.outerHTML + '</a>';
        }
    });
    $(".chosen-select").chosen(); 
    $(".venue_cat_wrap h5").click(function(){
    	$(this).parent('.venue_cat_wrap').toggleClass('open');
    	// if($(this).parent('.venue_cat_wrap').hasClass('open')){
    	// 	$("#tree1").show();
    	// }else{
    	// 	$("#tree1").hide();
    	// }
    });
});
</script>