<script src="<?php echo $this->basePath() ?>/showhidepassword/hideShowPassword.min.js"></script>
<script src="<?php echo $this->basePath() ?>/js/custom.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/showhidepassword/css/example.wink.css">

<div class="login-page container about">
    <div class="row">
        <div class="col-sm-12">
            <div class="block">
                <ul class="register_page clearfix">
                    <li class="blue"><a href="" class="active"> LOGIN</a> </li>
                    <li><a href="/profile"> REGISTER</a></li>
                </ul>                        
                <form action="/auth/authenticate" id="login-form" method="post" class="form">
                    <div class="form-group">
                        <label>EMAIL <span class="required">*</span></label>
                        <input type="text" value="" data-msg-required="" maxlength="100" class="form-control flat" name="email" id="email">
                    </div>
                    <div class="form-group">
                        <label>PASSWORD <span class="required">*</span></label>
                        <input type="password" value="" data-msg-required="" maxlength="100" class="form-control flat" name="password" id="password">
                    </div>
                    <div class="form-group">
                        <ul class="option">
                            <li class="remember">   
                                <div class="checkbox checkbox-primary">
                                    <input id="checkbox1" class="styled" type="checkbox" checked="">
                                    <label for="checkbox1">
                                        Remember me
                                    </label>
                                </div>
                            </li>
                            <li class="forgot">
                                <a href="/profile/forgotpassword">Forgot your Password?</a>
                            </li>
                        </ul>
                    </div>
                    <button type="submit" class="btn btn-default btn-submit btn-block" id="login-btn">LOGIN</button>

                    <div id="fb-auth" style="cursor:pointer">
                        <img src="<?php echo $this->basePath(); ?>/templates/mobile/images/facebook.png" class="img-responsive center-block register" alt="">
                    </div>
                </form>
            </div>
            <div id="status"></div>
        </div>
    </div>
</div>

<!-- API facebook -->
<script>
// This function is called when someone finishes with the Login
// Button.  See the onlogin handler attached to it in the sample
// code below.
function checkLoginState() {
    FB.getLoginStatus(function(response) {
        statusChangeCallback(response);
    });
}

// Load the SDK asynchronously
(function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

<script>
//Plugin Hide/Show Password
$('#password').hidePassword(true);  
//Script close popup   
$(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
    $("button.my_btn_ok").click(function(){
        $('a.close-reveal-modal').trigger('click');
    });
});

$(window).on('load', function () {
    //Show error when client input wrong email and pass
    <?php if(isset($_GET['status']) && $_GET['status']='-1'){ ?>
        myalert('alertLoginFail','type_missing','Sorry your password and email don\'t match','','Reset Password');
        $(".my_btn a").attr("href", "/profile/forgotpassword");
    <?php } ?>
    //Process when client click Login
    $("#login-btn").on("click", function(e) {
        if( !($("#email").val().match(/^[+a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i)) )
        {
            myalert('alertEmailNotValid','type_missing','Oops', 'Please enter valid email address','');
            $(".my_btn a").attr("href", "javascript:void(0)");
            return false;
        } 

        //Password validation
        var passInput = $('#password').val();
        if( !(passInput.length > 0 ) ) {
            myalert('alertPassNotValid','type_missing','Oops', 'Please enter password.','');
            $(".my_btn a").attr("href", "javascript:void(0)");
            return false;
        }
        $( "#login-form" ).submit();
    });
});

function checkPermission(){
    FB.api('/me/permissions', function(perms_response) {
        if(perms_response['data'][0].status =='granted' && perms_response['data'][1].status=='granted') {
            window.location.replace("/auth/fb-login");
        } else {
            myalert('myalertSignup1', 'type_missing','Oops', 'We were not able to pull all the required information, please provide the needed information and submit.','');
            $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
                $("button.my_btn_ok").click(function(){
                    $('a.close-reveal-modal').trigger('click');
                });
            });     
            return false;
        }
    });
}

$("#fb-auth").click(function(){ 
    FB.login(function(response) {      
        if (response.authResponse && response.status === 'connected') {
            FB.api('/me', function(info) {
                var accessToken = response.authResponse.accessToken;
                var action_name = 'login_only';
             	var url='/'; 
                $.ajax({
                    url: url+'auth/fb-login',
                    type: 'post',
                    dataType: 'json',
                    data: {action: action_name},
                    success: function(msg) { 
                        if(msg.status == 'fail') {
                            myalert('myalertSignup2', 'type_missing','Oops', 'Login Failed.','');
                            $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
                                $("button.my_btn_ok").click(function(){
                                    $('a.close-reveal-modal').trigger('click');
                                });
                            });  
                            return false;
                        } else if(msg.status == 'success') {
                            window.location.href=url+"service/";
                            return false;
                        }
                    } 
                });
            });	   
        } else {
            //user cancelled login or did not grant authorization
        }
    }, {scope:'public_profile,email,user_birthday,read_stream', auth_type: 'reauthenticate'});      
});
</script>
