<div id="banner" class="row">
    <div class="col-lg-10 col-lg-offset-1 banner-content">
        <h1>LOREM IPSUM TEXT</h1>
        <h3>Whether for casual or business attire, get choices tailored to you.</h3>
                   
        <form class="form_search">
            <input type="search" placeholder="Search lorem ipsum dolor sit amet consectur..." name="search1" class="search_input">
            <div class="charater-center"></div>
            <input type="search" placeholder="Search lorem ipsum dolor sit amet consectur..." name="search2" class="search_input">
            <button type="submit" class="search_submit">
                <i class="fa fa-search" aria-hidden="true" id="search_icon"></i>
            </button>
        </form>
    </div>
</div>