<!DOCTYPE html>
<html lang="en">
<div id="fb-root"></div>
<head>
    <meta charset="utf-8">
    <title>Find Your Stitch</title>
    <meta name="viewport" content="width=1190, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

    <!-- Le styles -->
    <link href="/css/autocomplete/jquery-ui.theme.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/autocomplete/jquery-ui.structure.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/autocomplete/jquery-ui.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/bootstrap_additional.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/fonts/font-awesome/css/font-awesome.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/vendor/flexslider/flexslider.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/vendor/magnific-popup/magnific-popup.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/theme.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/theme-elements.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/custom.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/theme-animate.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/skins/blue.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/theme-responsive.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/img/tie-ico.png" rel="shortcut icon" type="image/vnd.microsoft.icon">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/vendor/jquery.js"><\/script>')</script>


    <!-- Scripts -->
    <script type="text/javascript" src="/js/jquery-ui.js"></script>
    <script type="text/javascript" src="/vendor/modernizr.js"></script>
    <!--[if IE]>
    <link rel="stylesheet" href="/css/ie.css">
    <![endif]-->

    <!--[if lte IE 8]>
    <script src="/vendor/respond.js"></script>
    <![endif]-->
    <style type="text/css">
        /*.col-md-3 {
            width: 20%;
        }
        .col-md-9 {
            width: 80%;
        }*/
        body.sticky-menu-active header{top: -40px}
        .siteWideMessage{
            width:100%;
            min-width: 1170px;
            background-color:#fffa9c;
            text-transform:uppercase;
            text-align:center;
            position:fixed;
            top:0px;
            z-index:9999;
            height:22px;

        }
    </style>



</head>
<body class="sticky-menu-active" style="padding-top:70px">




<div class="body">
<header>
    <div role="main" class="siteWideMessage">We are currently under development. webSite is for review purposes only.</div>
    <div class="container">
        <h1 class="logo">
            <a href="/">
                <img alt="" src="/img/logo.png"
                     style="height: 40px; width: 167px; top: 28px;"
                    />
            </a>
        </h1>




    </div>
    <div class="navbar-collapse nav-main-collapse collapse" style="width: 1px">
        <div class="container">
            <div class="header-links" style="min-height:40px"></div>
        </div>
    </div>
</header>

<div role="main" class="main" style="border-top:1px solid #dddddd">

<div class="container">

<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.12.0/jquery.validate.min.js"></script>

<link rel="stylesheet" href="/vendor/jqueryui/development-bundle/themes/base/jquery.ui.all.css">
<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.core.js"></script>
<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.widget.js"></script>
<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.mouse.js"></script>
<script src="/vendor/jqueryui/development-bundle/ui/jquery.ui.slider.js"></script>

<script>
    $(document).ready(function(){
        $('#inr-wrap').fadeIn(2000);

        $("#myForm").validate({
            rules: {
                firstName: "required",
                lastName: "required"
            },
            messages: {
                firstName: {
                    required: 'Please enter firstname'
                },
                lastName: {
                    required: 'Please enter lastname'
                }
            }
        });
    });
</script>

<style type="text/css">
    form label { width: 250px; }
    form label.error {color: #FF0000; }
</style>

<link rel="stylesheet" type="text/css" href="/vendor/bootstrap/bootstrap-checkbox/css/bootstrap-checkbox.css">
<script src="/vendor/bootstrap/bootstrap-checkbox/js/bootstrap-checkbox.js"></script>

<div id="inr-wrap" style="display:none;">

<div class="progressBarHeader">

    <h3>JOIN Find Your Stitch</h3>
</div>


<table  width="50%" class="progressBar" align="center">
    <tr>
        <td><span class="badge">&nbsp;</span></td>
        <td width="15%"><hr /></td>
        <td><span class="badge">&nbsp;</span></td>
        <td width="15%"><hr /></td>
        <td><span class="badge">&nbsp;</span></td>
        <td width="15%"><hr /></td>
        <td><span class="badge">&nbsp;</span></td>
        <td width="15%"><hr /></td>
        <td><span class="badge">&nbsp;</span></td>
        <td width="15%"><hr /></td>
        <td><span class="badge badge-info">&nbsp;</span></td>
    </tr>
    <tr>
        <td>Style</td>
        <td>&nbsp;</td>
        <td>You</td>
        <td>&nbsp;</td>
        <td>Size</td>
        <td>&nbsp;</td>
        <td>Brands</td>
        <td>&nbsp;</td>
        <td>Price</td>
        <td>&nbsp;</td>
        <td nowrap="nowrap" class="active">Sign Up</td>
    </tr>
</table>


<br /><br />
<form name="myForm" id="myForm" method="POST">
<div class="row">

<div class="col-md-3"></div>
<div class="col-md-6">



<div style="width:100%;" align="center">
<div align="center" style="padding-top:15px; margin-bottom:15px">

    <div id="fb-root"></div>
    <div class="col-md-12 floatnone">
        <a href="#" class="fb-login">
            <img id="fb-auth" alt="sign in with facebook" src="/img/fb-sign-in.png">
        </a>
        <img class="loading" style="display: none;" src="img/bx_loader.gif"/>
    </div>

    <div class="col-md-12 floatnone">
        &nbsp;
    </div>

    <div class="col-md-12 floatnone">
        <div style="with:100%; height:50px;">
            <div style="position:absolute; top: 0; left: 0; right: 0; height:25px; border-bottom:2px solid #00979c">

            </div>
            <div style="position:absolute; top: 0; left: 0; right: 0; height:50px; padding-top:14px; font-size:18px; font-style:italic">
                <span style="background-color:#FFF;">&nbsp;&nbsp;&nbsp;OR&nbsp;&nbsp;&nbsp;&nbsp;</span>
            </div>

        </div>
    </div>

    <div class="col-md-12 floatnone">
        &nbsp;
    </div>

    <div class="form-group">
        <div class="col-md-6  floatnone">
            <input type="text"  placeholder="First Name" value="" data-msg-required="Please enter First Name." maxlength="100" class="form-control" name="firstName" id="firstName">
        </div>
        <div class="col-md-6  floatnone">
            <input type="text"  placeholder="Last Name" value="" data-msg-required="Please enter the Last Name" maxlength="100" class="form-control" name="lastName" id="lastName">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12  floatnone">
            <input type="text"  placeholder="Email" value="" data-msg-required="Please enter the Email" maxlength="100" class="form-control" name="email" id="email">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12  floatnone">
            <input type="password"  placeholder="Password" value="" data-msg-required="Please enter Password" maxlength="100" class="form-control" name="password" id="password">
        </div>
    </div>

    <div class="form-group">
        <div align="left" style="padding-left:6px">Birthday</div>
        <div class="col-md-4  floatnone">
            <!--<input type="text"  placeholder="Day" value="" data-msg-required="Please enter Day" maxlength="100" class="form-control" name="firstName" id="suDay">-->
            <select name="day" class="form-control" id="suDay" style="background:#DCDCDC;">
                <option value="01">01</option>
                <option value="02">02</option>
                <option value="03">03</option>
                <option value="04">04</option>
                <option value="05">05</option>
                <option value="06">06</option>
                <option value="07">07</option>
                <option value="08">08</option>
                <option value="09">09</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
                <option value="13">13</option>
                <option value="14">14</option>
                <option value="15">15</option>
                <option value="16">16</option>
                <option value="17">17</option>
                <option value="18">18</option>
                <option value="19">19</option>
                <option value="20">20</option>
                <option value="21">21</option>
                <option value="22">22</option>
                <option value="23">23</option>
                <option value="24">24</option>
                <option value="25">25</option>
                <option value="26">26</option>
                <option value="27">27</option>
                <option value="28">28</option>
                <option value="29">29</option>
                <option value="30">30</option>
                <option value="31">31</option>
            </select>
        </div>
        <div class="col-md-4  floatnone">
            <!--<input type="text"  placeholder="Month" value="" data-msg-required="Please enter the Month" maxlength="100" class="form-control" name="lastName" id="suMonth">-->
            <select name="month" class="form-control" name="month" id="suMonth" style="background:#DCDCDC;">
                <option value="01">January</option>
                <option value="02">February</option>
                <option value="03">March</option>
                <option value="04">April</option>
                <option value="05">May</option>
                <option value="06">June</option>
                <option value="07">July</option>
                <option value="08">August</option>
                <option value="09">September</option>
                <option value="10">October</option>
                <option value="11">November</option>
                <option value="12">December</option>
            </select>
        </div>
        <div class="col-md-4  floatnone">
            <!--<input type="text" placeholder="Year" value="" data-msg-required="Please enter the Year" maxlength="100" class="form-control" name="lastName" id="suYear">-->
            <select name="year" class="form-control" id="suYear" style="background:#DCDCDC;">
                <option value="1996">1996</option>
                <option value="1995">1995</option>
                <option value="1994">1994</option>
                <option value="1993">1993</option>
                <option value="1992">1992</option>
                <option value="1991">1991</option>
                <option value="1990">1990</option>
                <option value="1989">1989</option>
                <option value="1988">1988</option>
                <option value="1987">1987</option>
                <option value="1986">1986</option>
                <option value="1985">1985</option>
                <option value="1984">1984</option>
                <option value="1983">1983</option>
                <option value="1982">1982</option>
                <option value="1981">1981</option>
                <option value="1980">1980</option>
                <option value="1979">1979</option>
                <option value="1978">1978</option>
                <option value="1977">1977</option>
                <option value="1976">1976</option>
                <option value="1975">1975</option>
                <option value="1974">1974</option>
                <option value="1973">1973</option>
                <option value="1972">1972</option>
                <option value="1971">1971</option>
                <option value="1970">1970</option>
                <option value="1969">1969</option>
                <option value="1968">1968</option>
                <option value="1967">1967</option>
                <option value="1966">1966</option>
                <option value="1965">1965</option>
                <option value="1964">1964</option>
                <option value="1963">1963</option>
                <option value="1962">1962</option>
                <option value="1961">1961</option>
                <option value="1960">1960</option>
                <option value="1959">1959</option>
                <option value="1958">1958</option>
                <option value="1957">1957</option>
                <option value="1956">1956</option>
                <option value="1955">1955</option>
                <option value="1954">1954</option>
                <option value="1953">1953</option>
                <option value="1952">1952</option>
                <option value="1951">1951</option>
                <option value="1950">1950</option>
                <option value="1949">1949</option>
                <option value="1948">1948</option>
                <option value="1947">1947</option>
                <option value="1946">1946</option>
                <option value="1945">1945</option>
                <option value="1944">1944</option>
                <option value="1943">1943</option>
                <option value="1942">1942</option>
                <option value="1941">1941</option>
                <option value="1940">1940</option>
                <option value="1939">1939</option>
                <option value="1938">1938</option>
                <option value="1937">1937</option>
                <option value="1936">1936</option>
                <option value="1935">1935</option>
                <option value="1934">1934</option>
            </select>
        </div>

    </div>

    <div class="form-group">
        <div class="col-md-12  floatnone" style="text-align: left">

            Choose your default venue<br />
            <input type="checkbox" id="i1" name="i1" class="checkbox" checked="checked" /> Work
            <input type="checkbox" id="i2" name="i2"  class="checkbox" /> Nightout
            <input type="checkbox" id="i3" name="i3"  class="checkbox" /> Casual
        </div>

    </div>

    <div class="form-group">
        <div class="col-md-12  floatnone">
            <div style="text-align:justify; font-size:11px; line-height:12px">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            </div>
        </div>
    </div>


</div>


</div>

</div>
<div class="col-md-6"></div>



</div>

<br /><br />
<div class="col-md-12" align="center">
    <input class="btn btn-primary btn-lg btn-cta-blue" type="submit" data-loading-text="Loading..." value="Sign Up">
</div>
<br /><br /><br /><br />
</form>

</div>

<script>
    $(window).on('load', function () {

        $('.checkbox').on("click", function(e) {
            var callingElmId = this.id;
            $( ".checkbox" ).each(function() {
                if(this.id != callingElmId) {
                    $('#'+this.id).prop( "checked", false );
                    $('#'+this.id).checkbox('setChecked');
                }
            });
        });

        $('.checkbox').checkbox('setChecked');

        /*$("#btnNextStep").on("click", function(e) {

         if( !($("#firstName").val().match(/^[a-zA-Z\ \.]+$/)) )
         {
         alert('Please enter valid First Name');
         return false;
         }

         if( !($("#lastName").val().match(/^[a-zA-Z\ \.]+$/)) )
         {
         alert('Please enter valid Last Name');
         return false;
         }

         if( !($("#email").val().match(/^[+a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i)) )
         {
         alert('Enter valid Email address.');
         return false;
         }

         $.ajax({
         type: "POST",
         url: "/user/checkAccount",
         data: { email: $("#email").val() },
         async : false
         })
         .done(function( data ) {
         if( data == 'Exist' ) {
         alert('Email address already in use');
         return false;
         }
         });

         if( !($("#password").val().length >= 4 ) )
         {
         alert('Password shouldn\'t be less than 4 characters.');
         return false;
         }

         $( "#myForm" ).submit();
         });*/

    });


</script>
</div>

</div>
</div>
<script type="text/javascript">
    var showSmallHeader = true;
</script>
<!-- Libs -->
<script src="/js/plugins.js"></script>
<script src="/vendor/jquery.easing.js"></script>
<script src="/vendor/jquery.appear.js"></script>
<script src="/vendor/jquery.cookie.js"></script>
<script src="/vendor/bootstrap.js"></script>
<script src="/vendor/twitterjs/twitter.js"></script>
<script src="/vendor/flexslider/jquery.flexslider.js"></script>
<script src="/vendor/jflickrfeed/jflickrfeed.js"></script>
<script src="/vendor/magnific-popup/magnific-popup.js"></script>
<script src="/vendor/jquery.validate.js"></script>
<script src="/vendor/bootstrap/bootstrap-lightbox/bootstrap-lightbox.min.js"></script>

<!-- Theme Initializer -->
<script src="/js/theme.js"></script>

<!-- Custom JS -->
<script src="/js/custom.js"></script>


</body>
</html>
