<?php echo $this->doctype(); ?>
<html lang="en">
    <div id="fb-root"></div>
    <head>
        <meta charset="utf-8">
        <script type="text/javascript"> url = '<?php echo $this->basePath('');?>';</script>
        <?php echo $this->headTitle("ELNove")->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

<link rel="apple-touch-icon" sizes="57x57" href="/img/favicons/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/img/favicons/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/img/favicons/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/img/favicons/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/img/favicons/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/img/favicons/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/img/favicons/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/img/favicons/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/img/favicons/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/img/favicons/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/img/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/img/favicons/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/img/favicons/favicon-16x16.png">
<link rel="manifest" href="/img/favicons/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/img/favicons/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff"> 
        
        <!-- Le styles -->
        <?php
        echo $this->headLink()
                //->prependStylesheet($this->basePath() . '/css/theme-responsive.css')
                //->prependStylesheet($this->basePath() . '/css/skins/blue.css')
                //->prependStylesheet($this->basePath() . '/css/theme-animate.css')
                //->prependStylesheet($this->basePath() . '/css/custom.css')
                //->prependStylesheet($this->basePath() . '/css/theme-animate.css')
                //->prependStylesheet($this->basePath() . '/css/theme-elements.css')
                //->prependStylesheet($this->basePath() . '/css/theme.css')
                //->prependStylesheet($this->basePath() . '/vendor/magnific-popup/magnific-popup.css')
                //->prependStylesheet($this->basePath() . '/vendor/flexslider/flexslider.css')
                //->prependStylesheet($this->basePath() . '/css/fonts/font-awesome/css/font-awesome.css')
                //->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                //->prependStylesheet($this->basePath() . '/vendor/magnific-popup/magnific-popup.css')
                //->prependStylesheet($this->basePath() . '/vendor/flexslider/flexslider.css')
                //->prependStylesheet($this->basePath() . '/css/fonts/font-awesome/css/font-awesome.css')
                //->prependStylesheet($this->basePath() . '/css/bootstrap_additional.css')
                //->prependStylesheet($this->basePath() . '/css/bootstrap.css');
                ->prependStylesheet($this->basePath() . '/css/normalize.css')
                ->prependStylesheet($this->basePath() . '/css/owl.carousel.css')
                ->prependStylesheet($this->basePath() . '/fa/css/font-awesome.css')
                ->prependStylesheet($this->basePath() . '/css/style.css');
        ?>
        <!-- Scripts -->
        <?php
        //echo $this->headScript()->prependFile($this->basePath() . '/vendor/modernizr.js');
        echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.gray.js')
                                ->prependFile($this->basePath() . '/js/jquery.js');
        ?>

        <!--[if IE]>
                <!--<link rel="stylesheet" href="/css/ie.css">-->
        <![endif]-->

        <!--[if lte IE 8]>
                <!--<script src="/vendor/respond.js"></script>-->
        <![endif]-->
        <script type="text/javascript">url = '<?php echo $this->basePath('/')?>';</script>

    </head>
    <body>
    
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-5F6KJB"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5F6KJB');</script>
<!-- End Google Tag Manager -->

    <header class="fixed-nav-bar">

        <div class="container">

              

            <nav>
                <ul id="navbar">
                    <li><a href="javascript:void(0);" id="menuicon"><img src="/img/menu_icon.png" alt="menu" class="fleft" />  Menu</a>
                        <ul class="mainmenu hidemenu">
                            <li><a href="<?=$this->basePath()?>/comingsoon/how-it-works">How it works</a></li>
                            <li><a href="<?=$this->basePath()?>/comingsoon/about-us">About Us</a></li>
                            <li><a href="http://<?=URL_BLOG?>">Blog</a></li>
                            <li><a href="<?=$this->basePath()?>/comingsoon/frequently-asked-questions">FAQ</a></li>
                            <li><a href="<?=$this->basePath()?>/comingsoon/shipping">Shipping</a></li>
                            <li><a href="<?=$this->basePath()?>/comingsoon/pricing">Pricing</a></li>
                            <li><a href="<?=$this->basePath()?>/comingsoon/privacy-and-policies">Privacy and Policies</a></li>
                            <li><a href="<?=$this->basePath()?>/comingsoon/exchange_and_return">Exchange & Returns</a></li>
                            <li><a href="<?=$this->basePath()?>/comingsoon/careers">Careers</a></li>
                            <li><a href="<?=$this->basePath()?>/comingsoon/contact-us">Contact Us</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
<!-- 
            <div class="header_right">
                <a  href="/auth/login" class="link_new">SIGN IN</a>
                <?php
                $step = 0;
                $request_uri = $_SERVER['REQUEST_URI'];
                if($request_uri == '/profile') {
                    $step = 1;
                } else if($request_uri == '/profile/you') {
                    $step = 2;
                } else if($request_uri == '/profile/size') {
                    $step = 3;
                } else if($request_uri == '/profile/brands') {
                    $step = 4;
                } else if($request_uri == '/profile/price') {
                    $step = 5;
                } else if($request_uri == '/profile/signup') {
                    $step = 6;
                }
                ?>
                <?php if($step != 0) { ?>
                    <a  href="javascript:void(0);" class="green_btn">Step <?php echo $step; ?> of 6</a>
                <?php } else { ?>
                    <a href="/profile" class="green_btn">GET STARTED</a>
                <?php } ?>
            </div>
 -->
            <div class="logo2">
                <a href="<?=$this->basePath()?>/comingsoon"><img src="/img/lnove_logo.png" alt="lnove" /></a>
            </div>

            

        </div>

        <div class="clr"></div>
    </header>
    <div class="clr"></div>

    <?php echo $this->content; ?>

    <div class="clr"></div>
    <footer>
        <div class="container">
            <div class="left-foot">
                <div class="foot_one">
                    <ul class="list">
                        <li><a href="/comingsoon/how-it-works">How it works</a></li>
                        <li><a href="/comingsoon/about-us">About Us</a></li>
                        <li><a href="http://<?=URL_BLOG?>">Blog</a></li>
                        <li><a href="/comingsoon/frequently-asked-questions">FAQ</a></li>
                        <li><a href="/comingsoon/shipping">Shipping</a></li>
                    </ul>
                </div>

                <div class="foot_two">
                    <ul class="list">
                        <li><a href="/comingsoon/pricing">Pricing</a></li>
                        <li><a href="/comingsoon/privacy-and-policies">Privacy and Policies</a></li>
                        <li><a href="/comingsoon/exchange_and_return">Exchanges & Returns</a></li>
                        <li><a href="/comingsoon/contact-us">Contact Us</a></li>
                        <li><a href="/comingsoon/careers">Careers</a></li>
                    </ul>
                </div>
                <div class="input-box">
                    <input type="text" class="input" placeholder=" Your email Address">
                    <button class="button">  <img src="/img/arrow-right.png"></i>

                    </button>
                </div>
            </div>
            <div class="right-foot">
                <div>
                    <h4>CONTACT US</h4>
                    <span>Via Lorem Ipsum, 38 <br> 20121</span>
                    <p>City - Country</p>
                    <p>Tel. +00 00 00000000</p>
                    <p>email@example.com</p>
                </div>
            </div>
            <div class="clr"></div>
        </div>
        </div>
        </div>
        <div class="clr"></div>
        </section>
    </footer>
    <div class="last-foot">
        <div class="container">
            <div class="copy">COPYRIGHT 2016 STITCH STYLE SOLUTIONS INC. ALL RIGHTS RESERVED</div>
            <div class="social">
                <ul class="link">
                    <li>
                        <a href=""> <i class="fa fa-twitter"></i>
                        </a>
                    </li>                
                    <li>
                        <a href=""> <i class="fa fa-facebook "></i>
                        </a>
                    </li>
                    <li>
                        <a href=""> <i class="instagram_icon"></i>
                        </a>
                    </li>
                    <li>
                        <a href=""> <i class="vimo_icon"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <script src="/js/owl.carousel.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            var owl = $("#owl-demo1");
            owl.owlCarousel({
                itemsCustom : [
                    [0, 2],
                    [1200, 2],
                    [1920, 3]
                ],
                navigation : false,
                autoPlay: 3000
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function() {
            var owl = $("#owl-demo");
            owl.owlCarousel({
                itemsCustom : [
                    [0, 2],
                    [1200, 2],
                    [1920, 2]
                ],
                navigation : true,
                pagination:false,
                autoPlay: 3000
            });
        });
    </script>
    <script>
        /*$("#menuicon").on("click", function(e) {
         if($('.mainmenu').hasClass('hidemenu'))
         $('.mainmenu').removeClass('hidemenu').addClass('showmenu');
         else
         $('.mainmenu').removeClass('showmenu').addClass('hidemenu');
         });*/

        $(document).mouseup(function (e)
        {
            var container = $('#menuicon');

            if (!container.is(e.target) // if the target of the click isn't the container...
                && container.has(e.target).length === 0) // ... nor a descendant of the container
            {
                if($('.mainmenu').hasClass('showmenu'))
                    $('.mainmenu').removeClass('showmenu').addClass('hidemenu');

                if($('.mainmenu').hasClass('showmenu1'))
                    $('.mainmenu').removeClass('showmenu1').addClass('hidemenu1');
            }
            else
            {
                if($('.mainmenu').hasClass('hidemenu'))
                    $('.mainmenu').removeClass('hidemenu').addClass('showmenu');

                if($('.mainmenu').hasClass('hidemenu1'))
                    $('.mainmenu').removeClass('hidemenu1').addClass('showmenu1');
            }
        });
    </script>
    </body>
</html>
