<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
            
        <?php if( isset($this->additionalMeta) ) { echo $this->additionalMeta; }?>        
        
        <!-- Le styles -->
        <?php echo $this->headLink()

                        ->prependStylesheet($this->basePath() . '/css/jquery.gritter.css')
                        ->prependStylesheet($this->basePath() . '/css/lnovecustom.css')
                        ->prependStylesheet($this->basePath() . '/css/normalize.css')
                        ->prependStylesheet($this->basePath() . '/css/owl.carousel.css')
                        ->prependStylesheet($this->basePath() . '/fa/css/font-awesome.css')
                        // ->prependStylesheet($this->basePath() . '/css/style.css')
                        // ->prependStylesheet($this->basePath() . '/css/profile_myaccount.less')
                        ->prependStylesheet($this->basePath() . '/js/sweetalert-master/dist/sweetalert.css')
                        ->appendStylesheet($this->basePath() . '/css/hoang_careers.less')
                        ->appendStylesheet($this->basePath() . '/css/mystyle.css')
                        ->appendStylesheet($this->basePath() . '/myalert/css/reveal.css')
                        ->prependStylesheet($this->basePath() . '/myalert/css/foundation.css')
                        ->appendStylesheet($this->basePath() . '/myalert/css/style.css')
                        ->appendStylesheet($this->basePath() . '/tooltipster/css/tooltipster.css')
                        ->appendStylesheet($this->basePath() . '/tooltipster/css/themes/tooltipster-shadow.css')
                      ;
        ?>

        <link rel="icon" href="favicon.ico">
        <title>eLnove.com</title>
        <!-- Bootstrap core CSS -->
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
        <!-- FONT -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,700,900' rel='stylesheet' type='text/css'>
        <!-- Custom styles for this template -->
        <link href="/assets/css/custom.less" rel="stylesheet/less" type="text/css">
        <!-- <link href="/assets/css/custom_header.less" rel="stylesheet/less" type="text/css"> -->
        <!-- <link href="/assets/css/custom_banner.less" rel="stylesheet/less" type="text/css"> -->
        <!-- <link href="/assets/css/custom_product_list.less" rel="stylesheet/less" type="text/css"> -->
        <script src="http://cdnjs.cloudflare.com/ajax/libs/less.js/2.6.1/less.min.js"></script>
        <link rel="stylesheet/less" type="text/css" href="/assets/css/careers_page.less" />
        <!-- <link rel="stylesheet/less" type="text/css" href="bk/assets/css/quang.less" /> -->
        <script   src="/assets/js/jquery-1.12.4.min.js"></script>
        <script src="/assets/js/bootstrap.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/less.js/2.6.1/less.min.js"></script>
        <script src="/assets/js/jquery-ui.js"></script>
        <script src="/assets/js/jquery.fullscreen-popup.js"></script>


    </head>

     <script>
     
    //show popup full screen when click in object
            jQuery(function($) {
                
                $("#pop-menu").fullScreenPopup({
                    bgColor: '#fff'
                });
                $("#refine-search-popup").fullScreenPopup({
                    bgColor: '#fff'
                });
                $("#sort-item-popup").fullScreenPopup({
                    bgColor: '#fff'
                });
                
            });
        </script>
    <body>
<div id="header-block">
    <div id="header-container" class="container-fluid hidden-xs">
        <div class="row">
            <div class="header-top-navbar col-lg-12 ">
                <div class="row top-bar">
                    <div class="left-side col-lg-4 col-md-4 col-sm-4 col-xs-12" id="show-hide-menu">MENU</div>
                    <div class="logo col-lg-4 col-md-4 col-sm-4 col-xs-12"><img src="/assets/images/logo1.jpg" alt="" class="top-logo">
                    </div>
                    <div class="right-side col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <?php if( isset($this->showHeaderLinks) && $this->showHeaderLinks=='LOGGED_IN' ) { ?>
                            <div class="uc_clean_accordion">
                                <div class="uc_clean_accordion_wrap">
                                    <div id="accordion" class="uc_clean_accorder_content">
                                        <h3 class="uc_head_line">
                                            <a class="uc_link_tittle">WELCOME, <?php echo $this->firstName; ?></a>
                                        </h3>
                                        <div class="uc_line_content_header">
                                            <ul class="uc_des">
                                                <li><a href="/profile/myaccount">My Profile</a>
                                                </li>
                                                <li><a href="/auth/logout">Logout</a>
                                                </li>
                                            </ul>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        
                        <?php } else { ?>
                        <div class="login_signup">
                            <a href="/auth/login">LOGIN</a>
                            /
                            <a href="/profile">SIGN UP</a>
                        </div>
                    <?php }?>
                        <?php
                            $step = 0;
                            $request_uri = $_SERVER['REQUEST_URI'];
                            if($request_uri == '/profile') {
                                $step = 1;
                            } else if($request_uri == '/profile/you') {
                                $step = 2;
                            } else if($request_uri == '/profile/size') {
                                $step = 3;
                            } else if($request_uri == '/profile/brands') {
                                $step = 4;
                            } else if($request_uri == '/profile/price') {
                                $step = 5;
                            } else if($request_uri == '/profile/signup') {
                                $step = 6;
                            }
                            ?>
                            <?php if($step != 0) { ?>
                                <a  href="javascript:void(0);" class="btn-st-blue">Step <?php echo $step; ?> of 6</a>
                            <?php } else { ?>
                                <a href="/profile" class="btn-st-blue">GET STARTED</a>
                            <?php } ?>
                        <!-- <a href="#" class="btn-st-blue">GET STYLED</a> -->
                    </div>
                </div>
            </div>
            
        </div>

        <nav id="menu" class="row">
            <div class="col-lg-12 col-xs-12" id="row-top-navbar">
                <div class="row">
                    <div class="col-lg-12 col-xs-12 text-center" id="top-nav" class="top-navbar">
                        <ul>
                            <li><a href="/info/how-it-works">HOW IT WORKS</a>
                            </li>
                            <li><a href="/info/about-us">ABOUT US</a>
                            </li>
                            <li><a href="http://<?=URL_BLOG?>">BLOG</a>
                            </li>
                            <li><a href="/info/frequently-asked-questions">FAQ</a>
                            </li>
                            <li><a href="/info/frequently-asked-questions?tag=shipping">SHIPPING</a>
                            </li>
                            <li><a href="/info/frequently-asked-questions?tag=pricing">PRICING</a>
                            </li>
                            <li><a href="/info/frequently-asked-questions?tag=shipping">EXCHANGE & RETURNS</a>
                            </li>
                            <li><a href="/info/careers">CAREERS</a>
                            </li>
                            <li><a href="/info/contact-us">CONTACT US</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-10 col-lg-offseet-1 col-xs-10 col-xs-offset-1" id="search">
                <form class="searchbox">
                    <input type="search" placeholder="Search lorem ipsum dolor sit amet consectur..." name="search1" class="searchbox-input" onkeyup="buttonUp();">
                    <div class="charater-center"></div>
                    <input type="search" placeholder="Search lorem ipsum dolor sit amet consectur..." name="search2" class="searchbox-input" onkeyup="buttonUp();">
                    <button type="submit" class="searchbox-submit">
                        <span class="searchbox-icon"><i class="fa fa-search" aria-hidden="true" id="search_btn"></i></span>
                    </button>
                </form>
            </div>

        </nav>
    </div>
    <div id="mobile-header" class="container-fluid visible-xs">
        <div class="row">
            <div class="col-xs-12" id="mtop-bar">
             
                <div class="uc_clean_accordion col-xs-6" id="mtop-left">
                <?php if( isset($this->showHeaderLinks) && $this->showHeaderLinks=='LOGGED_IN' ) { ?>
                <div class="uc_clean_accordion_wrap">
                    <div id="login_signup" class="uc_clean_accorder_content">
                        <h3 class="uc_head_line" id="m-show-userbox">
                            <p class="uc_link_tittle">WELCOME, <?php echo $this->firstName; ?></p>
                        </h3>
                     </div>
                </div>
                <?php } else { ?>
                    <div class="login_signup">
                        <a href="/auth/login">LOGIN</a>
                        /
                        <a href="/profile">SIGN UP</a>
                    </div>
                    <?php }?>
                </div>
                <?php
                    $step = 0;
                    $request_uri = $_SERVER['REQUEST_URI'];
                    if($request_uri == '/profile') {
                        $step = 1;
                    } else if($request_uri == '/profile/you') {
                        $step = 2;
                    } else if($request_uri == '/profile/size') {
                        $step = 3;
                    } else if($request_uri == '/profile/brands') {
                        $step = 4;
                    } else if($request_uri == '/profile/price') {
                        $step = 5;
                    } else if($request_uri == '/profile/signup') {
                        $step = 6;
                    }
                    ?>
                    <?php if($step != 0) { ?>
                <div class="col-xs-6" id="mtop-right">
                    <a href="javascript:void(0);" class="btn-st-blue">GET STYLED</a>
                </div>
                 <?php } else { ?>
                <div class="col-xs-6" id="mtop-right">
                    <a href="/profile" class="btn-st-blue">GET STYLED</a>
                </div>
                <?php }?>
            </div>
        </div>
        <div class="row">
            <div class="user-mhiden" id="user-mblock">
                <p class="tit-head">WELCOM, <?php echo $this->firstName; ?> <span class="fa fa-times" id="hid-userbox"></span></p>
                <ul class="link-box-user">
                    <li><a href="/profile/myaccount">My Profile</a></li>
                    <li><a href="/auth/logout">Log out</a></li>
                </ul>
            </div>   
        </div>        
        <div class="row" id="menu-logo">
            <div class="col-xs-12">
                <span class="fa fa-plus" id="pop-menu" data-popup="#popup"></span>
                <img src="/assets/images/mobile-logo.png" alt="logo mobile" class="logo" />
            </div>
        </div>
        
        <div class="row" id="search-bar">
            <form class="searchbox-mobile col-xs-12">
                <input type="search" placeholder="Search lorem ipsum dolor sit amet consectur..." name="search1" class="m-searchbox-input">
                    <div class="charater-center"></div>
                    <input type="search" placeholder="Search lorem ipsum dolor sit amet consectur..." name="search2" class="m-searchbox-input" >
                <button type="submit" class="searchbox-submit">
                    <span class="m-searchbox-icon"><i class="fa fa-search" aria-hidden="true" id="m-search_btn"></i></span>
                </button>
            </form>
        </div>
        <div class="row">
            <div class="col-xs-12 text-left" id="popup">
                <div class="row">
                    <p class="m-title"> MENU</p>
                    <ul>
                        <li><a href="/info/how-it-works">HOW IT WORKS</a>
                        </li>
                        <li><a href="/info/about-us">ABOUT US</a>
                        </li>
                        <li><a href="http://<?=URL_BLOG?>">BLOG</a>
                        </li>
                        <li><a href="/info/frequently-asked-questions">FAQ</a>
                        </li>
                        <li><a href="/info/frequently-asked-questions?tag=shipping">SHIPPING</a>
                        </li>
                        <li><a href="/info/frequently-asked-questions?tag=pricing">PRICING</a>
                        </li>
                        <li><a href="/info/frequently-asked-questions?tag=shipping">EXCHANGE & RETURNS</a>
                        </li>
                        <li><a href="/info/careers">CAREERS</a>
                        </li>
                        <li><a href="/info/contact-us">CONTACT US</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
        <!-- <div class="row">
            <div class="user-mhiden" id="user-mblock">
                <p class="tit-head">WELCOM,JOHN <span class="fa fa-times" id="hid-userbox"></span></p>
                <ul class="link-box-user">
                    <li><a href="#">My Profile</a></li>
                    <li><a href="#">Log out</a></li>
                </ul>
             </div>   
            
        </div> -->
    </div>
</div>

<div id="body-container" class="container-fluid">
  <?php echo $this->content; ?>
        <!-- Modal -->
        
        <!-- <div id="modal_total"> -->

        <!-- Modal of Popup Quick-view-product-item -->
            <!-- <div class="modal fade bs-example-modal-lg modal_quick_view" id="modal_QV" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        </div>
                        <div class="modal-body">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-lg-6 modal_body_left">
                                        <img src="../assets/images/product_item_mobile.jpg" alt="">
                                    </div>
                                    <div class="col-lg-6 modal_body_right">
                                        <p class="modal_name_item">Puma Number One Active Hoodie</p>
                                        <p class="modal_brand_item">PUMA</p>
                                        <p class="modal_price_item">39.00 CAD</p>
                                        <div class="modal_buy_product">
                                            <span class="btn-st-blue">BUY</span>
                                            <i class="fa fa-heart-o" aria-hidden="true"></i>
                                        </div>
                                        <p class="modal_alert_detail">DETAILS</p>
                                        <p class="modal_alert_detail_atb">A classic branded sweater with lined hood</p>
                                        <p class="modal_alert_detail_atb">Hooded</p>
                                        <p class="modal_alert_detail_atb">Long sleeves</p>
                                        <p class="modal_alert_detail_atb">Front pouch pocket</p>
                                        <p class="modal_alert_detail_atb">Cotton/polyester</p>
                                        <p class="modal_alert_detail_atb">Machine wash</p>
                                        <p class="modal_alert_detail_atb">Imported</p>
                                        <div class="modal_body_icon_link">
                                            <a href="#"><i class="fa fa-facebook"></i></a>
                                            <a href="#"><i class="fa fa-pinterest-p"></i></a>
                                            <a href="#"><i class="fa fa-tumblr"></i></a>
                                            <a href="#"><i class="fa fa-google-plus"></i></a>
                                            <a href="#"><i class="fa fa-envelope-o fa_final"></i></a>
                                        </div>
                                        <div class="modal_body_footer">
                                            <i class="fa fa-bell-o" aria-hidden="true"></i>
                                            <span>Get Sale Alert</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>                  
                    </div>
                </div>
            </div>
 -->

        <!-- End Modal of Popup Quick-view-product-item -->
                
        <!-- Modal of Popup icon_alert -->
            <!-- <div class="modal fade bs-example-modal-lg modal_icon_alert" id="modal_alert" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                <div class="modal-dialog modal-lg" role="document">                              
                    <div class="modal-content modal_alert">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <i class="fa fa-bell-o" aria-hidden="true"></i>
                            <h2 class="popup_alert_title">CREATE SALE ALERT</h2>
                        </div>
                        <div class="modal-body">
                            <img src="../assets/images/product_item_detail-mobile.jpg" alt="">
                            <p class="modal_name_item">Botazzo Textural Derby Sneakers</p>
                            <p class="modal_brand_item">PEGABO</p>
                            <p class="modal_price_item">59.50 CAD</p>
                        </div>
                        <div class="modal-footer">
                            <p class="modal_footer_p1">Waiting for this item to go on sale?</p>
                            <p class="modal_footer_p2">We'll send an email when the price drops.</p>
                            <form action="" class="modal_form_alert">
                                <input type="text" name="email-alert" placeholder="Youre Email Address">
                                <button class="btn-st-blue" type="submit" name="alert-submit">SET SALE ALERT</button>
                            </form>
                            <span>By submiting this request,I confirm I agree with the Terms & Conditions</span>                    
                        </div>
                    </div>                                   
                </div>
            </div> -->
                <!-- End Modal of Popup icon_alert -->
        <!-- </div> -->

        <!-- End Modal -->
</div>
<script type="text/javascript">
    
    
        //when click in object '.refine .refine-colum .list-color .color' then check class of object exist "selected", if not then add class "selected" and append tag " <i class='check fa fa-check' aria-hidden='true'></i>" else remove class "select" and remove class ".check" of object.
    // $('.refine .refine-colum .list-color .color').click(function() {

    //     if ($(this).hasClass("selected") == false) {
    //         $(this).addClass('selected').append(" <i class='check fa fa-check' aria-hidden='true'></i>");
    //     } else {
    //         $(this).removeClass('selected');
    //         ($(this).find(".check").remove());
    //     }
    // });
    //when click in object '.fa-angle-down' then check if object do not exist class "fa-selected" then add class 'fa-selected' for object and add class 'li-up' for "'li#'+x", else then remove class 'fa-selected' and class 'li-up'.
  // $('.fa-angle-down').click(function(){
  //       var x = $(this)[0].attributes[0].nodeValue;
  //       if ($(this).hasClass("fa-selected") == false) {
  //           $(this).addClass('fa-selected');
  //           $('li#'+x).addClass('li-up');
  //       }else{
  //           $(this).removeClass('fa-selected');
  //           $('li#'+x).removeClass('li-up');
  //       }
  // });

    // $('.refine .refine-colum ul .fa-angle-down').click(function() {
    //     x = $(this).parents('.category');
    //     if(x.length == 0){
    //         if ($(this).hasClass("change") == false) {
    //             $(this).addClass('change selected');
    //         } else {
    //             $(this).removeClass('change selected');
    //         }
    //     }
    //     var attrContent = getComputedStyle(this, ':after').content;
    //     var currentId = $(this)[0].attributes[0].nodeValue;
    //     $('.refine .refine-colum .' + currentId +', .fsp-wrapper .refine-colum .' + currentId + '').animate({
    //         left: "+=50",
    //         height: "toggle"
    //     }, 800, function() {});
    // });

    // send catefory to form input
   //  $('.desktop  .category .has-child').click(function() {


   //          if ($(this).hasClass("has-child-selected") == false) {
   //              $(this).addClass('has-child-selected');
   //              category_id = $(this).attr('id');
   //              $('.desktop .'+category_id+' .has-child').addClass('has-child-selected');
   //              $('.desktop .'+category_id).find('.item').addClass('selected')
   //          } else {
   //              $(this).removeClass('has-child-selected');
   //              category_id = $(this).attr('id');
   //              $('.desktop .'+category_id+' .has-child').removeClass('has-child-selected');
   //              $('.desktop .'+category_id).find('.item').removeClass('selected')
   //          }
   //      array_category = $('.category .item.selected').toArray();
   //      var a2 =  [];
   //      for (i = 0; i < array_category.length ; i++) {
   //          var a1 = (array_category[i].attributes[0].nodeValue);
   //          a2.push(a1);
   //      };
   //      $("input[name='catids']").val(a2);
   //      var a2 = [];
   //      loadProductData();
            
   //  });
   // $('.mobile .category .has-child').click(function() {

   //          if ($(this).hasClass("has-child-selected") == false) {
   //              $(this).addClass('has-child-selected');
   //              category_id = $(this).attr('id');
   //              $('.mobile .'+category_id+' .has-child').addClass('has-child-selected');
   //              $('.mobile .'+category_id).find('.item').addClass('selected')
   //          } else {
   //              $(this).removeClass('has-child-selected');
   //              category_id = $(this).attr('id');
   //              $('.mobile .'+category_id+' .has-child').removeClass('has-child-selected');
   //              $('.mobile .'+category_id).find('.item').removeClass('selected')
   //          }
   //      array_category = $('.category .item.selected').toArray();
   //      var a2 =  [];
   //      for (i = 0; i < array_category.length ; i++) {
   //          var a1 = (array_category[i].attributes[0].nodeValue);
   //          a2.push(a1);
   //      };
   //      $("input[name='catids']").val(a2);
   //      var a2 = [];
   //      loadProductData();
   //  });
    //clear filter
    // $('.clear-filter').click(function(){

    //     $('.item.selected').removeClass('selected');
    //     $('.has-child-selected').removeClass('has-child-selected');
    //     $('.color.selected').removeClass('selected');
    //     $('i.check.fa.fa-check').remove();
    //     x = $('#productFilterDetail input[type="hidden"]');
    //    // console.log(x);
        
    //     for (i = 0; i < x.length ; i++) {
    //         y = x[i].attributes[3].nodeValue ;
    //         console.log("input[name="+y+"]");
    //         $("input[name="+y+"]").val("");
    //     };
    // });
    //clear filter
        // when click '.category .item' then check if it has class "selected" then remove class "selected" else add class "selected", and convert '.category .item.selected' to array, assign value of array for new array after assign value of new array for "input[name='catids']", final call function loadProductData().
    // $('.category .item').click(function(){
        
    //     if($(this).hasClass('selected')){
    //         $(this).removeClass('selected');
    //     }else{
    //         $(this).addClass('selected');
    //     }

    //     array_category = $('.category .item.selected').toArray();
    //     var a2 =  [];
    //     for (i = 0; i < array_category.length ; i++) {
    //         var a1 = (array_category[i].attributes[0].nodeValue);
    //         a2.push(a1);
    //     };
    //     $("input[name='catids']").val(a2);
    //     var a2 = [];
    //     loadProductData();

    // });
        // when click '.brands .list-brand li' then check if it has class "selected" then remove class "selected" else add class "selected", and convert '.brands .item.selected' to array, assign value of array for new array after assign value of new array for "input[name='brands']", final call function loadProductData(). 
    // $('.brands .list-brand li').click(function(){
    //     if($(this).hasClass('selected')){
    //         $(this).removeClass('selected');
    //     }else{
    //         $(this).addClass('selected');
    //     }

    //     array_brand = $('.brands .item.selected').toArray();
    //     var a2 =  [];
    //     for (i = 0; i < array_brand.length ; i++) {
    //         var a1 = (array_brand[i].attributes[0].nodeValue);
    //         a2.push(a1);
    //     };
    //     $("input[name='brands']").val(a2);
    //     var a2 = [];
    //     loadProductData();
        
    // });
        //when click '.colors .list-color .color' then convert '.color.selected' to array, ssign value of array for new array after assign value of new array for "input[name='colors']". 
    // $('.colors .list-color .color').click(function(){
    //     array_color = $('.color.selected').toArray();
    //     var a2 =  [];
    //     for (i = 0; i < array_color.length ; i++) {
    //         var a1 = (array_color[i].attributes[0].nodeValue);
    //         a2.push(a1);
    //     };
    //     $("input[name='colors']").val(a2);
    //     var a2 = [];
    // });
        //when click '.deals .item' then assign value its for "name_deal", check x = 1 then remove class "selected" and change value of  "input[name='"+name_deal+"']" is empty, else add class "selected" and change value of "input[name='"+name_deal+"']" is 1.
    // $('.deals .item').click(function(){
    //     console.log($(this));
    //         name_deal = $(this)[0].attributes[0].nodeValue;
    //         x = $("input[name='"+name_deal+"']").val();
    //         if(x == 1){
    //             $("input[name='"+name_deal+"']").val('');
    //             $(this).removeClass('selected');
    //         }else{
    //             $("input[name='"+name_deal+"']").val('1');
    //             $(this).addClass('selected');
    //         }         
    // });




    // send to form input
</script>

<!-- javascript of product-item -->

<script type="text/javascript">
    jQuery(document).ready(function($){
        // set css default of ".sort-list" when document ready
        $(".sort-list").css({"opacity": "0.3", "cursor": "default"});
            // hide "#search" when document ready
        $("#search").hide();
            //check if width of window >=992 then
        if(window.innerWidth >= 992)
        {      
                //when mouse move in '.product_item_popup' then show ".popup_item, .quick_view_v2" and assign height of ".quick_view_v2" and line hieght of tag "span" equal height of ".icon_like"
            $(document).on({
                mouseenter: function () {
                    $(this).parent().find(".popup_item, .quick_view_v2").show();
                    var height1 = $(this).parent().find(".icon_like").height();
                    $(this).parent().find(".quick_view_v2").height(height1).find("span").css("line-height",height1+'px');
                }
                // mouseleave: function () {
                //     $(this).find('.btn-group').fadeOut();
                // }
            }, '.product_item_popup');
                //when mouse leave '.uc_contact' then hide ".popup_item, .quick_view_v2"
            $(document).on({
                // mouseenter: function () {
                //     $(this).parent().find(".popup_item, .quick_view_v2").show();
                //     var height1 = $(this).parent().find(".icon_like").height();
                //     $(this).parent().find(".quick_view_v2").height(height1).find("span").css("line-height",height1+'px');
                // },
                mouseleave: function () {
                    $(this).parent().find(".popup_item, .quick_view_v2").hide() ;
                }
            }, '.uc_contact');

            // $(".product_item_popup").mouseenter(function(){
            //     $(this).parent().find(".popup_item, .quick_view_v2").show();
            //     var height1 = $(this).parent().find(".icon_like").height();
            //     $(this).parent().find(".quick_view_v2").height(height1).find("span").css("line-height",height1+'px');
            // });
            // $(".uc_contact").mouseleave(function(){
            //     $(this).parent().find(".popup_item, .quick_view_v2").hide() ;
            // });
            
            // $(document).on({
            //     mouseout: function () {
            //         $("body").css({"overflow": "auto", "padding-right": "0px"});
            //     }
            // }, '#modal_QV, #modal_alert');
            // $(document).on({
            //     mouseover: function () {
            //         $("body").css("overflow", "hidden");
            //     }
            // }, '#modal_QV, #modal_alert');
        }
            //when mouse leave '#modal_QV, #modal_alert' then change attribute css of body"
        $(document).on({
            mouseout: function () {
                $("body").css({"overflow": "auto", "padding-right": "0px"});
            }
        }, '#modal_QV, #modal_alert');
            //when mouse move in '#modal_QV, #modal_alert' then change attribute css of body"
        $(document).on({
            mouseover: function () {
                $("body").css("overflow", "hidden");
            }
        }, '#modal_QV, #modal_alert');        

    });
        // send "alertdataid" to '/service/getfeedalert', get content form '/service/getfeedalert' assign for "#alert-content"
    
        //when click '.modal_body_footer' then hide "#modal_QV", show "#modal_alert", call function  loadAjaxForAlert(alertdataid), change attribute css of '#modal_alert'.
    
        // when change width of window then height of '.share_product' equal sum height of ".uc_contact" and ".show_item"
    $(window).resize(function() {
        $('.share_product').height(function(){
            var height1 = $(this).parents(".product_item").find(".uc_contact").height();
            var height2 = $(this).parents(".product_item").find(".show_item").height();
            return height1 + height2;
        });
    });
    
        //when click ".sort-list" then remove class "col-xs-6" of ".product.col-lg-3.col-sm-4", change attribute css of its and ".sort-grid"
    $(".sort-list").click(function(){
        $(this).parents("body").find(".product.col-lg-3.col-sm-4").removeClass("col-xs-6");
        $(this).css({"opacity": "0.3", "cursor": "default"});
        $(this).parents(".row").find(".sort-grid").css({"opacity": "1", "cursor": "pointer"});

    });
        //when click ".sort-list" then remove class "col-xs-6" of ".product.col-lg-3.col-sm-4", change attribute css of its and ".sort-list"
    $(".sort-grid").click(function(){
        $(this).parents("body").find(".product.col-lg-3.col-sm-4").addClass("col-xs-6");
        $(this).css({"opacity": "0.3", "cursor": "default"});
        $(this).parents(".row").find(".sort-list").css({"opacity": "1", "cursor": "pointer"});

    });
        //when click '.hide_item' then hide ".share_product"
    $('body').on('click', '.hide_item', function (){
        $(this).parents(".product_item").find(".share_product").hide();
    });

    // $(".hide_item").click(function() {        
    //     $(this).parents(".product_item").find(".share_product").hide();
    // });
        //when click '.show_item' then show and change hieght of '.share_product'
    $('body').on('click', '.show_item', function (){
        $(this).parents('.product_item').find('.share_product').show();
        var height1 = $(this).height();
        $(this).parents(".product_item").find(".share_product").height(function(){
            var height2 = $(this).parents(".product_item").find(".uc_contact").height();
            return height1 + height2;
        });
    });

    // $(".show_item").click(function() {
    //     $(this).parents('.product_item').find('.share_product').show();
    //     var height1 = $(this).height();
    //     $(this).parents(".product_item").find(".share_product").height(function(){
    //         var height2 = $(this).parents(".product_item").find(".uc_contact").height();
    //         return height1 + height2;
    //     });
    // });
        //when click '.icon_like' then remove or add class "active"



    // $(".icon_like").click(function() {
    //     var myClasses = this.classList;
    //     if (myClasses.contains("active")) {
    //         myClasses.remove("active");
    //     } else {
    //         myClasses.add("active");
    //     }
    // });

    // $(".icon_alert").click(function() {
    //     var myClasses = this.classList;
    //     if (myClasses.contains("active")) {
    //         myClasses.remove("active");
    //     } else {
    //         myClasses.add("active");
    //     }
    // });   
    
    // $(".modal_body_icon_link").width(function(){
    //     return $(this).find(".fa-facebook").width() + $(this).find(".fa_final");
    // })  ;        
</script> 

<!-- End javascript of product-item -->

<!-- Javascript of selected_filter.php/sort-item -->

<script type="text/javascript">
        //when click ".sort-item" then check if its exist class "active" then remove class "active", ".icon_arrow" add class "fa-chevron-down" and remove class "fa-chevron-up", ".sort-item >.uc_line_content" close slide; else add class "active", ".icon_arrow" remove class "fa-chevron-down" and add class "fa-chevron-up", ".sort-item >.uc_line_content" open slide.
    $(".sort-item").click(function(){
        var myClasses = this.classList;
        if(myClasses.contains("active"))
        {
            myClasses.remove("active");
            $(".icon_arrow").removeClass("fa-chevron-up");
            $(".icon_arrow").addClass("fa-chevron-down");
            $(".sort-item >.uc_line_content").slideUp();
        }
        else
        {
            myClasses.add("active");
            $(".icon_arrow").removeClass("fa-chevron-down");
            $(".icon_arrow").addClass("fa-chevron-up");
            $(".sort-item >.uc_line_content").slideDown();
        }
        // $(".icon_arrow").removeClass("fa-chevron-down");
        // $(".icon_arrow").addClass("fa-chevron-up");
        // $(".uc_line_content").slideDown();
    });
    // $(".sort-item").click(function(){
    //     $(".icon_arrow").removeClass("fa-chevron-up");
    //     $(".icon_arrow").addClass("fa-chevron-down");
    //     $(".uc_line_content").slideUp();
    // });
        //when click ".sort-item-select" then assign content of it for ".sort-item-selected" and ".uc_line_content" close slide.
    $(".sort-item-select").click(function(){
        var content_sl = $(this).html();
        $(this).parents(".sort-item").find(".sort-item-selected").html(content_sl);
        $(this).parents(".uc_line_content").slideUp();
    });
</script>

<!-- End Javascript of selected_filter.php/sort-item -->
<!-- Footer -->
        <footer class="container-fluid">
            <div class="row">
                <div class="line-footer"></div>
                    <div class="footer-above">
                        <div class="menu-footer col-lg-6">
                            <div class="list-menu">
                                <ul>
                                    <li>How it work</li>
                                    <li>About Us</li>
                                    <li>Blog</li>
                                    <li>FAQ</li>
                                    <li>Shipping</li>
                                    <li>Pricing</li>
                                    <li>Exchange & Return</li>
                                    <li>Careers</li>
                                    <li>Contact Us</li>
                                </ul>
                            </div>
                        </div>

                        <div class="newsletter col-lg-4">
                            <div class="newsletter-wrap">
                                <div class="newsletter-signup">
                                    <span>Sign up for newsletter</span>
                                </div>
                                <div class="newsletter-input ">
                                    <input placeholder="Your Email Address Here" >
                                    <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>

                        <div class="footer-social col-lg-2">
                            <div class="social-block">
                            <div class="social" ><i class="fa fa-facebook" aria-hidden="true"></i></div>
                            <div class="social" ><i class="fa fa-twitter" aria-hidden="true"></i></div>
                            <div class="social" ><i class="fa fa-instagram" aria-hidden="true"></i></div>
                            <div class="social" ><i class="fa fa-youtube" aria-hidden="true"></i></div>
                          
                            </div>
                        </div>
                    </div>
                    
                    <div class="copyright">
                        <div class="copyright-wrap">
                            <p class="copyright-text"> COPYRIGHT 2016 STITCH STYLE SOLUTIONS INC.<span> ALL RIGHTS RESERVED</span>
                            </p>
                        </div>
                        <div class="terms">
                            <div class="terms-wrap">
                                <span>|</span>
                                <p class="copyright-text"> TERMS &amp; CONDITIONS</p>
                                <span>|</span>
                                <p class="copyright-text"> PRIVACY &amp; POLICY</p>
                            </div>
                        </div>
                    </div>
        </div>
        </footer>
        <!-- End-Footer -->
        <script type="text/javascript">
            // $('.uc_icon.icon_like').click(function(){
            //     alert(123);
            // });



        </script>
        <script>
            //
            $(document).ready(function(){
                var submitIcon = $('.searchbox-icon');
                var inputBox = $('.searchbox-input');
                var searchBox = $('.searchbox');
                var isOpen = false;
                // when click '.searchbox-icon' then check if '.searchbox-input' is empty then event default, if "isOpen" equal "false" then '.searchbox' add class 'searchbox-open' and focus '.searchbox-input' and value of "isOpen" is true and change attribute of "#search", else then counterwork
                submitIcon.click(function(e){
                    if(inputBox.val()==""){
                        e.preventDefault();
                    }
                    if(isOpen == false){
                        searchBox.addClass('searchbox-open');
                        inputBox.focus();
                        isOpen = true;
                         $("#search").css("z-index","99")
                        
                    } else {
                        searchBox.removeClass('searchbox-open');
                        inputBox.focusout();
                        isOpen = false;
                        $("#search").removeAttr("style");
                        //$("#show-hide-menu").click();
                    }
                     
                });  

                submitIcon.mouseup(function(){
                        return false;
                    });
                searchBox.mouseup(function(){
                        return false;
                    });
                $(document).mouseup(function(){
                        if(isOpen == true){
                            
                            submitIcon.click();
                        }
                    });
                
            });
                    // change value of '.searchbox-input' khi input value form keyboard
                function buttonUp(){
                    var inputVal = $('.searchbox-input').val();
                    inputVal = $.trim(inputVal).length;
                    if( inputVal == 0){
                         $('.searchbox-input').val('');
                    } 
                }
                var flag = false;
                    //show or hide '.searchbox-icon' when click "#show-hide-menu" or '.searchbox-icon'
                $("#show-hide-menu").click(function(){
                    $("#show-hide-menu").toggleClass("angleplus");
                    if(flag == false){
                        $('.searchbox-icon').click();
                        flag = true;
                    } else {
                        flag = false;
                    }
                    
                });
            var icons = {
            header: "ui-icon-circle-arrow-e",
            activeHeader: "ui-icon-circle-arrow-s"
            };
            // show menu khi click "#accordion", "#accordion-m"
            $( "#accordion" ).accordion({
                icons: icons,
                heightStyle:"content",
                collapsible: true,
                active: false
            });
            $( "#accordion-m" ).accordion({
                icons: icons,
                heightStyle:"content",
                collapsible: true,
                active: false
            });
                // change attribute of "#header-block" and "#search" when scroll window
            $(window).scroll(function(){
                if($(this).scrollTop() >= $("#header-block").height())
                {
                    $("#header-block").css({"position": "fixed", "width": "100%", "top": "0px", "background": "#fff", "z-index": "99"});
                    if(window.innerWidth >= 768) 
                    {                       
                        $("#search").show();
                        $(".form_search").hide();
                        $("#header-container").find(".row").addClass("wrap-header-top-navbar");
                        $(".searchbox").addClass("searchbox-open").css("z-index", "99");
                    }
                    else 
                    {
                        $(".form_search").hide();
                    }
                }
                else 
                {
                    $("#header-block").css("position","static");
                    if(window.innerWidth >= 768) 
                    {                       
                        $("#search").hide();
                        $(".form_search").show();
                        $("#header-container").find(".row").removeClass("wrap-header-top-navbar");
                        $(".searchbox").removeClass("searchbox-open");
                    }
                    else
                    {
                        $(".form_search").hide();
                    }
                }
            });



            
            $("#m-show-userbox").click(function(event) {
                $("#user-mblock").css('display','block');
            });
            $("#hid-userbox").click(function(){
                $("#user-mblock").removeAttr("style");
            });

            // $("#banner").css("margin-top",function(){
            //  return $(this).parent().find("#header-block").height();
            // });
            
            // $(window).scroll(function(){
            //     alert("true");
            //     if($(this).scrollTop() >= $("#header-block").height())
            //     {
            //         $("#header-block").css({"position": "fixed", "width": "100%", "top": "0px", "background": "#fff", "z-index": "99"});
            //     }
            //     else 
            //     {
            //         $("#header-block").css("position","static");
            //     }
            // });
            
        </script> 

    </body>
</html>