<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle("El Nove - Dress to the nines")->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="<?php echo $this->basePath();?>favicon.ico">

    <?php if( isset($this->additionalMeta) ) { echo $this->additionalMeta; }?>        
    
    <!-- Le styles -->
    <?php echo $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/jquery.gritter.css')
                    ->prependStylesheet($this->basePath() . '/css/lnovecustom.css')
                    ->prependStylesheet($this->basePath() . '/css/normalize.css')
                    ->prependStylesheet($this->basePath() . '/css/owl.carousel.css')
                    ->prependStylesheet($this->basePath() . '/fa/css/font-awesome.css')
                    ->prependStylesheet($this->basePath() . '/js/sweetalert-master/dist/sweetalert.css')
                    ->appendStylesheet($this->basePath() . '/css/mystyle.css')
                    ->appendStylesheet($this->basePath() . '/myalert/css/reveal.css')
                    ->prependStylesheet($this->basePath() . '/myalert/css/foundation.css')
                    ->appendStylesheet($this->basePath() . '/myalert/css/style.css')
                    ->appendStylesheet($this->basePath() . '/tooltipster/css/tooltipster.css')
                    ->appendStylesheet($this->basePath() . '/tooltipster/css/themes/tooltipster-shadow.css')
                    ->appendStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
                    ->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css')
                    ->appendStylesheet('https://fonts.googleapis.com/css?family=Roboto:400,300,500,700,900')
                    ->appendStylesheet($this->basePath() . '/showhidepassword/css/example.wink.css')
                    ->appendStylesheet('https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css')
                ;
    ?>

    <link href="/assets/css/custom.less" rel="stylesheet/less" type="text/css">
    <link href="/assets/css/info_about_us.less" rel="stylesheet/less" type="text/css">
    <link href="/assets/css/info_frequently_ask_question.less" rel="stylesheet/less" type="text/css">
    <link href="/assets/css/privacy_and_policies_page.less" rel="stylesheet/less" type="text/css">
   
    <link rel="stylesheet/less" type="text/css" href="/assets/css/careers_page.less" />

    <!-- style for defination -->
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" href="/assets/css/prism.css">
    <link rel="stylesheet" href="/assets/css/chosen.css">
    <!-- End style for defination -->

    

    <?php
    echo $this->headScript()->prependFile($this->basePath() . '/assets/js/jquery-ui.js')
                            ->prependFile($this->basePath() . '/js/jquery.js')
                            ->appendFile($this->basePath() . '/assets/js/bootstrap.min.js')
                            ->appendFile($this->basePath() . '/assets/js/jquery.fullscreen-popup.js')
                            ->appendFile($this->basePath() . '/myalert/js/foundation.min.js')
                            ->appendFile($this->basePath() . '/myalert/js/foundation.reveal.js')
                            ->appendFile($this->basePath() . '/myalert/js/modernizr.js')
                            ->appendFile($this->basePath() . '/myalert/js/fastclick.js')
                            ->appendFile($this->basePath() . '/myalert/js/my_alert.js') 
                            ->appendFile($this->basePath() . '/js/jquery.gray.js')
                            ->appendFile($this->basePath() . '/js/jquery.placeholder.min.js')
                            ->appendFile($this->basePath() . '/showhidepassword/hideShowPassword.min.js')
                            ->appendFile('http://cdnjs.cloudflare.com/ajax/libs/less.js/2.6.1/less.min.js')
                            ->appendFile($this->basePath() . '/assets/js/header.js')
                            ->appendFile($this->basePath() . '/assets/js/common.js')
                            ->appendFile('https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js')
                            ->appendFile('https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js')
                ;
    ?>
</head>
<body>
    <div id="header-block">
        <div id="header-container" class="container-fluid hidden-xs">
            <div class="row">
                <div class="header-top-navbar col-lg-12 ">
                    <div class="row top-bar">
                        <div class="left-side col-lg-4 col-md-4 col-sm-4 col-xs-12" id="show-hide-menu">MENU</div>
                        <div class="logo col-lg-4 col-md-4 col-sm-4 col-xs-12"><a href="/"><img src="/assets/images/logo1.jpg" alt="" class="top-logo"></a>
                        </div>
                        <div class="right-side col-lg-4 col-md-4 col-sm-4 col-xs-12">
                            <?php if( isset($this->showHeaderLinks) && $this->showHeaderLinks=='LOGGED_IN' ) { ?>
                                <div class="uc_clean_accordion">
                                    <div class="uc_clean_accordion_wrap">
                                        <div id="accordion" class="uc_clean_accorder_content">
                                            <h3 class="uc_head_line">
                                                <div id="status-login" data-login="1"></div>
                                                <a class="uc_link_tittle">WELCOME, <?php echo $this->userLogged->firstName; ?></a>
                                            </h3>
                                            <div class="uc_line_content_header">
                                                <ul class="uc_des">
                                                    <li><a href="/profile/myaccount">My Profile</a>
                                                    </li>
                                                    <?php if($this->userLogged->type == 'admin') { ?>
                                                    <li><a href="/style">Styles</a>
                                                    <?php } ?>
                                                    </li>
                                                    <li><a href="/auth/logout">Logout</a>
                                                    </li>
                                                </ul>

                                            </div>
                                        </div>
                                    </div>
                                </div>      
                            <?php } else { ?>
                            <div id="status-login" data-login="0"></div>
                            <div class="login_signup">
                                <a href="/auth/login">LOGIN</a>
                            </div>
                        <?php }?>
                            <?php
                                $step = 0;
                                $request_uri = $_SERVER['REQUEST_URI'];
                                if($request_uri == '/profile') {
                                    $step = 1;
                                } else if($request_uri == '/profile/you') {
                                    $step = 2;
                                } else if($request_uri == '/profile/size') {
                                    $step = 3;
                                // } else if($request_uri == '/profile/brands') {
                                //     $step = 4;
                                } else if($request_uri == '/profile/price') {
                                    $step = 4;
                                } else if($request_uri == '/profile/signup') {
                                    $step = 5;
                                }
                                ?>
                                <?php if($step != 0) { ?>
                                    <a  href="javascript:void(0);" class="btn-st-blue">Step <?php echo $step; ?> of 5</a>
                                <?php } else { ?>
                                    <a href="/profile" class="btn-st-blue">GET STARTED</a>
                                <?php } ?>
                            <!-- <a href="#" class="btn-st-blue">GET STYLED</a> -->
                        </div>
                    </div>
                </div>
            </div>

            <nav id="menu" class="row">
                <div class="col-lg-12 col-xs-12" id="row-top-navbar">
                    <div class="row">
                        <div class="col-lg-12 col-xs-12 text-center" id="top-nav" class="top-navbar">
                            <ul>
                                <li><a href="/info/how-it-works">HOW IT WORKS</a>
                                </li>
                                <li><a href="/info/about-us">ABOUT US</a>
                                </li>
                                <li><a href="http://<?=URL_BLOG?>">BLOG</a>
                                </li>
                                <li><a href="/info/frequently-asked-questions">FAQ</a>
                                </li>
                                <li><a href="/info/frequently-asked-questions?tag=shipping">SHIPPING</a>
                                </li>
                                <li><a href="/info/frequently-asked-questions?tag=pricing">PRICING</a>
                                </li>
                                <li><a href="/info/frequently-asked-questions?tag=shipping">EXCHANGE & RETURNS</a>
                                </li>
                                <li><a href="/info/careers">CAREERS</a>
                                </li>
                                <li><a href="/info/contact-us">CONTACT US</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-10 col-lg-offseet-1 col-xs-10 col-xs-offset-1" id="search">
                    <form class="searchbox">
                        <input type="search" placeholder="Search by Product..." name="search1" class="searchbox-input">
                        <div class="charater-center"></div>
                        <input type="search"  id="search-venue" placeholder="Search by Venue..." name="search2" class="searchbox-input">
                        <button type="submit" class="searchbox-submit">
                            <span class="searchbox-icon"><i class="fa fa-search" aria-hidden="true" id="search_btn"></i></span>
                        </button>
                    </form>
                </div>
            </nav>
        </div>
        <div id="mobile-header" class="container-fluid visible-xs">
            <div class="row">
                <div class="col-xs-12" id="mtop-bar">
                 
                    <div class="uc_clean_accordion col-xs-6" id="mtop-left">
                    <?php if( isset($this->showHeaderLinks) && $this->showHeaderLinks=='LOGGED_IN' ) { ?>
                    <div class="uc_clean_accordion_wrap">
                        <div id="login_signup" class="uc_clean_accorder_content">
                            <h3 class="uc_head_line" id="m-show-userbox">
                                <p class="uc_link_tittle">WELCOME, <?php echo $this->userLogged->firstName; ?></p>
                            </h3>
                         </div>
                    </div>
                    <?php } else { ?>
                        <div class="login_signup">
                            <a href="/auth/login">LOGIN</a>
                        </div>
                        <?php }?>
                    </div>
                    <?php
                        $step = 0;
                        $request_uri = $_SERVER['REQUEST_URI'];
                        if($request_uri == '/profile') {
                            $step = 1;
                        } else if($request_uri == '/profile/you') {
                            $step = 2;
                        } else if($request_uri == '/profile/size') {
                            $step = 3;
                        // } else if($request_uri == '/profile/brands') {
                        //     $step = 4;
                        } else if($request_uri == '/profile/price') {
                            $step = 4;
                        } else if($request_uri == '/profile/signup') {
                            $step = 5;
                        }
                        ?>
                        <?php if($step != 0) { ?>
                    <div class="col-xs-6" id="mtop-right">
                        <a  href="javascript:void(0);" class="btn-st-blue">Step <?php echo $step; ?> of 5</a>
                    </div>
                     <?php } else { ?>
                    <div class="col-xs-6" id="mtop-right">
                        <a href="/profile" class="btn-st-blue">GET STYLED</a>
                    </div>
                    <?php }?>
                </div>
            </div>
            <div class="row">
                <div class="user-mhiden" id="user-mblock">
                    <p class="tit-head">WELCOM, <?php echo $this->userLogged->firstName; ?> <span class="fa fa-times" id="hid-userbox"></span></p>
                    <ul class="link-box-user">
                        <li><a href="/profile/myaccount">My Profile</a></li>
                        <li><a href="/auth/logout">Log out</a></li>
                    </ul>
                </div>   
            </div>        
            <div class="row" id="menu-logo">
                <div class="col-xs-12">
                    <span class="fa fa-plus" id="pop-menu" data-popup="#popup"></span>
                    <a href="/"><img src="/assets/images/mobile-logo.png" alt="logo mobile" class="logo" /></a>
                </div>
            </div>
            <div class="row" id="search-bar">
                <form class="searchbox-mobile col-xs-12">
                    <input type="search" placeholder="Search by Product..." name="search1" class="m-searchbox-input">
                        <div class="charater-center"></div>
                        <input type="search" placeholder="Search by Venue..." name="search2" class="m-searchbox-input" >
                    <button type="submit" class="searchbox-submit">
                        <span class="m-searchbox-icon"><i class="fa fa-search" aria-hidden="true" id="m-search_btn"></i></span>
                    </button>
                </form>
            </div>
            <div class="row">
                <div class="col-xs-12 text-left" id="popup">
                    <div class="row">
                        <p class="m-title"> MENU</p>
                        <ul>
                            <li><a href="/info/how-it-works">HOW IT WORKS</a></li>
                            <li><a href="/info/about-us">ABOUT US</a></li>
                            <li><a href="http://<?=URL_BLOG?>">BLOG</a></li>
                            <li><a href="/info/frequently-asked-questions">FAQ</a></li>
                            <li><a href="/info/frequently-asked-questions?tag=shipping">SHIPPING</a></li>
                            <li><a href="/info/frequently-asked-questions?tag=pricing">PRICING</a></li>
                            <li><a href="/info/frequently-asked-questions?tag=shipping">EXCHANGE & RETURNS</a></li>
                            <li><a href="/info/careers">CAREERS</a></li>
                            <li><a href="/info/contact-us">CONTACT US</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="body-container" class="container-fluid">
      <?php echo $this->content; ?>  
    </div>
    <div class="top_page" id="click_back_to_top" >
        <a><img src="/img/arrow.png"></a>
    </div>
    <!-- Footer -->
    <footer class="container-fluid">
        <div class="row">
            <div class="line-footer"></div>
            <div class="footer-above">
                <div class="menu-footer col-lg-6">
                    <div class="list-menu">
                        <ul>
                            <li><a href="/info/how-it-works">HOW IT WORKS</a></li>
                            <li><a href="/info/about-us">ABOUT US</a></li>
                            <li><a href="http://<?=URL_BLOG?>">BLOG</a></li>
                            <li><a href="/info/frequently-asked-questions">FAQ</a></li>
                            <li><a href="/info/frequently-asked-questions?tag=shipping">SHIPPING</a></li>
                            <li><a href="/info/frequently-asked-questions?tag=pricing">PRICING</a></li>
                            <li><a href="/info/frequently-asked-questions?tag=shipping">EXCHANGE &amp; RETURNS</a></li>
                            <li><a href="/info/careers">CAREERS</a></li>
                            <li><a href="/info/contact-us">CONTACT US</a></li>
                        </ul>
                    </div>
                </div>

                <div class="newsletter col-lg-4">
                    <div class="newsletter-wrap">
                        <div class="newsletter-signup">
                            <span>Sign up for newsletter</span>
                        </div>
                        <div class="newsletter-input ">
                            <input id="idNewsLetterInput" placeholder="Your Email Address Here" >
                            <i class="fa fa-paper-plane-o" id="idNewsLetter" aria-hidden="true"></i>
                        </div>
                    </div>
                </div>

                <div class="footer-social col-lg-2">
                    <div class="social-block">
                    <div class="social" ><a href="https://www.facebook.com/elnovethe9s/" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></div>
                    <div class="social" ><a href="https://twitter.com/elnovethe9s" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></div>
                    <div class="social" ><a href="https://www.instagram.com/elnove/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></div>
                    <div class="social" ><a href="https://www.youtube.com/channel/UCpf1DXmAFx_Khiku7dQYQLw" target="_blank"><i class="fa fa-youtube" aria-hidden="true"></i></a></div>
                  
                    </div>
                </div>
            </div>
            
            <div class="copyright">
                <div class="copyright-wrap">
                    <p class="copyright-text"> COPYRIGHT 2016 STITCH STYLE SOLUTIONS INC.<span> ALL RIGHTS RESERVED</span>
                    </p>
                </div>
                <div class="terms">
                    <div class="terms-wrap">
                        <span>|</span>
                        <p class="copyright-text"><a href="/info/terms-and-conditions">TERMS &amp; CONDITIONS</a></p>
                        <span>|</span>
                        <p class="copyright-text"><a href="/info/privacy-and-policies">PRIVACY &amp; POLICY</a></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End-Footer -->
    <div class="alert">
        <?php include('alert.phtml') ?>
    </div>
    <div id="loading-div-background">
        <div id="loading-div" class="ui-corner-all" >
            <img style="margin-top:20px; height: 50px" src="/img/loading7_light_blue.gif" alt="Loading.."/>
            <h2 style="color:gray;font-weight:normal;">Please wait....</h2>
        </div>
    </div> 
</body>
</html>
<!-- JS for defination -->
        <script src="/assets/js/chosen.jquery.js" type="text/javascript"></script>
        <script src="/assets/js/prism.js" type="text/javascript" charset="utf-8"></script>
        <!-- End JS for defination -->