<div class="full">
<div class="container">
<div class="left-link-box">
    <div id="blue-btn">
        <div class="blue-btn1  ">
            <a href=""><img src="/img/circle-close.png"></a>
            <div class="square1"></div>
        </div>
        <div class="clr"></div>
        <p class="head1">Article Shopping / Outfit Shopping</p>
        <div class="clr"></div>
    </div>
    <div class="radio-box">
        <form>
            <input type="radio" name="option" id="radio1" checked/>
            <label for="radio1" class="outfit">
            <span class="fa-stack ">
                <i class="fa fa-circle-o fa-stack-1x"></i>
                <i class="fa fa-circle fa-stack-1x"></i>
            </span>
                OUTFIT
            </label>
            <input type="radio" name="option" id="radio2" />
            <label for="radio2"  class="outfit">
            <span class="fa-stack">
                <i class="fa fa-circle-o fa-stack-1x"></i>
                <i class="fa fa-circle fa-stack-1x"></i>
            </span>
                ARTICLES
            </label>
        </form>
    </div>

    <div class="refined">
        <h1>REFINED BY</h1>
        <div class="cat page_left_menu ">
            <h5> <img  src="/img/down.png">  VENUES</h5>
            <ul>
                <li><input type="checkbox" name="option" id="check1" checked/>
                    <label for="check1">
            <span class="fa-stack">
                <i class="fa fa-square-o fa-stack-1x"></i>
                <i class="fa fa-square fa-stack-1x"></i>
            </span>
                        All
                    </label></li>

                <li><input type="checkbox" name="option" id="check2" />
                    <label for="check2">
            <span class="fa-stack">
                <i class="fa fa-square-o fa-stack-1x"></i>
                <i class="fa fa-square fa-stack-1x"></i>
            </span>
                        Work
                    </label></li>
                <li><input type="checkbox" name="option" id="check1" checked/>
                    <label for="check1">
            <span class="fa-stack">
                <i class="fa fa-square-o fa-stack-1x"></i>
                <i class="fa fa-square fa-stack-1x"></i>
            </span>
                        Night Out
                    </label></li>

                <li><input type="checkbox" name="option" id="check2" />
                    <label for="check2">
            <span class="fa-stack">
                <i class="fa fa-square-o fa-stack-1x"></i>
                <i class="fa fa-square fa-stack-1x"></i>
            </span>
                        Casual
                    </label></li>

            </ul>
        </div>



        <div class="clr"></div>

    </div>


</div><!-- left_link_box-->



<div class="right-link-box">
<div class="bg_color"></div>
<!--<ul class="list-box">
    <li><a href="articles.html" class="active1"  >SAVED</a></li>
    <li><a href="bought.html" >BOUGHT</a></li>
</ul>-->
<div class="clr"></div>


<div class="big_box">

    <div class="img_box_main">
        <div class="main_big_product_box">
            <div class="main_big_product_img_box">
                <img src="/img/big_img.jpg" alt="product" />
            </div>
            <div class="main_big_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>



        <div class="main_sm_product_box">
            <div class="main_sm_product_img_box">
                <img src="/img/small_img2.jpg" alt="product" />
            </div>
            <div class="main_sm_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>

        <div class="main_sm_product_box">
            <div class="main_sm_product_img_box">
                <img src="/img/small_img2.jpg" alt="product" />
            </div>
            <div class="main_sm_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>




    </div>


    <div class="img_box_main">

        <div class="main_sm_product_box">
            <div class="main_sm_product_img_box">
                <img src="/img/small_img2.jpg" alt="product" />
            </div>
            <div class="main_sm_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>

        <div class="main_sm_product_box">
            <div class="main_sm_product_img_box">
                <img src="/img/small_img2.jpg" alt="product" />
            </div>
            <div class="main_sm_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>




        <div class="main_big_product_box">
            <div class="main_big_product_img_box">
                <img src="/img/big_img.jpg" alt="product" />
            </div>
            <div class="main_big_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>







    </div>






    <div class="black-box">
        <div class="thumb">
            <a href="">  <img src="/img/white-like.png" alt="image"> UNsave this outfit</a>
        </div>

        <div class="thumb">
            <a href=""> <img src="/img/share.png" alt="image"> SHARE THIS OUTFIT</a>
        </div>

        <div class="thumb">
            <p>bought entire outfit</p>
        </div>


        <a href=""> <img src="/img/white-like.png" alt="image"> <span>40</span></a>


    </div>


    <div class="clr"></div>
</div>  <!-- big_box-->



<div class="clr"></div>





<div class="big_box">

    <div class="img_box_main">
        <div class="main_big_product_box">
            <div class="main_big_product_img_box">
                <img src="/img/big_img.jpg" alt="product" />
            </div>
            <div class="main_big_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>



        <div class="main_sm_product_box">
            <div class="main_sm_product_img_box">
                <img src="/img/small_img2.jpg" alt="product" />
            </div>
            <div class="main_sm_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>

        <div class="main_sm_product_box">
            <div class="main_sm_product_img_box">
                <img src="/img/small_img2.jpg" alt="product" />
            </div>
            <div class="main_sm_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>




    </div>


    <div class="img_box_main">

        <div class="main_sm_product_box">
            <div class="main_sm_product_img_box">
                <img src="/img/small_img2.jpg" alt="product" />
            </div>
            <div class="main_sm_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>

        <div class="main_sm_product_box">
            <div class="main_sm_product_img_box">
                <img src="/img/small_img2.jpg" alt="product" />
            </div>
            <div class="main_sm_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>




        <div class="main_big_product_box">
            <div class="main_big_product_img_box">
                <img src="/img/big_img.jpg" alt="product" />
            </div>
            <div class="main_big_product_tag_box">
                <a href="#" class="fl">
                    <img src="/img/price.png" alt="price" />
                </a>
                <a  href="#"  class="fr">
                    <img src="/img/thumb.png" alt="like" />
                </a>


            </div>
        </div>







    </div>






    <div class="black-box">
        <div class="thumb">
            <a href="">  <img src="/img/white-like.png" alt="image"> UNsave this outfit</a>
        </div>

        <div class="thumb">
            <a href=""> <img src="/img/share.png" alt="image"> SHARE THIS OUTFIT</a>
        </div>

        <div class="thumb">
            <p>bought entire outfit</p>
        </div>


        <a href=""> <img src="/img/white-like.png" alt="image"> <span>40</span></a>


    </div>


    <div class="clr"></div>
</div>  <!-- big_box-->




</div>

</div>
<div class="clr"></div>
</div><!--container-->
</div>