<?php
$page_url = $this->serverUrl().'/service/feeddatadetail/'.$this->feedDataDetail['id'].'/'.rand();
$title = 'ELNove - '.$this->feedDataDetail['caption'];
?>
<div id="detail_page" class="content-page row">
<div class="col-lg-10 col-lg-offset-1 grey_bg">
   <?php
$page_url = $this->serverUrl().'/service/feeddatadetail/'.$this->feedDataDetail['id'].'/'.rand();
$title = 'ELNove - '.$this->feedDataDetail['caption'];
?>

<div class="col-lg-6 col-sm-6 modal_body_left">
    <img class="img-responsive" src="<?php echo $this->feedDataDetail['imageurl']; ?>" alt="product Image">
</div>
<div class="col-lg-6 col-sm-6 modal_body_right">
    <p class="modal_name_item"><?php echo $this->feedDataDetail['caption']; ?></p>
    <p class="modal_brand_item"> <?php echo $this->feedDataDetail['brand']; ?></p>
    <p class="modal_price_item"><span><?php echo ($this->feedDataDetail['onsale']=='Y'?$this->feedDataDetail['saleprice']:$this->feedDataDetail['price'])?></span><?php echo $this->feedDataDetail['currency'] ?></p>
    <div class="modal_buy_product">
        <a href="<?php echo $this->url('service/articlebought', array('feeddataid' => base64_encode($this->feedDataDetail['id']))); ?>" target="_blank"><span class="btn-st-blue">BUY</span></a>
        <i class="fa fa-heart-o" aria-hidden="true"></i>
    </div>
    <p class="modal_alert_detail">DETAILS</p>
    <p><?php echo $this->feedDataDetail['description']; ?></p>
    <div class="modal_body_icon_link">
        <a href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>"><i class="fa fa-facebook"></i></a>
        <a href="https://api.addthis.com/oexchange/0.8/forward/pinterest/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>"><i class="fa fa-pinterest-p"></i></a>
        <a href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>"><i class="fa fa-tumblr"></i></a>
        <a href="https://api.addthis.com/oexchange/0.8/forward/google_plusone_share/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>"><i class="fa fa-google-plus"></i></a>
        <a href="https://api.addthis.com/oexchange/0.8/forward/email/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>"><i class="fa fa-envelope-o fa_final"></i></a>
    </div>
    <div class="modal_body_footer" data-alert-id="<?php echo $this->feedDataDetail['id']; ?>">
        <i class="fa fa-bell-o" aria-hidden="true"></i>
        <span>Get Sale Alert</span>
    </div>
</div>



</div>
</div>
<!-- <div class="continue">
    <div class="container">
        <div class="image-cross fl">
            <a href="/service"><img src="/img/close.png">BACK</a>
        </div>

        <div class="btn-con1 fr">
            <a target="_blank my_tooltip" title="Purchase article through our partner" href="<?php //echo $this->url('service/articlebought', array('feeddataid' => base64_encode($this->feedDataDetail['id']))); ?>">BUY NOW</a>
        </div>
    </div><!--container-->
<!-- </div> continue --> 

<!-- <script src="js/owl.carousel.js"></script>
<script>
    $(document).ready(function () {
        $("#owl-demo9").owlCarousel({
            autoPlay: 3000, //Set AutoPlay to 3 seconds
            navigation: false,
            items: 3,
            itemsDesktop: [1199, 3],
            itemsDesktopSmall: [979, 3]
        });
        /*****************block for adding this product into my coloseset**************/
        $('.mycloseset').on('click', function () {
            var id = $(this).attr("id");
            var url = "/service/likeclosset/";
            $.ajax({
                url: url,
                type: 'POST',
                data: {closesetId: id},
                dataType: 'json',
                success: function (result) {
                    if (result.status == 'N') {
                        alert(result.mgs);
                    } else if (result.status == 'Y') {
                        alert("Article was successfully added to your closet");
                        //var likesd = result.count + ' likes';
                        //$('#like_' + result.idf).html(likesd);
                    } else {
                        alert("Internal Server Error");
                    }
                }});
        });
        /*****************End block for adding this product into my coloseset**************/
    });
</script> -->