<div class="refine-colum desktop hidden-xs">
    <ul> 
        <li id="category">CATEGORIES</li>
        <i data-class="category" class="fa fa-angle-down" aria-hidden="true"></i>
        <div class="category stage0" style="display: none; left: 100px;">
            <ul> 
            <?php foreach ($this->aJson as $aJson) { ?>
                <li <?php if(!isset($aJson['branch'])){echo 'data-catids="'.$aJson['id'].'"';} ?> class="stage1 <?php if(isset($aJson['branch'])){echo 'has-child';}else{echo 'item';} ?>" id="<?php  echo strtolower($aJson['label']); ?>"> <?php  echo $aJson['label']; ?> 
                </li>
                <?php if(isset($aJson['branch'])){ ?>
                     <i data-class="<?php $search = array(' ', '&');
                                echo strtolower (str_replace($search,'',$aJson['label'])); ?>" class="fa fa-angle-down" aria-hidden="true"></i>
               <?php } ?>

                
                    <div class="<?php  echo strtolower($aJson['label']); ?>">
                        <ul>
                            <?php 
                            if(isset($aJson['branch'])) :
                            foreach ($aJson['branch'] as $aJson1) { ?>
                                <li <?php if(!isset($aJson1['branch'])){echo 'data-catids="'.$aJson1['id'].'"';} ?> class="stage2 <?php if(isset($aJson1['branch'])){echo 'has-child';}else{echo 'item';} ?>" id="<?php $search = array(' ', '&');
                                echo strtolower (str_replace($search,'',$aJson1['label'])); ?>"><?php echo $aJson1['label']; ?>
                                </li>
                                <?php if(isset($aJson1['branch'])){ ?>
                                    <i data-class="<?php $search = array(' ', '&');
                                echo strtolower (str_replace($search,'',$aJson1['label'])); ?>" class="fa fa-angle-down" aria-hidden="true"></i>
                                <?php } ?>
                                
                                <div style="display: none; left: 100px;" class="<?php  echo strtolower (str_replace($search,'',$aJson1['label'])); ?>">
                                    <ul>
                                    <?php if(isset($aJson1['branch'])) :
                                    foreach ($aJson1['branch'] as $aJson2) { ?>
                                    
                                            <li <?php if(!isset($aJson2['branch'])){echo 'data-catids="'.$aJson2['id'].'"';} ?> class="stage3 <?php if(isset($aJson2['branch'])){echo 'has-child';}else{echo 'item';} ?>"><?php  echo ($aJson2['label']); ?>
                                            </li>
                                            <?php if(isset($aJson2['branch'])){ ?>
                                                 <i data-class="<?php $search = array(' ', '&');
                                echo strtolower (str_replace($search,'',$aJson2['label'])); ?>" class="fa fa-angle-down" aria-hidden="true"></i>
                                            <?php } ?>
                                            
                                        
                                    <?php }  endif; ?>
                                    </ul>
                                </div>
                            <?php }  endif; ?>
                        </ul>
                    </div>
            <?php } ?>
            </ul>
        </div>


        <li id="brands" >BRANDS</li>
        <i data-class="brands" class="fa fa-angle-down" aria-hidden="true"></i>
        <div class="brands stage0">
            <div class="brand">
                <?php if (!empty($this->allBrands) || !empty($this->allTopBrands)) { ?>
                <div class="list-brand">
                    <ul>
                    <table>
                    <tbody>

                        <?php if (!empty($this->allBrands)) { 
                                foreach ($this->allBrands as $brand) { ?>
                        <tr><td><li data-parent="brands" data-brand='<?php echo $brand[ 'id']; ?>' class='item'><?php echo $brand[ 'title']; ?></li></td></tr>
                        <?php } } ?>

                    </tbody>
                    </table>

                    </ul>
                </div>
                <?php } ?>
            </div>
        </div>

        <div id="1">
            <li id="prices">PRICE</li>
            <i data-class="prices" class="fa fa-angle-down" aria-hidden="true"></i>
            <div class="price prices stage0">
                <div class="slider-3 ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all">
                    <div class="ui-slider-range ui-widget-header ui-corner-all" style=" left: 25%;"></div><span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" style="left: 25%;"></span><span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" style="left: 100%;"></span>
                </div>
            </div>
        </div>

        <li id="colors">COLOR</li>                  
        <i data-class="colors" class="fa fa-angle-down" aria-hidden="true"></i>
        <div class="colors stage0">
            <div class="list-color">

            <?php
            if (!empty($this->allColors)) {
                foreach ($this->allColors as $color) {
                    if($color['value'] == 'WHITE') { $bdrcolor = '#CCCCCC'; } else { $bdrcolor = $color['value']; }
                    ?>
                    <div data-parent="colors" data-color="<?php echo $color['value']; ?>" class="color <?php if($color['value'] == 'BEIGE' || $color['value'] == 'WHITE' || $color['value'] == 'YELLOW' ){ echo 'special'; } ?>" style="background-color:<?php echo $color['value']; ?>;border:solid 1px <?php echo $bdrcolor; ?>;" value="<?php echo $color['value']; ?>" title="<?php echo $color['value']; ?>"></div>
                    <?php
                }
            }
            ?>

            </div>
        </div>
        <li id="deals">DEALS</li>
        <i data-class="deals" class="fa fa-angle-down" aria-hidden="true"></i>
        <div class="deals stage0">
            <ul>
                <li data-parent="deals" data-deal="onsale"  class="item">All item on sale</li>
                <li data-parent="deals" data-deal="todaynew"  class="item">New today</li>
                <li data-parent="deals" data-deal="newthisweek"  class="item">New this week</li>
                <li data-parent="deals" data-deal="freeshipping"  class="item">Free shipping</li>
                <li data-parent="deals" data-deal="specialoffer"  class="item">Special offer</li>
                <li data-parent="deals" data-deal="discountcode"  class="item">Discount</li>
            </ul>
        </div>
    </ul>
    <button class="clear-filter" type="submit" >CLEAR FILTER</button>
</div>
<!-- popup-->
<div class="refine " style="display: none;">
    <div class="refine-colum mobile" id="rfs-content-popup">
        <p class="m-title"> REFINE SEARCH</p>
        <div class="option-filter">
            <div class="option-filter-row">
                <label><span>ALL</span>
                </label>
                <input type="radio">
            </div>
            <div class="option-filter-row">
                <label><span>SALE</span>
                </label>
                <input type="radio">
            </div>

            <div class="option-filter-row">
                <label><span>SAVE ITEMS</span>
                </label>
                <input type="radio">
            </div>
        </div>
        <ul> 
        <li id="category">CATEGORIES</li>
        <i data-class="category" class="fa fa-angle-down" aria-hidden="true"></i>
        <div class="category stage0" style="display: none; left: 100px;">
            <ul>
            <?php foreach ($this->aJson as $aJson) { ?>
                <li <?php if(!isset($aJson['branch'])){echo 'data-catids="'.$aJson['id'].'"';} ?> class="stage1 <?php if(isset($aJson['branch'])){echo 'has-child';}else{echo 'item';} ?>" id="<?php  echo strtolower($aJson['label']); ?>"> <?php  echo $aJson['label']; ?> 
                </li>
                <?php if(isset($aJson['branch'])){ ?>
                     <i data-class="<?php $search = array(' ', '&');
                                echo strtolower (str_replace($search,'',$aJson['label'])); ?>" class="fa fa-angle-down" aria-hidden="true"></i>
               <?php } ?>
                    <div class="<?php  echo strtolower($aJson['label']); ?>">
                        <ul>
                            <?php 
                            if(isset($aJson['branch'])) :
                            foreach ($aJson['branch'] as $aJson1) { ?>
                                <li <?php if(!isset($aJson1['branch'])){echo 'data-catids="'.$aJson1['id'].'"';} ?> class="stage2 <?php if(isset($aJson1['branch'])){echo 'has-child';}else{echo 'item';} ?>" id="<?php $search = array(' ', '&');
                                echo strtolower (str_replace($search,'',$aJson1['label'])); ?>"><?php echo $aJson1['label']; ?>
                                </li>
                                <?php if(isset($aJson1['branch'])){ ?>
                                    <i data-class="<?php $search = array(' ', '&');
                                echo strtolower (str_replace($search,'',$aJson1['label'])); ?>" class="fa fa-angle-down" aria-hidden="true"></i>
                                <?php } ?>
                                
                                <div style="display: none; left: 100px;" class="<?php  echo strtolower (str_replace($search,'',$aJson1['label'])); ?>">
                                    <ul>
                                    <?php if(isset($aJson1['branch'])) :
                                    foreach ($aJson1['branch'] as $aJson2) { ?>
                                    
                                            <li <?php if(!isset($aJson2['branch'])){echo 'data-catids="'.$aJson2['id'].'"';} ?> class="stage3 <?php if(isset($aJson2['branch'])){echo 'has-child';}else{echo 'item';} ?>"><?php  echo ($aJson2['label']); ?>
                                            </li>
                                            <?php if(isset($aJson2['branch'])){ ?>
                                                 <i data-class="<?php $search = array(' ', '&');
                                echo strtolower (str_replace($search,'',$aJson2['label'])); ?>" class="fa fa-angle-down" aria-hidden="true"></i>
                                            <?php } ?>
                                    <?php }  endif; ?>
                                    </ul>
                                </div>
                            <?php }  endif; ?>
                        </ul>
                    </div>
            <?php } ?>
            </ul>
        </div>
        <li id="brands" >BRANDS</li>
        <i data-class="brands" class="fa fa-angle-down" aria-hidden="true"></i>
        <div class="brands stage0">
            <div class="brand">
                <?php if (!empty($this->allBrands) || !empty($this->allTopBrands)) { ?>
                <div class="list-brand">
                    <ul>
                    <table>
                    <tbody>

                        <?php if (!empty($this->allBrands)) { 
                                foreach ($this->allBrands as $brand) { ?>
                        <tr><td><li data-brand='<?php echo $brand[ 'id']; ?>' class='item'><?php echo $brand[ 'title']; ?></li></td></tr>
                        <?php } } ?>

                    </tbody>
                    </table>

                    </ul>
                </div>
                <?php } ?>
            </div>
        </div>

        <div id="2">
            <li id="prices">PRICE</li>
            <i data-class="prices" class="fa fa-angle-down" aria-hidden="true"></i>
            <div class="price prices stage0">
                <div class="slider-3 ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all">
                    <div class="ui-slider-range ui-widget-header ui-corner-all" style=" left: 25%;"></div><span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" style="left: 25%;"></span><span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" style="left: 100%;"></span>
                </div>
            </div>
        </div>

        <li id="colors">COLOR</li>                  
        <i data-class="colors" class="fa fa-angle-down" aria-hidden="true"></i>
        <div class="colors stage0">
            <div class="list-color">

            <?php
            if (!empty($this->allColors)) {
                foreach ($this->allColors as $color) {
                    if($color['value'] == 'WHITE') { $bdrcolor = '#CCCCCC'; } else { $bdrcolor = $color['value']; }
                    ?>
                    <div data-color="<?php echo $color['value']; ?>" class="color <?php if($color['value'] == 'BEIGE' || $color['value'] == 'WHITE' || $color['value'] == 'YELLOW' ){ echo 'special'; } ?>" style="background-color:<?php echo $color['value']; ?>;border:solid 1px <?php echo $bdrcolor; ?>;" value="<?php echo $color['value']; ?>" title="<?php echo $color['value']; ?>"></div>
                    <?php
                }
            }
            ?>

            </div>
        </div>
        <li id="deals">DEALS</li>
        <i data-class="deals" class="fa fa-angle-down" aria-hidden="true"></i>
        <div class="deals stage0">
            <ul>
                <li data-deal="onsale" class="item">All item on sale</li>
                <li data-deal="todaynew" class="item">New today</li>
                <li data-deal="newthisweek" class="item">New this week</li>
                <li data-deal="freeshipping" class="item">Free shipping</li>
                <li data-deal="specialoffer" class="item">Special offer</li>
                <li data-deal="discountcode" class="item">Discount</li>
            </ul>
        </div>
    </ul>
            <div class="m-button-foot col-xs-12">
                <div class="col-xs-6 btn-refine">
                    <button type="submit" class="clear-filter" form="form1" value="Submit" name="clear-filter">CLEAR FILTER</button>
                </div>
                <div class="col-xs-6 btn-refine">
                    <button type="submit" id="apply-submit" form="form1" value="Submit" name="apply">APPLY</button>
                </div>
            </div>
        </ul> 
    </div>
</div>