<?php
$outfitsData = $this->outfits;
?>
<link type="text/css"  href="<?php echo $this->basePath(); ?>/css/onlymodal.css"   rel="stylesheet" />
<link type="text/css"  href="<?php echo $this->basePath(); ?>/css/showfeeddetail.css"   rel="stylesheet" />
<script src="<?php echo $this->basePath(); ?>/vendor/bootstrap/bootstrap-select/bootstrap-select.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/vendor/jqueryui/development-bundle/themes/base/jquery.ui.all.css">

<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/fa/css/build.css">
<!--<link rel="stylesheet" href="/vendor/jqueryui/custom.css">-->
<script src="<?php echo $this->basePath(); ?>/vendor/jqueryui/development-bundle/ui/jquery.ui.slider.js"></script>

<script src="<?php echo $this->basePath(); ?>/simpleexpand/simple-expand.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/templates/mobile/js/bootstrap.min.js"></script>

<style> 
    .productsBox .overlay{margin-left:70px; top:90px; }
    .productsBox .overlay .plus{background-image:none}
    .productsBox .overlay .minus{background-image:none}

    ul.scrollheight { height: 300px;overflow-y: auto;}
    .activebrand{background-color: #CCCCCC;}
    .activecolor{border:2px solid black; background-image: url("/img/tick2.png"); background-size: 20px 15px; 
    background-repeat: no-repeat; 
    background-position: center center;} 
    .activedeal {background:#e06;text-decoration:none;}

    .form-control{height: 34px; padding:2px 2px 2px 6px; font-style:italic; font-size: 11px;}

    section.toggle {margin-top:0px}
    section.toggle input {
        height: auto;
        margin: 0;
        opacity: 1;
        position: static;
        width: auto;
    }
    section.toggle label { border:none; color: #000; padding: 3px 20px 3px 10px }
    section.toggle.active {
        /*background-color: #fbfcfb;*/
        border-color: #fbfcfb;
    }
    section.toggle.active > label {
        background: none repeat scroll 0 0 #F4F4F4;
        border-color: #CCCCCC;
    }
    section.toggle .toggle-content{
        white-space:nowrap;
    }

    section.toggle .toggle-content .aciTree label{
        border: none;
        background: none;
        border-style: none;
        border-left-style: none;
        border-right-style: none;
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 100%;
        font: inherit;
        vertical-align: baseline;
    }
    section.toggle .toggle-content .aciTree label:before{
        border: none;
        background: none;
        border-style: none;
        border-left-style: none;
        border-right-style: none;
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 100%;
        font: inherit;
        vertical-align: baseline;
    }
</style>
<style>
    .price-box {
        background: none repeat scroll 0 0 #E9E9E9;
        margin: 20px auto 0 7px;
        width: 200px;
    }
    .form-pricing {
        background: none repeat scroll 0 0 #FFFFFF;
        border-radius: 4px 4px 4px 4px;
        padding: 5px;
    }
    .price-slider {
        margin-bottom: 30px;
    }
    .col-sm-padding {
        padding: 0;
    }

    .ui-corner-all {
        border-radius: 4px 4px 4px 4px;
    }
    .ui-widget-content {
        background: none repeat scroll 0 0 #DCF0F0;
        border: 1px solid #AAAAAA;
        color: #222222;
        height: 8px;
        margin-top: 0;
    }
    .ui-slider .ui-slider-handle {
        cursor: pointer;
    }
    .ui-slider-horizontal .ui-slider-handle {
        margin-left: -0.5em;
    }
    .ui-slider-horizontal .ui-slider-handle {
        top: -0.9em;
    }
    .ui-slider .ui-slider-handle {
        color: #FFFFFF;
        cursor: default;
        font-size: 15px;
        height: 2em;
        line-height: 30px;
        margin: 0 -30px auto !important;
        position: absolute;
        text-align: center;
        text-decoration: none;
        width: 3.4em;
        z-index: 2;
    }
    .ui-slider a, .ui-slider a:focus {
        cursor: pointer;
        outline: medium none;
    }
    .ui-state-default, .ui-widget-content .ui-state-default {
        /*background: none repeat scroll 0 0 #254F73 !important;*/
        /*border: 1px solid #254F73 !important;*/
        box-shadow: none;
        height: 13px;
        margin: 10px -5px auto !important;
        width: 13px;
    }
    .ui-corner-all {
        border-radius: 4px 4px 4px 4px;
    }
    .ui-state-default, .ui-widget-content .ui-state-default label {
        color: #FFFFFF !important;
    }
    .ui-slider-handle.ui-state-default.ui-corner-all > label {
        color: #5E5E5E !important;
        left: -28px;
        position: absolute;
        top: -24px;
    }
    #slider > a:nth-child(even) > label:first-child {
        left: -10px;
        width: 35px;
    }
    #slider2 > a > label:first-child {
        left: -22px;
        width: 40px;
    }
    label {
        margin-bottom: 7px;
    }
    .price-slider span {
        color: #7F8C8D;
        display: inline-block;
        font-size: 13px;
        font-weight: 200;
    }
    .price-min-max {
        background-image: url("/img/step_bars.jpg");
        height: 8px;
        margin-top: -24px;
        position: relative;
        display: none;
    }
    .col-sm-padding {
        padding: 0;
    }
    .ui-autocomplete { height: auto !important; }
    .ui-menu .ui-menu-item a{ font-size: 13px !important; }
    .sharepoup{
        top: -110px;
        cursor: pointer;
    }
    .outfitcheckbox{
        cursor: pointer;
    }
    
    
    
    
    #loading-div-background 
    {
        display:none;
        position:fixed;
        top:0;
        left:0;
        background:black;
        width:100%;
        height:100%;
        opacity: 0.6;
        z-index: 1000;
     }
    #loading-div
    {
         width: 300px;
         height: 150px;
         text-align:center;
         position:absolute; 
         left: 50%;
         top: 50%;
         margin-left:-150px;
         margin-top: -100px;
        opacity: 1;
     }
     
        .toggle.expander.expanded {
            padding-left: 22px;
            background-position: left center;
            background-repeat: no-repeat;
            background-image: url('/img/down.png');
        }
    
        .toggle.expander.collapsed {
            padding-left: 22px;
            background-position: left center;
            background-repeat: no-repeat;
            background-image: url('/img/right.png');
        } 
        .cat h5{
            cursor: pointer;
        }
        button.deal{
            -webkit-box-shadow: none;
            -moz-box-shadow: none;
            box-shadow: none;
        }
        #tree .aciTreeText{
            font-family: 'Roboto' !important;
        }

        /* style for checkbox */

        .brandslist .checkbox label::before{
            border-radius: 0;
            border-color: #acaeb5;
        }
        .brandslist .checkbox label::after{
            background-color: #acaeb5;
        }
        .brandslist .checkbox input[type="checkbox"]:checked + label::after{
            content: ' ';
        }
        .brandslist .checkbox label::before{
            width: 14px;
            height: 14px;
        }
        .brandslist .checkbox label::after {
            width: 12px;
            height: 14px;
        }
        #slider > a > label {
            width:50px;
        }
        .round-color li{
            font-size: 13px;
            font-family: 'Roboto';
        }
        .round-color .fa-check{
            color:#fff;
        }
        .round-color .fa-check:before {
            margin-left: 3px;
        }
        .deals_box label{
            margin-bottom: 0;
        }
        .deals_box .fa-circle-o:before {
            font-size: 17px;
        }
        .left-box-check input[type="radio"]:checked + label .fa-circle,input[type="checkbox"]:checked + label .fa-square {
            color: #fff;
        }
        .continueFixAtBottom{
            padding-top: 35px;
        }
        .image-cross{
            padding: 0;
        }
        .btn-con1{
            margin-top: 0;
        }
       
</style>
<!--============================================================contener-01=============-->
<script type="text/javascript">var feedsids = {};</script>
<!--============================================================contener-01 end =============-->
<?php if(isset($this->shareOutfitImage)) { ?>
    <div align="center">
        <img src="<?php echo $this->shareOutfitImage?>"  /> <br /><br />
         To see details of this outfit, please login to <a href="/auth">ELNOVE</a>.
    </div>
   
<?php } ?>
<div id="service-page" class="full" <?php echo (isset($this->fromSocialMedia)?'style="display:none"':'');?>>
    <div class="container outerBoxContainer" style="background-color:#F6F6F4;">
        <div id="blue-btn-top" <?php echo (isset($this->fromSocialMedia)?'style="display:none"':'');?>>
            <!-- <div id="div">
                <div class="blue-btn1 my_tooltip" title="Switch between outfits and articles">
                    <a href="#" class="square1_tick"><img src="/img/circle-ok.png" id="panel"></a>
                    <div class="square1 on" style="font-size:0px;">on</div>
                </div>
             
                <div class="clr"></div>
                <p class="head1">Outfit View </p>
            </div> -->
            <div class="switch" style="display:none">
                <ul class="list-radio">
                    <li>
                        <div class="radio">
                            <input type="radio" name="outart" id="outfit" value="outfit" checked="">
                            <label for="outfit" class="radio-label upcase">
                                outfits
                            </label>
                        </div>
                    </li>
                    <li>
                        <div class="radio">
                            <input type="radio" name="outart" id="articles" value="articles">
                            <label for="articles" class="radio-label upcase">
                                articles
                            </label>
                        </div>
                    </li> 
                </ul>
            </div>

            <div id="leftaction" style="display:none">

                <ul class="left-box-check my_tooltip" title="Which venue are you dressing for?">
                    <li><input type="checkbox" name="all" id="check1" value="All"/>
                        <label for="check1">
                            <span class="fa-stack outfitcheckbox">
                                <i class="fa fa-square-o fa-stack-1x"></i>
                                <i class="fa fa-square fa-stack-1x"></i>
                            </span>
                            All
                        </label></li>

                    <li><input type="checkbox" name="outfit[]" id="check2" <?php echo (in_array('Work', $this->defaultVenue)?'checked':'')?> value="Work"/>
                        <label for="check2">
                            <span class="fa-stack outfitcheckbox">
                                <i class="fa fa-square-o fa-stack-1x"></i>
                                <i class="fa fa-square fa-stack-1x"></i>
                            </span>
                            Work
                        </label></li>
                    <li><input type="checkbox" name="outfit[]" id="check3" <?php echo (in_array('NightOut', $this->defaultVenue)?'checked':'')?> value="Night Out"/>
                        <label for="check3">
                            <span class="fa-stack outfitcheckbox">
                                <i class="fa fa-square-o fa-stack-1x"></i>
                                <i class="fa fa-square fa-stack-1x"></i>
                            </span>
                            Night Out
                        </label></li>

                    <li><input type="checkbox" name="outfit[]" id="check4" <?php echo (in_array('Casual', $this->defaultVenue)?'checked':'')?> value="Casual"/>
                        <label for="check4">
                            <span class="fa-stack outfitcheckbox">
                                <i class="fa fa-square-o fa-stack-1x"></i>
                                <i class="fa fa-square fa-stack-1x"></i>
                            </span>
                            Casual
                        </label></li>
                </ul>


            </div>
        </div>
        <div id="outfit-block" style="display:none">
        
            <input type="hidden" id="outfits_offset" value="0"  />
            <input type="hidden" id="outfits_count" value="<?=$this->outfits_count?>"  />
        
        
            <div id="slideout" style="right:-65px;">
                <a class="link-settings-colors sharepoup"><img src="/img/switch.png" /></a>
                <div id="slideout_inner">
                    <form id="switchform">
                        <ul>
                            <?php
                            $page_url = $this->serverUrl() . '/service?outfit=' . $outfitsData[1][0]['outfit_id'];
                            $title = 'ELNove - ' . $outfitsData[1][0]['outfittitle'];
                            ?>
                            <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/white_fb.png"></a></li>
                            <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/pinterest/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/white_p.png"></a></li>
                            <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/white-t.png"></a></li>
                            <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/google_plusone_share/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/white_google.png"></a></li>
                            <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/email/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/white_msg.png"></a></li>
                        </ul>

                    </form>
                </div>
            </div>
            <?php if (isset($outfitsData) && !empty($outfitsData)) { ?>
                <div class="big_box1_outer">
                    <div class="prevOutfit">
                        <?php echo $this->partial('service_outfits', array('data'=>$outfitsData[0], 'likesArray'=>$likearray, 'float'=>'right', 'id'=>'left'));?>
                        <div class="overlay"><img src="/img/grey_arrow_left.png"  class="my_tooltip" title="Previous outfit" /></div>
                    </div>
                    <?php echo $this->partial('service_outfits', array('data'=>$outfitsData[1], 'likesArray'=>$likearray, 'id'=>''));?>
                    <div class="nextOutfit">
                        <?php echo $this->partial('service_outfits', array('data'=>$outfitsData[2], 'likesArray'=>$likearray, 'float'=>'left', 'id'=>'right'));?>
                        <div class="overlay"><img src="/img/grey_arrow_right.png" class="my_tooltip" title="Next outfit" /></div> 
                    </div>
                </div>
                
                <div class="clr"></div>
                
                <div align="right"><a class="iFeelLucky my_tooltip" href="#" title="Show new outfit"><span>I FEEL LUCKY</span></a> </div> 
                                
                <div class="outfit_desc_block">
                    <div class="profileImg" style="background-image:url(/img/profilepic/<?=$this->outfitsData[1]['user_prp_pic']?>);"></div>
                    <div class="profileCreator">
                        <div class="createdBy">CREATED BY</div> 
                        <?=$this->outfitsData[1]['firstName']?> <?=$this->outfitsData[1]['lastName']?>
                    </div>
                    <div class="outFitDesc"> 
                        <div class="createdBy">VENUE: <?=str_replace('|', ', ', $this->outfitsData[1]['venue'])?></div> 
                        <div class="outfitDescription"><?=$this->outfitsData[1]['description']?></div> 
                    </div>  
                     <div class="outFitSharing"> 
                        <div class="refresh savecloseout my_tooltip" title="Save outfit to your closet">
                            <a href="javascript:void(0);"><div class="saveoutfit"></div> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Save this Outfit </a>
                        </div>
        
                        <div id="idSharethisOutfit" class="share1 shclose">
                            <a href="javascript:void(0);"><div class="shareoutfit"></div> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Share this outfit </a>

                              <div class='arrow_box' id="shareThisOutfitPopup" style="display:none">
                                <a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/white_fb.png"></a>
                                <a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/pinterest/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/white_p.png"></a>
                                <a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/white-t.png"></a>
                                <a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/google_plusone_share/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/white_google.png"></a>
                                <a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/email/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" ><img src="/img/white_msg.png"></a>
                              </div>                            
                            
                            </div>     
                        
                        <div class="outfitlikes">
                            <img alt="" src="<?=($this->outfitsData[1]['outfitLikesCount']>0?'/img/thumb.png':'/img/blank-2.png')?>"> <span><?=$this->outfitsData[1]['outfitLikesCount']?><span>
                        </div>
                                        
                    </div>  
                </div>
                
                
                
            <?php } else { ?>
                <div class="outfitsnot" style="font-size: 20px; line-height: 40px; text-align: center; margin: 25px; ">
                    Outfits not available.
                </div>
            <?php } ?>
        </div>

        <div id="article-block" style="display: block;">
        
            <? if(!isset($this->shareOutfitImage)) {?> 
        
            <div class="left-link-box" id="leftLinkBoxID">

                <div class="refined">
                    <h1>REFINED BY</h1>
                    <div class="cat page_left_menu ">
                        <section class="toggle active">
                            <h5 class="expander toggle collapsed"> categories</h5>
                            <div class="content">
                                <div id="catBtnDiv" class="toggle-content">
                                    <div id="tree" class="aciTree"></div>
                                </div>
                            </div>
                        </section>
                    </div>

                                <?php if (!empty($this->allBrands) || !empty($this->allTopBrands)) { ?>

                                    <div class="cat page_left_menu brandslist">
                                        <h5 class="expander toggle collapsed"> BRANDS</h5>
                                        <div class="content">
                                            <input type="text" class="form-control form-control-01 brand" name="brandautocomplete" id="brandautocomplete" placeholder="Search more brands">
                                        <ul>
                                            <?php if (!empty($this->allTopBrands)) { ?>
                                                <?php foreach ($this->allTopBrands as $brand) { ?>
                                                    <li>

                                                  <!--   <input type="checkbox" name="option" id="<?php echo $brand['id']; ?>" class="brandSelection" value="<?php echo $brand['id']; ?>" />
                                                        <label for="<?php echo $brand['id']; ?>">
                                                            <span class="fa-stack">
                                                                <i class="fa fa-square-o fa-stack-1x"></i>
                                                                <i class="fa fa-square fa-stack-1x"></i>
                                                            </span>
                                                            <?php echo $brand['title']; ?>
                                                        </label> -->
                                                    </li>
                                                <?php } ?>
                                            <?php } ?>

                                            <?php if (!empty($this->allBrands)) { ?>
                                                <?php 
                                                $i = 1;
                                                foreach ($this->allBrands as $brand) { ?>
                                                    <li>
                                                    <div class="checkbox">
                                                    <input id="<?php echo $brand['id']; ?>" class="brandSelection styled" type="checkbox" name="option" value="<?php echo $brand['id']; ?>">
                                                    <label for="<?php echo $brand['id']; ?>">
                                                        <?php  echo $brand['title']; ?>
                                                    </label>
                                                </div>
                                     
                                                    <!-- <input type="checkbox" name="option" id="<?php echo $brand['id']; ?>" class="brandSelection" value="<?php echo $brand['id']; ?>" />
                                                        <label for="<?php echo $brand['id']; ?>">
                                                            <span class="fa-stack">
                                                                <i class="fa fa-square-o fa-stack-1x"></i>
                                                                <i class="fa fa-square fa-stack-1x"></i>
                                                            </span>
                                                            <?php echo $brand['title']; ?>
                                                        </label> -->
                                                    </li>
                                                <?php $i++; } ?>
                                            <?php } ?>
                                        </ul>
                                        </div>
                                        
                                    </div>

                                <?php } ?>

                                <div class="cat page_left_menu ">
                                    <h5 class="expander toggle collapsed">PRICE</h5>
                                    <div class="content">
                                        <div id="priceboxglobalOverlay" style="width:95%; height: 48px; margin-top:-10px; z-index: 1000; display:block; position:absolute; background-image:url(/img/spacer.gif)"></div> 
                                        <div class="price-box" id="priceboxglobal" style="display:block; opacity: 0.2">
                                            <form class="form-horizontal form-pricing" role="form">
                                                
                                                <div class="price-slider">
                                                    <div class="col-sm-12 col-sm-padding">
                                                        <div id="slider" class="slider-01"></div>
                                                    </div>
                                                </div>
                                                <div class="price-min-max">
                                                    <div class="col-lg-6 col-sm-padding" style="text-align:left; margin-top:5px;color:#aaaaaa;">
                                                        <span>0</span>
                                                    </div>
                                                    <div class="col-lg-6 col-sm-padding" style="text-align:right;margin-top:5px;color:#aaaaaa;">
                                                        <span><?php echo $this->maxRangePrice; ?></span>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        
                                        
                                    
                                          <div class="remember" style="margin-bottom:15px">
                                                <input type="checkbox"  id="profilePrices" class="profilePrices" checked="checked" >
                                                <label for="profilePrices">
                                                    <span class="fa-stack"> 
                                                        <i class="fa fa-square-o fa-stack-1x"></i>
                                                        <i class="fa fa-check-square fa-stack-1x"></i>
                                                    </span>
                                                    <span class="rememberLabel">Show MY PRICES only</span>
                                                </label>                
                                          </div>
                                          
                                          <div style="clear:both; padding-bottom:15px"></div>     
                                                                                
                                    </div>
                                   
                                </div>

                                <?php if (!empty($this->allColors)) { ?>

                                    <div class="cat page_left_menu ">
                                        <h5 class="expander toggle collapsed">COLOR</h5>
                                        <div class="content">
                                            <ul class="round-color">
                                            <?php
                                            if (!empty($this->allColors)) {
                                                foreach ($this->allColors as $color) {
                                                    if($color['value'] == 'WHITE') { $bdrcolor = '#CCCCCC'; } else { $bdrcolor = $color['value']; }
                                                    ?>
                                                    <li class="fa btn-01 btn-coloer-01 colorselection" style="background-color:<?php echo $color['value']; ?>;border:solid 1px <?php echo $bdrcolor; ?>;" value="<?php echo $color['value']; ?>" title="<?php echo $color['value']; ?>"></li>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </ul>
                                        </div>
                                        
                                    </div>

                                <?php } ?>
                                
                            
                                <?php if (!empty($this->allStores) || !empty($this->allTopStores)) { ?>

                                    <div class="cat page_left_menu ">
                                        <h5 class="expander toggle collapsed">STORE</h5>
                                        <div class="content">
                                        <input type="text" class="form-control form-control-01 brand" id="storeautocomplete" name="storeautocomplete" placeholder="Search more stores">
                                        <ul>

                                            <?php if (!empty($this->allTopStores)) { ?>
                                                <?php foreach ($this->allTopStores as $store) { ?>
                                                    <li><input class="storeSelection" type="checkbox" name="option" id="<?php echo $store['title']; ?>"  value="<?php echo $store['id']; ?>" />
                                                        <label for="<?php echo $store['title']; ?>">
                                                            <span class="fa-stack">
                                                                <i class="fa fa-square-o fa-stack-1x"></i>
                                                                <i class="fa fa-square fa-stack-1x"></i>
                                                            </span>
                                                            <?php echo $store['title']; ?>
                                                        </label>
                                                    </li>
                                                <?php } ?>
                                            <?php } ?>

                                            <?php if (!empty($this->allStores)) { ?>
                                                <?php foreach ($this->allStores as $store) { ?>
                                                    <li><input class="storeSelection" type="checkbox" name="option" id="<?php echo $store['title']; ?>"  value="<?php echo $store['id']; ?>" />
                                                        <label for="<?php echo $store['title']; ?>">
                                                            <span class="fa-stack">
                                                                <i class="fa fa-square-o fa-stack-1x"></i>
                                                                <i class="fa fa-square fa-stack-1x"></i>
                                                            </span>
                                                            <?php echo $store['title']; ?>
                                                        </label>
                                                    </li>
                                                <?php } ?>
                                            <?php } ?>

                                        </ul>
                                        </div>
                                    </div>
                                <?php } ?>
                              


                                <div class="cat page_left_menu deals_box">
                                    <h5 class="expander toggle collapsed">DEALS</h5>
                                    <div class="content">
                                        <ul>
                                        <li><input type="radio" name="option" id="deal1" onclick="chooseDeals(this, 'onsale');" />
                                            <label for="deal1"  class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> All Items on Sale
                                            </label>
                                        </li>
                                        <li><input type="radio" name="option" id="deal2" onclick="chooseDeals(this, 'todaynew');" />
                                            <label for="deal2"  class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> New Today
                                            </label>
                                        </li>
                                        <li><input type="radio" name="option" id="deal3" onclick="chooseDeals(this, 'newthisweek');" />
                                            <label for="deal3"  class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> New this week
                                            </label>
                                        </li>
                                        <li><input type="radio" name="option" id="deal4" onclick="chooseDeals(this, 'freeshipping');" />
                                            <label for="deal4" class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> Free Shipping
                                            </label>
                                        </li>
                                        <li><input type="radio" name="option" id="deal5" onclick="chooseDeals(this, 'specialoffer');" />
                                            <label for="deal5"  class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> Special Offer
                                            </label>
                                        </li>
                                        <li><input type="radio" name="option" id="deal6" onclick="chooseDeals(this, 'discountcode');" />
                                            <label for="deal6"  class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> Discount
                                            </label>
                                        </li>
                                    </ul>
                                    
                          

                                    <div class="cat page_left_menu ">
                                        <div class="price-box">
                                            <form class="form-horizontal form-pricing" role="form">
                                                <div class="price-slider">
                                                    <div class="col-sm-12 col-sm-padding">
                                                        <div id="slider2" class="slider-02"></div>
                                                    </div>
                                                </div>
                                                <div class="price-min-max">
                                                    <div class="col-lg-6 col-sm-padding" style="text-align:left;margin-top:5px; color:#aaaaaa;">
                                                        <span>0%</span>
                                                    </div>
                                                    <div class="col-lg-6 col-sm-padding" style="text-align:right;margin-top:5px; color:#aaaaaa;">
                                                        <span>100%</span>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>

                                    
                                    </div>
                                    
                                    
                                    <div class="clr"></div>
                                    <button class="deal">CLEAR FILTER</button>
                                  <!--   <div class="clr"></div>
                                    <a href="/service?dv=article" class="clear">Clear filter</a> -->
                                </div>

                                <div class="clr"></div>
                            </div>
                    </div><!-- left_link_box-->



                    <div class="right-link-box">

                        <div class="clr"></div>

                        <div class="image-box bottomWorkingArea" id="productlisting">

                            <?php
                            foreach ($this->feedData as $prod) {

                                $page_url = $this->serverUrl() . '/service/feeddatadetail/' . $prod->feeddataid . '/' . rand();
                                $title = 'ELNove - ' . $prod->caption;
                                ?>
                                <div class="main_big1_product_box productsBox draggable-element" data-pid="<?=$prod->feeddataid?>">
                                    <!--<div class="portfolio-item img-thumbnail productsBox">-->

                                    <div class="main_big1_product_img_box">
                                        <img onerror="imageError(this)" src="<?php echo ($prod->feedId==4?str_replace(array('/product/thumbnails/', 't.jpg'), array('/product/images/', '.jpg'), $prod->feedimageurl):$prod->feedimageurl) ?>" id="img">
                                    </div>
                                    <?php if($prod->onsale == 'Y') {?><div class="salePrice"><?php echo round(($prod->price-$prod->saleprice)/$prod->price*100)?>%<br/>OFF</div><?php }?>
                                    <div class="main_big1_product_tag_box">
                                        <a href="javascript:void(0);" class="fr likes" id="<?php echo  base64_encode($prod->feeddataid); ?>">
                                            <?php if(in_array($prod->feeddataid,$likearray)) { ?>
                                                <img data-status="<?php echo $prod->feeddataid?>" src="/img/thumb.png" alt="Like" id="like<?php echo $prod->feeddataid;?>" />
                                            <?php } else { ?>
                                                <img data-status="<?php echo $prod->feeddataid?>" class ="my_tooltip" title="Save article to your closet" src="/img/blank_like.png" alt="Like" id="like<?php echo $prod->feeddataid;?>" />
                                            <?php } ?>
                                        </a>
                                    </div>
                                    <div class="box-block">
                                        <div class="pad">
                                            <span class="like_<?php echo  $prod->feeddataid; ?>"><?php echo  $prod->likesCount != 0 ? $prod->likesCount . ' likes' : "&nbsp;"; ?></span>
                                            <h4><?php echo $this->string_helper($prod->caption); ?></h4>
                                            <p><?php echo ($prod->onsale=='Y'?$prod->saleprice:$prod->price)?><span class="currency"><?php echo $prod->currency ?></span></p>
                                            <a class="buy_now gotourl my_tooltip" href="<?php echo $this->url('service/articlebought', array('feeddataid' => base64_encode($prod->feeddataid))); ?>"  title="Purchase article through our partner">buy now</a>
                                            <br/>
                                           

                                            <a data-value="<?php echo $prod->feeddataid; ?>" href="javascript:void(0)" class="discover my_tooltip" title="Learn more about this article">DISCOVER <img src="/img/right1.png" id="im"></a>
                                        </div>
                                        <div class="social_box">
                                            <ul>
                                                <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" class="gotourl"><img src="/img/f.png"></a></li>
                                                <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/pinterest/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" class="gotourl"><img src="/img/p1.png"></a></li>
                                                <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" class="gotourl"><img src="/img/t.png"></a></li>
                                                <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/google_plusone_share/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" class="gotourl"><img src="/img/g.png"></a></li>
                                                <li><a class="sharethis" href="https://api.addthis.com/oexchange/0.8/forward/email/offer?url=<?php echo $page_url; ?>&title=<?php echo $title; ?>" target="_blank" class="gotourl"><img src="/img/msg.png"></a></li>
                                            </ul>
                                        </div>
                                    </div>

                                    <!--</div>-->
                                </div>  
                            <?php } ?>

                        </div>

                        <div id='loading' style="text-align:center;padding-top:50px;padding-bottom:50px;display:none;" class="col-md-10">
                            <!-- <img src="<?php echo $this->basePath('img/bx_loader.gif') ?>"/> -->
                        </div>
                        <div id='ajx_loader_div' style="display:none;z-index:999999;">
                            <img src="<?php echo $this->basePath('img/bx_loader.gif') ?>" id="ajx_loader_image" />
                        </div>

                        <div class="clr"></div>
                    </div>
                    <? }?>
                    
                </div>
                <div class="clr"></div>
            </div><!--container-->
        </div>

        <br /><br /><br /><br />

        <script src="<?php echo $this->basePath('vendor/jqModal/jqModal.js') ?>"></script>

        <form id="productFilterDetail" name="productFilterDetail">
            <input type="hidden" id="minamount" class="form-control" name="minamount">
            <input type="hidden" id="maxamount" class="form-control" name="maxamount">
            <input type="hidden" id="minduration" class="form-control" name="minduration">
            <input type="hidden" id="maxduration" class="form-control" name="maxduration">
            <input type="hidden" id="catids" class="form-control" name="catids">
            <input type="hidden" id="brands" class="form-control" name="brands">
            <input type="hidden" id="colors" class="form-control" name="colors">
            <input type="hidden" id="stores" class="form-control" name="stores">
            <input type="hidden" id="deals" class="form-control" name="deals">
            <input type="hidden" id="onsale" class="form-control" name="onsale">
            <input type="hidden" id="todaynew" class="form-control" name="todaynew">
            <input type="hidden" id="newthisweek" class="form-control" name="newthisweek">
            <input type="hidden" id="freeshipping" class="form-control" name="freeshipping">
            <input type="hidden" id="specialoffer" class="form-control" name="specialoffer">
            <input type="hidden" id="discountcode" class="form-control" name="discountcode">
            <input type="hidden" id="page" class="form-control" name="page" value="2">
            <input type="hidden" id="limit" class="form-control" name="limit" value="<?php echo PRODUCTS_PER_PAGE;?>">
            <input type="hidden" id="profileBasePrices" class="form-control" name="profileBasePrices" value="1">
        </form>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display:none">
  <div class="modal-dialog" role="document">
    <div class="modal-content grey_bg">
      <div class="modal-body append">
        
      </div>
  
    </div>
  </div>
</div>

<div id="loading-div-background" style="display: none;">
    <div id="loading-div" class="ui-corner-all">
      <img style="margin-top:20px; height: 50px" src="/img/loading7_light_blue.gif" alt="Loading..">
      <h2 style="color:gray;font-weight:normal;">Please wait....</h2>
     </div>
</div>

        <!--=================script-by-designer=============-->
        <script src="<?php echo $this->basePath(); ?>/js/showfeeddetail.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/clearfilter.js"></script>
        
        <script type="text/javascript">
        //$(document).foundation();
     
            $(document).ready(function () {
             <?php 
                $session = new \Zend\Session\Container('alert');
                if(isset($session->alert) && $session->alert ==true ) 
                {
              ?>
               // start show alert overlay
                myalert('type_thankyou_id1','type_thankyou','Thank You!','','Agree','You have just begun your journey to dressing to the nines.',
                        function(){
                            if( $('#type_thankyou_id1 .receive_alert_bx').prop("checked")){
                                $.ajax({
                                    url: "/index/newsletter",
                                    type: 'POST',
                                    data: {newsLetterInput: '<?php echo $this->userEmail?>', from: 'ServicePage'},
                                    dataType: 'json',
                                    success: function (result) {
                                        console.log(result); 
                                        console.log(result.status); 
                                    }});        
                              }            
                              $('#type_thankyou_id1').foundation('reveal','close'); 
                        }
                ); 

                setTimeout(function(){
                  $("#type_thankyou_id1").foundation('reveal', 'close');
                }, 100000);

                /*end show alert overlay*/
                
              <?php unset($session->alert); } ?>
               
                /*expand filter*/
                 $('.expander').simpleexpand();

              



            
                $(document).on('click', '.overlay-01', function () {
                    reditectToBuyurl(this);
                });
                $('.overlay-01').click(function () {
                    reditectToBuyurl(this);
                });
                function reditectToBuyurl(obj) {
                    $("#contener-01").css("display", "block");
                    $('.progress-bar').progressbar();
                    $('#productbuyurl').attr('href', $(obj).attr('href'));
                    setTimeout(function () {
                        jQuery('#productbuyurl')[0].click();
                        $("#contener-01").css("display", "none");
                    }, 3000);
                }
            });
            
            /* my close */
            // $(function () {
            //     $(".btn-01").click(function () {
            //         // remove classes from all
            //         $(".btn-01").removeClass("active");
            //         $(this).addClass("active");
            //     });
            // });

        </script>
        <script type="text/javascript">
        function imageError(obj) {
            $(obj).closest( ".productsBox" ).remove();
            //obj.src = 'http://dev.elnove.com/img/nophoto.png';
            console.log('here:'+$(obj).closest( ".productsBox" ).data('pid'));
        }        
            $(function () {
                $(".slider-01").click(function () {
                    // remove classes from all
                    $(".price-form-01").css("display", "block");
                    // add class to the one we clicked
                });
            });
        </script>
        <script type="text/javascript">
            $(function () {
                $(".price-01").click(function () {
                    // remove classes from all
                    $(".price-form-01").css("display", "none");
                    // add class to the one we clicked
                });
            });
        </script>
        <script type="text/javascript">
            $(function () {
                $(".slider-02").click(function () {
                    // remove classes from all
                    $(".price-form-02").css("display", "block");
                    // add class to the one we clicked
                });
            });
        </script>
        <script type="text/javascript">
            $(function () {
                $(".price-02").click(function () {
                    // remove classes from all
                    $(".price-form-02").css("display", "none");
                    // add class to the one we clicked
                });
            });
        </script>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#slider").slider({
                    range: true,
                    min: 0,
                    max: <?php echo $this->maxRangePrice; ?>,
                    values: [0, <?php echo $this->maxRangePrice; ?>],
                    slide: function (event, ui) {
                        update(1, ui.values); //changed
                    },
                    stop: function (event, ui) {
                        loadProductData();
                    }
                });
                $("#slider2").slider({
                    range: true,
                    min: 0,
                    max: 100,
                    values: [0,100],
                    step: 10,
                    slide: function (event, ui) {
                        update(2, ui.values); //changed
                    },
                    stop: function (event, ui) {
                        loadProductData();
                    }
                });
                //Added, set initial value.
                $("#minamount").val($("#slider").slider("option", "min"));
                $("#maxamount").val($("#slider").slider("option", "max"));

 
                $("#minduration").val($("#slider2").slider("option", "min"));
                $("#maxduration").val($("#slider2").slider("option", "max"));

                //$("#duration").val($("#slider").slider("option", "min"));
                //$("#amount-label").text(0);
                //$("#duration-label").text(0);
                update();
            });

            //changed. now with parameter
            function update(slider, val) {
                //changed. Now, directly take value from ui.value. if not set (initial, will use current value.)
                var $minamount = slider == 1 ? val[0] : $("#minamount").val();
                var $maxamount = slider == 1 ? val[1] : $("#maxamount").val();
                //var $duration = slider == 2 ? val : $("#duration").val();

                var minduration = slider == 2 ? val[0] : $("#minduration").val();
                var maxduration = slider == 2 ? val[1] : $("#maxduration").val();

                /* commented
                 $amount = $( "#slider" ).slider( "value" );
                 $duration = $( "#slider2" ).slider( "value" );
                 */

                //$total = "$" + ($amount * $duration);
                $("#minamount").val($minamount);
                $("#maxamount").val($maxamount);
                //$("#amount-label").text($amount);
                
                /*my close*/
                    // $("#duration").val($duration);
                    // $("#duration-label").text($duration);
                /*end*/

                $("#minduration").val(minduration);
                $("#maxduration").val(maxduration);

                // $("#total").val($total);
                //$("#total-label").text($total);
                sliderLinks = $('#slider a');

                $(sliderLinks[0]).html('<label >' + $minamount + ' </label>');
              if($maxamount >= <?php echo $this->maxRangePrice;?>) {
                $(sliderLinks[1]).html('<label ><?php echo $this->maxRangePrice;?>+' + ' </label>');
                $("#maxamount").val(<?php echo $this->actualMaxRangePrice?>);
              } else {
                $(sliderLinks[1]).html('<label >' + $maxamount + ' </label>');
              }
             
              

                sliderLinks = $('#slider2 a');
                $(sliderLinks[0]).html('<label>' + minduration +"<span>%</span>" + ' </label>');
                $(sliderLinks[1]).html('<label >' + maxduration + "<span >%</span>" + ' </label>');
                //$('#slider2 a').html('<label style="margin-left:15px;">' + $duration + '%</label>');
            }
        </script>
        <script type="text/javascript">

            /*$(document).ready(function() {
             $(".overlay-02").css("display","none");
             
             $(".thumb-info").hover(function(){
             $(hover-one).css("display","block");
             },function(){
             $(hover-one).css("display","none");
             });
             });    */

            $(document).ready(function () {
                $(document).on('mouseenter', '.thumb-info', function () {
                    $(this).find(".overlay-02").css("display", "block");
                }).on('mouseleave', '.thumb-info', function () {
                    $(this).find(".overlay-02").css("display", "none");
                });
            });

            $(document).ready(function () {
                $(document).on('click', '.aciTreeLi', function () {
                    var fontthis = this;
                    $(fontthis).siblings(".aciTreeLi").find(".aciTreeText").removeClass("font-bold");
                    $(fontthis).find(fontthis).addClass("font-bold");
                    //      $(fontthis).parents(".aciTreeText").addClass(".font-bold");
                });
            });
        </script>

        <!--=================script-by-designer end portfolio-single-project.html====================-->

        <script type="text/javascript">
            $(document).ready(function () {

                $("#idArticlesPerPageSelect").change(function () {
                    $("#ArticlesPerPageForm").submit()
                });

                $('.selectpicker').selectpicker({
                    //'selectedText': 'cat'
                    width: '120px'
                });

                var t = $('#dialog');

                $('#dialog').jqm({
                    trigger: 'div.productdialogs',
                    ajax: '@href', /* Extract ajax URL from the 'href' attribute of triggering element */
                    target: t,
                    modal: true, /* FORCE FOCUS */
                });

                $('input.jqmdX')
                        .hover(
                                function () {
                                    $(this).addClass('jqmdXFocus');
                                },
                                function () {
                                    $(this).removeClass('jqmdXFocus');
                                })
                        .focus(
                                function () {
                                    this.hideFocus = true;
                                    $(this).addClass('jqmdXFocus');
                                })
                        .blur(
                                function () {
                                    $(this).removeClass('jqmdXFocus');
                                });

                $('input.jqmdX')
                        .hover(
                                function () {
                                    $(this).addClass('jqmdXFocus');
                                },
                                function () {
                                    $(this).removeClass('jqmdXFocus');
                                })
                        .focus(
                                function () {
                                    this.hideFocus = true;
                                    $(this).addClass('jqmdXFocus');
                                })
                        .blur(
                                function () {
                                    $(this).removeClass('jqmdXFocus');
                                });

                $('#dialog').css('padding-bottom', '0px');

                $(".bottomWorkingArea .productsBox").on("click", function (e) {

                    if ($(this).find(".lock").length) {
                        $(this).find(".lock").removeClass('lock').addClass('open')
                    }
                    else {
                        $(this).find(".open").removeClass('open').addClass('lock')
                    }

                    return false;

                });

                $(".topWorkingArea .topBigBox,.topMediumBox,.topSmallBox").on("click", function (e) {

                    if ($(this).find(".open").length) {
                        $(this).find(".open").removeClass('open')
                        $(this).find(".plus").addClass('plusOpen')
                        $(this).find(".minus").addClass('minusOpen')
                    }
                    else {
                        $(this).find(".lock").addClass('open')
                        $(this).find(".plus").removeClass('plusOpen')
                        $(this).find(".minus").removeClass('minusOpen')
                    }
                    return false;
                });
            });
        </script>

        <script class="code" type="text/javascript">

            $(function () {

                // init the tree
                $('#tree').aciTree({
                    ajax: {
                        url: '/attributes/get-categories-json?mapped=true&ec=<?php echo  $this->excludeCats ?>&levels=3&id='
                    },
                    checkbox: true
                });

                $('#tree').on('acitree', function (event, api, item, eventName, options) {
                    switch (eventName) {
                        case 'checked':
                            //alert(item);
                            //alert('checked: ' + api.getId(item));
                            //break;
                        case 'unchecked':
                            getAllCheckedElements(event, api, item, eventName, options);
                            loadProductData();
                            break;
                        case 'init' :
                            getAllCheckedElements(event, api, item, eventName, options);
                            break;
                    }
                });

            });

            function getAllCheckedElements(event, api, item, eventName, options)
            {
                var checkedElements = $("#tree .aciTreeLi .aciTreeLeaf");
                checkedElementsArr = api.checkboxes(checkedElements, true);
                var catIdStr = '';
                checkedElementsArr.each(function (index, item) {
                    var $item = $(item);
                    catIdStr += api.getId($item) + ',';
                    console.log(api.getId($item) + ": " + api.getLabel($item));
                });
                $("#catids").val(catIdStr);
            }

        </script>

        <script type="text/javascript">
          
            var loading = 0;
            var endData = 0;
            function loadProductData(isLazyLoading)
            {
                if (typeof isLazyLoading == 'undefined' || isLazyLoading == '')
                {
                    showAjxLoadingDiv($("#productlisting"));
                    $("#page").val(1);
                    endData = 0;
                }
                else {
                    showAjxLoadingDiv($("#productlisting"));
                    $("#loading").show();
                }
                loading = 1;
                var url = "/service/getfeeds/" + Math.random();
                var filterData = $("#productFilterDetail").serialize();
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: filterData,
                    dataType: 'html',
                    success: function (result) {
                        loading = 0;
                        if (typeof isLazyLoading == 'undefined' || isLazyLoading == '')
                        {
                            $("#productlisting").html(result);
                            hideAjxLoadingDiv();
                            $("#page").val(2);
                            //enableDragg();
                        }
                        else
                        {
                            if (result.indexOf('No Record') > 0)
                            {
                                endData = 1;
                            }
                            else
                            {
                                $("#page").val(parseInt($("#page").val()) + 1); 
                                $("#productlisting").append(result);
                                //enableDragg();
                            }
                            $("#loading").hide();
                            hideAjxLoadingDiv();
                        }
                        $('.my_tooltip').tooltipster({
                            position: 'top',
                            theme: 'tooltipster-shadow',
                        });

                    }

                });


            }

            $(function () {


                $(".check_category").click(function () {
                    if ($(this).is(':checked') == true) {
                        var $infos = $(this).parent('.category');
                        $infos.find("input[type=checkbox]").prop("checked", true);
                    } else {
                        var $infos = $(this).parent('.category');
                        $infos.find("input[type=checkbox]").prop("checked", false);
                    }
                })

                $(".check_subcategory").click(function () {
                    if ($(this).is(':checked') == true) {
                        //alert('Hello');
                        var $infos = $(this).parents('.subcategory');
                        $infos.find("input[type=checkbox]").prop("checked", true);
                    } else {
                        alert('Hey');
                        var $infos = $(this).parents('.subcategory');
                        $infos.find("input[type=checkbox]").prop("checked", false);
                    }
                })

                $(".brandSelection").click(function () {
                    $(this).toggleClass('activebrand');
                    var brands = '';
                    var allSelectedBrands = $(".brandSelection");
                    $(allSelectedBrands).each(function () {
                        if ($(this).hasClass('activebrand')) {
                            brands += ($(this).attr('value')) + ',';
                        }
                    })
                    $("#brands").val(brands);
                    loadProductData();
                })


                $(".profilePrices").change(function () {
                    if($(this).prop('checked')) {
                        $('#priceboxglobal').css('opacity', 0.2);
                        $('#profileBasePrices').val(1); 
                        $("#priceboxglobalOverlay").show();
                    }
                    else {
                        $('#priceboxglobal').css('opacity', 1);
                        $('#profileBasePrices').val(0);
                        $("#priceboxglobalOverlay").hide();
                    }
                    loadProductData(); 
                })                

                $(".storeSelection").click(function () {
                    //alert('hello');
                    $(this).toggleClass('activebrand');
                    var stores = '';
                    var allSelectedStores = $(".storeSelection");
                    $(allSelectedStores).each(function () {
                        if ($(this).hasClass('activebrand')) {
                            stores += ($(this).attr('value')) + ',';
                        }
                    })
                    $("#stores").val(stores);
                    loadProductData();
                })


                var availableBrandTags = <?php echo $this->jsonBrands; ?>;
                $("#brandautocomplete").autocomplete({
                    source: availableBrandTags,
                    select: function (event, ui) {
                        $(".brandslist ul li input[value=" + ui.item.id + "]").addClass('activebrand').prop('checked',true);
                       
                        $("#brands").val($("#brands").val() + ui.item.id +',');
             
                        loadProductData();
                        return false;
                    }
                });

                var availableStoreTags = <?php echo $this->jsonStores; ?>;
                $("#storeautocomplete").autocomplete({
                    source: availableStoreTags,
                    select: function (event, ui) {
                        $("ul.storeSelection li[value=" + ui.item.id + "]").addClass('activebrand');
                        $("#stores").val($("#stores").val() + ui.item.id + ',');
                        loadProductData();
                        return false;
                    }
                });

                $(".colorselection").click(function () {
                    $(this).toggleClass('activecolor');
                    var colors = '';
                    var allSelectedColors = $(".colorselection.activecolor");
                    $(allSelectedColors).each(function () {
                        colors += ($(this).attr('value')) + ',';
                    })
                    $("#colors").val(colors);
                    loadProductData();
                });
            })


            function chooseDeals(currref, dealName)
            {
//                 $(currref).closest( "li" ).find()
//                 console.log(dealName)
//                 $('.sale-option-checkbox', currref).toggleClass('activedeal');
//                 if ($('.sale-option-checkbox', currref).hasClass('activedeal'))
//                 {
//                     $("#" + dealName).val(1);
//                 }
//                 else
//                 {
//                     $("#" + dealName).val('');
//                 }

               
                $('#onsale').val('');
                $('#todaynew').val('');
                $('#newthisweek').val('');
                $('#freeshipping').val('');
                $('#specialoffer').val('');
                $('#discountcode').val('');
                $('#'+dealName).val(1);
                
                loadProductData();
            }
            $(document).ready(function () {

//              var element = $('.left-link-box'),
//                 originalY = 121;
//                 var topMargin = 80;
//                 element.css('position', 'relative'); 

                $('#leftLinkBoxID').hcSticky({stickTo:document, top:80, bottom:10});   
            
                $(window).scroll(function (event) {
                     if( $('#article-block').css('display') == 'block' ) {
                         
                        if ($("#loading-div-background").css('display') == 'block')
                        {
                            var windowheight = $(window).height();
                            var scrolltop = $($("#productlisting")).scrollTop();
                            var windowwidth = $(window).width();
                            //showAjxLoadingDiv($("#productlisting"));
                            // $("#ajx_loader_image").css({top: scrolltop + (windowheight / 2), left: windowwidth / 2, position: 'absolute'});
                        }
    
                        //if ($(window).scrollTop() + $(window).height() >= ($('#productlisting').offset().top + $("#productlisting").height()) + 10) {
                        if(  ($(document).height()-400)   <= $(window).scrollTop()+$(window).height() ){
                            if (loading == 0 && endData == 0)
                            {
                                loadProductData(1);
                            }
                        }

//                         var sTop = $(window).scrollTop();
//                         $(".left-link-box").css({ top: (sTop < (originalY-80) ? 0 : sTop - originalY + topMargin) });                       
                        
                     }
                });

                /*****************block for handling likes product**************/
           

                $('.likes').on('click', function () {
                    var id = $(this).attr("id");
                    var url = "/service/likeclosset/";
                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {closesetId: id},
                        dataType: 'json',
                        success: function (result) {
                                  var class_name ='growl-missing';
                            if(result.status =='Y') {
                                class_name = 'growl-success';
                            } 


                            //alert(result.mgs);
                            //$("#gritter-notice-wrapper").addClass('type_success');
                            jQuery.gritter.add({
                                //title: result.mgs,
                                title: '<div class="wrap_ion_mgs"><div class="icon_gritter"></div><div class="dary_message">' + result.mgs +'</div></div><div class="my_close my_wrap_close">\
                <a href="javascript:void(0)"  class="close-reveal-modal x_close type_close"><span>X</span></a>\
                </div>',
                                class_name: class_name,
                                sticky: false,
                                time: 3000
                            })                             
                            if (result.status == 'N') {
                                //alert(result.mgs);
                            } else if (result.status == 'Y') {
                                var likesd = result.count + ' likes';
                                $('.like_' + result.idf).html(likesd);

                                if($(this).find('#like'+result.idf))
                                    $('#like'+result.idf).attr('src','/img/thumb.png');
                            } else {
                                //alert("Internal Server Error");
                            }
                        }
                    });
                });

                $('body').on('click', '.likes', function () {
                    var id = $(this).attr("id");
                    var url = "/service/likeclosset/";
                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {closesetId: id},
                        dataType: 'json',
                        success: function (result) {
                                      var class_name ='growl-missing';
                            if(result.status =='Y') {
                                class_name = 'growl-success';
                            } 


                            //alert(result.mgs);
                            //$("#gritter-notice-wrapper").addClass('type_success');
                            jQuery.gritter.add({
                                //title: result.mgs,
                                title: '<div class="wrap_ion_mgs"><div class="icon_gritter"></div><div class="dary_message">' + result.mgs +'</div></div><div class="my_close my_wrap_close">\
                <a href="javascript:void(0)"  class="close-reveal-modal x_close type_close"><span>X</span></a>\
                </div>',
                                class_name: class_name,
                                sticky: false,
                                time: 3000
                            })                             
                            if (result.status == 'N') {
                                //alert(result.mgs);
                            } else if (result.status == 'Y') {
                                var likesd = result.count + ' likes';
                                $('.like_' + result.idf).html(likesd);

                                if($(this).find('#like'+result.idf))
                                    $('#like'+result.idf).attr('src','/img/thumb.png');
                            } else {
                                //alert("Internal Server Error");
                            }

                        }
                    });
                });
                

               

                $('body').on('click', '.type_close', function () {
                    $('.gritter-close').trigger('click');
                });

                $('body').on('click', '.likesout', function () {
                    var id = $(this).attr("id");
                    var url = "/service/likeclosset/";
                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {closesetId: id},
                        dataType: 'json',
                        success: function (result) {
                            var class_name ='growl-missing';
                            if(result.status =='Y') {
                                class_name = 'growl-success';
                            } 


                            //alert(result.mgs);
                            //$("#gritter-notice-wrapper").addClass('type_success');
                            jQuery.gritter.add({
                                //title: result.mgs,
                                title: '<div class="wrap_ion_mgs"><div class="icon_gritter"></div><div class="dary_message">' + result.mgs +'</div></div><div class="my_close my_wrap_close">\
                <a href="javascript:void(0)"  class="close-reveal-modal x_close type_close"><span>X</span></a>\
                </div>',
                                class_name: class_name,
                                sticky: false,
                                time: 3000
                            })                             
                            if (result.status == 'N') {
                                //alert(result.mgs);
                            } else if (result.status == 'Y') {
                                var likesd = result.count + ' likes';
                                $('.like_' + result.idf).html(likesd);

                                if($(this).find('#likeout'+result.idf))
                                    $('#likeout'+result.idf).attr('src','/img/thumb.png');
                            } else {
                                //alert("Internal Server Error");
                            }
                        }
                    });
                });

                /*****************block for handling likes product**************/


            });

            function showAjxLoadingDiv(target)
            {
                $("#loading-div-background").show();
//                 //var target=$('#'+targetId);
//                 var tarheight = $(target).height();
//                 var tartop = $(target).offset().top;
//                 var tarleft = $(target).offset().left;

//                 var scrollheight = $(target).height();
//                 var scrollwidth = $(target).width();
//                 var windowheight = $(target).height();
//                 var windowwidth = $(target).width();
//                 $("#ajx_loader_div").css({height: scrollheight, width: scrollwidth, display: 'block', top: (tartop + (60)), left: tarleft, position: 'absolute'});
//                 $("#ajx_loader_image").css({top: windowheight / 2, left: windowwidth / 2, position: 'absolute'});
            }

            function hideAjxLoadingDiv()
            {
                //$("#ajx_loader_div").css({display: 'none'});
                $("#loading-div-background").hide();
            }

            function toggleslide(obj) {
                $('#outfit-window').toggle();
                $('#article-window').toggle();
                $('#productlisting').toggle();
                $('#loading').hide();
                if ($(obj).html() == 'Show Outfit') {
                    $(obj).html('Show Articles');
                } else {
                    $(obj).html('Show Outfit');
                }
            }
            $(document).on('click', '.refresh', function (e) {

                $.ajax({
                    url: '<?php echo $this->basePath('service') ?>',
                    success: function (data) {
                        $('#outfit-window').html($(data).find("#outfit-window").html()); 
                    }
                });
            });

            function adjustNewOutfitLayout() {
                for(var i=0; i<10; i++) {
                    $('.big_box1_outer').css('width', $(document).width()+'px')
                    var w = ($(document).width() - $('.container').width()) / 2;
                    $('.big_box1_outer .prevOutfit').width(w)
                    $('.big_box1_outer').css('margin-left', -(w))
                    $('.big_box1_outer .nextOutfit').width(w)
                }                
            }

            $(window).load(function () {

            //  $( ".square1_tick" ).on( "click", function(event) {
            //        event.preventDefault();
                //       $( ".square1" ).trigger( "click" );
                // });


                // $('.square1').on('click', function () {
                //     var valueD = $(this).html();
                //     if (valueD == 'on') {
                //         $(this).html('off');
                //         $('#panel').attr('src','/img/circle-close.png');
                //         $(this).removeClass('on');
                //         $(this).addClass('off');
                //         $('#article-block').show();
                //         $('#outfit-block').hide();
                //         $('.outfitrefresh').hide();
                //         $('#leftaction').hide();
                //         $("footer").hide();
                //         $(".last-foot").hide();
                //         $(".square1").css('float', 'left');
                //         $(".square1").css('margin-left', '5px');
                //         $(".head1").text("Article Shopping");
                //     } else {
                //         $(this).html('on');
                //         $('#panel').attr('src','/img/circle-ok.png');
                //         $(this).removeClass('off');
                //         $(this).addClass('on');
                //         $('#article-block').hide();
                //         $('#outfit-block').show();
                //         $('.outfitrefresh').show();
                //         $('#leftaction').show();
                //         $("footer").show();
                //         $(".last-foot").show();
                //         $(".square1").css('float', 'right');
                //         $(".square1").css('margin-left', '0px');
                //         $(".head1").text("Outfit Shopping");
                //     }
                // });
                // 
                $('input[name="outart"]').change(
                    function(){
                        if($(this).is(':checked') && $(this).val() == 'outfit'){
                            $('#outfit-block').show();
                            $('#article-block').hide();
                            $('.outfitrefresh').show();
                            $('#leftaction').show();
                            $("footer").show();
                            $(".last-foot").show();
                        }
                        if($(this).is(':checked') && $(this).val() == 'articles') {
                            $('#outfit-block').hide();
                            $('#article-block').show();
                            $('.outfitrefresh').hide();
                            $('#leftaction').hide();
                            $("footer").hide();
                            $(".last-foot").hide();
                        }
                });
                $('.blue-btn1').on('click', function () {
                    var currentSelector = ".square1";
                    var valueD = $(currentSelector).html();
                    if (valueD == 'on') {
                        $(currentSelector).html('off');
                        $('#panel').attr('src','/img/circle-close.png');
                        $(currentSelector).removeClass('on');
                        $(currentSelector).addClass('off');
                        $('#article-block').show();
                        $('#outfit-block').hide();
                        $('.outfitrefresh').hide();
                        $('#leftaction').hide();
                        $("footer").hide();
                        $(".last-foot").hide();
                        $(".square1").css('float', 'left');
                        $(".square1").css('margin-left', '5px');
                        $(".head1").text("Article View");
                    } else {
                        $(currentSelector).html('on');
                        $('#panel').attr('src','/img/circle-ok.png');
                        $(currentSelector).removeClass('off');
                        $(currentSelector).addClass('on');
                        $('#article-block').hide();
                        $('#outfit-block').show();
                        $('.outfitrefresh').show();
                        $('#leftaction').show();
                        $("footer").show();
                        $(".last-foot").show();
                        $(".square1").css('float', 'right');
                        $(".square1").css('margin-left', '0px');
                        $(".head1").text("Outfit View");
                    }
                });

                $('body').on('click', '.iFeelLucky', function (event) {
                    event.preventDefault();
                    var iRandom; 
                    do{
                        iRandom = Math.floor(Math.random() * ($('#outfits_count').val() - 0 + 1)) + 0;
                    } while( $('#outfits_offset').val() != iRandom );
                    $('#outfits_offset').val( iRandom ); 
                    getOutfit(1);
                });



                $(document).keydown(function (event){

                    if(event.ctrlKey && event.keyCode == 39) {
                     getOutfit(1);
                    }
                    if(event.ctrlKey && event.keyCode == 37) {
                         getOutfit(-1);
                    }                   
                    
                  });                

                
                $('body').on('click', '.nextOutfit', function () {
                    getOutfit(1);
                });

                $('body').on('click', '.prevOutfit', function () {
                    getOutfit(-1);
                });
                                
                $('body').on('click', '.sharepoup', function () {
                    $('#slideout_inner').css('right', '-165px');
                    $('#slideout').css('right', '-65px');
                    $(this).removeClass('shopen');
                    $(this).addClass('shclose');
                    $('#idSharethisOutfit').removeClass('shopen');
                    $('#idSharethisOutfit').addClass('shclose');                    

                });
//                 $('body').on('click', '.share1', function () {
//                     var clases = $(this).attr('class');
//                     var classesA = clases.split(" ");
//                     if (classesA[1] == 'shclose') {
//                         $('#slideout_inner').css('right', '0');
//                         $('#slideout').css('right', '90px');
//                         $(this).removeClass('shclose');
//                         $(this).addClass('shopen');
//                     } else {
//                         $('#slideout_inner').css('right', '-165px');
//                         $('#slideout').css('right', '-65px');
//                         $(this).removeClass('shopen');
//                         $(this).addClass('shclose');
//                     }
//                 })
                $('body').on('click', '.share1', function () {
                    if ( $('#shareThisOutfitPopup').css('display') == 'none' ) {
                        $('#shareThisOutfitPopup').show()
                    } else {
                        $('#shareThisOutfitPopup').hide()
                    }
                })
                
                /*****************block for adding this product into my coloseset**************/
                $('body').on('click', '.savecloseout', function () {
                    var id = $('#closesetId').val();
                    var url = "/service/outfitclosset/";
                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {closesetId: id},
                        dataType: 'json',
                        success: function (result) {
                                 var class_name ='growl-missing';
                            if(result.status =='Y') {
                                class_name = 'growl-success';
                                $('.outfitlikes img').attr('src', '/img/thumb.png');
                                $('.outfitlikes span').html( parseInt($('.outfitlikes span').html()) + 1 );
                            } 


                            //alert(result.mgs);
                            //$("#gritter-notice-wrapper").addClass('type_success');
                            if(!$("#gritter-notice-wrapper ." + class_name).length) {
                                jQuery.gritter.add({
                                //title: result.mgs,
                                title: '<div class="wrap_ion_mgs"><div class="icon_gritter"></div><div class="dary_message">' + result.mgs +'</div></div><div class="my_close my_wrap_close">\
                                    <a href="javascript:void(0)"  class="close-reveal-modal x_close type_close"><span>X</span></a>\
                                    </div>',
                                        class_name: class_name,
                                        sticky: false,
                                        time: 3000,
                                });
                            }
                                

                            if (result.status == 'N') {
                                //alert(result.mgs);
                            } else if (result.status == 'Y') {
                                 var likesd = result.count + ' likes';
                                $('#like_' + result.idf).html(likesd);
                            } else {
                                //alert("Internal Server Error");
                            }                        
              



                            // if (result.status == 'N') {
                            //     swal("Oops!", result.mgs)
                            // } else if (result.status == 'Y') {
                            //     swal("Outfit Saved!", "You can find this Outfit in Saved Section.", "success")
                            //     //var likesd = result.count + ' likes';
                            //     //$('#like_' + result.idf).html(likesd);
                            // } else {
                            //     sweetAlert("Oops...", "Internal Server Error", "error");
                            // }
                        }});
                });
                /*****************End block for adding this product into my coloseset**************/

                /*******************block for filter jquery *********/
                $('#check1').on('click', function () {
                    if ($(this).is(':checked')) {
                        $('input[type="checkbox"]').prop('checked', true);
                    } else {
                        $('input[type="checkbox"]').prop('checked', false);
                    }
                    getOutfit();
                });
                $("input[name='outfit[]']").on('click', function () {
                    var checkedLen = $('input[name="outfit[]"]:checked').length;
                    var totalCheckBox = $('input[name="outfit[]"]').length;
                    if (checkedLen == totalCheckBox) {
                        $('#check1').prop('checked', true);
                    } else {
                        $('#check1').prop('checked', false);
                    }
                    getOutfit();
                });

                adjustNewOutfitLayout();

                function getOutfit (direction) {

                    if( direction == undefined ) direction = 0;
                    
                  console.log(direction);
                  var val1 = [];
                  var result = {};
                  $("input[name='outfit[]']:checked").each(function (i) {
                        val1[i] = $(this).val();
                        result['outfit'] = val1;
                  });

                  if(result['outfit'] == undefined || result['outfit'].length == 0) {
                    result['outfit'] = ['Work','Night Out','Casual'];
                  }
                  //console.log( result['outfit']);
               
                  if( direction === 1 ) {
                         $('#outfits_offset').val( parseInt($('#outfits_offset').val()) + 1 ); 
                  }
                  else if( direction === -1 ) {
                        $('#outfits_offset').val( parseInt($('#outfits_offset').val()) - 1 );
                  }

    
                  if( parseInt($('#outfits_offset').val()) < 0 ) {
                      $('#outfits_offset').val( parseInt($('#outfits_count').val()) - 1 );
                  }
                                            
                    result['outfits_offset'] = $("#outfits_offset").val();
                    console.log(result);
                    //result.push({'outfits_offset':$("#outfits_offset").val()});
                    $.ajax({
                        url: '/service/alloutfits',
                        type: 'POST',
                        data: {filterArg: result},
                        success: function (data) {
                            //console.log(data);
                            // if(data.indexOf('not available') > 0) {
                            //     $('#outfits_offset').val(0);
                            //     getOutfit(1);
                            // } else {
                                  $('#outfit-block').html(data);
                                adjustNewOutfitLayout();
                                
                                //show tooltip
                                $('.my_tooltip').tooltipster({
                                    position: 'top',
                                    theme: 'tooltipster-shadow',
                                    
                                });
                           // }
                          
                     
                            
                        }
                    });
                }

                /*******************End block for filter jquery *********/

                <?php if( isset($this->defaultView) && $this->defaultView=='article' ) {?>
                $( ".square1" ).trigger( "click" );
                <?php }?>


                
            });
            $( window ).resize(function() {
                adjustNewOutfitLayout();
            });


        </script>


        <!--<script src="/vendor/jquery-ui.min.js"></script>-->
        <!--<script type="text/javascript" src="/js/bootstrap-progressbar.js"></script>-->

        

<div id="loading-div-background">
    <div id="loading-div" class="ui-corner-all" >
      <img style="margin-top:20px; height: 50px" src="/img/loading7_light_blue.gif" alt="Loading.."/>
      <h2 style="color:gray;font-weight:normal;">Please wait....</h2>
     </div>
</div>       