<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/templates/mobile/ion.rangeSlider/css/ion.rangeSlider.css')
                ->appendStylesheet($this->basePath() . '/templates/mobile/ion.rangeSlider/css/ion.rangeSlider.skinHTML5.css')
                 ;
 ?>
<?php echo $this->partial('application/common/banner_header.phtml'); ?> 

<div id="filter-selected" class="container-fluid" >    
    <div class="row">
        <div class="col-lg-2 col-sm-3 col-lg-offset-1 " id="refineseacrch-left">
            <div class="row">
                <div class="box refine-search col-lg-12 hidden-xs" >
                    <span>REFINE SEARCH</span>
                </div>
                <div class="box refine-search col-lg-12 visible-xs" id="refine-search-popup" data-popup="#rfs-content-popup">
                    <span>REFINE SEARCH</span>
                </div>
                <div class="box popup-sort-item " id="sort-item-popup" data-popup="#sis-content-popup" >
                    <span>SORT ITEMS</span>
                </div>
                <div class="box sort-list "><i class="fa fa-bars" aria-hidden="true"></i></div>
                <div class="box sort-grid "><i class="fa fa-th-large" aria-hidden="true"></i></div>
            </div>
         </div>
        <div class="col-lg-8 col-sm-9 selected_right ">
            <div class="option-filter">
                <form class="filterTypeMain">                    
                    <input data-parent="filterTypeMain" type="radio" name="filter" id="all" value="all" checked="checked">
                    <label for="all">ALL</label>

                    <input data-parent="filterTypeMain" type="radio" name="filter" id="sale" value="sale">
                   <label for="sale">BOUGHT</label>

                    <input data-parent="filterTypeMain" type="radio" name="filter" id="saveitem" value="saveitem">
                    <label for="saveitem">SAVE ITEMS</label>
                </form>
            </div>
            <div class="option-selected">
               
            </div>
            <div class="sort-item " id="accordion-select" >
                <span class="uc_head_line">
                    <span class="icon_arrow fa fa-chevron-down"></span>
                    <p class="uc_link_tittle sort-item-selected">Sort By</p>
                </span>
                <div class="uc_line_content">
                    <ul class="uc_des orderBy">
                        <!-- <li data-parent="orderBy" value="relevance" class="sort-item-select" >Relevance</li> -->
                        <li data-parent="orderBy" value="" class="sort-item-select" >Sort By</li>
                        <li data-parent="orderBy" value="lowest" class="sort-item-select" >Lowest price</li>
                        <li data-parent="orderBy" value="highest" class="sort-item-select" >Highest price</li>
                       <!--  <li data-parent="orderBy" value="mostpopular" class="sort-item-select" >Most Popular</li>
                        <li data-parent="orderBy" value="favorites" class="sort-item-select" >Favorites</li> -->
                        <li data-parent="orderBy" value="newest" class="sort-item-select" >Newest</li>
                        
                    </ul>
                </div>
                <div class="sort-filter-contentpopup visible-xs" id="sis-content-popup">
                    <p class="m-title">SORT ITEMS BY</p>
                    <ul class="orderBy">
                        <!-- <li data-parent="orderBy" value="relevance" class="sort-item-select" >Relevance</li> -->
                        <li data-parent="orderBy" value="" class="sort-item-select" >Sort by</li>
                        <li data-parent="orderBy" value="lowest" class="sort-item-select" >Lowest price</li>
                        <li data-parent="orderBy" value="highest" class="sort-item-select" >Highest price</li>
                       <!--  <li data-parent="orderBy" value="mostpopular" class="sort-item-select" >Most Popular</li>
                        <li data-parent="orderBy" value="favorites" class="sort-item-select" >Favorites</li> -->
                        <li data-parent="orderBy" value="newest" class="sort-item-select" >Newest</li>
                        
                    </ul>
                </div>                  
            </div>
        </div>
    </div> 
</div> 

<div class="row">
    <!-- REFINE SEARCH Block -->
    <div class="refine col-lg-2 col-lg-offset-1 col-sm-3">
        <?php echo $this->partial('application/service/index_refine.phtml'); ?> 
    </div>
    <!-- Products List Block -->
    <div class="col-lg-8 col-sm-9">
        <div class="row">
            <div id="body-main-sideright" class="col-lg-12">
                <div class="row "  id="load-product-list">
                    <!-- Possition for load products from Ajax -->
                </div>
                <div id="load-more" class="row text-center">
                    <button class="btn-st-silver">Load more</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Form for REFINE SEARCH -->
<form id="productFilterDetail" name="productFilterDetail">
    <input type="hidden" id="minamount" name="minamount">
    <input type="hidden" id="maxamount" name="maxamount">
    <input type="hidden" id="minduration" name="minduration">
    <input type="hidden" id="maxduration" name="maxduration">
    <input type="hidden" id="catids" name="catids">
    <input type="hidden" id="brands" name="brands">
    <input type="hidden" id="colors" name="colors">
    <input type="hidden" id="stores" name="stores">
    <input type="hidden" id="deals" name="deals">
    <input type="hidden" id="onsale" name="onsale">
    <input type="hidden" id="todaynew" name="todaynew">
    <input type="hidden" id="newthisweek" name="newthisweek">
    <input type="hidden" id="freeshipping" name="freeshipping">
    <input type="hidden" id="specialoffer" name="specialoffer">
    <input type="hidden" id="discountcode" name="discountcode">
    <input type="hidden" id="page" name="page" value="2">
    <input type="hidden" id="limit" name="limit" value="<?php echo PRODUCTS_PER_PAGE;?>">
    <input type="hidden" id="profileBasePrices" name="profileBasePrices" value="1">
    <input type="hidden" id="filterTypeMain" name="filterTypeMain" value="all">
    <input type="hidden" id="orderBy" name="orderBy">
    <?php $arrSearch = $this->arrSearch; ?>
    <input type="hidden" id="searchArticle" name="searchArticle" value="<?php echo $arrSearch['search1'];?>">
    <input type="hidden" id="searchVenue" name="searchVenue" value="<?php echo $arrSearch['search2'];?>">
</form>

<!-- Modal -->
<div id="modal_total">
    <!-- Modal of Popup Quick-view-product-item -->
    <div class="modal fade bs-example-modal-lg modal_quick_view" id="modal_QV" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <div class="container-fluid">
                        <div class="row" id="append_modal">
                        </div>
                    </div>
                </div>                  
            </div>
        </div>
    </div>
    <!-- End Modal of Popup Quick-view-product-item -->
        
    <!-- Modal of Popup icon_alert -->
    <div class="modal fade bs-example-modal-lg modal_icon_alert" id="modal_alert" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
        <div class="modal-dialog modal-lg" role="document">                              
            <div class="modal-content modal_alert" id="alert-content">
            </div>                                   
        </div>
    </div>
    <!-- End Modal of Popup icon_alert -->
</div>
<!-- End Modal -->

<!-- Background Loading -->
<!-- <div id="loading-div-background">
    <div id="loading-div" class="ui-corner-all" >
        <img style="margin-top:20px; height: 50px" src="/img/loading7_light_blue.gif" alt="Loading.."/>
        <h2 style="color:gray;font-weight:normal;">Please wait....</h2>
    </div>
</div>  -->
<script src="<?php echo $this->basePath().'/templates/mobile' ?>/ion.rangeSlider/js/ion.rangeSlider.min.js"></script>
<script src="/assets/js/jquery.filtertable.js"></script>
<script src="/assets/js/product.js"></script>
<script src="/assets/js/refine.js"></script>
<script src="/assets/js/header.js"></script>
<!--script>
$(document).ready(function() {
    // apply filterTable to all tables on this page but don't filter content with the no-filter class
    $('table').filterTable({ignoreClass: 'no-filter'});
    $('.desktop p.filter-table').prependTo('.desktop .brands .brand');
    $('.mobile p.filter-table').prependTo('.mobile .brands .brand');
});
</script-->