    <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.gray.js')
                                ->prependFile($this->basePath() . '/js/jquery.js')
                                 ->appendFile($this->basePath() . '/js/jquery.placeholder.min.js')
                                ;
        ?>

<div class="row">
    <div class="refine col-lg-2 col-lg-offset-1 col-sm-3">
        <div class="refine-colum hidden-xs">
            <ul> 


           
                <li id="category">CATEGORIES</li>
                <div  class="category stage0" style="display: none; left: 100px;">
                    <ul>
                    
                    <?php foreach ($this->aJson as $aJson) { ?>
                        <li class="stage1 <?php if(isset($aJson['branch'])){echo 'has-child';}else{echo 'item';} ?>" id="<?php  echo strtolower($aJson['label']); ?>"> <?php  echo $aJson['label']; ?> </li>
                            <div class="<?php  echo strtolower($aJson['label']); ?>">
                                <ul>
                                    <?php 
                                    if(isset($aJson['branch'])) :
                                    foreach ($aJson['branch'] as $aJson1) { ?>
                                        <li class="stage2 <?php if(isset($aJson1['branch'])){echo 'has-child';}else{echo 'item';} ?>" id="<?php $search = array(' ', '&');
                                        echo strtolower (str_replace($search,'',$aJson1['label'])); ?>"><?php echo $aJson1['label']; ?></li>
                                        <div style="display: none; left: 100px;" class="<?php  echo strtolower (str_replace($search,'',$aJson1['label'])); ?>">
                                            <ul>
                                            <?php if(isset($aJson1['branch'])) :
                                            foreach ($aJson1['branch'] as $aJson2) { ?>
                                            
                                                    <li class="stage3 <?php if(isset($aJson2['branch'])){echo 'has-child';}else{echo 'item';} ?>"><?php  echo ($aJson2['label']); ?></li>
                                                
                                            <?php }  endif; ?>
                                            </ul>
                                        </div>
                                    <?php }  endif; ?>
                                </ul>
                            </div>
                    <?php } ?>
                    </ul>
                </div>


                <li id="brands" >BRANDS</li>
                <div class="brands stage0">
                    <div class="brand">
                        <?php if (!empty($this->allBrands) || !empty($this->allTopBrands)) { ?>
                        <div class="list-brand">
                            <ul>
                            <table>
                            <tbody>

                                <?php if (!empty($this->allBrands)) { 
                                        foreach ($this->allBrands as $brand) { ?>
                                <tr><td><li data-brand='<?php echo $brand[ 'id']; ?>' class='item'><?php echo $brand[ 'title']; ?></li></td></tr>
                                <?php } } ?>

                            </tbody>
                            </table>

                            </ul>
                        </div>
                        <?php } ?>
                    </div>
                </div>

                <div id="1">
                    <li id="prices">PRICE</li>
                    <div class="price prices stage0">
                        <div class="slider-3 ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all">
                            <div class="ui-slider-range ui-widget-header ui-corner-all" style=" left: 25%;"></div><span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" style="left: 25%;"></span><span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" style="left: 100%;"></span>
                        </div>
                    </div>
                    <script>
                        $(function() {
                            $(".slider-3").slider({
                                range: true,
                                min: 0,
                                max: 1000,
                                values: [250, 1000],
                                slide: function(event, ui) {
                                    minprice = (ui.values[0]);
                                    maxprice = (ui.values[1]);
                                    $('#1 .slider-3 span:eq(0) p').empty().append(minprice);
                                    $('#1 .slider-3 span:eq(1) p').empty().append(maxprice);
                                    $('#2 .slider-3 span:eq(0) p').empty().append(minprice);
                                    $('#2 .slider-3 span:eq(1) p').empty().append(maxprice);
                                    $("input[name='minamount']").val(minprice);
                                    $("input[name='maxamount']").val(maxprice);
                                }
                            });
                            $("#min-price").val("$" + $(".slider-3").slider("values", 0));
                            $("#max-price").val("$" + $(".slider-3").slider("values", 1));

                        });
                    </script>
                </div>

                <li id="colors">COLOR</li>                  
                                        
                <div class="colors stage0">
                    <div class="list-color">

                    <?php
                    if (!empty($this->allColors)) {
                        foreach ($this->allColors as $color) {
                            if($color['value'] == 'WHITE') { $bdrcolor = '#CCCCCC'; } else { $bdrcolor = $color['value']; }
                            ?>
                            <div data-color="<?php echo $color['value']; ?>" class="color <?php if($color['value'] == 'BEIGE' || $color['value'] == 'WHITE' || $color['value'] == 'YELLOW' ){ echo 'special'; } ?>" style="background-color:<?php echo $color['value']; ?>;border:solid 1px <?php echo $bdrcolor; ?>;" value="<?php echo $color['value']; ?>" title="<?php echo $color['value']; ?>"></div>
                            <?php
                        }
                    }
                    ?>

                    </div>
                </div>
                <li id="deals">DEALS</li>
                <div class="deals stage0">
                    <ul>
                        <li data-deal="onsale" class="item">All item on sale</li>
                        <li data-deal="todaynew" class="item">New today</li>
                        <li data-deal="newthisweek" class="item">New this week</li>
                        <li data-deal="freeshipping" class="item">Free shipping</li>
                        <li data-deal="specialoffer" class="item">Special offer</li>
                        <li data-deal="discountcode" class="item">Discount</li>
                    </ul>
                </div>
                <li id="sizes">SIZE</li>
                <div class="sizes stage0">
                    <div class="list-size">
                        <div class="size"><span value="xs" class="select">XS</span>
                        </div>
                        <div class="size"><span value="s" class="select">S</span>
                        </div>
                        <div class="size"><span value="m" class="select">M</span>
                        </div>
                        <div class="size"><span value="l" class="select">L</span>
                        </div>
                        <div class="size"><span value="xl" class="select">XL</span>
                        </div>
                        <div class="size"><span value="xxl" class="select">XXL</span>
                        </div>
                        <div class="size"><span value="xxxl" class="select">XXXL</span>
                        </div>
                    </div>
                </div>
                <li id="stores">STORE</li>
                <div class="stores stage0">
                    <div class="brand">
                        <input class="label-brand" placeholder="Search Stores">
                        <div class="list-brand">
                            <ul>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                                <li class="select">Brand Name</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </ul>
            <button id="submit" type="submit" form="form1" value="Submit">CLEAR FILTER</button>
        </div>
        <!-- popup-->
        <div class="refine" style="display: none;">
            <div class="refine-colum" id="rfs-content-popup">
                <p class="m-title"> REFINE SEARCH</p>
                <div class="option-filter">
                    <div class="option-filter-row">
                        <label><span>ALL</span>
                        </label>
                        <input type="radio">
                    </div>
                    <div class="option-filter-row">
                        <label><span>SALE</span>
                        </label>
                        <input type="radio">
                    </div>

                    <div class="option-filter-row">
                        <label><span>SAVE ITEMS</span>
                        </label>
                        <input type="radio">
                    </div>
                </div>
                <ul>
                    <li id="category">CATEGORIES</li>
                    <div class="category" style="display: none; left: 100px;">
                        <ul>
                            <li id="clothing">CLOTHING</li>
                            <div class="clothing" style="display: block; left: 50px;">
                                <ul>
                                    <li class="select">Filter</li>
                                    <li class="select">Filter</li>
                                    <li class="select">Filter</li>
                                    <li class="select">Filter</li>
                                    <li class="select">Filter</li>
                                </ul>
                            </div>
                        </ul>
                        <ul>
                            <li id="footwear">FOOTWEAR</li>
                            <div class="footwear">
                                <ul>
                                    <li class="select">Sneakers</li>
                                    <li class="select">Sandals</li>
                                    <li class="select">Dress</li>
                                    <li class="select">Casual</li>
                                    <li class="select">Boots</li>
                                </ul>
                            </div>
                        </ul>
                        <ul>
                            <li id="accessories">ACCESSORIES</li>
                            <div class="accessories">
                                <ul>
                                    <li class="select">Filter</li>
                                    <li class="select">Filter</li>
                                    <li class="select">Filter</li>
                                    <li class="select">Filter</li>
                                    <li class="select">Filter</li>
                                </ul>
                            </div>
                        </ul>
                    </div>
                    <li id="brands">BRANDS</li>
                    <div class="brands">
                        <div class="brand">
                            <input class="label-brand" placeholder="Search Brands">
                            <div class="list-brand">
                                <ul>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div id="2">
                        <li id="prices">PRICE</li>
                        <div class="price prices">
                            <div class="slider-3 ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all">
                                <div class="ui-slider-range ui-widget-header ui-corner-all" style="width: 75%; left: 25%;"></div><span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" style="left: 25%;"></span><span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" style="left: 100%;"></span>
                            </div>
                        </div>
                        <script>
                            // $(function() {
                            //     $(".slider-3").slider({
                            //         range: true,
                            //         min: 0,
                            //         max: 1000,
                            //         values: [250, 1000],
                            //         slide: function(event, ui) {
                            //             minprice = (ui.values[0]);
                            //             maxprice = (ui.values[1]);
                            //             $('#1 .slider-3 span:eq(0) p').empty().append(minprice);
                            //             $('#1 .slider-3 span:eq(1) p').empty().append(maxprice);
                            //             $('#2 .slider-3 span:eq(0) p').empty().append(minprice);
                            //             $('#2 .slider-3 span:eq(1) p').empty().append(maxprice);
                            //         }
                            //     });
                            //     $("#min-price").val("$" + $(".slider-3").slider("values", 0));
                            //     $("#max-price").val("$" + $(".slider-3").slider("values", 1));

                            // });
                        </script>
                    </div>

                    <li id="colors">COLOR</li>
                    <div class="colors ">
                        <div class="list-color">
                            <div class="color" style="background: #000"></div>
                            <div class="color special" style="background: #F5F5DC"></div>
                            <div class="color" style="background: #0000FF"></div>
                            <div class="color" style="background: #A52A2A"></div>
                            <div class="color" style="background: #008000"></div>
                            <div class="color" style="background: #808080"></div>
                            <div class="color" style="background: #FFA500"></div>
                            <div class="color" style="background: #FFC0CB"></div>
                            <div class="color" style="background: #800080"></div>
                            <div class="color" style="background: #FF0000"></div>
                            <div class="color special" style="background: #FFFFFF"></div>
                            <div class="color special" style="background: #FFFF00"></div>
                        </div>
                    </div>
                    <li id="deals">DEALS</li>
                    <div class="deals">
                        <ul>
                            <li class="select">All item on sale</li>
                            <li class="select">New today</li>
                            <li class="select">New this week</li>
                            <li class="select">Free shipping</li>
                            <li class="select">Special offer</li>
                            <li class="select">Discount</li>
                        </ul>
                    </div>
                    <li id="sizes">SIZE</li>
                    <div class="sizes">
                        <div class="list-size">
                            <div class="size"><span value="xs" class="select">XS</span>
                            </div>
                            <div class="size"><span value="s" class="select">S</span>
                            </div>
                            <div class="size"><span value="m" class="select">M</span>
                            </div>
                            <div class="size"><span value="l" class="select">L</span>
                            </div>
                            <div class="size"><span value="xl" class="select">XL</span>
                            </div>
                            <div class="size"><span value="xxl" class="select">XXL</span>
                            </div>
                            <div class="size"><span value="xxxl" class="select">XXXL</span>
                            </div>
                        </div>
                    </div>
                    <li id="stores">STORE</li>
                    <div class="stores">
                        <div class="brand">
                            <input class="label-brand" placeholder="Search Stores">
                            <div class="list-brand">
                                <ul>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                    <li class="select">Brand Name</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="m-button-foot col-xs-12">
                        <div class="col-xs-6 btn-refine">
                            <button type="submit" id="clear-submit" form="form1" value="Submit" name="clear-filter">CLEAR FILTER</button>
                        </div>
                        <div class="col-xs-6 btn-refine">
                            <button type="submit" id="apply-submit" form="form1" value="Submit" name="apply">APPLY</button>
                        </div>
                    </div>
                </ul>
            </div>
        </div>
        <form id="productFilterDetail" name="productFilterDetail">
            <input type="hidden" id="minamount" class="form-control" name="minamount">
            <input type="hidden" id="maxamount" class="form-control" name="maxamount">
            <input type="hidden" id="minduration" class="form-control" name="minduration">
            <input type="hidden" id="maxduration" class="form-control" name="maxduration">
            <input type="hidden" id="catids" class="form-control" name="catids">
            <input type="hidden" id="brands" class="form-control" name="brands">
            <input type="hidden" id="colors" class="form-control" name="colors">
            <input type="hidden" id="stores" class="form-control" name="stores">
            <input type="hidden" id="deals" class="form-control" name="deals">
            <input type="hidden" id="onsale" class="form-control" name="onsale">
            <input type="hidden" id="todaynew" class="form-control" name="todaynew">
            <input type="hidden" id="newthisweek" class="form-control" name="newthisweek">
            <input type="hidden" id="freeshipping" class="form-control" name="freeshipping">
            <input type="hidden" id="specialoffer" class="form-control" name="specialoffer">
            <input type="hidden" id="discountcode" class="form-control" name="discountcode">
            <input type="hidden" id="page" class="form-control" name="page" value="2">
            <input type="hidden" id="limit" class="form-control" name="limit" value="<?php echo PRODUCTS_PER_PAGE;?>">
            <input type="hidden" id="profileBasePrices" class="form-control" name="profileBasePrices" value="1">
        </form>
    </div>

    <div class="col-lg-8 col-sm-9">
        <div class="row">
            <div id="body-main-sideright" class="col-lg-12">

                <div class="row"  id="load-product-list">

                    
                </div>
                <div id="load-more" class="row text-center">
                    <button class="btn-st-silver">Load more</button>
                </div>
            </div>
        </div>
      
    </div>
</div>
<div id="loading-div-background">
    <div id="loading-div" class="ui-corner-all" >
      <img style="margin-top:20px; height: 50px" src="/img/loading7_light_blue.gif" alt="Loading.."/>
      <h2 style="color:gray;font-weight:normal;">Please wait....</h2>
     </div>
</div> 

    <script src="js/jquery.filtertable.js"></script>
    <script>
    $(document).ready(function() {
        loadProductData();
        // apply filterTable to all tables on this page but don't filter content with the no-filter class
        $('table').filterTable({ignoreClass: 'no-filter'});
        $('p.filter-table').prependTo('.brands .brand');

        //Click button loadmore 
        $("#load-more>.btn-st-silver").click(function(){
           if (loading == 0 && endData == 0)
            {
                loadProductData(1);
            }
        });
        
    });


    </script>
     <script type="text/javascript">
          
            var loading = 0;
            var endData = 0;
            function loadProductData(isLazyLoading){
                
                if (typeof isLazyLoading == 'undefined' || isLazyLoading == '')
                {
                    //showAjxLoadingDiv($("#productlisting"));
                    $("#page").val(1);
                    endData = 0;
                }
                // else {
                //     //showAjxLoadingDiv($("#productlisting"));
                //     //$("#loading").show();
                // }
                loading = 1;
                var url = "/service/getfeeds/" + Math.random();
                var filterData = $("#productFilterDetail").serialize();
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: filterData,
                    dataType: 'html',
                    success: function (result) {
                        loading = 0;
                        if (typeof isLazyLoading == 'undefined' || isLazyLoading == '')
                        {
                            $("#load-product-list").html(result);
                            hideAjxLoadingDiv();
                            $("#page").val(2);
                            //enableDragg();
                        }
                        else
                        {
                            if (result.indexOf('No Record') > 0)
                            {
                                endData = 1;
                            }
                            else
                            {
                                $("#page").val(parseInt($("#page").val()) + 1); 
                                $("#load-product-list").append(result);
                                //enableDragg();
                            }
                            // $("#loading").hide();
                            hideAjxLoadingDiv();
                        }
                        
                    }
                });
            };
            function showAjxLoadingDiv(target)
            {
                $("#loading-div-background").show();
            }
            function hideAjxLoadingDiv()
            {
                $("#loading-div-background").hide();
            };

        $(function () {
            $(window).scroll(function() {

                var offset = ($(document).height() - $(window).height() )-2200;
                  console.log("window scrollTop :"+ $(window).scrollTop() + ",document height :" + $(document).height() + ", window height"+ offset);
                if($(window).scrollTop() >= offset) {
                   
                     // ajax call get data from server and append to the div
                    if (loading == 0 && endData == 0){
                        console.log("loading");
                        loadProductData(1);
                    }
                }
                if($(window).scrollTop()  >= $(document).height() - $(window).height()-300)  {
                    showAjxLoadingDiv();
                }
            });
                
            });
             $("#load-more>.btn-st-silver").click(function(){
              
               if (loading == 0 && endData == 0)
                {
                    loadProductData(1);
                    showAjxLoadingDiv();
                }
            });

</script>
<!-- <script src="/assets/js/jquery.fullscreen-popup.js"></script> -->
<script>
    $(function() {
        $("#pop-menu").fullScreenPopup({
            bgColor: '#fff'
        });
        $("#refine-search-popup").fullScreenPopup({
            bgColor: '#fff'
        });
        $("#sort-item-popup").fullScreenPopup({
            bgColor: '#fff'
        });
    });

</script>
<script src="/assets/js/jquery.fullscreen-popup.js"></script>
