    <div class="myModal" id="myModalContainer"></div>
    <div id="myModalTemplate"><div class="reveal-modal type_success" data-reveal>
			<div class="header my_header">
				<div class="my_close my_wrap_close">
				<a class="close-reveal-modal x_close type_close"><span>X</span></a>
				</div>
			</div>
			<div class="icon">
					<div class="ge_icon my_icon">

					</div>
				</div>
			<div class="my_body">
				<div class="wrap_body">
					<h4 class="my_title text-center">Removed</h4>
					<p class="sub_title text-center"></p>
					<div class="paragraph text-center"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod</p>
					</div>
				
				</div>
				<div class="under_area" style="margin-top:40px;">
					<div class="remember">
		                <input type="checkbox" class="receive_alert_bx" name="receive">
		                <label class="receive_alert_bx_lbl">
		                    <span class="fa-stack">
		                        <i class="fa fa-square-o fa-stack-1x"></i>
		                        <i class="fa fa-check-square fa-stack-1x"></i>
		                    </span>
		                    I would like to receive the latest fashion news
		                </label>   		                          
		          	</div>
                    <div style="width:100%; clear:both"></div> 
		          	<div class="group_btn">
						<div class="my_cancel my_visibility"><a href="javascript:void(0)">Cancel</a></div>
						<div class="my_btn"><a href="javascript:void(0)"><button class="my_btn_ok my_btn_type">OK</button></a></div>
					</div>
				</div>
				
			</div>
		</div>
	</div>

