<script src="<?php echo $this->basePath() ?>/showhidepassword/hideShowPassword.min.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/showhidepassword/css/example.wink.css">

<style type="text/css">
#btnNextStep { margin-top: 30px; width: 530px; }
#myForm lable { line-height: 50px; width: 100%; }
</style>

<div class="container topnavi">
    <div class="brand-box">
        <div class="lost-password-box">
            <div class="choose-box">
                <h1>Lost Your Password?</h1>
                <form name="myForm" id="myForm" method="POST" class="form">
                    <lable>NEW PASSWORD*</lable> <br>
                    <input type="password" class="input_box" data-msg-required="Please enter new password" maxlength="100" name="password" id="password">
                    <br>

                    <lable>RE-ENTER YOUR NEW PASSWORD*</lable> <br>
                    <input type="password" class="input_box" data-msg-required="Please enter confirm password" maxlength="100" name="repassword" id="repassword">
                    <br>

                    <input type="hidden" name="email" id="email" value="<?php echo $this->encryptemail; ?>" />

                    <input type="submit" class="confirm" id="btnNextStep" value="Confirm">
                </form>
            </div><!--choose-box -->
        </div>
    </div><!--brand-box -->

    <div class="clr"></div>
</div><!--container-->

<script type="text/javascript">
$(function() {
    //Plugin Hide/Show Password
    $('#password').hidePassword(true); 
    $('#repassword').hidePassword(true); 

    //Script close popup
    $(document).on('opened.fndtn.reveal', '[data-reveal]', function () {
        $("button.my_btn_ok").click(function(){
            $('a.close-reveal-modal').trigger('click');
        });
    });

    $("#btnNextStep").on("click", function(e) {
        var newPass = $.trim($("#password").val());
        var confirmPass = $.trim($("#repassword").val());
        //Password validation
        var upperCase= new RegExp('[A-Z]');
        var lowerCase= new RegExp('[a-z]');
        var numbers = new RegExp('[0-9]');
        if( !(newPass.length >= 8 ) || !newPass.match(upperCase) || !newPass.match(lowerCase) || !newPass.match(numbers))
        {
            myalert('alertPassNotValid','type_missing','Oops', 'Password shouldn\'t be less than 8 characters. It must contain a mixture of upper and lower case letters, and at least one number.','');
        } else if (confirmPass == ""){
            myalert('alertConfirmPassNull','type_missing','Oops', 'Seems like you forgot to tell us confirm password.','');
        } else if (newPass != confirmPass) {
            myalert('alertPassAndConfirmNotSame','type_missing','Oops', 'Please enter confirm password same as password.','');
        } else {
            return true;
        }
        return false;
    });
});
</script>