
	<div class="portfolio-item thumbnail" style="width:100%">
		<div style="width:100%; background-color:#e1e1e1; text-align:center; padding-top:15px">
		
			<div class="row center">
				<div class="col-md-12">
					<h2 class="short"><strong class="inverted">JOIN</strong> Find Your Stitch</h2>
				</div>
			</div>	
			
		</div>
	</div>
	
<style>
<!--
.progressBar{}
.progressBar td{text-align:center}
-->
</style>

<table  width="50%" class="progressBar" align="center">
  <tr>
    <td><span class="badge badge-info">&nbsp;</span></td>
    <td width="15%"><hr /></td>
    <td><span class="badge">&nbsp;</span></td>
    <td width="15%"><hr /></td>
    <td><span class="badge">&nbsp;</span></td>
    <td width="15%"><hr /></td>
    <td><span class="badge">&nbsp;</span></td>
    <td width="15%"><hr /></td>
    <td><span class="badge">&nbsp;</span></td>
    <td width="15%"><hr /></td>
    <td><span class="badge">&nbsp;</span></td>
  </tr>
  <tr>
    <td>Style</td>
    <td>&nbsp;</td>
    <td>You</td>
    <td>&nbsp;</td>
    <td>Size</td>
    <td>&nbsp;</td>
    <td>Brands</td>
    <td>&nbsp;</td>
    <td>Price</td>
    <td>&nbsp;</td>
    <td nowrap="nowrap">Sign Up</td>
  </tr>  
</table>
	
	
<br /><br /><br />						
		
	<h2>What's your <strong>STYLE</strong></h2>
	
	<div class="row">
	
		<div class="col-md-6">
		
			<div class="portfolio-item img-thumbnail">
				<div align="center" style="padding-top:15px; margin-bottom:15px"> 
					<h4 style="margin-bottom: 0px"<strong>Work</strong></h4> 
					Choose one or many
				</div> 
				<ul class="portfolio-list sort-destination" data-sort-id="portfolio" >
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					
		
				</ul>		
			</div>

		</div>
		
		
		
		
		<div class="col-md-6">
		
			<div class="portfolio-item img-thumbnail">
				<div align="center" style="padding-top:15px; margin-bottom:15px"> 
					<h4 style="margin-bottom: 0px"<strong>Night Out</strong></h4> 
					Choose one or many
				</div> 
				<ul class="portfolio-list sort-destination" data-sort-id="portfolio" >
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					
		
				</ul>		
			</div>

		</div>
		
		
	</div>					
					
	


	
	<br /><br /><br />
	
	
	
	
	
		
	<div class="row">
	
		<div class="col-md-6">
		
			<div class="portfolio-item img-thumbnail">
				<div align="center" style="padding-top:15px; margin-bottom:15px"> 
					<h4 style="margin-bottom: 0px"<strong>Casual</strong></h4> 
					Choose one or many
				</div> 
				<ul class="portfolio-list sort-destination" data-sort-id="portfolio" >
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					
		
				</ul>		
			</div>

		</div>
		
		
		
		
		<div class="col-md-6">
		
			<div class="portfolio-item img-thumbnail">
				<div align="center" style="padding-top:15px; margin-bottom:15px"> 
					<h4 style="margin-bottom: 0px"<strong>What would you never wear?</strong></h4> 
					Choose one or many
				</div> 
				<ul class="portfolio-list sort-destination" data-sort-id="portfolio" >
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
		
					<li class="col-md-3 isotope-item brands">
						<div class="portfolio-item img-thumbnail">
							<a href="#" class="thumb-info">
								<img alt="" class="img-responsive" src="img/projects/project-1.jpg" style="height:130px">
								<span class="thumb-info-action">
									<span title="Universal" href="#" class="thumb-info-action-icon"><i class="icon icon-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					
		
				</ul>		
			</div>

		</div>
		
		
	</div>					
					
	
<br /><br />
<div class="col-md-12" align="center">
	<input class="btn btn-primary btn-lg" type="button" data-loading-text="Loading..." value="Next Step">
</div>
<br /><br /><br /><br />