<?php 

	   echo $this->headLink()
     // ->appendStylesheet($this->basePath() . '/vendor/bootstrap/bootstrap-combined.min.css')
     ->appendStylesheet($this->basePath() . '/vendor/bootstrap/tabcordion-demo.css')
     ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
     ->appendStylesheet($this->basePath() . '/fancybox/source/jquery.fancybox.css')
     ->appendStylesheet($this->basePath() . '/css/jquery.datetimepicker.css')
     ->appendStylesheet($this->basePath() . '/css/style.css');
     echo $this->headScript()->offsetSetFile(100, $this->basePath().'/fancybox/source/jquery.fancybox.js')
                               ->appendFile($this->basePath().'/js/jquery.datetimepicker.js')
                              
     ;
 ?>
<style type="text/css">
	.btn{
		  display: inline-block;
	  padding: 6px 12px;
	  margin-bottom: 0;
	  font-size: 14px;
	  font-weight: 400;
	  line-height: 1.42857143;
	  text-align: center;
	  white-space: nowrap;
	  vertical-align: middle;
	  -ms-touch-action: manipulation;
	  touch-action: manipulation;
	  cursor: pointer;
	  -webkit-user-select: none;
	  -moz-user-select: none;
	  -ms-user-select: none;
	  user-select: none;
	  background-image: none;
	  border: 1px solid transparent;
	  border-radius: 4px;
	}
	table td {
		padding-right: 0 !important;
	}
	.btn-add{
		margin:10px 0;
		margin-right: 10px;
	}
  .logo{
    /*margin-right: 53px;*/
    width: 20%;
    text-align: center;
    margin-left: 0;
  }
  .community a{
    color:#fff;
    text-decoration: none;
  }
  .right_block .get_style img {
      margin-right: 6px !important;
      margin-bottom: 2px !important;
  }
</style>
 <script src="<?php echo $this->basePath(); ?>/vendor/bootstrap/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/vendor/bootstrap/tabcordion.js"></script>
<div class="container" style="margin-top: 100px; ">
<div class="tabcordion tabs-left tabbable">
  <ul class="nav nav-tabs">
  <?php 
  		$i = 0;
      $found = false;
      if(in_array($this->tabactive,$this->listBucketID)) $found=true;

      $active='';
  		foreach ($aStyles as $key => $value) {
        if($found == true) {
            if($this->tabactive == $value['BucketID']) {
              $active ='active';
            } else $active='';
        } else if($i == 0) $active = 'active'; else $active='';
        
       

  	?>
    <li class="<?php echo $active ?>" data-value="<?php echo $value['BucketID']; ?>">
      <a data-target="#<?php echo $value['BucketID']; ?>" data-toggle="tab" >
        <?php echo $key  ?>
      </a>
    </li>
    <?php $i++; } ?>

  </ul>
  <div class="tab-content">
  	<div class="form-group text-right"> <!-- Button trigger modal -->
  		<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-success btn-add">Add Definition</button>
  	</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Definition Info</h4>
      </div>
      <form method="POST" action="/bucket/add" class="form-horizontal" id="adminForm">
      <div class="modal-body">
        <div class="form-group">
          <label for="title">Definition Title</label>
          <input id="title" name="title" type="text" class="form-control" value="" placeholder="Definition Title">
        </div>
       
      </div>
      <div class="modal-footer">
        <a type="button" class="btn btn-default" data-dismiss="modal">Close</a>
        <a type="button" class="btn btn-primary save">Save changes</a>
      </div>
      <input name="bucketID" type="hidden" class="form-control" value="" id="bucketID">
         <input name="definitionID" type="hidden" class="form-control" value="" id="definitionID">
         <input name="tabActive" type="hidden" class="form-control" value="" id="tabActive">
      </form>
    </div>
  </div>
</div>
<!-- end modal -->
    
<div class="alertMsg">
<?php 
    echo $this->flashMessenger()->render('success', array(
        'alert',
        'alert-success'
    ));
    echo $this->flashMessenger()->render('error', array(
        'alert',
        'alert-danger'
    ));
 ?>
 </div>
    <?php 

  		$count = 0;
      $active ='';
  		foreach ($aStyles as $key1 => $value1) {
         if($found == true) {
            if($this->tabactive == $value1['BucketID']) {
              $active ='active';
            } else $active='';
        } else if($count == 0) $active = 'active'; else $active='';
  	?>
    <div id="<?php echo $value1['BucketID']; ?>" class="tab-pane <?php echo $active; ?>">
   		<table class="table table-hover">
   			<tbody>
	   			<?php
          foreach ($listDefinition as $key2 => $value2) {
             
            if($value1['BucketID']== $value2['bucketID'] ){
	   			?>
	   			<tr>
	   				<td><?php echo $value2['title'] ?></td>
	   				<td style="width:5%"><button data-value="<?php echo $value2['id'] ?>" type="button" class="btn btn-primary edit">Edit</button></td>
	   				<td style="width:5%"><a data-id="<?php echo $value2['id'] ?>" href="javascript:void(0)" class="btn btn-danger delete">Delete</a></td>
            <td style="width:5%"><a href="/bucket/edit-bucket-attribute?bdid=<?php echo $value2['id'].'&tabactive='.$value1['BucketID'] ?>" type="button" class="btn btn-danger update-attr">Update Atribute</button></td>
	   			</tr>
	   			<?php } }?>
   			</tbody>
   		</table>
    </div>
    <?php  $count++;} ?>
  </div>
</div>
</div>
<script type="text/javascript">
  $('.delete').on('click', function () {
      var objThisRef = this;
      var id= $(this).data('id'); 
      myalert(
        'moveToBoughtAlert1', 'type_remove','Are you sure?','This definition will be removed.',null,null,
        function(){
          window.location.href="/bucket/delete/"+id;
        });                         
                    
  });

function getValueActiveTab(){
  $("#tabActive").val($(".tabcordion ul li.active").data('value'));
}
 var action;
  $(".btn-add").click(function(){
    action ="add";
    getValueActiveTab();
  });


  $(".save").click(function(){
      if( $("input[name=title]").val().trim() == '' )
      {
        alert("Please enter title of definition");
        return false;
      }
      var bucketID = $(".tabcordion ul li.active").data('value');
   
      $("#bucketID").val(bucketID);

      if(action == 'edit')  {
         var linkSubmit = $("#adminForm").attr('action').replace(/add/gi, "edit");
         submitFormAdmin(linkSubmit);
      }

      $("#adminForm").submit();
  });
  $(".edit").click(function(){
    getValueActiveTab();
    action ='edit';
      $('#myModal').modal('show');
        $("#title").val($(this).parents('tr').children('td:eq(0)').text()); 
       
        $("#definitionID").val($(this).data('value'));
  });
function submitFormAdmin(url) {
    if (url != "") {
        $("#adminForm").attr('action', url);
    }
    $("#adminForm").submit();
}

</script>
<script type="text/javascript">
    window.setTimeout(function() {
    $(".alertMsg .alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 3000);
</script>