<?php
    $outfitsData = $this->outfits;
?>
<!--<link rel="stylesheet" type="text/css" href="/vendor/bootstrap/bootstrap-select/bootstrap-select.css">-->
<!--<link href="/css/edit.css" media="screen" rel="stylesheet" type="text/css">-->
<!--<link rel="stylesheet/less" type="text/css" href="/css/bootstrap-progressbar-3.0.0.less">
<link rel="stylesheet" type="text/css" href="/css/bootstrap-progressbar-3.0.0.css">-->
<!-- <link type="text/css"  href="<?php echo $this->basePath(); ?>/myalert/css/foundation.css"   rel="stylesheet" /> -->
<link type="text/css"  href="<?php echo $this->basePath(); ?>/css/onlymodal.css"   rel="stylesheet" />
<link type="text/css"  href="<?php echo $this->basePath(); ?>/css/showfeeddetail.css"   rel="stylesheet" />
<script src="<?php echo $this->basePath(); ?>/vendor/bootstrap/bootstrap-select/bootstrap-select.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/vendor/jqueryui/development-bundle/themes/base/jquery.ui.all.css">

<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/fa/css/build.css">
<!--<link rel="stylesheet" href="/vendor/jqueryui/custom.css">-->
<script src="<?php echo $this->basePath(); ?>/vendor/jqueryui/development-bundle/ui/jquery.ui.slider.js"></script>

<script src="<?php echo $this->basePath(); ?>/simpleexpand/simple-expand.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/templates/mobile/js/bootstrap.min.js"></script>

<style> 
    .productsBox .overlay{margin-left:70px; top:90px; }
    .productsBox .overlay .plus{background-image:none}
    .productsBox .overlay .minus{background-image:none}

    ul.scrollheight { height: 300px;overflow-y: auto;}
    .activebrand{background-color: #CCCCCC;}
    .activecolor{border:2px solid black; background-image: url("/img/tick2.png"); background-size: 20px 15px; 
    background-repeat: no-repeat; 
    background-position: center center;} 
    .activedeal {background:#e06;text-decoration:none;}

    .form-control{height: 34px; padding:2px 2px 2px 6px; font-style:italic; font-size: 11px;}

    section.toggle {margin-top:0px}
    section.toggle input {
        height: auto;
        margin: 0;
        opacity: 1;
        position: static;
        width: auto;
    }
    section.toggle label { border:none; color: #000; padding: 3px 20px 3px 10px }
    section.toggle.active {
        /*background-color: #fbfcfb;*/
        border-color: #fbfcfb;
    }
    section.toggle.active > label {
        background: none repeat scroll 0 0 #F4F4F4;
        border-color: #CCCCCC;
    }
    section.toggle .toggle-content{
        white-space:nowrap;
    }

    section.toggle .toggle-content .aciTree label{
        border: none;
        background: none;
        border-style: none;
        border-left-style: none;
        border-right-style: none;
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 100%;
        font: inherit;
        vertical-align: baseline;
    }
    section.toggle .toggle-content .aciTree label:before{
        border: none;
        background: none;
        border-style: none;
        border-left-style: none;
        border-right-style: none;
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 100%;
        font: inherit;
        vertical-align: baseline;
    }
</style>
<style>
    .price-box {
        background: none repeat scroll 0 0 #E9E9E9;
        margin: 20px auto 0 7px;
        width: 200px;
    }
    .form-pricing {
        background: none repeat scroll 0 0 #FFFFFF;
        border-radius: 4px 4px 4px 4px;
        padding: 5px;
    }
    .price-slider {
        margin-bottom: 30px;
    }
    .col-sm-padding {
        padding: 0;
    }

    .ui-corner-all {
        border-radius: 4px 4px 4px 4px;
    }
    .ui-widget-content {
        background: none repeat scroll 0 0 #DCF0F0;
        border: 1px solid #AAAAAA;
        color: #222222;
        height: 8px;
        margin-top: 0;
    }
    .ui-slider .ui-slider-handle {
        cursor: pointer;
    }
    .ui-slider-horizontal .ui-slider-handle {
        margin-left: -0.5em;
    }
    .ui-slider-horizontal .ui-slider-handle {
        top: -0.9em;
    }
    .ui-slider .ui-slider-handle {
        color: #FFFFFF;
        cursor: default;
        font-size: 15px;
        height: 2em;
        line-height: 30px;
        margin: 0 -30px auto !important;
        position: absolute;
        text-align: center;
        text-decoration: none;
        width: 3.4em;
        z-index: 2;
    }
    .ui-slider a, .ui-slider a:focus {
        cursor: pointer;
        outline: medium none;
    }
    .ui-state-default, .ui-widget-content .ui-state-default {
        /*background: none repeat scroll 0 0 #254F73 !important;*/
        /*border: 1px solid #254F73 !important;*/
        box-shadow: none;
        height: 13px;
        margin: 10px -5px auto !important;
        width: 13px;
    }
    .ui-corner-all {
        border-radius: 4px 4px 4px 4px;
    }
    .ui-state-default, .ui-widget-content .ui-state-default label {
        color: #FFFFFF !important;
    }
    .ui-slider-handle.ui-state-default.ui-corner-all > label {
        color: #5E5E5E !important;
        left: -28px;
        position: absolute;
        top: -24px;
    }
    #slider > a:nth-child(even) > label:first-child {
        left: -10px;
        width: 35px;
    }
    #slider2 > a > label:first-child {
        left: -22px;
        width: 40px;
    }
    label {
        margin-bottom: 7px;
    }
    .price-slider span {
        color: #7F8C8D;
        display: inline-block;
        font-size: 13px;
        font-weight: 200;
    }
    .price-min-max {
        background-image: url("/img/step_bars.jpg");
        height: 8px;
        margin-top: -24px;
        position: relative;
        display: none;
    }
    .col-sm-padding {
        padding: 0;
    }
    .ui-autocomplete { height: auto !important; }
    .ui-menu .ui-menu-item a{ font-size: 13px !important; }
    .sharepoup{
        top: -110px;
        cursor: pointer;
    }
    .outfitcheckbox{
        cursor: pointer;
    }
    
    
    
    
    #loading-div-background 
    {
        display:none;
        position:fixed;
        top:0;
        left:0;
        background:black;
        width:100%;
        height:100%;
    	opacity: 0.6;
    	z-index: 1000;
     }
    #loading-div
    {
         width: 300px;
         height: 150px;
         text-align:center;
         position:absolute; 
         left: 50%;
         top: 50%;
         margin-left:-150px;
         margin-top: -100px;
    	opacity: 1;
     }
     
        .toggle.expander.expanded {
            padding-left: 22px;
            background-position: left center;
            background-repeat: no-repeat;
            background-image: url('/img/down.png');
        }
    
        .toggle.expander.collapsed {
            padding-left: 22px;
            background-position: left center;
            background-repeat: no-repeat;
            background-image: url('/img/right.png');
        } 
        .cat h5{
            cursor: pointer;
        }
        button.deal{
            -webkit-box-shadow: none;
            -moz-box-shadow: none;
            box-shadow: none;
        }
        #tree .aciTreeText{
            font-family: 'Roboto' !important;
        }

        /* style for checkbox */

        .brandslist .checkbox label::before{
            border-radius: 0;
            border-color: #acaeb5;
        }
        .brandslist .checkbox label::after{
            background-color: #acaeb5;
        }
        .brandslist .checkbox input[type="checkbox"]:checked + label::after{
            content: ' ';
        }
        .brandslist .checkbox label::before{
            width: 14px;
            height: 14px;
        }
        .brandslist .checkbox label::after {
            width: 12px;
            height: 14px;
        }
        #slider > a > label {
            width:50px;
        }
        .round-color li{
            font-size: 13px;
            font-family: 'Roboto';
        }
        .round-color .fa-check{
            color:#fff;
        }
        .round-color .fa-check:before {
            margin-left: 3px;
        }
        .deals_box label{
            margin-bottom: 0;
        }
        .deals_box .fa-circle-o:before {
            font-size: 17px;
        }
        .left-box-check input[type="radio"]:checked + label .fa-circle,input[type="checkbox"]:checked + label .fa-square {
            color: #fff;
        }
        .continueFixAtBottom{
            padding-top: 35px;
        }
        .image-cross{
            padding: 0;
        }
        .btn-con1{
            margin-top: 0;
        }


     .box-block{
        border: 0;
        text-align: center;
     }
     .box-block a{
        font-size: 30px;
     }
     .pad{
        padding-top: 90px;
        margin-left: 35px;
     }     
     .myfa{
     
      position: absolute;
      right: 8px;
      top: 8px;
      font-size: 23px;
     }
     .myfa-red{
        color: red;
     }
     .myfa-green{
        color:green;
     }
     .myfa-orange{
        color:orange;
     }
     .main_big1_product_img_box{
        position: relative;
     }
</style>
<!--============================================================contener-01=============-->
<script type="text/javascript">var feedsids = {};</script>
<!--============================================================contener-01 end =============-->

    <div class="container" style="background-color:#F6F6F4;">
        <div id="article-block" style="display: block;">
            <div class="left-link-box" id="leftLinkBoxID">


                <div class="refined">
                    <h1>REFINED BY</h1>
                    
                          <div class="cat page_left_menu ">
                                    <h5 class="expander toggle collapsed"> INFO ADDED</h5>
                                    <div class="content">
                                        <ul>
                                        <li><input type="radio" name="info-added" id="info-added1" checked onclick="chooseInfoAdded(this, '');" />
                                            <label for="info-added1"  class="outfit">
                                                <span class="fa-stack infoadded-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> All Items
                                            </label>
                                        </li>
                                        <li><input type="radio" name="info-added" id="info-added2" onclick="chooseInfoAdded(this, 'yes');" />
                                            <label for="info-added2"  class="outfit">
                                                <span class="fa-stack infoadded-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> Yes
                                            </label>
                                        </li>
                                        <li><input type="radio" name="info-added" id="info-added3" onclick="chooseInfoAdded(this, 'no');" />
                                            <label for="info-added3"  class="outfit">
                                                <span class="fa-stack infoadded-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> No
                                            </label>
                                        </li>
                                    </ul>
                                    </div>
                                    

                                </div>                    
                    
                    
                    
                    <div class="cat page_left_menu ">
                        <section class="toggle active">
                            <h5 class="expander toggle collapsed"> categories</h5>
                            <div class="content">
                                <div id="catBtnDiv" class="toggle-content">
                                    <div id="tree" class="aciTree"></div>
                                </div>
                            </div>
                        </section>
                    </div>

                                <?php if (!empty($this->allBrands) || !empty($this->allTopBrands)) { ?>

                                    <div class="cat page_left_menu brandslist">
                                        <h5 class="expander toggle collapsed"> BRANDS</h5>
                                        <div class="content">
                                            <input type="text" class="form-control form-control-01 brand" name="brandautocomplete" id="brandautocomplete" placeholder="Search more brands">
                                        <ul>
                                            <?php if (!empty($this->allTopBrands)) { ?>
                                                <?php foreach ($this->allTopBrands as $brand) { ?>
                                                    <li>

                                                  <!--   <input type="checkbox" name="option" id="<?php echo $brand['id']; ?>" class="brandSelection" value="<?php echo $brand['id']; ?>" />
                                                        <label for="<?php echo $brand['id']; ?>">
                                                            <span class="fa-stack">
                                                                <i class="fa fa-square-o fa-stack-1x"></i>
                                                                <i class="fa fa-square fa-stack-1x"></i>
                                                            </span>
                                                            <?php echo $brand['title']; ?>
                                                        </label> -->
                                                    </li>
                                                <?php } ?>
                                            <?php } ?>

                                            <?php if (!empty($this->allBrands)) { ?>
                                                <?php 
                                                $i = 1;
                                                foreach ($this->allBrands as $brand) { ?>
                                                    <li>
                                                    <div class="checkbox">
                                                    <input id="<?php echo $brand['id']; ?>" class="brandSelection styled" type="checkbox" name="option" value="<?php echo $brand['id']; ?>">
                                                    <label for="<?php echo $brand['id']; ?>">
                                                        <?php  echo $brand['title']; ?>
                                                    </label>
                                                </div>
                                     
                                                    <!-- <input type="checkbox" name="option" id="<?php echo $brand['id']; ?>" class="brandSelection" value="<?php echo $brand['id']; ?>" />
                                                        <label for="<?php echo $brand['id']; ?>">
                                                            <span class="fa-stack">
                                                                <i class="fa fa-square-o fa-stack-1x"></i>
                                                                <i class="fa fa-square fa-stack-1x"></i>
                                                            </span>
                                                            <?php echo $brand['title']; ?>
                                                        </label> -->
                                                    </li>
                                                <?php $i++; } ?>
                                            <?php } ?>
                                        </ul>
                                        </div>
                                        
                                    </div>

                                <?php } ?>

                                <div class="cat page_left_menu ">
                                    <h5 class="expander toggle collapsed">PRICE</h5>
                                    <div class="content">
                                         <div class="price-box">
                                        <form class="form-horizontal form-pricing" role="form">
                                            <div class="price-slider">
                                                <div class="col-sm-12 col-sm-padding">
                                                    <div id="slider" class="slider-01"></div>
                                                </div>
                                            </div>
                                            <div class="price-min-max">
                                                <div class="col-lg-6 col-sm-padding" style="text-align:left; margin-top:5px;color:#aaaaaa;">
                                                    <span>$0</span>
                                                </div>
                                                <div class="col-lg-6 col-sm-padding" style="text-align:right;margin-top:5px;color:#aaaaaa;">
                                                    <span><?php echo $this->maxRangePrice; ?></span>
                                                    <span class="currency"><?php echo $this->currency; ?></span>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    </div>
                                   
                                </div>

                                <?php if (!empty($this->allColors)) { ?>

                                    <div class="cat page_left_menu ">
                                        <h5 class="expander toggle collapsed">COLOR</h5>
										<div class="content">
                                         <ul>
                                            <li><input type="radio" name="check-color" id="check-color1" checked onclick="checknocolor('no');" />
                                                <label for="check-color1"  class="outfit">
                                                    <span class="fa-stack checkcolor-option-checkbox">
                                                        <i class="fa fa-circle-o fa-stack-1x"></i>
                                                        <i class="fa fa-circle fa-stack-1x"></i>
                                                    </span> All
                                                </label>
                                            </li>
                                            <li><input type="radio" name="check-color" id="check-color2" onclick="checknocolor('yes');" />
                                                <label for="check-color2"  class="outfit">
                                                    <span class="fa-stack checkcolor-option-checkbox">
                                                        <i class="fa fa-circle-o fa-stack-1x"></i>
                                                        <i class="fa fa-circle fa-stack-1x"></i>
                                                    </span> No color
                                                </label>
                                            </li>
                                        </ul>

                                        <ul class="round-color">
                                            <?php
                                            if (!empty($this->allColors)) {
                                                foreach ($this->allColors as $color) {
                                                    if($color['value'] == 'WHITE') { $bdrcolor = '#CCCCCC'; } else { $bdrcolor = $color['value']; }
                                                    ?>
                                                    <li class="fa btn-01 btn-coloer-01 colorselection" style="background-color:<?php echo $color['value']; ?>;border:solid 1px <?php echo $bdrcolor; ?>;" value="<?php echo $color['value']; ?>" title="<?php echo $color['value']; ?>"></li>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </ul>
                                        </div>
                                        
                                    </div>

                                <?php } ?>

                                <?php if (!empty($this->allStores) || !empty($this->allTopStores)) { ?>

                                    <div class="cat page_left_menu ">
                                        <h5 class="expander toggle collapsed">STORE</h5>
                                        <div class="content">
                                            <input type="text" class="form-control form-control-01 brand" id="storeautocomplete" name="storeautocomplete" placeholder="Search more stores">
                                        <ul>

                                            <?php if (!empty($this->allTopStores)) { ?>
                                                <?php foreach ($this->allTopStores as $store) { ?>
                                                    <li><input class="storeSelection" type="checkbox" name="option" id="<?php echo $store['title']; ?>"  value="<?php echo $store['id']; ?>" />
                                                        <label for="<?php echo $store['title']; ?>">
                                                            <span class="fa-stack">
                                                                <i class="fa fa-square-o fa-stack-1x"></i>
                                                                <i class="fa fa-square fa-stack-1x"></i>
                                                            </span>
                                                            <?php echo $store['title']; ?>
                                                        </label>
                                                    </li>
                                                <?php } ?>
                                            <?php } ?>

                                            <?php if (!empty($this->allStores)) { ?>
                                                <?php foreach ($this->allStores as $store) { ?>
                                                    <li><input class="storeSelection" type="checkbox" name="option" id="<?php echo $store['title']; ?>"  value="<?php echo $store['id']; ?>" />
                                                        <label for="<?php echo $store['title']; ?>">
                                                            <span class="fa-stack">
                                                                <i class="fa fa-square-o fa-stack-1x"></i>
                                                                <i class="fa fa-square fa-stack-1x"></i>
                                                            </span>
                                                            <?php echo $store['title']; ?>
                                                        </label>
                                                    </li>
                                                <?php } ?>
                                            <?php } ?>

                                        </ul>
                                        </div>
                                        
                                    </div>
                                <?php } ?>


                                <div class="cat page_left_menu deals_box">
                                    <h5 class="expander toggle collapsed">DEALS</h5>
                                    <div class="content">
                                        <ul>
                                        <li><input type="radio" name="option" id="deal1" onclick="chooseDeals(this, 'onsale');" />
                                            <label for="deal1"  class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> All Items on Sale
                                            </label>
                                        </li>
                                        <li><input type="radio" name="option" id="deal2" onclick="chooseDeals(this, 'todaynew');" />
                                            <label for="deal2"  class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> New Today
                                            </label>
                                        </li>
                                        <li><input type="radio" name="option" id="deal3" onclick="chooseDeals(this, 'newthisweek');" />
                                            <label for="deal3"  class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> New this week
                                            </label>
                                        </li>
                                        <li><input type="radio" name="option" id="deal4" onclick="chooseDeals(this, 'freeshipping');" />
                                            <label for="deal4" class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> Free Shipping
                                            </label>
                                        </li>
                                        <li><input type="radio" name="option" id="deal5" onclick="chooseDeals(this, 'specialoffer');" />
                                            <label for="deal5"  class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> Special Offer
                                            </label>
                                        </li>
                                        <li><input type="radio" name="option" id="deal6" onclick="chooseDeals(this, 'discountcode');" />
                                            <label for="deal6"  class="outfit">
                                                <span class="fa-stack sale-option-checkbox">
                                                    <i class="fa fa-circle-o fa-stack-1x"></i>
                                                    <i class="fa fa-circle fa-stack-1x"></i>
                                                </span> Discount
                                            </label>
                                        </li>
                                    </ul>
                                    
                          

                                    <div class="cat page_left_menu ">
                                        <div class="price-box">
                                            <form class="form-horizontal form-pricing" role="form">
                                                <div class="price-slider">
                                                    <div class="col-sm-12 col-sm-padding">
                                                        <div id="slider2" class="slider-02"></div>
                                                    </div>
                                                </div>
                                                <div class="price-min-max">
                                                    <div class="col-lg-6 col-sm-padding" style="text-align:left;margin-top:5px; color:#aaaaaa;">
                                                        <span>0%</span>
                                                    </div>
                                                    <div class="col-lg-6 col-sm-padding" style="text-align:right;margin-top:5px; color:#aaaaaa;">
                                                        <span>100%</span>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>

                                    
                                    </div>
                                    
                                    
                                    <div class="clr"></div>
                                    <button class="deal">CLEAR FILTER</button>
                                  <!--   <div class="clr"></div>
                                    <a href="/service?dv=article" class="clear">Clear filter</a> -->
                                </div>

                                <div class="clr"></div>
                            </div>
                    </div><!-- left_link_box-->



                    <div class="right-link-box">

                        <div class="clr"></div>
                        <div style="text-align:center;color:#254F73">
                        <h3 id="feedCount" style="background-color: rgb(255, 255, 255);margin: 0px;padding: 25px 0px; border-bottom:2px solid #F6F6F4">
                        <?php if (!empty($this->feedData)) echo number_format($this->feedCount)  ?> results was found</h3>
                        </div>
                        <div class="image-box bottomWorkingArea" id="productlisting">

                            <?php
                            foreach ($this->feedData as $prod) {

                                $page_url = $this->serverUrl() . '/service/feeddatadetail/' . $prod->feeddataid . '/' . rand();
                                $title = 'ELnove - ' . $prod->caption;
                                ?>
                                <div class="main_big1_product_box productsBox draggable-element">
                                    <!--<div class="portfolio-item img-thumbnail productsBox">-->

                                    <div class="main_big1_product_img_box">
                                        <img src="<?php echo ($prod->feedId==4?str_replace(array('/product/thumbnails/', 't.jpg'), array('/product/images/', '.jpg'), $prod->feedimageurl):$prod->feedimageurl) ?>" id="img">
                                        
                                        <?php if($prod->icon == 'red') { ?>
                                        <i class="myfa myfa-red fa fa-lightbulb-o"></i>
                                        <?php } else if($prod->icon == 'green'){ ?>
                                         <i class="myfa myfa-green fa fa-lightbulb-o"></i>
                                        <?php } else {?>
                                        <i class="myfa myfa-orange fa fa-lightbulb-o"></i>
                                        <?php } ?>
                                    </div>
                                    <div class="main_big1_product_tag_box">
                                    </div>
                                   <div class="box-block">
                                            <div class="pad">
                                            <div>
                                                <a target="_blank" href="/feed/edit-article?pid=<?php echo $prod->feeddataid;?>" class="gotourl">Edit</a>
                                            </div>
                                     
                                         <!--        <a href="#" class="gotourl">Remove</a> -->
                                            </div>
                    
                                        </div>
                                    </div>  
                            <?php } ?>

                        </div>

                        <div id='loading' style="text-align:center;padding-top:50px;padding-bottom:50px;display:none;" class="col-md-10">
                            <!-- <img src="<?php echo $this->basePath('img/bx_loader.gif') ?>"/> -->
                        </div>
                        <div id='ajx_loader_div' style="display:none;z-index:999999;">
                            <img src="<?php echo $this->basePath('img/bx_loader.gif') ?>" id="ajx_loader_image" />
                        </div>

                        <div class="clr"></div>
                    </div>
                </div>
                <div class="clr"></div>
            </div><!--container-->
        </div>

        <br /><br /><br /><br />

        <script src="<?php echo $this->basePath('vendor/jqModal/jqModal.js') ?>"></script>

        <form id="productFilterDetail" name="productFilterDetail">
            <input type="hidden" id="minamount" class="form-control" name="minamount">
            <input type="hidden" id="maxamount" class="form-control" name="maxamount">
            <input type="hidden" id="minduration" class="form-control" name="minduration">
            <input type="hidden" id="maxduration" class="form-control" name="maxduration">
            <input type="hidden" id="catids" class="form-control" name="catids">
            <input type="hidden" id="brands" class="form-control" name="brands">
            <input type="hidden" id="colors" class="form-control" name="colors">
            <input type="hidden" id="stores" class="form-control" name="stores">
            <input type="hidden" id="deals" class="form-control" name="deals">
            <input type="hidden" id="onsale" class="form-control" name="onsale">
            <input type="hidden" id="todaynew" class="form-control" name="todaynew">
            <input type="hidden" id="newthisweek" class="form-control" name="newthisweek">
            <input type="hidden" id="freeshipping" class="form-control" name="freeshipping">
            <input type="hidden" id="specialoffer" class="form-control" name="specialoffer">
            <input type="hidden" id="discountcode" class="form-control" name="discountcode">
            <input type="hidden" id="page" class="form-control" name="page" value="2">
            <input type="hidden" id="limit" class="form-control" name="limit" value="<?php echo PRODUCTS_PER_PAGE;?>">
            <input type="hidden" id="infoadded" class="form-control" name="infoadded" value="">
            <input type="hidden" id="checknocolor" class="form-control" name="checknocolor" value="">

        </form>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display:none">
  <div class="modal-dialog" role="document">
    <div class="modal-content grey_bg">
      <div class="modal-body append">
        
      </div>
  
    </div>
  </div>
</div>

<div id="loading-div-background" style="display: none;">
    <div id="loading-div" class="ui-corner-all">
      <img style="margin-top:20px; height: 50px" src="/img/loading7_light_blue.gif" alt="Loading..">
      <h2 style="color:gray;font-weight:normal;">Please wait....</h2>
     </div>
</div>

        <!--=================script-by-designer=============-->
        <script src="<?php echo $this->basePath(); ?>/js/showfeeddetail.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/clearfilter.js"></script>
        
        <script type="text/javascript">
        //$(document).foundation();
            $('.expander').simpleexpand();
            $(document).ready(function () {

                $(document).on('click', '.overlay-01', function () {
                    reditectToBuyurl(this);
                });
                $('.overlay-01').click(function () {
                    reditectToBuyurl(this);
                });
                function reditectToBuyurl(obj) {
                    $("#contener-01").css("display", "block");
                    $('.progress-bar').progressbar();
                    $('#productbuyurl').attr('href', $(obj).attr('href'));
                    setTimeout(function () {
                        jQuery('#productbuyurl')[0].click();
                        $("#contener-01").css("display", "none");
                    }, 3000);
                }
            });

        </script>
        <script type="text/javascript">
            $(function () {
                $(".slider-01").click(function () {
                    // remove classes from all
                    $(".price-form-01").css("display", "block");
                    // add class to the one we clicked
                });
            });
        </script>
        <script type="text/javascript">
            $(function () {
                $(".price-01").click(function () {
                    // remove classes from all
                    $(".price-form-01").css("display", "none");
                    // add class to the one we clicked
                });
            });
        </script>
        <script type="text/javascript">
            $(function () {
                $(".slider-02").click(function () {
                    // remove classes from all
                    $(".price-form-02").css("display", "block");
                    // add class to the one we clicked
                });
            });
        </script>
        <script type="text/javascript">
            $(function () {
                $(".price-02").click(function () {
                    // remove classes from all
                    $(".price-form-02").css("display", "none");
                    // add class to the one we clicked
                });
            });
        </script>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#slider").slider({
                    range: true,
                    min: 0,
                    max: <?php echo $this->maxRangePrice; ?>,
                    values: [0, <?php echo $this->maxRangePrice; ?>],
                    slide: function (event, ui) {
                        update(1, ui.values); //changed
                    },
                    stop: function (event, ui) {
                        loadProductData();
                    }
                });
                $("#slider2").slider({
                    range: true,
                    min: 0,
                    max: 100,
                    values: [0,100],
                    step: 10,
                    slide: function (event, ui) {
                        update(2, ui.values); //changed
                    },
                    stop: function (event, ui) {
                        loadProductData();
                    }
                });
                //Added, set initial value.
                $("#minamount").val($("#slider").slider("option", "min"));
                $("#maxamount").val($("#slider").slider("option", "max"));

 
                $("#minduration").val($("#slider2").slider("option", "min"));
                $("#maxduration").val($("#slider2").slider("option", "max"));

                //$("#duration").val($("#slider").slider("option", "min"));
                //$("#amount-label").text(0);
                //$("#duration-label").text(0);
                update();
            });

            //changed. now with parameter
            function update(slider, val) {
                //changed. Now, directly take value from ui.value. if not set (initial, will use current value.)
                var $minamount = slider == 1 ? val[0] : $("#minamount").val();
                var $maxamount = slider == 1 ? val[1] : $("#maxamount").val();
                //var $duration = slider == 2 ? val : $("#duration").val();

                var minduration = slider == 2 ? val[0] : $("#minduration").val();
                var maxduration = slider == 2 ? val[1] : $("#maxduration").val();

                /* commented
                 $amount = $( "#slider" ).slider( "value" );
                 $duration = $( "#slider2" ).slider( "value" );
                 */

                //$total = "$" + ($amount * $duration);
                $("#minamount").val($minamount);
                $("#maxamount").val($maxamount);
                //$("#amount-label").text($amount);
                
                /*my close*/
                    // $("#duration").val($duration);
                    // $("#duration-label").text($duration);
                /*end*/

                $("#minduration").val(minduration);
                $("#maxduration").val(maxduration);

                // $("#total").val($total);
                //$("#total-label").text($total);
                sliderLinks = $('#slider a');

                $(sliderLinks[0]).html('<label>' + $minamount + '<span class="currency">' + $this->currency + '</span></label>');
              if($maxamount >= <?php echo $this->maxRangePrice;?>) {
                $(sliderLinks[1]).html('<label ><?php echo $this->maxRangePrice;?><span class="currency"><?php echo $this->currency ?></span>+' + ' </label>');
                $("#maxamount").val(<?php echo $this->actualMaxRangePrice?>);
              } else {
                $(sliderLinks[1]).html('<label >' + $maxamount + ' <span class="currency">' + $this->currency + '</span></label>');
              }
             
              

                sliderLinks = $('#slider2 a');
                $(sliderLinks[0]).html('<label>' + minduration +"<span>%</span>" + ' </label>');
                $(sliderLinks[1]).html('<label >' + maxduration + "<span >%</span>" + ' </label>');
                //$('#slider2 a').html('<label style="margin-left:15px;">' + $duration + '%</label>');
            }
        </script>
        <script type="text/javascript">

            /*$(document).ready(function() {
             $(".overlay-02").css("display","none");
             
             $(".thumb-info").hover(function(){
             $(hover-one).css("display","block");
             },function(){
             $(hover-one).css("display","none");
             });
             });	*/

            $(document).ready(function () {
                $(document).on('mouseenter', '.thumb-info', function () {
                    $(this).find(".overlay-02").css("display", "block");
                }).on('mouseleave', '.thumb-info', function () {
                    $(this).find(".overlay-02").css("display", "none");
                });
            });

            $(document).ready(function () {
                $(document).on('click', '.aciTreeLi', function () {
                    var fontthis = this;
                    $(fontthis).siblings(".aciTreeLi").find(".aciTreeText").removeClass("font-bold");
                    $(fontthis).find(fontthis).addClass("font-bold");
                    //		$(fontthis).parents(".aciTreeText").addClass(".font-bold");
                });
            });
        </script>

        <!--=================script-by-designer end portfolio-single-project.html====================-->

        <script type="text/javascript">
            $(document).ready(function () {

                $("#idArticlesPerPageSelect").change(function () {
                    $("#ArticlesPerPageForm").submit()
                });

                $('.selectpicker').selectpicker({
                    //'selectedText': 'cat'
                    width: '120px'
                });

                var t = $('#dialog');

                $('#dialog').jqm({
                    trigger: 'div.productdialogs',
                    ajax: '@href', /* Extract ajax URL from the 'href' attribute of triggering element */
                    target: t,
                    modal: true, /* FORCE FOCUS */
                });

                $('input.jqmdX')
                        .hover(
                                function () {
                                    $(this).addClass('jqmdXFocus');
                                },
                                function () {
                                    $(this).removeClass('jqmdXFocus');
                                })
                        .focus(
                                function () {
                                    this.hideFocus = true;
                                    $(this).addClass('jqmdXFocus');
                                })
                        .blur(
                                function () {
                                    $(this).removeClass('jqmdXFocus');
                                });

                $('input.jqmdX')
                        .hover(
                                function () {
                                    $(this).addClass('jqmdXFocus');
                                },
                                function () {
                                    $(this).removeClass('jqmdXFocus');
                                })
                        .focus(
                                function () {
                                    this.hideFocus = true;
                                    $(this).addClass('jqmdXFocus');
                                })
                        .blur(
                                function () {
                                    $(this).removeClass('jqmdXFocus');
                                });

                $('#dialog').css('padding-bottom', '0px');

                $(".bottomWorkingArea .productsBox").on("click", function (e) {

                    if ($(this).find(".lock").length) {
                        $(this).find(".lock").removeClass('lock').addClass('open')
                    }
                    else {
                        $(this).find(".open").removeClass('open').addClass('lock')
                    }

                    return false;

                });

                $(".topWorkingArea .topBigBox,.topMediumBox,.topSmallBox").on("click", function (e) {

                    if ($(this).find(".open").length) {
                        $(this).find(".open").removeClass('open')
                        $(this).find(".plus").addClass('plusOpen')
                        $(this).find(".minus").addClass('minusOpen')
                    }
                    else {
                        $(this).find(".lock").addClass('open')
                        $(this).find(".plus").removeClass('plusOpen')
                        $(this).find(".minus").removeClass('minusOpen')
                    }
                    return false;
                });
            });
        </script>

        <script class="code" type="text/javascript">

            $(function () {

                // init the tree
                $('#tree').aciTree({
                    ajax: {
                        url: '/attributes/get-categories-json?ec=<?php echo  $this->excludeCats ?>&levels=3&id='
                    },
                    checkbox: true
                });

                $('#tree').on('acitree', function (event, api, item, eventName, options) {
                    switch (eventName) {
                        case 'checked':
                            //alert(item);
                            //alert('checked: ' + api.getId(item));
                            //break;
                        case 'unchecked':
                            getAllCheckedElements(event, api, item, eventName, options);
                            loadProductData();
                            break;
                        case 'init' :
                            getAllCheckedElements(event, api, item, eventName, options);
                            break;
                    }
                });

            });

            function getAllCheckedElements(event, api, item, eventName, options)
            {
                var checkedElements = $("#tree .aciTreeLi .aciTreeLeaf");
                checkedElementsArr = api.checkboxes(checkedElements, true);
                var catIdStr = '';
                checkedElementsArr.each(function (index, item) {
                    var $item = $(item);
                    catIdStr += api.getId($item) + ',';
                    //console.log(api.getId($item) + ": " + api.getLabel($item));
                });
                $("#catids").val(catIdStr);
            }

        </script>

        <script type="text/javascript">
            function formatThousands(n, dp) {
              var s = ''+(Math.floor(n)), d = n % 1, i = s.length, r = '';
              while ( (i -= 3) > 0 ) { r = ',' + s.substr(i, 3) + r; }
              return s.substr(0, i + 3) + r + (d ? '.' + Math.round(d * Math.pow(10,dp||2)) : '');
            }
            var loading = 0;
            var endData = 0;
            function loadProductData(isLazyLoading)
            {
                if (typeof isLazyLoading == 'undefined' || isLazyLoading == '')
                {
                    showAjxLoadingDiv($("#productlisting"));
                    $("#page").val(1);
                    endData = 0;
                }
                else {
                	showAjxLoadingDiv($("#productlisting"));
                    $("#loading").show();
                }
                loading = 1;
                var url = "/feed/getfeeds/" + Math.random();
                var filterData = $("#productFilterDetail").serialize();
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: filterData,
                    dataType: 'html',
                    success: function (result) {
                        loading = 0;
                        if (typeof isLazyLoading == 'undefined' || isLazyLoading == '')
                        {
                            $("#productlisting").html(result);
                            //var feedCount = number_format($("#feedCountAjax").val());
                            var feedCount = formatThousands($("#feedCountAjax").val());
                            $("#feedCount").html(feedCount +  ' results was found');

                            hideAjxLoadingDiv();
                            $("#page").val(2);
                            //enableDragg();
                        }
                        else
                        {
                            if (result.indexOf('No Record') > 0)
                            {
                                endData = 1;
                            }
                            else
                            {
                                $("#page").val(parseInt($("#page").val()) + 1); 
                                $("#productlisting").append(result);
                                //enableDragg();
                            }
                            $("#loading").hide();
                            hideAjxLoadingDiv();
                        }
                    }});
            }

            $(function () {


                $(".check_category").click(function () {
                    if ($(this).is(':checked') == true) {
                        var $infos = $(this).parent('.category');
                        $infos.find("input[type=checkbox]").prop("checked", true);
                    } else {
                        var $infos = $(this).parent('.category');
                        $infos.find("input[type=checkbox]").prop("checked", false);
                    }
                })

                $(".check_subcategory").click(function () {
                    if ($(this).is(':checked') == true) {
                        //alert('Hello');
                        var $infos = $(this).parents('.subcategory');
                        $infos.find("input[type=checkbox]").prop("checked", true);
                    } else {
                        alert('Hey');
                        var $infos = $(this).parents('.subcategory');
                        $infos.find("input[type=checkbox]").prop("checked", false);
                    }
                })

                $(".brandSelection").click(function () {
                    $(this).toggleClass('activebrand');
                    var brands = '';
                    var allSelectedBrands = $(".brandSelection");
                    $(allSelectedBrands).each(function () {
                        if ($(this).hasClass('activebrand')) {
                            brands += ($(this).attr('value')) + ',';
                        }
                    })
                    $("#brands").val(brands);
                    loadProductData();
                })

                $(".storeSelection").click(function () {
                    //alert('hello');
                    $(this).toggleClass('activebrand');
                    var stores = '';
                    var allSelectedStores = $(".storeSelection");
                    $(allSelectedStores).each(function () {
                        if ($(this).hasClass('activebrand')) {
                            stores += ($(this).attr('value')) + ',';
                        }
                    })
                    $("#stores").val(stores);
                    loadProductData();
                })


                var availableBrandTags = <?php echo $this->jsonBrands; ?>;
                $("#brandautocomplete").autocomplete({
                    source: availableBrandTags,
                    select: function (event, ui) {
                        $(".brandslist ul li input[value=" + ui.item.id + "]").addClass('activebrand').prop('checked',true);
                       
                        $("#brands").val($("#brands").val() + ui.item.id +',');
             
                        loadProductData();
                        return false;
                    }
                });

                var availableStoreTags = <?php echo $this->jsonStores; ?>;
                $("#storeautocomplete").autocomplete({
                    source: availableStoreTags,
                    select: function (event, ui) {
                        $("ul.storeSelection li[value=" + ui.item.id + "]").addClass('activebrand');
                        $("#stores").val($("#stores").val() + ui.item.id + ',');
                        loadProductData();
                        return false;
                    }
                });

                $(".colorselection").click(function () {
                    $(this).toggleClass('activecolor');
                    var colors = '';
                    var allSelectedColors = $(".colorselection.activecolor");
                    $(allSelectedColors).each(function () {
                        colors += ($(this).attr('value')) + ',';
                    })
                    $("#colors").val(colors);
                    loadProductData();
                });
            })


            function chooseDeals(currref, dealName)
            {
//                 $(currref).closest( "li" ).find()
//                 console.log(dealName)
//                 $('.sale-option-checkbox', currref).toggleClass('activedeal');
//                 if ($('.sale-option-checkbox', currref).hasClass('activedeal'))
//                 {
//                     $("#" + dealName).val(1);
//                 }
//                 else
//                 {
//                     $("#" + dealName).val('');
//                 }

         	   
                $('#onsale').val('');
                $('#todaynew').val('');
                $('#newthisweek').val('');
                $('#freeshipping').val('');
                $('#specialoffer').val('');
                $('#discountcode').val('');
                $('#'+dealName).val(1);
            	
                loadProductData();
            }

            function chooseInfoAdded(currref, val)
            {
                $("#infoadded").val(val);
    
               loadProductData();
            }

            function checknocolor(val)
            {
                $("#checknocolor").val(val);
               loadProductData();
            }

            $(document).ready(function () {

//             	var element = $('.left-link-box'),
//                 originalY = 121;
//                 var topMargin = 80;
//                 element.css('position', 'relative'); 

            	$('#leftLinkBoxID').hcSticky({stickTo:document, top:80, bottom:10});
            
                $(window).scroll(function (event) {
                   	 if( $('#article-block').css('display') == 'block' ) {
                       	 
                        if ($("#loading-div-background").css('display') == 'block')
                        {
                            var windowheight = $(window).height();
                            var scrolltop = $($("#productlisting")).scrollTop();
                            var windowwidth = $(window).width();
                            //showAjxLoadingDiv($("#productlisting"));
                            // $("#ajx_loader_image").css({top: scrolltop + (windowheight / 2), left: windowwidth / 2, position: 'absolute'});
                        }
    
                        //if ($(window).scrollTop() + $(window).height() >= ($('#productlisting').offset().top + $("#productlisting").height()) + 10) {
                        if(  ($(document).height()-400)   <= $(window).scrollTop()+$(window).height() ){
                            if (loading == 0 && endData == 0)
                            {
                                loadProductData(1);
                            }
                        }

//                         var sTop = $(window).scrollTop();
//                         $(".left-link-box").css({ top: (sTop < (originalY-80) ? 0 : sTop - originalY + topMargin) });                       
                        
                   	 }
                });

                /*****************block for handling likes product**************/
           

                $('.likes').on('click', function () {
                    var id = $(this).attr("id");
                    var url = "/service/likeclosset/";
                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {closesetId: id},
                        dataType: 'json',
                        success: function (result) {
                                  var class_name ='growl-missing';
                            if(result.status =='Y') {
                                class_name = 'growl-success';
                            } 


                            //alert(result.mgs);
                            //$("#gritter-notice-wrapper").addClass('type_success');
                            jQuery.gritter.add({
                                //title: result.mgs,
                                title: '<div class="wrap_ion_mgs"><div class="icon_gritter"></div><div class="dary_message">' + result.mgs +'</div></div><div class="my_close my_wrap_close">\
                <a href="javascript:void(0)"  class="close-reveal-modal x_close type_close"><span>X</span></a>\
                </div>',
                                class_name: class_name,
                                sticky: false,
                                time: 3000
                            })                             
                            if (result.status == 'N') {
                                //alert(result.mgs);
                            } else if (result.status == 'Y') {
                                var likesd = result.count + ' likes';
                                $('.like_' + result.idf).html(likesd);

                                if($(this).find('#like'+result.idf))
                                    $('#like'+result.idf).attr('src','/img/thumb.png');
                            } else {
                                //alert("Internal Server Error");
                            }
                        }
                    });
                });

                $('body').on('click', '.likes', function () {
                    var id = $(this).attr("id");
                    var url = "/service/likeclosset/";
                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {closesetId: id},
                        dataType: 'json',
                        success: function (result) {
                                      var class_name ='growl-missing';
                            if(result.status =='Y') {
                                class_name = 'growl-success';
                            } 


                            //alert(result.mgs);
                            //$("#gritter-notice-wrapper").addClass('type_success');
                            jQuery.gritter.add({
                                //title: result.mgs,
                                title: '<div class="wrap_ion_mgs"><div class="icon_gritter"></div><div class="dary_message">' + result.mgs +'</div></div><div class="my_close my_wrap_close">\
                <a href="javascript:void(0)"  class="close-reveal-modal x_close type_close"><span>X</span></a>\
                </div>',
                                class_name: class_name,
                                sticky: false,
                                time: 3000
                            })                             
                            if (result.status == 'N') {
                                //alert(result.mgs);
                            } else if (result.status == 'Y') {
                                var likesd = result.count + ' likes';
                                $('.like_' + result.idf).html(likesd);

                                if($(this).find('#like'+result.idf))
                                    $('#like'+result.idf).attr('src','/img/thumb.png');
                            } else {
                                //alert("Internal Server Error");
                            }

                        }
                    });
                });
                

               

                $('body').on('click', '.type_close', function () {
                    $('.gritter-close').trigger('click');
                });

                $('body').on('click', '.likesout', function () {
                    var id = $(this).attr("id");
                    var url = "/service/likeclosset/";
                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {closesetId: id},
                        dataType: 'json',
                        success: function (result) {
                            var class_name ='growl-missing';
                            if(result.status =='Y') {
                                class_name = 'growl-success';
                            } 


                            //alert(result.mgs);
                            //$("#gritter-notice-wrapper").addClass('type_success');
                            jQuery.gritter.add({
                                //title: result.mgs,
                                title: '<div class="wrap_ion_mgs"><div class="icon_gritter"></div><div class="dary_message">' + result.mgs +'</div></div><div class="my_close my_wrap_close">\
                <a href="javascript:void(0)"  class="close-reveal-modal x_close type_close"><span>X</span></a>\
                </div>',
                                class_name: class_name,
                                sticky: false,
                                time: 3000
                            })                             
                            if (result.status == 'N') {
                                //alert(result.mgs);
                            } else if (result.status == 'Y') {
                                var likesd = result.count + ' likes';
                                $('.like_' + result.idf).html(likesd);

                                if($(this).find('#likeout'+result.idf))
                                    $('#likeout'+result.idf).attr('src','/img/thumb.png');
                            } else {
                                //alert("Internal Server Error");
                            }
                        }
                    });
                });

                /*****************block for handling likes product**************/


            });

            function showAjxLoadingDiv(target)
            {
            	$("#loading-div-background").show();
//                 //var target=$('#'+targetId);
//                 var tarheight = $(target).height();
//                 var tartop = $(target).offset().top;
//                 var tarleft = $(target).offset().left;

//                 var scrollheight = $(target).height();
//                 var scrollwidth = $(target).width();
//                 var windowheight = $(target).height();
//                 var windowwidth = $(target).width();
//                 $("#ajx_loader_div").css({height: scrollheight, width: scrollwidth, display: 'block', top: (tartop + (60)), left: tarleft, position: 'absolute'});
//                 $("#ajx_loader_image").css({top: windowheight / 2, left: windowwidth / 2, position: 'absolute'});
            }

            function hideAjxLoadingDiv()
            {
                //$("#ajx_loader_div").css({display: 'none'});
            	$("#loading-div-background").hide();
            }

            function toggleslide(obj) {
                $('#outfit-window').toggle();
                $('#article-window').toggle();
                $('#productlisting').toggle();
                $('#loading').hide();
                if ($(obj).html() == 'Show Outfit') {
                    $(obj).html('Show Articles');
                } else {
                    $(obj).html('Show Outfit');
                }
            }
            $(document).on('click', '.refresh', function (e) {

                $.ajax({
                    url: '<?php echo $this->basePath('service') ?>',
                    success: function (data) {
                        $('#outfit-window').html($(data).find("#outfit-window").html()); 
                    }
                });
            });

            $(window).load(function () {

            // 	$( ".square1_tick" ).on( "click", function(event) {
            // 		  event.preventDefault();
          		//       $( ".square1" ).trigger( "click" );
          		// });


                // $('.square1').on('click', function () {
                //     var valueD = $(this).html();
                //     if (valueD == 'on') {
                //         $(this).html('off');
                //         $('#panel').attr('src','/img/circle-close.png');
                //         $(this).removeClass('on');
                //         $(this).addClass('off');
                //         $('#article-block').show();
                //         $('#outfit-block').hide();
                //         $('.outfitrefresh').hide();
                //         $('#leftaction').hide();
                //         $("footer").hide();
                //         $(".last-foot").hide();
                //         $(".square1").css('float', 'left');
                //         $(".square1").css('margin-left', '5px');
                //         $(".head1").text("Article Shopping");
                //     } else {
                //         $(this).html('on');
                //         $('#panel').attr('src','/img/circle-ok.png');
                //         $(this).removeClass('off');
                //         $(this).addClass('on');
                //         $('#article-block').hide();
                //         $('#outfit-block').show();
                //         $('.outfitrefresh').show();
                //         $('#leftaction').show();
                //         $("footer").show();
                //         $(".last-foot").show();
                //         $(".square1").css('float', 'right');
                //         $(".square1").css('margin-left', '0px');
                //         $(".head1").text("Outfit Shopping");
                //     }
                // });
                $('.blue-btn1').on('click', function () {
                    var currentSelector = ".square1";
                    var valueD = $(currentSelector).html();
                    if (valueD == 'on') {
                        $(currentSelector).html('off');
                        $('#panel').attr('src','/img/circle-close.png');
                        $(currentSelector).removeClass('on');
                        $(currentSelector).addClass('off');
                        $('#article-block').show();
                        $('#outfit-block').hide();
                        $('.outfitrefresh').hide();
                        $('#leftaction').hide();
                        $("footer").hide();
                        $(".last-foot").hide();
                        $(".square1").css('float', 'left');
                        $(".square1").css('margin-left', '5px');
                        $(".head1").text("Article View");
                    } else {
                        $(currentSelector).html('on');
                        $('#panel').attr('src','/img/circle-ok.png');
                        $(currentSelector).removeClass('off');
                        $(currentSelector).addClass('on');
                        $('#article-block').hide();
                        $('#outfit-block').show();
                        $('.outfitrefresh').show();
                        $('#leftaction').show();
                        $("footer").show();
                        $(".last-foot").show();
                        $(".square1").css('float', 'right');
                        $(".square1").css('margin-left', '0px');
                        $(".head1").text("Outfit View");
                    }
                });

                $('.refreshout').on('click', function () {
                    getOutfit();
                });
                $('body').on('click', '.sharepoup', function () {
                    $('#slideout_inner').css('right', '-165px');
                    $('#slideout').css('right', '-65px');
                    $(this).removeClass('shopen');
                    $(this).addClass('shclose');
                    $('#idSharethisOutfit').removeClass('shopen');
                    $('#idSharethisOutfit').addClass('shclose');                    

                });
                $('.share1').on('click', function () {
                    var clases = $(this).attr('class');
                    var classesA = clases.split(" ");
                    if (classesA[1] == 'shclose') {
                        $('#slideout_inner').css('right', '0');
                        $('#slideout').css('right', '90px');
                        $(this).removeClass('shclose');
                        $(this).addClass('shopen');
                    } else {
                        $('#slideout_inner').css('right', '-165px');
                        $('#slideout').css('right', '-65px');
                        $(this).removeClass('shopen');
                        $(this).addClass('shclose');
                    }
                })

                /*****************block for adding this product into my coloseset**************/
                $('.savecloseout').on('click', function () {
                    var id = $('#closesetId').val();
                    var url = "/service/outfitclosset/";
                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {closesetId: id},
                        dataType: 'json',
                        success: function (result) {
                                 var class_name ='growl-missing';
                            if(result.status =='Y') {
                                class_name = 'growl-success';
                            } 


                            //alert(result.mgs);
                            //$("#gritter-notice-wrapper").addClass('type_success');
                            jQuery.gritter.add({
                                //title: result.mgs,
                                title: '<div class="wrap_ion_mgs"><div class="icon_gritter"></div><div class="dary_message">' + result.mgs +'</div></div><div class="my_close my_wrap_close">\
                <a href="javascript:void(0)"  class="close-reveal-modal x_close type_close"><span>X</span></a>\
                </div>',
                                class_name: class_name,
                                sticky: false,
                                time: 3000,
                            });    

                            if (result.status == 'N') {
                                //alert(result.mgs);
                            } else if (result.status == 'Y') {
                                 var likesd = result.count + ' likes';
                                $('#like_' + result.idf).html(likesd);
                            } else {
                                //alert("Internal Server Error");
                            }                        
              



                            // if (result.status == 'N') {
                            //     swal("Oops!", result.mgs)
                            // } else if (result.status == 'Y') {
                            //     swal("Outfit Saved!", "You can find this Outfit in Saved Section.", "success")
                            //     //var likesd = result.count + ' likes';
                            //     //$('#like_' + result.idf).html(likesd);
                            // } else {
                            //     sweetAlert("Oops...", "Internal Server Error", "error");
                            // }
                        }});
                });
                /*****************End block for adding this product into my coloseset**************/

                /*******************block for filter jquery *********/
                $('#check1').on('click', function () {
                    if ($(this).is(':checked')) {
                        $('input[type="checkbox"]').prop('checked', true);
                    } else {
                        $('input[type="checkbox"]').prop('checked', false);
                    }
                    getOutfit();
                });
                $("input[name='outfit[]']").on('click', function () {
                    var checkedLen = $('input[name="outfit[]"]:checked').length;
                    var totalCheckBox = $('input[name="outfit[]"]').length;
                    if (checkedLen == totalCheckBox) {
                        $('#check1').prop('checked', true);
                    } else {
                        $('#check1').prop('checked', false);
                    }
                    getOutfit();
                });

                var getOutfit = function () {
                    var val1 = [];
                    var result = {};
                    $("input[name='outfit[]']:checked").each(function (i) {
                        val1[i] = $(this).val();
                        result['outfit'] = val1;
                    });
                    $.ajax({
                        url: '/service/alloutfits',
                        type: 'POST',
                        data: {filterArg: result},
                        success: function (data) {
                            $('#outfit-block').html(data);
                            //show tooltip
                            $('.my_tooltip').tooltipster({
                                position: 'top',
                                theme: 'tooltipster-shadow',
                                
                            });
                        }
                    });
                }

                /*******************End block for filter jquery *********/
            });



        </script>


        <!--<script src="/vendor/jquery-ui.min.js"></script>-->
        <!--<script type="text/javascript" src="/js/bootstrap-progressbar.js"></script>-->

        

<div id="loading-div-background">
    <div id="loading-div" class="ui-corner-all" >
      <img style="margin-top:20px; height: 50px" src="/img/loading7_light_blue.gif" alt="Loading.."/>
      <h2 style="color:gray;font-weight:normal;">Please wait....</h2>
     </div>
</div>        