<link rel="stylesheet"	href="<?php echo $this->basePath(); ?>/vendor/multiselect/css/common.css"	type="text/css" />
<link type="text/css" rel="stylesheet"	href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/base/ui.all.css" />
<link type="text/css"	href="<?php echo $this->basePath(); ?>/vendor/multiselect/css/ui.multiselect.css"	rel="stylesheet" />



<script type="text/javascript"	src="<?php echo $this->basePath(); ?>/vendor/multiselect/js/jquery-ui-1.8.custom.min.js"></script>
<script type="text/javascript"	src="<?php echo $this->basePath(); ?>/vendor/multiselect/js/plugins/localisation/jquery.localisation-min.js"></script>
<script type="text/javascript"	src="<?php echo $this->basePath(); ?>/vendor/multiselect/js/plugins/scrollTo/jquery.scrollTo-min.js"></script>
<script type="text/javascript"	src="<?php echo $this->basePath(); ?>/vendor/multiselect/js/ui.multiselect.js"></script>
<?php 

    echo $this->headLink()
     ->appendStylesheet($this->basePath() . '/vendor/bootstrap/bootstrap-combined.min.css')
     ->appendStylesheet($this->basePath() . '/vendor/bootstrap/tabcordion-demo.css')
     ->appendStylesheet($this->basePath() . '/css/style.css');

 ?>

<br />
<br />
<style>
<!--
.attributesCol {
	width: 60%;
	float: left
}

.itemInfoCol {
	width: 35%;
	float: right;
	padding-left: 10px;
	/*background-image: url('<?=$this->item['imageurl']?>');*/
/*	background-size: auto 200px;
	background-repeat: no-repeat;
	background-position: top right;*/
}

.itemInfoCol .row {
	clear: both;
	width: 100%;
	padding: 3px 0 3px 20px
}

.itemInfoCol .left {
	width: 100%;
	float: left;
	font-weight: bold;
    white-space: nowrap;
    overflow:hidden !important;
    text-overflow: ellipsis;
}

.itemInfoCol .right {
	/*width: 70%;*/
	/*float: left*/
}

.attributes {
	border-bottom: 1px solid #CCC
}

input[type="checkbox"] {
	display: inline;
}

-->
.activecolor {
	border: 2px solid black;
	background-image: url("<?php echo $this->basePath();?>/img/tick.png");
	background-size: 20px 20px;
	background-repeat: no-repeat;
	background-position: center center;
}

.btn-lv1 .nav-tabs>.active>a, .btn-lv1 .nav-tabs>.active>a:hover {
	background-color: none;
	border: 0;
}

.attributes {
	border: 0;
}

.btn-lv1 .nav-tabs {
	border: 0;
}

.btn-lv1 .nav-tabs li a {
	border: 0;
	padding: 0;
	margin-right: 0;
}

.btn-lv1 button.btn.btn-default {
	padding: 3px 15px;
	border: 1px solid GREY;
	font-size: 15px;
	background-color: #e6e6e6;
	color: #005580;
}

.level4 input[type="radio"] {
	display: block;
	margin-top: 0;
}

.list-attr {
	padding-left: 0;
	margin-left: 0;
}

.list-attr li {
	display: inline-block;
	width: 40%;
}

.list-attr li  input {
	float: left;
}

li.color {
	border-radius: 50px;
	cursor: pointer;
	float: left !important;
	font-size: 37px;
	height: 19px;
	margin-bottom: 13px;
	margin-right: 14px;
	padding: 7px !important;
	width: 19px !important;
}

ul.connected-list {
	height: 171px !important;
}

.ui-multiselect {
	width: inherit !important;
}

.ui-multiselect div.selected {
	width: 49% !important;
}

.ui-multiselect div.available {
	width: 50% !important;
}

input.search.empty.ui-widget-content.ui-corner-all {
	padding-bottom: 3px;
	font-size: 10px;
}

.level1.active .btn {
	font-weight: bold;
	color: red
}
.itemInfoCol-left{
    width: 65%;
    float: left;
}
.itemInfoCol-right {
    width: 35%;
    float: right;
}
.logo{
    /*margin-right: 53px;*/
    width: 20%;
    text-align: center;
    margin-left: 0;
}
  .community a{
    color:#fff;
    text-decoration: none;
  }
  .right_block .get_style img {
      margin-right: 6px !important;
      margin-bottom: 2px !important;
  }
</style>

<script>
$(document).ready(function() {
        $("#ignoreItem").click(function(e) {
            if( $("#ignoreItem").is(':checked') ){
                $('.attribute').prop('checked', false);
                $('.attribute').prop('disabled', true);
            }
            else {
                $('.attribute').prop('disabled', false);
            }
    });
});
</script>

<script
	src="<?php echo $this->basePath(); ?>/vendor/bootstrap/bootstrap.min.js"></script>
<script
	src="<?php echo $this->basePath(); ?>/vendor/bootstrap/tabcordion.js"></script>
<!-- <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/vendor/bootstrap/bootstrap-combined.min.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/vendor/bootstrap/tabcordion-demo.css"> -->


<div class="container" style="background-color: #F6F6F4;">
	<form id="editAttribsForm" action="/feed/edit-article?pid=<?=$this->item['id']?>"
		method="post" name="addInfo" id="addInfo">
		<div class="attributesCol">

		<!-- 	<div class="attributes" style="padding-left: 0px">
				<input id="ignoreItem" name="ignoreItem" type="checkbox" />&nbsp;&nbsp;Ignore
				this item <br />
				<br />
				<br />
			</div> -->
    
            <?php
            function printAttributes( $attributes, &$level, $parentId=0, $product_attributes ) {
                
                foreach( $attributes as $att ) {

                    $str  = '<div class="attributes" style="padding-left:'.($level*100).'px">';
                    
                    $checked = '';
                    if (isset($product_attributes['categories']) ){
                        if( 
                                (is_array($product_attributes['categories']) && in_array($att['id'], $product_attributes['categories'])) ||
                                ($att['id'] == $product_attributes['categories']) 
                            ) {
                            $checked = 'checked="checked"';
                        }
                    }
                    $str .= $att['pid'] != 0 ? '<input name="categories[] "'.$checked.' data-parent="'.$parentId.'" class="attribute" type="checkbox" id="id'.$att['id'].'" value="'.$att['id'].'" />&nbsp;&nbsp;' : '';
                    $str .= $att['title'];
                    $str .= '</div>';

                    echo $str;

                    if(count($att['child'])) {
                            $level++;
                            printAttributes( $att['child'], $level, $att['id'], $product_attributes );
                            $level--;
                    }
                }
            }
    
            $level = 0;
            //printAttributes($this->attributes, $level, 0, $this->product_attributes);

            
            function getChildAttribute($attributes, $attributeId = 1){
                $listItem = array();
                foreach ($attributes[$attributeId]['child'] as $value) {
                    $listItem[] = $value;
                }
                return $listItem;
            } 
            ?>

            <!-- tab -->
			<!-- level 1 -->

			<div class="tabcordion tabbable">
				<div class="btn-lv1">
					<ul class="nav nav-tabs">
                <?php
                    $listItemCategory =  getChildAttribute($attributes);
                    $i = 0;
                    //$tabpage = 1;
                    $listItemLevel2 = array();
                    
                    $bFound = false;
                    foreach ($listItemCategory as $value) {

                        if(in_array($value['id'], $this->product_attributes_ids)) {
                            $bFound = true;
                        }
                    }
                    
                    foreach ($listItemCategory as $value) {
                        $listItemLevel2[$value['id']] = $value['child'];  ?>
                        <li
							class="level1 <?=(in_array($value['id'], $this->product_attributes_ids)?'active':(!$bFound && $i==0?'active':''))?>"
							data-id="<?=$value['id']?>"><a
							data-target="#tab-<?php echo $value['id']?>" data-toggle="tab"
							class="accordion-toggle collapsed">
								<button class="btn btn-default"><?php echo $value['title']; ?></button>

						</a></li> <?php 

                            $i++;
                        } 
                    ?>
                    

                </ul>
				</div>
				<div class="tab-content" style="display: block;">
                    <?php 

                    $i=0; $acc = '';
                    foreach ($listItemLevel2 as $key => $valuelv1) {  
                        ?>
                    <div
						class="parentClass<?=$key?> home tab-pane collapse <?=(in_array($key, $this->product_attributes_ids)?'active':'')?>"
						id="tab-<?php echo $key;?>" style="height: auto;">
						<!-- level 2 -->
						<div class="tabcordion tabbable">
							<ul class="nav nav-tabs">

                                <?php 
                                    $i =0;
                                    $listItemLevel3 = array();
                                    
                                    $bFound = false;
                                    foreach ($valuelv1 as $valuelv2) {

                                        if(in_array($valuelv2['id'], $this->product_attributes_ids)) {
                                            $bFound = true;
                                        }
                                    }                                    
                                    
                                    
                                    foreach ($valuelv1 as $valuelv2) {
                                         $listItemLevel3[$valuelv2['id']] = $valuelv2['child'];  ?>
                                         <li
									class="level2 <?=(in_array($valuelv2['id'], $this->product_attributes_ids)?'active':(!$bFound && $i==0?'active':''))?>"
									data-id="<?=$valuelv2['id']?>"><a
									data-target="#tab-<?php echo $valuelv2['id']?>"
									data-toggle="tab" class="accordion-toggle collapsed">
                                                <?php echo $valuelv2['title']?>
                                            </a></li> <?php
                                        $i++;
                                    } 

                                ?>
                            </ul>
							<div class="tab-content" style="display: block;">
                                <?php 

                                
                                $bFound = false;
                                foreach ($listItemLevel3 as $key=>$valuelv2) {
                                    if(in_array($key, $this->product_attributes_ids)) {
                                        $bFound = true;
                                    }
                                }                                
                                
                                $i=0;
                                foreach ($listItemLevel3 as $key=>$valuelv2) {   
                                
                                    if($key == 37) {
                                        $a = 1;
                                    }
                                    ?>
                                <div
									class="parentClass<?=$key?> home tab-pane collapse <?=(in_array($key, $this->product_attributes_ids)?'active':(!$bFound && $i==0?'active':''))?>"
									id="tab-<?php echo $key;?>" style="height: auto;">
									<!-- level 3 -->
									<div class="tabcordion tabs-left tabbable">
										<ul class="nav nav-tabs">

                                              <?php 
                                                $i =0;
                                                $listItemLevel4 = array();
                                                 
                                    foreach ($valuelv2 as $valuelv3) {
                                        $val= array();
                                        foreach ($valuelv3['child'] as $key => $value) {
                                            $value['inputType'] = $valuelv3['inputType'];
                                            $val[$key] =  $value;
                                        }

                                        //$listItemLevel4[$valuelv3['id']] = $valuelv3['child'];
                                        $listItemLevel4[$valuelv3['id']] =   $val;
                                              
                                 ?>

                                 <li
												class="level3 <?php if($i==0) echo 'active'; ?>"
												data-id="<?=$valuelv3['id']?>"><a
												data-target="#tab-<?php echo $valuelv3['id']?>"
												data-toggle="tab" class="accordion-toggle collapsed">

                                        <?php echo $valuelv3['title']?>
                                    </a></li>
                                <?php $i++;} 
                                ?>                                       
                                        </ul>
										<div class="tab-content" style="display: block;">
                                            <?php
                                            $i=0;
                                             foreach ($listItemLevel4 as $key => $valuelv3) {
                                                  
                                                 foreach ($valuelv3 as $value) {
                                                     $inputType = $value['inputType'];
                                                     break;
                                                 }
                                            ?>
                                            <div
												data-inputtype="<?=$inputType?>"
												class="parentClass<?=$key?> level4 home in tab-pane collapse <?php if($i==0) echo 'active'; ?>"
												id="tab-<?php echo $key;?>" style="height: auto;">
                                            <?php 

                                         
                                                if($inputType !='multiselect') { 
                                            ?>
                
                                            <!-- level 4 -->
												<ul class="list-attr">
                                                <?php 
                                                $type='checkbox';
                                                    foreach ($valuelv3 as $valuelv4) {  
                                                      
                                                        if($valuelv4['inputType']=="radio") {
                                                            $type = "radio";
                                                        }
                                                        else   
                                                        if($valuelv4['inputType']=="checkbox") {
                                                            $type="checkbox";
                                                        }
                                                        else if($valuelv4['inputType']=="color") {
                                                            $type ='color';
                                                        }
                                                            $checked = '';
                                                            $active='';
                                                            $activecolor='';

                                                            if( $acc == '1' && $valuelv4['id']=='7967' ) {
                                                                $a=1;
                                                            }
                                                        
                                                        foreach ($this->product_attributes as $value) {
                                                            foreach ($value as $attr) {
                                                                if(($attr['value']==$valuelv4['title'] || $attr['value'] == $valuelv4['id']) && $attr['attributeParentId'] == $key){
                                                                        $checked= 'checked'; 
                                                                        $active = 'active';
                                                                        $activecolor = 'activecolor'; 
                                                                    }
                                                            }
                                                        }

                                                  

                                                 ?>
                                                 <!-- checkbox -->
                                                 <?php if($type == 'checkbox') { ?>
                                                          <li><label><input
															<?php echo $checked; ?> type="checkbox"
															class="categories <?php echo $active ?>"
															value="<?php echo $valuelv4['id'] ?>">&nbsp;&nbsp;&nbsp;<?php echo $valuelv4['title'] ?></label></li>
													<!-- end checkbox -->
                                                <?php } else  if($type == 'radio') { ?>
                                                    <!-- radio -->
													<!-- <input type="radio" name="option" id="<?php echo $valuelv4['id'] ?>" value="<?php echo $valuelv4['id'] ?>"/>
                                                    <label for="<?php echo $valuelv4['id'] ?>" class="outfit">
                                                        <span class="fa-stack option-radio">
                                                            <i class="fa fa-circle-o fa-stack-1x"></i>
                                                            <i class="fa fa-circle fa-stack-1x"></i>
                                                        </span> <?php echo $valuelv4['title'] ?>
                                                    </label> -->
													<li><input <?php echo $checked; ?> type="radio"
														value="<?php echo $valuelv4['id'] ?>"
														name="<?php echo $key ?>"
														id="<?php echo $valuelv4['id'] ?>"
														class="categories <?php echo $active ?>"> <label
														for="<?php echo $valuelv4['id'] ?>">
                                                                <?php echo $valuelv4['title'] ?>
                                                        </label></li>
													<!-- end radio -->
                                                <?php } else if($type == 'color') { ?>
                                                <!-- color -->
													<li class="color <?php echo $active; ?> btn-01 btn-coloer-01 colorattrselection <?php echo $activecolor; ?>" style="background-color:<?php echo $valuelv4['title']; ?>;border:solid 1px <?php echo $valuelv4['title']; ?>;" data-value="<?php echo $valuelv4['id']; ?>" title="<?php echo $valuelv4['title']; ?>">
													</li>

                                                <?php   } ?> <!-- end color -->

                                                <?php $i++; }?>
                                                    
                                            </ul>

												<!-- end level 4 -->

                                            <?php } else { 
                                            
                                                if( $key == '2055' ) {
                                                    $a =1;
                                                }
                                                
                                                ?>
                                                <select  class="multiselect" multiple="multiple">
                                                <?php  foreach ($valuelv3 as $valuelv4) { 
                                                        $selected='';
                                                      foreach ($this->product_attributes as $value) {
                                                            foreach ($value as $attr) {
                                                                if($attr['value']==$valuelv4['title'] && $attr['attributeParentId'] == $key){
                                                                        $selected= 'selected'; 

                                                                    }
                                                            }
                                                        }


                                                    ?>
                                                <option
														<?php echo $selected;?>
														value="<?php echo $valuelv4['id']; ?>"><?php echo $valuelv4['title']  ?>
                                                </option>
                                                <?php } ?>

                                                </select>
                                            <?php } ?>

                                            </div>
											<!-- end div level4 -->
                                             <?php  $i ++; 
                                             } ?> <!-- end foreach listItemLevel4 -->

										</div>
									</div>
									<!-- end level 3 -->
								</div>

                                <?php
                                    $i ++;
                                    }
                                 ?>
                            </div>
						</div>
						<!-- end level 2 -->
					</div>
                    <?php $i++; } ?>
            
         
                </div>
			</div>
			<!-- end level 1 -->
			<!-- end tab -->



		</div>



		<div class="itemInfoCol">
            <div class="my_wrapper" style="width:100%;display:block;clear:both">
                <div class="itemInfoCol-left">
                <?php if( is_array($this->item) ) { ?>
            
                <div class="row">
                    <div class="left">ID:</div>
                    <div><?=$this->item['id']?></div>
                </div>
                <div class="row">
                    <div class="left">UID:</div>
                    <div><?=$this->item['uid']?></div>
                </div>
                <div class="row">
                    <div class="left">Program Name:</div>
                    <div><?=$this->item['programname']?></div>
                </div>

                <div class="row">
                    <div class="left">Program URL:</div>
                    <div><a href="<?=$this->item['programurl']?>"><?=$this->item['programurl']?></a></div>
                </div>

                <div class="row">
                    <div class="left">Date Added:</div>
                    <div><?=$this->item['dateadded']?></div>
                </div>

                <div class="row">
                    <div class="left">SKU:</div>
                    <div><?=$this->item['sku']?></div>
                </div>

                <div class="row">
                    <div class="left">Currency:</div>
                    <div><?=$this->item['currency']?></div>
                </div>

                <div class="row">
                    <div class="left">Price:</div>
                    <div><?=$this->item['price']?></div>
                </div>

                <div class="row">
                    <div class="left">Sale Price:</div>
                    <div><?=$this->item['saleprice']?></div>
                </div>

                <div class="row">
                    <div class="left">In-Stock:</div>
                    <div><?=$this->item['instock']?></div>
                </div>

                <div class="row">
                    <div class="left">Adv. Category:</div>
                    <div><?=$this->item['advertisercategory']?></div>
                </div>

                <div class="row">
                    <div class="left">Name</div>
                    <div><?=$this->item['name']?></div>
                </div>

                <div class="row">
                    <div class="left">Description:</div>
                    <div><?=$this->item['description']?></div>
                </div>

                <div class="row">
                    <div class="left">Buy URL:</div>
                    <div>
                        <a href="<?=$this->item['buyurl']?>" target="_blank"><?=$this->item['buyurl']?></a>
                    </div>
                </div>

                <div class="row">
                    <div class="left">Impression URL:</div>
                    <div>
                        <a href="<?=$this->item['impressionurl']?>" target="_blank"><?=$this->item['impressionurl']?></a>
                    </div>
                </div>

                <div class="row">
                    <div class="left">Image URL:</div>
                    <div>
                        <a href="<?=$this->item['imageurl']?>" target="_blank"><?=$this->item['imageurl']?></a>
                    </div>
                </div>

                <?php }?>
            </div>
            <div class="itemInfoCol-right">
                <img src="<?=$this->item['imageurl']?>">
            </div>
            </div>       
    </div>


		<div style="clear: both; padding-top: 30px">
			<input class="btn btn-primary" type="button" value="Save" id="save" />
		</div>


		<input type="hidden" id="categories" class="form-control"
			name="categories" value="">

	</form>
</div>



<script>

/* function getAttrCategories(){
    var listId = [];
    var selector ='.level4';
    var elementActive = $(selector).find(".active");

    if(elementActive.length > 0) {
        $(elementActive).each(function(key,value){

            console.log(value);
            if($(value).is('li')) {

                id = $(value).data('value');
            } else {
                id = $(value).val();
            }
            listId.push(id); 
            var parents= $(this).parents(".home.tab-pane");
           
            if(parents.length > 0) {
                $(parents).each(function(key,value){
                    idtab = $(value).attr('id');
                    idparent = idtab.replace("tab-","");

                     if(jQuery.inArray(idparent,listId) >= 0){
                          
                     }
                     else {
                        listId.push(idparent); 
                     }
                    // đẩy id cha vào lưu của item hiện tại
                });
            }

        });
    }
    return listId;
} */

function verify() {
	
	var IDS = [];
	var attributes = getAttrCategories();
	attributes = JSON.parse(attributes);
	$.map(attributes, function(n, i){
        n = n.split(':'); 
        IDS.push( parseInt(n[1]) );
	})

    found =false;
    $.map([<?=implode(',', $this->level1CategoryIds)?>], function(n, i){
        if( $.inArray( n, IDS ) != -1 ) {
            found =true;
        }
    })	
    if(!found) {
        alert('Please provide Major Category.');
        return false;
    }   

    found =false;
    $.map([<?=implode(',', $this->level2CategoryIds)?>], function(n, i){
        if( $.inArray( n, IDS ) != -1 ) {
            found =true;
        }
    })	
    if(!found) {
        alert('Please provide Sub Category.');
        return false;
    }       


    found =false;
    $.map([<?=implode(',', $this->categoryTypeIds)?>], function(n, i){
        if( $.inArray( n, IDS ) != -1 ) {
            found =true;
        }
    })	
    if(!found) {
        alert('Please provide Type.');
        return false;
    } 

    return true;
        
}


function getAttrCategories() {
	
    var attributes = [];

    $('.level1.active').each(function(key,value) {
        
        //console.log('catagory - ' + $(value).data('id') );
        attributes.push('catagory:' + $(value).data('id'));
        
        $('.parentClass'+$(value).data('id')+' .level2.active').each(function(key,value) {
         
          //console.log('catagory - ' + $(value).data('id') );
          attributes.push( 'catagory:' + $(value).data('id') );
          
          $('.parentClass'+$(value).data('id')+' .level3').each(function(key,value){
            
            if( $('.parentClass'+$(value).data('id')).data('inputtype')=='radio' ) {
              val = $.map($('.parentClass'+$(value).data('id')+' input[type=radio]:checked'), function(n, i){return n.value;}).join(',');
              if( val ) {
                //console.log('att:'+$(value).data('id')+' - ' + val );
                attributes.push( 'attribute:' + val );
              }
            }

			
            if( $('.parentClass'+$(value).data('id')).data('inputtype')=='checkbox' ) {
              val = $.map($('.parentClass'+$(value).data('id')+' input[type=checkbox]:checked'), function(n, i){return n.value;}).join(',');
              if( val ) {
                //console.log('att:'+$(value).data('id')+' - ' + val );
                attributes.push( 'attribute:' + val );
              }
            }	


            if( $('.parentClass'+$(value).data('id')).data('inputtype')=='multiselect' ) {
                val = $('.parentClass'+$(value).data('id')+' select').val();
                val = (val ? val.join(',') : '' );            	
                if( val ) {
                    //console.log('att:'+$(value).data('id')+' - ' + val );
                    attributes.push( 'attribute:' + val );
                }            	
            }            		 

            if( $('.parentClass'+$(value).data('id')).data('inputtype')=='color' ) {
            	val = $.map($('.parentClass'+$(value).data('id')+' .color.active'), function(n, i){return $(n).data('value');}).join(',');
                if( val ) {
                    //console.log('att:'+$(value).data('id')+' - ' + val );
                    attributes.push( 'attribute:' + val );
                }            	
            } 
            			
            
          });      
        });
    });

	//console.log( JSON.stringify(attributes) );
	return JSON.stringify(attributes);
}


$(document).ready(function(){
       $(".multiselect").multiselect();
       $("#save").on('click',function(e){
           if( verify() ) {
                $(".multiselect option:selected").addClass("active");
                $("#categories").val(getAttrCategories());
                console.log($("#categories").val());
                $('#editAttribsForm').submit();
            }

       });

//        var listId = getAttrCategories();
//        if(listId.length > 0) 
//             listId= listId.toString();
//             console.log(listId);
//         $("#categories").val(listId);


/*        $(".level4 input[type=checkbox]").click(function(){
            if($(this).hasClass('active'))
            $(this).removeClass('active');
            else
            $(this).addClass('active');
         var listId = getAttrCategories();
         if(listId.length > 0) 
            listId= listId.toString();
            console.log(listId);
            $("#categories").val(listId);
       });

        $(".level4 input[type=radio]").click(function(){
            console.log($(this).parents(".level4.active").find($("input[type=radio]")));
            $(this).parents(".level4.active").find($("input[type=radio]")).removeClass('active');
          
            //$(this).parent.removeClass('active');
            $(this).addClass('active');

         var listId = getAttrCategories();
         if(listId.length > 0) 
            listId= listId.toString();
            console.log(listId);
            $("#categories").val(listId);
       });*/

        $(".level4 li.color").click(function(){
            if($(this).hasClass('active'))
                $(this).removeClass('active');
                else
                $(this).addClass('active');

//              var listId = getAttrCategories();
//              if(listId.length > 0) 
//                 listId= listId.toString();
//                 //console.log(listId);
//                 $("#categories").val(listId);
       }); 

    $(".colorattrselection").click(function () {
        $(this).toggleClass('activecolor');
    });         

});


(function($) {

    // var element = $('.itemInfoCol'),
    //     originalY = element.offset().top;

    // // Space between element and top of screen (when scrolling)
    // var topMargin = 100;

    // // Should probably be set in CSS; but here just for emphasis
    // element.css('position', 'relative');

    // $(window).on('scroll', function(event) {
    //     var scrollTop = $(window).scrollTop();

    //     element.stop(false, false).animate({
    //         top: scrollTop < originalY
    //                 ? 0
    //                 : scrollTop - originalY + topMargin
    //     }, 0);
    // });

//     $('.attributesCol input[type=checkbox]').each(function () {
//         	$(this).prop('checked',false);
//     });
        
    $('.attributesCol input[type=checkbox]').click(function () {
        obj = this;
        if( $(obj).prop('checked') ) {
            while( $(obj).attr('id') != undefined ) {
            	$('#id'+$(obj).data('parent')).prop('checked',true);
            	obj = $('#id'+$(obj).data('parent'));

                //mycode 
               // $("#catids").val($(obj).val());
            }
        }
        else {
        	unCheck( obj );

        }
   });

    function unCheck( obj ) {
    	$('input[data-parent="'+$(obj).val()+'"]').each(function () {
        	$(this).prop('checked',false);
        	unCheck( this )
        });
    }

    $(".colorselection").click(function () {
        $(this).toggleClass('activecolor');
        var colors = '';
        var allSelectedColors = $(".colorselection.activecolor");
        $(allSelectedColors).each(function () {
            colors += ($(this).attr('value')) + ',';
        })
        $("#colors").val(colors);
    });

    
})(jQuery);    

$(".btn-group button").click(function(){
    return false;
});      
</script>