<!-- temp -->
<style type="text/css">
    .image-list,.media_box,.testimonial_box,.slider_box{
        display: none;
    }
</style>

<!-- end temp -->
<div class="banner">
    <div class="heading">Whether for casual or business attire,<br />get choices tailored to you.</div>
    <div align="center"><a href="<?php echo $this->basePath('/profile')?>" class="btnHomeBanner"><span>GET DRESSED</span></a> </div> 
    <div class="learn"> <a href="#learn_more" class="smooth_learn"> Learn More </a>
        <br><i class="fa fa-caret-down white"></i>
    </div>
</div>
<div id="homepage" class="container">
<section>
<div class="about" id="learn_more">
<h1 class="title" >DRESS TO  THE NINES</h1>
<p class="description">
Fashion isn't something that comes easily to most men. However, that doesn't mean that men don't want to look their best! <br>
Simply tell us about yourself and we'll find clothes that will complement your look, your personality, your profession, and your lifestyle.<br> 
At all venues, you'll be looking your best, and people will notice.
</p> 
<div class="round">
    <div class="box-1">
        <div class="img">
            <img src="img/round_male.png">
        </div>
        <h3>TELL US ABOUT YOU</h3>
        <p>Getting inside of the clothes that you're meant to wear begins with you. Let us learn about you, so we can dress you to the nines.</p>
    </div>
    <div class="icon"><i class="fa fa-angle-right fa-lg orange"></i>
    </div>
    <div class="box-1">
        <div class="img">
            <img src="img/round_shirt.png">
        </div>
        <h3>GET STYLED</h3>
        <p>Our understanding of fashion and partnerships with leading brands allow us to find the perfect wardrobe for you.</p>
    </div>
    <div class="icon"><i class="fa fa-angle-right fa-lg orange"></i>
    </div>
    <div class="box-1">
        <div class="img">
            <img src="img/round_shirt0ne.png">
        </div>
        <h3>GET DRESSED</h3>
        <p>After your clothes have been located, we'll connect you with our partners. Check out the items and simply make the purchase!</p>
    </div>
    <div class="clr"></div>
</div>
<div class="clr"></div>
<div class="service">
    <div class="left-service">
        <div class="left-img"></div>
        <div class="service-detail">
            <h1>FREE SERVICE</h1>
            <p>El Nove is your personal stylist. For free. We do the work and show you clothing that are tailored to you. With no obligation to purchase and no fee from us, there's no risk at all!</p>
            <a href="/profile" class="sign-up">Sign up for free and start dressing</a>
        </div>
    </div>
    <div class="right-service">
        <div class="right-img"></div>
        <div class="img2"></div>
    </div>
    <div class="clr"></div>
</div>
<div class="box-2">
    <div class="left_box2">
        
    </div>
    <div class="center_box2">
        <div class="one">
            <h1>DRESS FOR <br> YOUR VENUE</h1>
        </div>
        <div class="clr"></div>
        <div class="two">
            <p>El Nove finds the right clothes for whatever situation you plan on finding yourself in. If you're looking for smart attire for the office or something that pops for a night out in the club, we can help.</p>
        </div>
    </div>
    <div class="right_box2">
        <div class="img_one"></div>
        <div class="img_two"></div>
    </div>
    <div class="clr"></div>
</div>
<!-- 
<div class="slider_box">
    <div class="left_box">
        <div class="top"><h1>OVER 100 GREAT PARTNERS </h1></div>
        <div class="bottom">
            <p>
            In order to make sure that men like you are dressed to the nines, we've partnered with the world's leading men's fashion brands. <br /><br />
            Naturally, you'll see many of the high-quality brands you're already familiar with. But, there's so much more. LNove will also introduce you to smaller, boutique brands, which always carry unique items!<br /><br />
            It doesn't matter what you choose, because we've only partnered with the highest quality purveyors of men's fashion. When you put your new clothes on, you'll feel the difference, and others will see the difference.
            </p>
        </div>
    </div>
    <div class="right_box">
        <div class="small-slider">
            <div id="owl-demo1" class="owl-carousel owl-theme">
                <div class="item"> <div class="slide_img">
                        <img src="img/lacoste.png">
                    </div></div>
                <div class="item"> <div class="slide_img">
                        <img src="img/lacoste.png">
                    </div></div>
                <div class="item"> <div class="slide_img">
                        <img src="img/lacoste.png">
                    </div></div>
                <div class="item"> <div class="slide_img">
                        <img src="img/lacoste.png">
                    </div></div>
                <div class="item"> <div class="slide_img">
                        <img src="img/lacoste.png">
                    </div></div>
                <div class="item"> <div class="slide_img">
                        <img src="img/lacoste.png">
                    </div></div>
            </div>
        </div> <!--small-slider  -- >
        <div class="line">
        </div>
    </div>
</div>
<div class="clr"></div>
<div class="testimonial_box">
    <div class="left-test">
        <h1>testimonials</h1>
    </div>
    <div class="center-test"></div>
    <div class="clr"></div>

    <div class="slider">

        <div class="container">
            <div class="testi_slider">

                <div id="owl-demo" class="owl-carousel owl-theme">
                    <div class="item">
                        <div class="slider-box">
                            <div class="text">
                                <p>Proin gravida nibh vel velit auctor aliquet.
                                    Aenean sollicitudin, lorem quis bibendum auctor,
                                    nisi elit cuat ipsum, nec sagittis sem nibh id elit.
                                </p>
                            </div>
                            <div class="slider-image">
                                <div class="col-half" data-label="Gray">
                                    <img src="img/client_two.jpg" class="grayscale grayscale-fade">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="slider-box bluebgcolor">
                            <div class="text">
                                <p>Proin gravida nibh vel velit auctor aliquet.
                                    Aenean sollicitudin, lorem quis bibendum auctor,
                                    nisi elit cuat ipsum, nec sagittis sem nibh id elit.
                                </p>
                            </div>
                            <div class="slider-image">
                                <div class="col-half" data-label="Gray">
                                    <img src="img/client_two.jpg" class="grayscale grayscale-fade">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="slider-box ">
                            <div class="text">
                                <p>Proin gravida nibh vel velit auctor aliquet.
                                    Aenean sollicitudin, lorem quis bibendum auctor,
                                    nisi elit cuat ipsum, nec sagittis sem nibh id elit.
                                </p>
                            </div>
                            <div class="slider-image">
                                <div class="col-half" data-label="Gray">
                                    <img src="img/client_two.jpg" class="grayscale grayscale-fade">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="slider-box bluebgcolor">
                            <div class="text">
                                <p>Proin gravida nibh vel velit auctor aliquet.
                                    Aenean sollicitudin, lorem quis bibendum auctor,
                                    nisi elit cuat ipsum, nec sagittis sem nibh id elit.
                                </p>
                            </div>
                            <div class="slider-image">
                                <div class="col-half" data-label="Gray">
                                    <img src="img/client_two.jpg" class="grayscale grayscale-fade">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="slider-box ">
                            <div class="text">
                                <p>Proin gravida nibh vel velit auctor aliquet.
                                    Aenean sollicitudin, lorem quis bibendum auctor,
                                    nisi elit cuat ipsum, nec sagittis sem nibh id elit.
                                </p>
                            </div>
                            <div class="slider-image">
                                <div class="col-half" data-label="Gray">
                                    <img src="img/client_two.jpg" class="grayscale grayscale-fade">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="slider-box bluebgcolor">
                            <div class="text">
                                <p>Proin gravida nibh vel velit auctor aliquet.
                                    Aenean sollicitudin, lorem quis bibendum auctor,
                                    nisi elit cuat ipsum, nec sagittis sem nibh id elit.
                                </p>
                            </div>
                            <div class="slider-image">
                                <div class="col-half" data-label="Gray">
                                    <img src="img/client_two.jpg" class="grayscale grayscale-fade">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clr"></div>
    </div>
</div>
<div class="media_box">
    <h1>FOUND IN MEDIA</h1>
    <div class="clr"></div>
</div>
<div class="clr"></div>
<div class="image-list">
    <div class="image rgt  ">
        <img src="img/lacoste.png">
    </div>
    <div class="image rgt ">
        <img src="img/lacoste.png">
    </div>
    <div class="image rgt ">
        <img src="img/lacoste.png">
    </div>
    <div class="image rgt ">
        <img src="img/lacoste.png">
    </div>
    <div class="image rgt ">
        <img src="img/lacoste.png">
    </div>
    <div class="image rgt ">
        <img src="img/lacoste.png">
    </div>
    <div class="image">
        <img src="img/lacoste.png">
    </div>
    <div class="clr"></div>
    <div class="clr"></div>
</div>

<div class="clr"></div>
-->
<div class="top_page" style="padding-top:0px">
    <img src="img/arrow.png" class="click_to_top">
    <p><span class="click_to_top">TOP OF PAGE</span></p>
</div>

</div>
<div class="clr"></div>
</section>
</div>
<script type="text/javascript">
    $('.click_to_top').click(function(){
        $('html, body').animate({scrollTop : 0},800);
        return false;
    });


      $('.smooth_learn').click(function(){
        $('html, body').animate({
            scrollTop: $("#learn_more").offset().top - 80
        }, 800);
        return false;
    });
</script>
