<style>
<!--
.home-concept{background: none;}
.banner{
	height: 500px; 
	background-image:url('/img/home/banner.jpg'); 
	background-position:center; 
	background-repeat:no-repeat;	
}
.banner .bannerMessage{
	padding-top: 100px;
	text-transform:uppercase;
	text-align: center;
	text-shadow: 0px 2px 1px rgba(0, 0, 0, 0.66);	
}
.banner .bannerMessage h1{
	font-size: 60px;
	font-weight:bold;
	color: #FFF;
	line-height:70px;
	margin-bottom: 10px;
	
}
.banner .bannerMessage h3{
	font-size: 30px;
	font-weight:normal;
	color: #FFF;
	line-height:40px;
	
-->
</style>


<div role="main" class="main maxWidth" style="border-top:1px solid #dddddd;">

	<div class="banner">
		<div class="container" >
			<div class="bannerMessage">
				<h1>Finding Your Style Needs Just<br />Got Easier</h1>
				<h3>A free personalized style engine.</h3>
			</div>
		</div>	
	</div>				
	
	<section class="page-top" style="border-top:none; border-bottom:none">
		<div class="container">

			<div class="row center">
				<div class="col-md-12" style="margin-bottom:5px">
					<table align="center">
						<tr>
							<td><h2 class="short" style="border:none">CONNECTING YOU TO YOUR STYLE</h2><td>
							<td style="padding-top:8px; padding-left:30px"><input class="btn btn-primary btn-lg" type="button" data-loading-text="Loading..." onclick="window.location='/profile'" value="GET STARTED"><td>
						</tr>
					</table>
				</div>
			</div>	
			
		</div>
	</section>
		
</div>				

<style>
<!--
.home-concept .small{font-size:17px; margin-top:10px; line-height:20px}
-->
</style>
<div role="main" class="main">

	<div class="container">
	
		<div class="home-concept" style="background: none;">
			<div class="container">
	
				<div class="row center" style="height:360px; " align="center">
					<div class="col-md-3" style="margin-left:30px">
							<img src="img/home/about_you.png" alt="" />
							<strong style="color:#4d4b50; font-weight:bold">TELL US ABOUT YOU</strong>
							<div class="small">Tell us about your style.</div>
					</div>
					<div class="col-md-1"></div>
					<div class="col-md-3">
							<img src="img/home/get_style.png" alt="" />
							<strong style="color:#4d4b50; font-weight:bold">GET STYLED</strong>
							<div class="small">Let our Stylengine find the<br />perfect outfit for you.</div>
					</div>
					<div class="col-md-1"></div>
					<div class="col-md-3">
							<img src="img/home/get_dressed.png" alt="" />
							<strong style="color:#4d4b50; font-weight:bold">Get DRESSED</strong>
							<div class="small">Purchase the clothing from the<br />worlds most popular brands.</div>
					</div>								
	
				</div>
	
			</div>
		</div>					
	
	</div>

</div>				

<style>
<!--
.banner2{
	margin-bottom:30px; 
	margin-top:50px; 
	height: 459px; 
	background-image:url('/img/home/banner2_bg.jpg'); 
	background-position: center center;
	background-repeat: repeat-x;
	
}
.banner2 .outfitwindow{
	width: 520px; 
	height: 455px; 
	background-image:url('/img/home/outfitwindow.png'); 
	background-repeat: no-repeat;
	float: right;
}
.banner2 .banner2Message{
	width: 500px; 
	height: 455px; 
	float: right;
	text-align:center;
	padding-top:90px
}
.banner2 .banner2Message h1{
	font-size: 60px;
	font-weight:bold;
	color: #FFF;
	letter-spacing:2px;
	line-height:70px;
	text-shadow: 2px 2px #000000;
}
.banner2 .banner2Message h3{
	font-size: 30px;
	font-weight:normal;
	color: #FFF;
	letter-spacing:2px;
	line-height:40px;
	text-transform:none;
}
-->
</style>

<div role="main"  class="banner2 maxWidth">
	<div class="container" >
		<div class="outfitwindow"></div>
		<div class="banner2Message">
			<h1>BUILT FROM<br />YOUR CLOSET</h1>
			<h3>our algorithm builds an outfit<br />specifically for <strong>you</strong>.</h3>
		</div>
	</div>
</div>				




<div role="main" class="main">

	<div class="container">
	
	
	

	

			


										
	

	
					
	<div class="row">
		<div class="col-md-6">
			<br /><br />
			<h2><strong>FREE SERVICE</strong></h2>
			<p>From managing your clothing using MyCloset to finding the perfect outfit using the FashionEngine, all the 
				services and features that you have at your fingertips to help you with your outfits will be absolutely 
				free! Signup for free and start dressing!</p>
		</div>
		<div class="col-md-6">
			<div>
				<img alt="" class="img-responsive" src="/img/home/free_service.jpg">
			</div>
		</div>
	</div>					

	<hr />
	<br />
	<div class="row center">
		<div class="col-md-12">
			<h2><strong>DRESS FOR YOUR VENUE</strong></h2>
			<div align="center">
				<img src="/img/home/night_out.jpg" alt="" style="margin-right:45px" />
				<img src="/img/home/work.jpg" alt="" />
				<img src="/img/home/casual.jpg" alt="" style="margin-left:45px" />
			</div>
			<br />
			<p>Our FashionEngine will help you find the perfect outfit for any occasion. From a casual outing to a dress 
			to impress event- we have you covered.</p>
			
		</div>
	</div>		
	
<br /><br />					
		
	
	
		
	<div class="row maxWidth">
	
		<div class="col-md-12">
			<div align="center">
				<h2>
					<strong>OVER <span style="color:#16979d">100</span> GREAT PARTNERS</strong> <br />
					<img src="/img/home/100_brands.jpg" alt="" />
				</h2>
			</div>
			
			<div style="padding-top:20px" class="maxWidth">
			
				<div style="float:left; width:20px; height:400px; position: relative">
					<div style="float:right; padding:180px 2px 0 0">
						<img alt="" class="img-responsive" src="/img/home/left_arrow.png">
					</div>
				</div>
				<div style="float:right; width:20px; height:400px;">
					<div style="left; padding:180px 0 0 2px">
						<img alt="" class="img-responsive" src="/img/home/right_arrow.png">
					</div>
				</div>	
				<div style="overflow: hidden; ">
					<div class="col-md-12">
						<ul class="portfolio-list sort-destination" data-sort-id="portfolio" >
				
							<?php for($i=1; $i<=12; $i++) {?>
							<li class="col-md-2 brands">
								<div class="portfolio-item img-thumbnail">
									<a href="#" class="thumb-info">
										<img alt="" class="img-responsive" src="/img/projects/project-2.jpg">
									</a>
								</div>
							</li>
							<?php }?>
						</ul>		
					</div>
				</div>	
				<!-- 			

				 -->
			
			
			</div>

		</div>

		
	</div>
	
	
	<div class="row">
	
		<div class="col-md-6">
			<br /><br />
			<h2><strong>MEET THE TEAM</strong></h2>
		
			<div>
				<img alt="" class="img-responsive" src="/img/home/team.jpg">
			</div>
		</div>
	
		<div class="col-md-6">
			<br /><br />
			<h2><strong>THREAD</strong></h2>
			<p>
				<strong style="color:#ce163f">Lorem ipsum dolor sit amet</strong><br /><br />
				<span style="font-size:11px">Lorem ipsum dolor sit amet</span><br />
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus nibh sed elit mattis adipiscing. Fusce in hendrerit purus.
				
				<br /><br />
				
				<strong style="color:#ce163f">Lorem ipsum dolor sit amet</strong><br /><br />
				<span style="font-size:11px">Lorem ipsum dolor sit amet</span><br />
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus nibh sed elit mattis adipiscing. Fusce in hendrerit purus.
								
			</p>
		</div>
	</div>							
				

				
	</div>

</div>				