<?php 	$singleItem = $this->singleItem; 
		$listAttrValue = $this->listAttrValue;
		$styleItem = $this->styleItem;
		$listStyle = array();
		foreach($styleItem as $style){
			$listStyle[] = $style['styleId'];
		}
?>
<div class="row content-page" id="defination_page">
	<div class="defination_page col-lg-10 col-lg-offset-1">
		<div id="top_left" >
			<div class="row">
				<a href="/style" class="back-to">&lt; Back to List Styles</a>
				<div class="top_left_title top_title_style">Style</div>
				<form method="post" id="update-style">
					<div class="style_title col-lg-5 col-lg-offset-1">
						<label for="">Name: </label>
						<input type="text" name="name_style" value="<?php if(isset($singleItem->title)){echo $singleItem->title;}else{echo '';};?>">
						<input type="hidden" name="update-style" value="<?php if(isset($singleItem->id)){echo $singleItem->id;} ?>">
					</div>
					<div class="style_status col-lg-5">
						<label for="">Status: </label>
						<div class="style_status_content">
							<select name="status_select">
							  <option <?php if(isset($singleItem->isActive) && $singleItem->isActive == 1){ echo 'selected="selected"';}?> value="1">Enable 
							  </option>
							  <option <?php if(isset($singleItem->isActive) && $singleItem->isActive == 0){ echo 'selected="selected"';}?> value="0">Disable
							  </option>
							</select>
						</div>
						<img id="df-notice" src="http://www.freeiconspng.com/uploads/success-icon-7.png">
					</div>
					<input type="submit" name="submit" class="upgrade_style btn btn-primary col-lg-1"  value="Update">

				</form>
			</div>
		</div>
		<div class="clr"></div>

		<div id="top_right">

			<div class="row">
				<div class="top_right_title top_title_style">Defination</div>
				
	<?php 
	$count = 0;
	foreach($styleItem as $style){
		$count++;  ?>

					<form class="style-update" id="style-update-<?php echo $count ?>" method="post">
							<div class="top_right_attName col-lg-5 col-lg-offset-1">
								<select style="width:350px;" name='attr_name-<?php echo $count ?>'  class="chosen_select_left" data-number="<?php echo $count ?>" data-value-<?php echo $count ?>="<?php echo $style['value']; ?>">
									<option selected disabled >Select </option>
										<?php foreach($listAttrValue as $attr ){ ?>
										<option <?php if($style['attribute'] == $attr){echo 'selected';}?> value="<?php echo $attr;?>"> <?php echo $attr;?></option>
										<?php }  ?>
								</select>
							</div>

							<div class="top_right_attValue col-lg-5">
								<img src="/assets/images/loading.gif" style="margin-top: -12px; display: none;margin-left: -55px; position: absolute; float: left;">

									<select name='attr_value-<?php echo $count ?>' data-placeholder="Choose style defination..." style="width:350px;" multiple class="chosen_select_right" id="select-right-<?php echo $count ?>">
										<option value='all' <?php if($style['value'] == 'all'){echo 'selected="selected"';} ?> class="all" >All</option>
										
        
									</select>
							</div>

							<input type="hidden" name='number' value="<?php echo $count ?>">
							<input type="hidden" name='id' value="<?php echo $style['id']; ?>">
							<input class="add_attr btn btn-primary col-lg-1" type="submit" data-action='update' value="Update">
							<input class="delete_style btn btn-danger col-lg-1" type="submit" data-action='delete' value="Delete">

					</form>	
	<?php }?>
					

					<form id="add-new" method="post">
						
							<div class="top_right_attName col-lg-5 col-lg-offset-1">
								<select style="width:350px;" name='attr_name' class="chosen_select_left" data-number="<?php echo 'add' ?>" >
									<option selected disabled >Select </option>
									<?php foreach($listAttrValue as $attr ){ ?>
									<option value="<?php echo $attr;?>"> <?php echo $attr;?></option>
									<?php }  ?>
								</select>
							</div>

							<div class="top_right_attValue col-lg-5">
								<img src="/assets/images/loading.gif" style="margin-top: -12px; display: none;margin-left: -55px; position: absolute; float: left;">
									
									<select name='attr_value' data-placeholder="Choose style defination..." style="width:350px;" multiple="multiple" class="chosen_select_right" id="select-right-add">
										
									</select>
							</div>
							<input type="hidden" name='id-attr' value="<?php if(isset($singleItem->id)){echo $singleItem->id;} ?>">
							<input class="add_attr btn btn-primary col-lg-1" type="submit" value="Add">

					</form>	
		</div>
		<div class="clr"></div>
	</div>
</div>

