<div class="row content-page" id="defination_page">
	<div class="defination_page col-lg-10 col-lg-offset-1">
		<div id="top_left" >
			<div class="row">
				<div class="top_left_title top_title_style">Style</div>
				<form method="post">
					<div class="style_title col-lg-5 col-lg-offset-1">
						<label for="">Style: </label>
						<input type="text" name="name_style" value="">
					</div>
					<div class="style_status col-lg-5">
						<label for="">Status: </label>
						<div class="style_status_content">
							<select name="status_select">
							  <option value="1">Enable</option>
							  <option value="0">Disable</option>
							</select>
						</div>
					</div>
					<input type="submit" name="submit" class="upgrade_style btn btn-primary col-lg-1"  value="Upgrade">
				</form>
			</div>
		</div>
		<div class="clr"></div>

		<div id="top_right">
			<div class="row">
				<div class="top_right_title top_title_style">Defination</div>
				<div class="top_right_attName col-lg-5 col-lg-offset-1">
					<select style="width:350px;" class="chosen_select_left" >
						<option value="AL">Alabama</option>
						<option value="AL">Alabama1</option>
						<option value="AL">Alabama2</option>
						<option value="AL">Alabama3</option>
						<option value="WY">Wyoming</option>
					</select>
					<select style="width:350px;" class="chosen_select_left" >
						<option value="AL">Alabama</option>
						<option value="AL">Alabama1</option>
						<option value="AL">Alabama2</option>
						<option value="AL">Alabama3</option>
						<option value="WY">Wyoming</option>
					</select>
					<select style="width:350px;" class="chosen_select_left" >
						<option value="AL">Alabama</option>
						<option value="AL">Alabama1</option>
						<option value="AL">Alabama2</option>
						<option value="AL">Alabama3</option>
						<option value="WY">Wyoming</option>
					</select>
				</div>
				<div class="top_right_attValue col-lg-5">
					<select data-placeholder="Choose style defination..." style="width:350px;" multiple class="chosen_select_right">
						<option value="AL">Alabama</option>
						<option value="AL">Alabama1</option>
						<option value="AL">Alabama2</option>
						<option value="AL">Alabama3</option>
						<option value="WY">Wyoming</option>
					</select>
					<select data-placeholder="Choose style defination..." style="width:350px;" multiple class="chosen_select_right">
						<option value="AL">Alabama</option>
						<option value="AL">Alabama1</option>
						<option value="AL">Alabama2</option>
						<option value="AL">Alabama3</option>
						<option value="WY">Wyoming</option>
					</select>
					<select data-placeholder="Choose style defination..." style="width:350px;" multiple class="chosen_select_right">
						<option value="AL">Alabama</option>
						<option value="AL">Alabama1</option>
						<option value="AL">Alabama2</option>
						<option value="AL">Alabama3</option>
						<option value="WY">Wyoming</option>
					</select>
				</div>
				<div class="add_attr btn btn-primary col-lg-1">Add</div>
			</div>
		</div>
		<div class="clr"></div>
	</div>
</div>
