<?php 
$listItem = $this->listItem; 
$userName = $this->userName; 

?>
<div class="row content-page" id="style_page">
	<div class="style_page col-lg-10 col-lg-offset-1">
		<div class="create_style">
			<a href="/style/defination" class="sb_create_style">Creat Style</a>
		</div>
		<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
	        <thead>
	            <tr>
	                <th>ID</th>
	                <th>Title</th>
	                <th>Creator</th>
	                <th>Staus</th>
	                <th>Option</th>
	            </tr>
	        </thead>
	        <tfoot>
	            <tr>
	                <th>ID</th>
	                <th>Title</th>
	                <th>Creator</th>
	                <th>Staus</th>
	                <th>Option</th>
	            </tr>
	        </tfoot>
	        <tbody>

	        <?php foreach($listItem as $item ){ ?>
	            <tr>
	                <td><?php echo ($item['id']); ?></td>
	                <td><?php echo ($item['title']); ?></td>
	                <td><?php echo ($userName); ?></td>
	                <td><?php echo ($item['isActive']); ?></td>
	                <td>
	                	<button type="button" class="btn btn-info"><a href="style/defination?id=<?php echo ($item['id']); ?>">Edit</a></button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>

  			<?php } ?>

	            <!-- <tr>
	                <td>2</td>
	                <td>Accountant</td>
	                <td>Tokyo</td>
	                <td>63</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>3</td>
	                <td>Junior Technical Author</td>
	                <td>San Francisco</td>
	                <td>66</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>4</td>
	                <td>Senior Javascript Developer</td>
	                <td>Edinburgh</td>
	                <td>22</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>5</td>
	                <td>Accountant</td>
	                <td>Tokyo</td>
	                <td>33</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>6</td>
	                <td>Integration Specialist</td>
	                <td>New York</td>
	                <td>61</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>7</td>
	                <td>Sales Assistant</td>
	                <td>San Francisco</td>
	                <td>59</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>8</td>
	                <td>Integration Specialist</td>
	                <td>Tokyo</td>
	                <td>55</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>9</td>
	                <td>Javascript Developer</td>
	                <td>San Francisco</td>
	                <td>39</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>10</td>
	                <td>Software Engineer</td>
	                <td>Edinburgh</td>
	                <td>23</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>11</td>
	                <td>Office Manager</td>
	                <td>London</td>
	                <td>30</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>12</td>
	                <td>Support Lead</td>
	                <td>Edinburgh</td>
	                <td>22</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>13</td>
	                <td>Regional Director</td>
	                <td>San Francisco</td>
	                <td>36</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>14</td>
	                <td>Senior Marketing Designer</td>
	                <td>London</td>
	                <td>43</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr>
	            <tr>
	                <td>15</td>
	                <td>Regional Director</td>
	                <td>London</td>
	                <td>19</td>
	                <td>
	                	<button type="button" class="btn btn-info">Edit</button>
	                	<button type="button" class="btn btn-danger">Delete</button>
	                </td>
	            </tr> -->
	            
	        </tbody>
	    </table>

	</div>

</div>

<script type="text/javascript">
	$('#example').dataTable( {
	  "pageLength": 999,
	  "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ]
	} );

</script>