<?php 
$listItem = $this->listItem; 
$userName = $this->userName; 

?>
<div class="row content-page" id="style_page">
	<div class="style_page col-lg-10 col-lg-offset-1">
		<div class="create_style">
			<a href="/style/defination" class="sb_create_style">Create Style</a>
		</div>
		<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
	        <thead>
	            <tr>
	                <th>ID</th>
	                <th>Title</th>
	                <th>Creator</th>
	                <th>Staus</th>
	                <th>Option</th>
	            </tr>
	        </thead>
	        <tfoot>
	            <tr>
	                <th>ID</th>
	                <th>Title</th>
	                <th>Creator</th>
	                <th>Staus</th>
	                <th>Option</th>
	            </tr>
	        </tfoot>
	        <tbody>

	        <?php foreach($listItem as $item ){ ?>
	            <tr>
	                <td><?php echo ($item['id']); ?></td>
	                <td><?php echo ($item['title']); ?></td>
	                <td><?php echo ($userName); ?></td>
	                <td><?php echo ($item['isActive'] == 1 ? '<span class="label label-success">Enable</span>' : '<span class="label label-danger">Disable</span>'); ?></td>
	                <td>
	                	<a href="/style/defination/<?php echo ($item['id']); ?>"><button type="button" class="btn"><span class="glyphicon glyphicon-edit"></span></button></a>
	                	<button type="button" class="btn"><span class="glyphicon glyphicon-remove"></span></button>
	                </td>
	            </tr>

  			<?php } ?>
	        </tbody>
	    </table>

	</div>

</div>

<script type="text/javascript">
	$('#example').dataTable( {
	  "pageLength": 25,
	  "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ]
	} );

</script>